set echo on
set linesize 1000
set pagesize 300
set trimspool on
SET SERVEROUTPUT OFF
SPOOL PREM_INIT_CREATE_TEMP_OBJECTS.LOG

CREATE OR REPLACE TYPE GIS_STG.ADDRESSPARSEDTYPE FORCE
AS
  OBJECT
  (
    HOUSE_NUMBER             NUMBER (10,0),
    DIRECTION_INDICATOR      VARCHAR2 (3 BYTE),
    STREET_NAME              VARCHAR2 (30 BYTE),
    STREET_TYPE              VARCHAR2 (10 BYTE),
    DIRECTIONAL_IND_TRAILING VARCHAR2 (3 BYTE),
    DWELLING_TYPE            VARCHAR2 (10 BYTE),
    UNIT                     VARCHAR2 (5 BYTE)) ;
    
/

CREATE OR REPLACE TYPE GIS_STG.ADDRESSPARSEDTABLETYPE FORCE
AS
  TABLE OF GIS_STG.ADDRESSPARSEDTYPE;
  
/

CREATE OR REPLACE PACKAGE GIS_STG.PREMISEADDRESSINITIALIZATION
IS

  FUNCTION PARSEADDRESS (
      P_ADDRESS VARCHAR2)
    RETURN GIS_STG.ADDRESSPARSEDTABLETYPE PIPELINED ;

END PREMISEADDRESSINITIALIZATION;

/

CREATE OR REPLACE PACKAGE BODY GIS_STG.PREMISEADDRESSINITIALIZATION
IS

  FUNCTION PARSEADDRESS (
      P_ADDRESS VARCHAR2)
    RETURN GIS_STG.ADDRESSPARSEDTABLETYPE PIPELINED
  AS
    L_OUT_ROW GIS_STG.ADDRESSPARSEDTYPE := GIS_STG.ADDRESSPARSEDTYPE (NULL,NULL,NULL,NULL,NULL,NULL,NULL) ;
    V_ERRM VARCHAR2 (64) ;
    V_CODE NUMBER;
  BEGIN
    DBMS_OUTPUT.DISABLE;
    GIS_ONC.GISPKG_CCB_ESILOCATION.PARSEADDRESS (P_ADDRESS,L_OUT_ROW.HOUSE_NUMBER,L_OUT_ROW.DIRECTION_INDICATOR,L_OUT_ROW.STREET_NAME,L_OUT_ROW.STREET_TYPE,L_OUT_ROW.DIRECTIONAL_IND_TRAILING,L_OUT_ROW.DWELLING_TYPE,L_OUT_ROW.UNIT) ;
    DBMS_OUTPUT.ENABLE;
    PIPE ROW (L_OUT_ROW) ;

    RETURN;

  EXCEPTION  
    WHEN OTHERS THEN
      DBMS_OUTPUT.ENABLE;
      V_CODE := SQLCODE;
      V_ERRM := SUBSTR (SQLERRM,1,64) ;
      DBMS_OUTPUT.PUT_LINE ('ERROR CODE ' || V_CODE || ' : ' || TO_CHAR (SYSTIMESTAMP,'YYYY/MM/DD HH:MI:SS') || ' ') ;
      DBMS_OUTPUT.PUT ('  ' || DBMS_UTILITY.FORMAT_ERROR_STACK) ;
      DBMS_OUTPUT.PUT ('  ' || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE) ;

  END PARSEADDRESS;

END PREMISEADDRESSINITIALIZATION;

/

CREATE INDEX GIS_STG.IDX_CIS_ESI_LOCATION ON GIS_STG.CIS_ESI_LOCATIONS (ESI_LOCATION);

/

CREATE INDEX IDX_PREMISE_N_PREM_NBR ON B$PREMISE_N (PREMISE_NBR);

/

spool off;
