SET ECHO ON
SET LINESIZE 1000
SET PAGESIZE 300
SET TRIMSPOOL ON
SET SERVEROUTPUT ON
SPOOL PREM_INIT_PARSE_ADDR.LOG

ALTER TABLE GIS_STG.CIS_ESI_LOCATIONS DISABLE ALL TRIGGERS;

UPDATE GIS_STG.CIS_ESI_LOCATIONS ESI
  SET
    (
      HOUSE_NUMBER
    ,DIRECTION_INDICATOR
    ,STREET_NAME
    ,STREET_TYPE
    ,DIRECTIONAL_IND_TRAILING
    ,UNIT
    )
    =
    (SELECT   ADDR.HOUSE_NUMBER
      ,ADDR.DIRECTION_INDICATOR
      ,ADDR.STREET_NAME
      ,ADDR.STREET_TYPE
      ,ADDR.DIRECTIONAL_IND_TRAILING
      ,ADDR.UNIT
      FROM TABLE (GIS_STG.PREMISEADDRESSINITIALIZATION.PARSEADDRESS (ESI.ADDRESS)) ADDR
    ) ;
    
COMMIT;

ALTER TABLE GIS_STG.CIS_ESI_LOCATIONS ENABLE ALL TRIGGERS;

spool off;