SET ECHO ON
SET LINESIZE 1000
SET PAGESIZE 300
SET TRIMSPOOL ON
SET SERVEROUTPUT OFF
SPOOL PREM_INIT_UPDATE_PREMISE_N.LOG 

ALTER TABLE GIS.B$PREMISE_N DISABLE ALL TRIGGERS;

UPDATE GIS.B$PREMISE_N P
  SET
    (
      P.ADDRESS
    ,P.HOUSE_NBR
    ,P.HOUSE_FRACTION_NBR
    ,P.DIR_LEADING_C
    ,P.STREET_NM
    ,P.STREET_TYPE_C
    ,P.DIR_TRAILING_C
    ,P.UNIT_NBR
    ,P.ZIP_C
    ,P.CITY_C
    ,P.TYPE_C
    ,P.RATE_CODE_C
    ,P.SIC_C
    ,P.COUNTY_C
    ,P.INSIDE_CITY_LIMITS_YN
    ,P.CRITICAL_LOAD_Q
    ,P.CRITICAL_CUSTOMER_C
    ,P.PREMISE_STATUS
    ,P.MAJOR_CUSTOMER_C
    ,P.DWELLING_TYPE_C
    )
    =
    (SELECT   C.ADDRESS
      ,C.HOUSE_NUMBER
      ,C.FRACTIONAL_HOUSE_NUMBER
      ,C.DIRECTION_INDICATOR
      ,C.STREET_NAME
      ,C.STREET_TYPE
      ,C.DIRECTIONAL_IND_TRAILING
      ,C.UNIT
      ,C.ZIP_CODE
      ,C.CITY
      ,C.PREMISE_TYPE
      ,C.RATE_CODE
      ,C.SIC_CODE
      ,C.COUNTY_CODE
      ,C.INSIDE_CITY_LIMITS
      ,C.CRITICAL_LOAD
      ,C.CRITICAL_CUSTOMER
      ,C.PREMISE_STATUS
      ,C.MAJOR_CUSTOMER
      ,C.DWELLING_TYPE
      FROM GIS_STG.CIS_ESI_LOCATIONS C
      WHERE C.ESI_LOCATION = P.PREMISE_NBR
    )
  WHERE EXISTS
    (SELECT   1
      FROM GIS_STG.CIS_ESI_LOCATIONS C
      WHERE C.ESI_LOCATION = P.PREMISE_NBR
    ) ;
    
COMMIT;

ALTER TABLE GIS.B$PREMISE_N ENABLE ALL TRIGGERS;

SPOOL OFF;