SET ECHO ON
SET LINESIZE 1000
SET PAGESIZE 300
SET TRIMSPOOL ON
SET SERVEROUTPUT OFF
SPOOL PREM_INIT_DROP_TEMP_OBJECTS.LOG

DROP PACKAGE GIS_STG.PREMISEADDRESSINITIALIZATION;
DROP TYPE GIS_STG.ADDRESSPARSEDTABLETYPE;
DROP TYPE GIS_STG.ADDRESSPARSEDTYPE;

spool off;