CREATE OR REPLACE VIEW "GIS_ONC"."CCB_PREMISE_MAPPING_VW" ("ESI_LOCATION","SUBSTATION_CODE","FEEDER_ID","FEEDER_NBR","SERVICE_STRUCTURE_ID","TRANSFORMER_STRUCTURE_ID","PROTECTIVE_DEVICE_STRUCTURE_ID","TRANSFORMER_FID","SERVICE_POINT_LATITUDE","SERVICE_POINT_LONGITUDE")
                     AS
WITH CONNSERVICELINE AS
    (SELECT   NODE_2_ID
      ,MAX (G3E_FID) G3E_FID
     ,MAX (PROTECTIVE_DEVICE_FID) PROTECTIVE_DEVICE_FID
      FROM GIS.B$CONNECTIVITY_N
      WHERE 1 = 1
        --AND NODE_2_ID <> 0
        AND G3E_FNO = 54
        AND LTT_ID  = 0
        and NODE_2_ID <> 0
      GROUP BY PROTECTIVE_DEVICE_FID
      ,NODE_2_ID
    )
  ,CONNECTIVITY AS
    (SELECT   CONNSERVICEPOINT.G3E_FID SP_FID
      ,CONNSERVICEPOINT.NODE_1_ID SP_NODE1
      ,CONNSERVICEPOINT.NODE_2_ID SP_NODE2
      ,CONNSERVICELINE.PROTECTIVE_DEVICE_FID SL_PROTDEVICE
      ,CONNSERVICELINE.NODE_2_ID SL_NODE2
      ,CONNSERVICELINE.G3E_FID SL_FID
      ,CONNXFMR.SSTA_C SUBSTATION_CODE
      ,CONNXFMR.FEEDER_1_ID FEEDER_ID
      ,CAST (REGEXP_REPLACE (CONNXFMR.FEEDER_1_ID,'[^0-9]','') AS VARCHAR2 (14)) FEEDER_NBR
      ,CONNXFMR.G3E_FID TRANSFORMER_FID
      ,CONNXFMR.PROTECTIVE_DEVICE_FID XFMR_PROTDEVICE
      FROM GIS.B$CONNECTIVITY_N CONNSERVICEPOINT
      INNER JOIN CONNSERVICELINE
      ON CONNSERVICEPOINT.NODE_1_ID = CONNSERVICELINE.NODE_2_ID
      INNER JOIN GIS.B$CONNECTIVITY_N CONNXFMR
      ON CONNSERVICELINE.PROTECTIVE_DEVICE_FID = CONNXFMR.G3E_FID
      WHERE 1                                  = 1
        AND CONNSERVICEPOINT.G3E_FNO           = 55
        AND CONNSERVICEPOINT.LTT_ID            = 0
        AND CONNXFMR.LTT_ID                    = 0
        AND CONNXFMR.G3E_FNO                  IN (59,60)
        and CONNSERVICEPOINT.NODE_1_ID <> 0
    )
  ,COMM AS
    (SELECT   COMMSP.LATITUDE SERVICE_POINT_LATITUDE
      ,COMMSP.LONGITUDE SERVICE_POINT_LONGITUDE
      ,COMMSL.STRUCTURE_ID SERVICE_STRUCTURE_ID
      ,COMMXFMR.STRUCTURE_ID TRANSFORMER_STRUCTURE_ID
      ,COMMPD.STRUCTURE_ID PROTECTIVE_DEVICE_STRUCTURE_ID
      ,CON.*
      FROM CONNECTIVITY CON
      INNER JOIN GIS.B$COMMON_N COMMSP
      ON CON.SP_FID = COMMSP.G3E_FID
      INNER JOIN GIS.B$COMMON_N COMMSL
      ON CON.SL_FID = COMMSL.G3E_FID
      INNER JOIN GIS.B$COMMON_N COMMXFMR
      ON CON.TRANSFORMER_FID = COMMXFMR.G3E_FID
      INNER JOIN GIS.B$COMMON_N COMMPD
      ON CON.XFMR_PROTDEVICE = COMMPD.G3E_FID
      WHERE 1                = 1
        AND COMMSP.LTT_ID    = 0
        AND COMMSL.LTT_ID    = 0
        AND COMMXFMR.LTT_ID  = 0
        AND COMMPD.LTT_ID    = 0
    )
  SELECT   PREMISE.PREMISE_NBR ESI_LOCATION
    ,COMM.SUBSTATION_CODE
    ,COMM.FEEDER_ID
    ,COMM.FEEDER_NBR
    ,COMM.SERVICE_STRUCTURE_ID
    ,COMM.TRANSFORMER_STRUCTURE_ID
    ,COMM.PROTECTIVE_DEVICE_STRUCTURE_ID
    ,COMM.TRANSFORMER_FID
    ,COMM.SERVICE_POINT_LATITUDE
    ,COMM.SERVICE_POINT_LONGITUDE
    FROM COMM
    INNER JOIN GIS.B$PREMISE_N PREMISE
    ON COMM.SP_FID             = PREMISE.G3E_FID
    WHERE 1                    = 1
      AND PREMISE.PREMISE_NBR <> '0'
      AND PREMISE.LTT_ID       = 0 ;