------------------------------------------------------------------------------
--CREATE BOUNDARY TO STREETLIGHT ACCOUNT ASSOCIATION TABLE
--INSERT DATA USING SL BOUNDARY TO ACCOUNT MAPPING SPREADSHEET
------------------------------------------------------------------------------
DECLARE
    RESULT_COUNT NUMBER(2,0) := 0;
    SQL_STMT VARCHAR(200 BYTE) := 'CREATE TABLE GIS_ONC.STLT_ACCT_BNDY_ASSOC(ACCOUNT_ID VARCHAR2(10 BYTE),BOUNDARY_CLASS NUMBER(5,0),BOUNDARY_ID VARCHAR2(100 BYTE))';
BEGIN
    SELECT COUNT(*) INTO RESULT_COUNT FROM ALL_TABLES WHERE TABLE_NAME = 'STLT_ACCT_BNDY_ASSOC' AND OWNER = 'GIS_ONC';
    IF RESULT_COUNT > 0 THEN
        EXECUTE IMMEDIATE 'DROP TABLE GIS_ONC.STLT_ACCT_BNDY_ASSOC';
        EXECUTE IMMEDIATE SQL_STMT;
		EXECUTE IMMEDIATE 'COMMIT';
    ELSE
        EXECUTE IMMEDIATE SQL_STMT;
		EXECUTE IMMEDIATE 'COMMIT';
    END IF;
END;