ALTER TABLE GT_PLOT_MAPFRAME
 DROP PRIMARY KEY CASCADE;

DROP TABLE GT_PLOT_MAPFRAME CASCADE CONSTRAINTS;

CREATE TABLE GT_PLOT_MAPFRAME
(
  MF_NO                     NUMBER,
  GROUP_NO                  NUMBER,
  MF_DATATYPE               VARCHAR2(30 BYTE),
  MF_NAME                   VARCHAR2(255 BYTE),
  MF_GEO_LNO                NUMBER(5),
  MF_DET_LNO                NUMBER(5),
  MF_COORDINATE_X1          NUMBER,
  MF_COORDINATE_Y1          NUMBER,
  MF_COORDINATE_X2          NUMBER,
  MF_COORDINATE_Y2          NUMBER,
  MF_NORTHARROW_SIZE        NUMBER(5),
  MF_NORTHARROW_SYMBOLFILE  VARCHAR2(255 BYTE),
  MF_STYLE_NO               NUMBER,
  MF_DISPLAY_FACTOR         NUMBER,
  MF_EDITDATE               DATE                NOT NULL
)
TABLESPACE GC_DATA_PRODUCT
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX PK_GT_PLOT_MAPFRAME_MF_NO ON GT_PLOT_MAPFRAME
(MF_NO)
LOGGING
TABLESPACE GC_DATA_PRODUCT
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE OR REPLACE TRIGGER M_T_BIUR_GTPLOTMAPFR_EDATE 
BEFORE INSERT OR UPDATE ON GT_PLOT_MAPFRAME
FOR EACH ROW
BEGIN

  :NEW.MF_EDITDATE := SYSDATE;
END;
/


CREATE OR REPLACE TRIGGER M_T_BIUR_GT_PLOT_MAPFRAME 
BEFORE INSERT OR UPDATE
ON GT_PLOT_MAPFRAME
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
DECLARE
  refValue            NUMBER;
  invalid_reference   EXCEPTION;
  CURSOR curReference (newValue NUMBER) IS
    SELECT GROUP_NO
    FROM GT_PLOT_GROUPS_DRI
    WHERE GROUP_NO = newValue;
BEGIN

  OPEN curReference(:NEW.GROUP_NO);
  FETCH curReference INTO refValue;
  IF curReference%NOTFOUND THEN
    RAISE invalid_reference;
  END IF;
  CLOSE curReference;

EXCEPTION
  WHEN invalid_reference THEN
    CLOSE curReference;
    raise_application_error ( -20001, 'A reference to GT_PLOT_MAPFRAME.GROUP_NO=' || :NEW.GROUP_NO || ' does not exists in GT_PLOT_GROUPS_DRI.GROUP_NO');
  WHEN OTHERS THEN
    RAISE;
END M_T_BIUR_GT_PLOT_MAPFRAME;
/


CREATE OR REPLACE PUBLIC SYNONYM GT_PLOT_MAPFRAME FOR GT_PLOT_MAPFRAME;


ALTER TABLE GT_PLOT_MAPFRAME ADD (
  CONSTRAINT PK_GT_PLOT_MAPFRAME_MF_NO
  PRIMARY KEY
  (MF_NO)
  USING INDEX PK_GT_PLOT_MAPFRAME_MF_NO
  ENABLE VALIDATE);

GRANT SELECT ON GT_PLOT_MAPFRAME TO FINANCE;

GRANT SELECT ON GT_PLOT_MAPFRAME TO MARKETING;

GRANT DELETE, INSERT, SELECT, UPDATE ON GT_PLOT_MAPFRAME TO PUBLIC;

Insert into GT_PLOT_MAPFRAME
   (MF_NO, GROUP_NO, MF_DATATYPE, MF_NAME, MF_GEO_LNO, 
    MF_DET_LNO, MF_COORDINATE_X1, MF_COORDINATE_Y1, MF_COORDINATE_X2, MF_COORDINATE_Y2, 
    MF_NORTHARROW_SIZE, MF_NORTHARROW_SYMBOLFILE, MF_STYLE_NO, MF_DISPLAY_FACTOR, MF_EDITDATE)
 Values
   (10010001, 10001, 'Map Frame', 'A-Size Portrait', 1, 
    2, 10, 10, 205.9, 269.4, 
    72, 'arrow1.wmf', NULL, NULL, TO_DATE('04/05/2013 22:02:05', 'MM/DD/YYYY HH24:MI:SS'));
Insert into GT_PLOT_MAPFRAME
   (MF_NO, GROUP_NO, MF_DATATYPE, MF_NAME, MF_GEO_LNO, 
    MF_DET_LNO, MF_COORDINATE_X1, MF_COORDINATE_Y1, MF_COORDINATE_X2, MF_COORDINATE_Y2, 
    MF_NORTHARROW_SIZE, MF_NORTHARROW_SYMBOLFILE, MF_STYLE_NO, MF_DISPLAY_FACTOR, MF_EDITDATE)
 Values
   (10010002, 10002, 'Map Frame', 'A-Size Landscape', 1, 
    2, 10, 10, 269.4, 205.9, 
    72, 'arrow1.wmf', NULL, NULL, TO_DATE('04/05/2013 22:02:05', 'MM/DD/YYYY HH24:MI:SS'));
Insert into GT_PLOT_MAPFRAME
   (MF_NO, GROUP_NO, MF_DATATYPE, MF_NAME, MF_GEO_LNO, 
    MF_DET_LNO, MF_COORDINATE_X1, MF_COORDINATE_Y1, MF_COORDINATE_X2, MF_COORDINATE_Y2, 
    MF_NORTHARROW_SIZE, MF_NORTHARROW_SYMBOLFILE, MF_STYLE_NO, MF_DISPLAY_FACTOR, MF_EDITDATE)
 Values
   (10010003, 10003, 'Map Frame', 'B-Size Portrait', 1, 
    2, 10, 10, 269.4, 421.8, 
    72, 'arrow1.wmf', NULL, NULL, TO_DATE('04/05/2013 22:02:05', 'MM/DD/YYYY HH24:MI:SS'));
Insert into GT_PLOT_MAPFRAME
   (MF_NO, GROUP_NO, MF_DATATYPE, MF_NAME, MF_GEO_LNO, 
    MF_DET_LNO, MF_COORDINATE_X1, MF_COORDINATE_Y1, MF_COORDINATE_X2, MF_COORDINATE_Y2, 
    MF_NORTHARROW_SIZE, MF_NORTHARROW_SYMBOLFILE, MF_STYLE_NO, MF_DISPLAY_FACTOR, MF_EDITDATE)
 Values
   (10010004, 10004, 'Map Frame', 'B-Size Landscape', 1, 
    2, 10, 10, 421.8, 269.4, 
    72, 'arrow1.wmf', NULL, NULL, TO_DATE('04/05/2013 22:02:05', 'MM/DD/YYYY HH24:MI:SS'));
Insert into GT_PLOT_MAPFRAME
   (MF_NO, GROUP_NO, MF_DATATYPE, MF_NAME, MF_GEO_LNO, 
    MF_DET_LNO, MF_COORDINATE_X1, MF_COORDINATE_Y1, MF_COORDINATE_X2, MF_COORDINATE_Y2, 
    MF_NORTHARROW_SIZE, MF_NORTHARROW_SYMBOLFILE, MF_STYLE_NO, MF_DISPLAY_FACTOR, MF_EDITDATE)
 Values
   (10010005, 10005, 'Map Frame', 'C-Size Portrait', 1, 
    2, 10, 10, 421.8, 548.8, 
    72, 'arrow1.wmf', NULL, NULL, TO_DATE('04/05/2013 22:02:05', 'MM/DD/YYYY HH24:MI:SS'));
Insert into GT_PLOT_MAPFRAME
   (MF_NO, GROUP_NO, MF_DATATYPE, MF_NAME, MF_GEO_LNO, 
    MF_DET_LNO, MF_COORDINATE_X1, MF_COORDINATE_Y1, MF_COORDINATE_X2, MF_COORDINATE_Y2, 
    MF_NORTHARROW_SIZE, MF_NORTHARROW_SYMBOLFILE, MF_STYLE_NO, MF_DISPLAY_FACTOR, MF_EDITDATE)
 Values
   (10010006, 10006, 'Map Frame', 'C-Size Landscape', 1, 
    2, 10, 10, 548.8, 421.8, 
    72, 'arrow1.wmf', NULL, NULL, TO_DATE('04/05/2013 22:02:05', 'MM/DD/YYYY HH24:MI:SS'));
Insert into GT_PLOT_MAPFRAME
   (MF_NO, GROUP_NO, MF_DATATYPE, MF_NAME, MF_GEO_LNO, 
    MF_DET_LNO, MF_COORDINATE_X1, MF_COORDINATE_Y1, MF_COORDINATE_X2, MF_COORDINATE_Y2, 
    MF_NORTHARROW_SIZE, MF_NORTHARROW_SYMBOLFILE, MF_STYLE_NO, MF_DISPLAY_FACTOR, MF_EDITDATE)
 Values
   (10010007, 10007, 'Map Frame', 'D-Size Portrait', 1, 
    2, 10, 10, 548.8, 853.6, 
    72, 'arrow1.wmf', NULL, NULL, TO_DATE('04/05/2013 22:02:05', 'MM/DD/YYYY HH24:MI:SS'));
Insert into GT_PLOT_MAPFRAME
   (MF_NO, GROUP_NO, MF_DATATYPE, MF_NAME, MF_GEO_LNO, 
    MF_DET_LNO, MF_COORDINATE_X1, MF_COORDINATE_Y1, MF_COORDINATE_X2, MF_COORDINATE_Y2, 
    MF_NORTHARROW_SIZE, MF_NORTHARROW_SYMBOLFILE, MF_STYLE_NO, MF_DISPLAY_FACTOR, MF_EDITDATE)
 Values
   (10010008, 10008, 'Map Frame', 'D-Size Landscape', 1, 
    2, 10, 10, 853.6, 548.8, 
    72, 'arrow1.wmf', NULL, NULL, TO_DATE('04/05/2013 22:02:05', 'MM/DD/YYYY HH24:MI:SS'));
Insert into GT_PLOT_MAPFRAME
   (MF_NO, GROUP_NO, MF_DATATYPE, MF_NAME, MF_GEO_LNO, 
    MF_DET_LNO, MF_COORDINATE_X1, MF_COORDINATE_Y1, MF_COORDINATE_X2, MF_COORDINATE_Y2, 
    MF_NORTHARROW_SIZE, MF_NORTHARROW_SYMBOLFILE, MF_STYLE_NO, MF_DISPLAY_FACTOR, MF_EDITDATE)
 Values
   (10010009, 10009, 'Map Frame', 'E-Size Portrait', 1, 
    2, 10, 10, 853.6, 1107.6, 
    72, 'arrow1.wmf', NULL, NULL, TO_DATE('04/05/2013 22:02:05', 'MM/DD/YYYY HH24:MI:SS'));
Insert into GT_PLOT_MAPFRAME
   (MF_NO, GROUP_NO, MF_DATATYPE, MF_NAME, MF_GEO_LNO, 
    MF_DET_LNO, MF_COORDINATE_X1, MF_COORDINATE_Y1, MF_COORDINATE_X2, MF_COORDINATE_Y2, 
    MF_NORTHARROW_SIZE, MF_NORTHARROW_SYMBOLFILE, MF_STYLE_NO, MF_DISPLAY_FACTOR, MF_EDITDATE)
 Values
   (10010010, 10010, 'Map Frame', 'E-Size Landscape', 1, 
    2, 10, 10, 1107.6, 853.6, 
    72, 'arrow1.wmf', NULL, NULL, TO_DATE('04/05/2013 22:02:05', 'MM/DD/YYYY HH24:MI:SS'));
Insert into GT_PLOT_MAPFRAME
   (MF_NO, GROUP_NO, MF_DATATYPE, MF_NAME, MF_GEO_LNO, 
    MF_DET_LNO, MF_COORDINATE_X1, MF_COORDINATE_Y1, MF_COORDINATE_X2, MF_COORDINATE_Y2, 
    MF_NORTHARROW_SIZE, MF_NORTHARROW_SYMBOLFILE, MF_STYLE_NO, MF_DISPLAY_FACTOR, MF_EDITDATE)
 Values
   (10010101, 10101, 'Map Frame', 'A-Size Portrait (Engineering)', 1, 
    2, 17, 17, 199, 237, 
    72, 'arrow1.wmf', NULL, NULL, TO_DATE('04/05/2013 22:02:05', 'MM/DD/YYYY HH24:MI:SS'));
Insert into GT_PLOT_MAPFRAME
   (MF_NO, GROUP_NO, MF_DATATYPE, MF_NAME, MF_GEO_LNO, 
    MF_DET_LNO, MF_COORDINATE_X1, MF_COORDINATE_Y1, MF_COORDINATE_X2, MF_COORDINATE_Y2, 
    MF_NORTHARROW_SIZE, MF_NORTHARROW_SYMBOLFILE, MF_STYLE_NO, MF_DISPLAY_FACTOR, MF_EDITDATE)
 Values
   (10010102, 10102, 'Map Frame', 'A-Size Landscape (Engineering)', 1, 
    2, 17, 17, 262.46, 173.4, 
    72, 'arrow1.wmf', NULL, NULL, TO_DATE('04/05/2013 22:02:05', 'MM/DD/YYYY HH24:MI:SS'));
Insert into GT_PLOT_MAPFRAME
   (MF_NO, GROUP_NO, MF_DATATYPE, MF_NAME, MF_GEO_LNO, 
    MF_DET_LNO, MF_COORDINATE_X1, MF_COORDINATE_Y1, MF_COORDINATE_X2, MF_COORDINATE_Y2, 
    MF_NORTHARROW_SIZE, MF_NORTHARROW_SYMBOLFILE, MF_STYLE_NO, MF_DISPLAY_FACTOR, MF_EDITDATE)
 Values
   (10010103, 10103, 'Map Frame', 'B-Size Portrait (Engineering)', 1, 
    2, 17, 17, 262.46, 389.26, 
    72, 'arrow1.wmf', NULL, NULL, TO_DATE('04/05/2013 22:02:05', 'MM/DD/YYYY HH24:MI:SS'));
Insert into GT_PLOT_MAPFRAME
   (MF_NO, GROUP_NO, MF_DATATYPE, MF_NAME, MF_GEO_LNO, 
    MF_DET_LNO, MF_COORDINATE_X1, MF_COORDINATE_Y1, MF_COORDINATE_X2, MF_COORDINATE_Y2, 
    MF_NORTHARROW_SIZE, MF_NORTHARROW_SYMBOLFILE, MF_STYLE_NO, MF_DISPLAY_FACTOR, MF_EDITDATE)
 Values
   (10010104, 10104, 'Map Frame', 'B-Size Landscape (Engineering)', 1, 
    2, 17, 17, 354.8, 236.86, 
    72, 'arrow1.wmf', NULL, NULL, TO_DATE('04/05/2013 22:02:05', 'MM/DD/YYYY HH24:MI:SS'));
Insert into GT_PLOT_MAPFRAME
   (MF_NO, GROUP_NO, MF_DATATYPE, MF_NAME, MF_GEO_LNO, 
    MF_DET_LNO, MF_COORDINATE_X1, MF_COORDINATE_Y1, MF_COORDINATE_X2, MF_COORDINATE_Y2, 
    MF_NORTHARROW_SIZE, MF_NORTHARROW_SYMBOLFILE, MF_STYLE_NO, MF_DISPLAY_FACTOR, MF_EDITDATE)
 Values
   (10010105, 10105, 'Map Frame', 'C-Size Portrait (Engineering)', 1, 
    2, 17, 17, 414.93, 516.2, 
    72, 'arrow1.wmf', NULL, NULL, TO_DATE('04/05/2013 22:02:05', 'MM/DD/YYYY HH24:MI:SS'));
Insert into GT_PLOT_MAPFRAME
   (MF_NO, GROUP_NO, MF_DATATYPE, MF_NAME, MF_GEO_LNO, 
    MF_DET_LNO, MF_COORDINATE_X1, MF_COORDINATE_Y1, MF_COORDINATE_X2, MF_COORDINATE_Y2, 
    MF_NORTHARROW_SIZE, MF_NORTHARROW_SYMBOLFILE, MF_STYLE_NO, MF_DISPLAY_FACTOR, MF_EDITDATE)
 Values
   (10010106, 10106, 'Map Frame', 'C-Size Landscape (Engineering)', 1, 
    2, 17, 17, 481.94, 389.33, 
    72, 'arrow1.wmf', NULL, NULL, TO_DATE('04/05/2013 22:02:05', 'MM/DD/YYYY HH24:MI:SS'));
Insert into GT_PLOT_MAPFRAME
   (MF_NO, GROUP_NO, MF_DATATYPE, MF_NAME, MF_GEO_LNO, 
    MF_DET_LNO, MF_COORDINATE_X1, MF_COORDINATE_Y1, MF_COORDINATE_X2, MF_COORDINATE_Y2, 
    MF_NORTHARROW_SIZE, MF_NORTHARROW_SYMBOLFILE, MF_STYLE_NO, MF_DISPLAY_FACTOR, MF_EDITDATE)
 Values
   (10010107, 10107, 'Map Frame', 'D-Size Portrait (Engineering)', 1, 
    2, 17, 17, 541.86, 821.13, 
    72, 'arrow1.wmf', NULL, NULL, TO_DATE('04/05/2013 22:02:05', 'MM/DD/YYYY HH24:MI:SS'));
Insert into GT_PLOT_MAPFRAME
   (MF_NO, GROUP_NO, MF_DATATYPE, MF_NAME, MF_GEO_LNO, 
    MF_DET_LNO, MF_COORDINATE_X1, MF_COORDINATE_Y1, MF_COORDINATE_X2, MF_COORDINATE_Y2, 
    MF_NORTHARROW_SIZE, MF_NORTHARROW_SYMBOLFILE, MF_STYLE_NO, MF_DISPLAY_FACTOR, MF_EDITDATE)
 Values
   (10010108, 10108, 'Map Frame', 'D-Size Landscape (Engineering)', 1, 
    2, 17, 17, 786.6, 516.2, 
    72, 'arrow1.wmf', NULL, NULL, TO_DATE('04/05/2013 22:02:05', 'MM/DD/YYYY HH24:MI:SS'));
Insert into GT_PLOT_MAPFRAME
   (MF_NO, GROUP_NO, MF_DATATYPE, MF_NAME, MF_GEO_LNO, 
    MF_DET_LNO, MF_COORDINATE_X1, MF_COORDINATE_Y1, MF_COORDINATE_X2, MF_COORDINATE_Y2, 
    MF_NORTHARROW_SIZE, MF_NORTHARROW_SYMBOLFILE, MF_STYLE_NO, MF_DISPLAY_FACTOR, MF_EDITDATE)
 Values
   (10010109, 10109, 'Map Frame', 'E-Size Portrait (Engineering)', 1, 
    2, 17, 17, 786.6, 1075.1, 
    72, 'arrow1.wmf', NULL, NULL, TO_DATE('04/05/2013 22:02:05', 'MM/DD/YYYY HH24:MI:SS'));
Insert into GT_PLOT_MAPFRAME
   (MF_NO, GROUP_NO, MF_DATATYPE, MF_NAME, MF_GEO_LNO, 
    MF_DET_LNO, MF_COORDINATE_X1, MF_COORDINATE_Y1, MF_COORDINATE_X2, MF_COORDINATE_Y2, 
    MF_NORTHARROW_SIZE, MF_NORTHARROW_SYMBOLFILE, MF_STYLE_NO, MF_DISPLAY_FACTOR, MF_EDITDATE)
 Values
   (10010110, 10110, 'Map Frame', 'E-Size Landscape (Engineering)', 1, 
    2, 17, 17, 1040.6, 821.1, 
    72, 'arrow1.wmf', NULL, NULL, TO_DATE('04/05/2013 22:02:05', 'MM/DD/YYYY HH24:MI:SS'));
COMMIT;
