ALTER TABLE GT_PLOT_SHEETS
 DROP PRIMARY KEY CASCADE;

DROP TABLE GT_PLOT_SHEETS CASCADE CONSTRAINTS;

CREATE TABLE GT_PLOT_SHEETS
(
  SHEET_ID              NUMBER,
  SHEET_NAME            VARCHAR2(255 BYTE),
  SHEET_NAME_FR         VARCHAR2(255 BYTE),
  SHEET_HEIGHT          NUMBER,
  SHEET_WIDTH           NUMBER,
  SHEET_SIZE            VARCHAR2(30 BYTE),
  SHEET_ORIENTATION     VARCHAR2(30 BYTE),
  SHEET_ORIENTATION_FR  VARCHAR2(30 BYTE),
  GTP_LOCALECOMMENT     VARCHAR2(240 BYTE),
  GTP_EDITDATE          DATE                    NOT NULL
)
TABLESPACE GC_DATA_PRODUCT
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX PK_GT_PLOT_SHEETS_SHEET_ID ON GT_PLOT_SHEETS
(SHEET_ID)
LOGGING
TABLESPACE GC_DATA_PRODUCT
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE OR REPLACE TRIGGER M_T_ADR_GT_PLOT_SHEETS_DL 
AFTER DELETE ON GT_PLOT_SHEETS
FOR EACH ROW
DECLARE
  dlno              INTEGER;
  tmpString         G3E_DELETIONLOG.G3E_USERNAME%TYPE;
  string_too_long   EXCEPTION;
  PRAGMA EXCEPTION_INIT (string_too_long, -6502);
BEGIN

  SELECT M_S_G3E_DELETIONLOG.NEXTVAL INTO dlno FROM DUAL;

  tmpString := 'SHEET_ID=' || :OLD.SHEET_ID;
  tmpString := tmpString || ' SHEET_NAME=' || :OLD.SHEET_NAME;
  tmpString := tmpString || ' SHEET_ORIENTATION=' || :OLD.SHEET_ORIENTATION;

  INSERT INTO G3E_DELETIONLOG VALUES
    (dlno,
    'GT_PLOT_SHEETS',
    tmpString,
    SYSDATE);
EXCEPTION



  WHEN string_too_long THEN

  INSERT INTO G3E_DELETIONLOG VALUES
    (dlno,
    'GT_PLOT_SHEETS',
    'Error, string length.',
    SYSDATE);
END;
/


CREATE OR REPLACE TRIGGER M_T_BUR_GT_PLOT_SHEETS 
BEFORE UPDATE OF SHEET_ID ON GT_PLOT_SHEETS
FOR EACH ROW
WHEN (
NEW.SHEET_ID != OLD.SHEET_ID
      )
BEGIN
  :NEW.SHEET_ID := :OLD.SHEET_ID;
END;
/


CREATE OR REPLACE TRIGGER M_T_BIUR_GTPLOTSHEET_EDATE 
BEFORE INSERT OR UPDATE ON GT_PLOT_SHEETS
FOR EACH ROW
BEGIN

  :NEW.GTP_EDITDATE := SYSDATE;
END;
/


CREATE OR REPLACE PUBLIC SYNONYM GT_PLOT_SHEETS FOR GT_PLOT_SHEETS;


ALTER TABLE GT_PLOT_SHEETS ADD (
  CONSTRAINT PK_GT_PLOT_SHEETS_SHEET_ID
  PRIMARY KEY
  (SHEET_ID)
  USING INDEX PK_GT_PLOT_SHEETS_SHEET_ID
  ENABLE VALIDATE);

GRANT SELECT ON GT_PLOT_SHEETS TO FINANCE;

GRANT SELECT ON GT_PLOT_SHEETS TO MARKETING;

GRANT DELETE, INSERT, SELECT, UPDATE ON GT_PLOT_SHEETS TO PUBLIC;

Insert into GT_PLOT_SHEETS
   (SHEET_ID, SHEET_NAME, SHEET_NAME_FR, SHEET_HEIGHT, SHEET_WIDTH, 
    SHEET_SIZE, SHEET_ORIENTATION, SHEET_ORIENTATION_FR, GTP_LOCALECOMMENT, GTP_EDITDATE)
 Values
   (1, 'A-Size', 'Taille-A', 279.4, 215.9, 
    '8.5 x 11', 'Portrait', 'Portrait', NULL, TO_DATE('04/05/2013 22:02:05', 'MM/DD/YYYY HH24:MI:SS'));
Insert into GT_PLOT_SHEETS
   (SHEET_ID, SHEET_NAME, SHEET_NAME_FR, SHEET_HEIGHT, SHEET_WIDTH, 
    SHEET_SIZE, SHEET_ORIENTATION, SHEET_ORIENTATION_FR, GTP_LOCALECOMMENT, GTP_EDITDATE)
 Values
   (2, 'A-Size', 'Taille-A', 215.9, 279.4, 
    '8.5 x 11', 'Landscape', 'Paysage', NULL, TO_DATE('04/05/2013 22:02:05', 'MM/DD/YYYY HH24:MI:SS'));
Insert into GT_PLOT_SHEETS
   (SHEET_ID, SHEET_NAME, SHEET_NAME_FR, SHEET_HEIGHT, SHEET_WIDTH, 
    SHEET_SIZE, SHEET_ORIENTATION, SHEET_ORIENTATION_FR, GTP_LOCALECOMMENT, GTP_EDITDATE)
 Values
   (3, 'B-Size', 'Taille-B', 431.8, 279.4, 
    '11 x 17', 'Portrait', 'Portrait', NULL, TO_DATE('04/05/2013 22:02:05', 'MM/DD/YYYY HH24:MI:SS'));
Insert into GT_PLOT_SHEETS
   (SHEET_ID, SHEET_NAME, SHEET_NAME_FR, SHEET_HEIGHT, SHEET_WIDTH, 
    SHEET_SIZE, SHEET_ORIENTATION, SHEET_ORIENTATION_FR, GTP_LOCALECOMMENT, GTP_EDITDATE)
 Values
   (4, 'B-Size', 'Taille-B', 279.4, 431.8, 
    '11 x 17', 'Landscape', 'Paysage', NULL, TO_DATE('04/05/2013 22:02:05', 'MM/DD/YYYY HH24:MI:SS'));
Insert into GT_PLOT_SHEETS
   (SHEET_ID, SHEET_NAME, SHEET_NAME_FR, SHEET_HEIGHT, SHEET_WIDTH, 
    SHEET_SIZE, SHEET_ORIENTATION, SHEET_ORIENTATION_FR, GTP_LOCALECOMMENT, GTP_EDITDATE)
 Values
   (5, 'C-Size', 'Taille-C', 558.8, 431.8, 
    '17 x 22', 'Portrait', 'Portrait', NULL, TO_DATE('04/05/2013 22:02:05', 'MM/DD/YYYY HH24:MI:SS'));
Insert into GT_PLOT_SHEETS
   (SHEET_ID, SHEET_NAME, SHEET_NAME_FR, SHEET_HEIGHT, SHEET_WIDTH, 
    SHEET_SIZE, SHEET_ORIENTATION, SHEET_ORIENTATION_FR, GTP_LOCALECOMMENT, GTP_EDITDATE)
 Values
   (6, 'C-Size', 'Taille-C', 431.8, 558.8, 
    '17 x 22', 'Landscape', 'Paysage', NULL, TO_DATE('04/05/2013 22:02:05', 'MM/DD/YYYY HH24:MI:SS'));
Insert into GT_PLOT_SHEETS
   (SHEET_ID, SHEET_NAME, SHEET_NAME_FR, SHEET_HEIGHT, SHEET_WIDTH, 
    SHEET_SIZE, SHEET_ORIENTATION, SHEET_ORIENTATION_FR, GTP_LOCALECOMMENT, GTP_EDITDATE)
 Values
   (7, 'D-Size', 'Taille-D', 863.6, 558.8, 
    '22 x 34', 'Portrait', 'Portrait', NULL, TO_DATE('04/05/2013 22:02:05', 'MM/DD/YYYY HH24:MI:SS'));
Insert into GT_PLOT_SHEETS
   (SHEET_ID, SHEET_NAME, SHEET_NAME_FR, SHEET_HEIGHT, SHEET_WIDTH, 
    SHEET_SIZE, SHEET_ORIENTATION, SHEET_ORIENTATION_FR, GTP_LOCALECOMMENT, GTP_EDITDATE)
 Values
   (8, 'D-Size', 'Taille-D', 558.8, 863.6, 
    '22 x 34', 'Landscape', 'Paysage', NULL, TO_DATE('04/05/2013 22:02:05', 'MM/DD/YYYY HH24:MI:SS'));
Insert into GT_PLOT_SHEETS
   (SHEET_ID, SHEET_NAME, SHEET_NAME_FR, SHEET_HEIGHT, SHEET_WIDTH, 
    SHEET_SIZE, SHEET_ORIENTATION, SHEET_ORIENTATION_FR, GTP_LOCALECOMMENT, GTP_EDITDATE)
 Values
   (9, 'E-Size', 'Taille-E', 1117.6, 863.6, 
    '34 x 44', 'Portrait', 'Portrait', NULL, TO_DATE('04/05/2013 22:02:05', 'MM/DD/YYYY HH24:MI:SS'));
Insert into GT_PLOT_SHEETS
   (SHEET_ID, SHEET_NAME, SHEET_NAME_FR, SHEET_HEIGHT, SHEET_WIDTH, 
    SHEET_SIZE, SHEET_ORIENTATION, SHEET_ORIENTATION_FR, GTP_LOCALECOMMENT, GTP_EDITDATE)
 Values
   (10, 'E-Size', 'Taille-E', 863.6, 1117.6, 
    '34 x 44', 'Landscape', 'Paysage', NULL, TO_DATE('04/05/2013 22:02:05', 'MM/DD/YYYY HH24:MI:SS'));
COMMIT;
