ALTER TABLE GT_PLOT_GROUPS_DRI
 DROP PRIMARY KEY CASCADE;

DROP TABLE GT_PLOT_GROUPS_DRI CASCADE CONSTRAINTS;

CREATE TABLE GT_PLOT_GROUPS_DRI
(
  GROUP_NO        NUMBER,
  GROUP_NAME      VARCHAR2(255 BYTE),
  DRI_ID          NUMBER,
  USERPLACE       NUMBER                        DEFAULT 0,
  GROUP_OFFSET_X  NUMBER,
  GROUP_OFFSET_Y  NUMBER,
  GROUP_EDITDATE  DATE                          NOT NULL,
  GROUP_REDLINES  NUMBER                        DEFAULT 1
)
TABLESPACE GC_DATA_PRODUCT
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX PK_GT_PLOT_GROUPS_DRI ON GT_PLOT_GROUPS_DRI
(DRI_ID, GROUP_NO)
LOGGING
TABLESPACE GC_DATA_PRODUCT
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE OR REPLACE TRIGGER M_T_BIUR_GTPLOTGRDRI_EDATE 
BEFORE INSERT OR UPDATE ON GT_PLOT_GROUPS_DRI
FOR EACH ROW
BEGIN

  :NEW.GROUP_EDITDATE := SYSDATE;
END;
/


CREATE OR REPLACE PUBLIC SYNONYM GT_PLOT_GROUPS_DRI FOR GT_PLOT_GROUPS_DRI;


ALTER TABLE GT_PLOT_GROUPS_DRI ADD (
  CONSTRAINT PK_GT_PLOT_GROUPS_DRI
  PRIMARY KEY
  (DRI_ID, GROUP_NO)
  USING INDEX PK_GT_PLOT_GROUPS_DRI
  ENABLE VALIDATE);

GRANT SELECT ON GT_PLOT_GROUPS_DRI TO FINANCE;

GRANT SELECT ON GT_PLOT_GROUPS_DRI TO MARKETING;

GRANT DELETE, INSERT, SELECT, UPDATE ON GT_PLOT_GROUPS_DRI TO PUBLIC;

Insert into GT_PLOT_GROUPS_DRI
   (GROUP_NO, GROUP_NAME, DRI_ID, USERPLACE, GROUP_OFFSET_X, 
    GROUP_OFFSET_Y, GROUP_EDITDATE, GROUP_REDLINES)
 Values
   (10001, 'A-Size Portrait  - Map Frame', 10000, 1, 0, 
    0, TO_DATE('11/15/2013 23:34:20', 'MM/DD/YYYY HH24:MI:SS'), 1);
Insert into GT_PLOT_GROUPS_DRI
   (GROUP_NO, GROUP_NAME, DRI_ID, USERPLACE, GROUP_OFFSET_X, 
    GROUP_OFFSET_Y, GROUP_EDITDATE, GROUP_REDLINES)
 Values
   (10002, 'A-Size Landscape - Map Frame', 20000, 1, 0, 
    0, TO_DATE('11/15/2013 23:34:20', 'MM/DD/YYYY HH24:MI:SS'), 1);
Insert into GT_PLOT_GROUPS_DRI
   (GROUP_NO, GROUP_NAME, DRI_ID, USERPLACE, GROUP_OFFSET_X, 
    GROUP_OFFSET_Y, GROUP_EDITDATE, GROUP_REDLINES)
 Values
   (10003, 'B-Size Portrait  - Map Frame', 30000, 1, 0, 
    0, TO_DATE('11/15/2013 23:34:20', 'MM/DD/YYYY HH24:MI:SS'), 1);
Insert into GT_PLOT_GROUPS_DRI
   (GROUP_NO, GROUP_NAME, DRI_ID, USERPLACE, GROUP_OFFSET_X, 
    GROUP_OFFSET_Y, GROUP_EDITDATE, GROUP_REDLINES)
 Values
   (10004, 'B-Size Landscape - Map Frame', 40000, 1, 0, 
    0, TO_DATE('11/15/2013 23:34:20', 'MM/DD/YYYY HH24:MI:SS'), 1);
Insert into GT_PLOT_GROUPS_DRI
   (GROUP_NO, GROUP_NAME, DRI_ID, USERPLACE, GROUP_OFFSET_X, 
    GROUP_OFFSET_Y, GROUP_EDITDATE, GROUP_REDLINES)
 Values
   (10005, 'C-Size Portrait  - Map Frame', 50000, 1, 0, 
    0, TO_DATE('11/15/2013 23:34:20', 'MM/DD/YYYY HH24:MI:SS'), 1);
Insert into GT_PLOT_GROUPS_DRI
   (GROUP_NO, GROUP_NAME, DRI_ID, USERPLACE, GROUP_OFFSET_X, 
    GROUP_OFFSET_Y, GROUP_EDITDATE, GROUP_REDLINES)
 Values
   (10006, 'C-Size Landscape - Map Frame', 60000, 1, 0, 
    0, TO_DATE('11/15/2013 23:34:20', 'MM/DD/YYYY HH24:MI:SS'), 1);
Insert into GT_PLOT_GROUPS_DRI
   (GROUP_NO, GROUP_NAME, DRI_ID, USERPLACE, GROUP_OFFSET_X, 
    GROUP_OFFSET_Y, GROUP_EDITDATE, GROUP_REDLINES)
 Values
   (10007, 'D-Size Portrait  - Map Frame', 70000, 1, 0, 
    0, TO_DATE('11/15/2013 23:34:20', 'MM/DD/YYYY HH24:MI:SS'), 1);
Insert into GT_PLOT_GROUPS_DRI
   (GROUP_NO, GROUP_NAME, DRI_ID, USERPLACE, GROUP_OFFSET_X, 
    GROUP_OFFSET_Y, GROUP_EDITDATE, GROUP_REDLINES)
 Values
   (10008, 'D-Size Landscape - Map Frame', 80000, 1, 0, 
    0, TO_DATE('11/15/2013 23:34:20', 'MM/DD/YYYY HH24:MI:SS'), 1);
Insert into GT_PLOT_GROUPS_DRI
   (GROUP_NO, GROUP_NAME, DRI_ID, USERPLACE, GROUP_OFFSET_X, 
    GROUP_OFFSET_Y, GROUP_EDITDATE, GROUP_REDLINES)
 Values
   (10009, 'E-Size Portrait  - Map Frame', 90000, 1, 0, 
    0, TO_DATE('11/15/2013 23:34:20', 'MM/DD/YYYY HH24:MI:SS'), 1);
Insert into GT_PLOT_GROUPS_DRI
   (GROUP_NO, GROUP_NAME, DRI_ID, USERPLACE, GROUP_OFFSET_X, 
    GROUP_OFFSET_Y, GROUP_EDITDATE, GROUP_REDLINES)
 Values
   (10010, 'E-Size Landscape - Map Frame', 100000, 1, 0, 
    0, TO_DATE('11/15/2013 23:34:20', 'MM/DD/YYYY HH24:MI:SS'), 1);
Insert into GT_PLOT_GROUPS_DRI
   (GROUP_NO, GROUP_NAME, DRI_ID, USERPLACE, GROUP_OFFSET_X, 
    GROUP_OFFSET_Y, GROUP_EDITDATE, GROUP_REDLINES)
 Values
   (10101, 'A-Size Portrait  - Engineering - Map Frame', 10001, 1, 0, 
    0, TO_DATE('11/15/2013 23:34:20', 'MM/DD/YYYY HH24:MI:SS'), 1);
Insert into GT_PLOT_GROUPS_DRI
   (GROUP_NO, GROUP_NAME, DRI_ID, USERPLACE, GROUP_OFFSET_X, 
    GROUP_OFFSET_Y, GROUP_EDITDATE, GROUP_REDLINES)
 Values
   (10102, 'A-Size Landscape - Engineering - Map Frame', 20001, 1, 0, 
    0, TO_DATE('11/15/2013 23:34:20', 'MM/DD/YYYY HH24:MI:SS'), 1);
Insert into GT_PLOT_GROUPS_DRI
   (GROUP_NO, GROUP_NAME, DRI_ID, USERPLACE, GROUP_OFFSET_X, 
    GROUP_OFFSET_Y, GROUP_EDITDATE, GROUP_REDLINES)
 Values
   (10103, 'B-Size Portrait  - Engineering - Map Frame', 30001, 1, 0, 
    0, TO_DATE('11/15/2013 23:34:20', 'MM/DD/YYYY HH24:MI:SS'), 1);
Insert into GT_PLOT_GROUPS_DRI
   (GROUP_NO, GROUP_NAME, DRI_ID, USERPLACE, GROUP_OFFSET_X, 
    GROUP_OFFSET_Y, GROUP_EDITDATE, GROUP_REDLINES)
 Values
   (10104, 'B-Size Landscape - Engineering - Map Frame', 40001, 1, 0, 
    0, TO_DATE('11/15/2013 23:34:20', 'MM/DD/YYYY HH24:MI:SS'), 1);
Insert into GT_PLOT_GROUPS_DRI
   (GROUP_NO, GROUP_NAME, DRI_ID, USERPLACE, GROUP_OFFSET_X, 
    GROUP_OFFSET_Y, GROUP_EDITDATE, GROUP_REDLINES)
 Values
   (10105, 'C-Size Portrait  - Engineering - Map Frame', 50001, 1, 0, 
    0, TO_DATE('11/15/2013 23:34:20', 'MM/DD/YYYY HH24:MI:SS'), 1);
Insert into GT_PLOT_GROUPS_DRI
   (GROUP_NO, GROUP_NAME, DRI_ID, USERPLACE, GROUP_OFFSET_X, 
    GROUP_OFFSET_Y, GROUP_EDITDATE, GROUP_REDLINES)
 Values
   (10106, 'C-Size Landscape - Engineering - Map Frame', 60001, 1, 0, 
    0, TO_DATE('11/15/2013 23:34:20', 'MM/DD/YYYY HH24:MI:SS'), 1);
Insert into GT_PLOT_GROUPS_DRI
   (GROUP_NO, GROUP_NAME, DRI_ID, USERPLACE, GROUP_OFFSET_X, 
    GROUP_OFFSET_Y, GROUP_EDITDATE, GROUP_REDLINES)
 Values
   (10107, 'D-Size Portrait  - Engineering - Map Frame', 70001, 1, 0, 
    0, TO_DATE('11/15/2013 23:34:20', 'MM/DD/YYYY HH24:MI:SS'), 1);
Insert into GT_PLOT_GROUPS_DRI
   (GROUP_NO, GROUP_NAME, DRI_ID, USERPLACE, GROUP_OFFSET_X, 
    GROUP_OFFSET_Y, GROUP_EDITDATE, GROUP_REDLINES)
 Values
   (10108, 'D-Size Landscape - Engineering - Map Frame', 80001, 1, 0, 
    0, TO_DATE('11/15/2013 23:34:20', 'MM/DD/YYYY HH24:MI:SS'), 1);
Insert into GT_PLOT_GROUPS_DRI
   (GROUP_NO, GROUP_NAME, DRI_ID, USERPLACE, GROUP_OFFSET_X, 
    GROUP_OFFSET_Y, GROUP_EDITDATE, GROUP_REDLINES)
 Values
   (10109, 'E-Size Portrait  - Engineering - Map Frame', 90001, 1, 0, 
    0, TO_DATE('11/15/2013 23:34:20', 'MM/DD/YYYY HH24:MI:SS'), 1);
Insert into GT_PLOT_GROUPS_DRI
   (GROUP_NO, GROUP_NAME, DRI_ID, USERPLACE, GROUP_OFFSET_X, 
    GROUP_OFFSET_Y, GROUP_EDITDATE, GROUP_REDLINES)
 Values
   (10110, 'E-Size Landscape - Engineering - Map Frame', 100001, 1, 0, 
    0, TO_DATE('11/15/2013 23:34:20', 'MM/DD/YYYY HH24:MI:SS'), 1);
Insert into GT_PLOT_GROUPS_DRI
   (GROUP_NO, GROUP_NAME, DRI_ID, USERPLACE, GROUP_OFFSET_X, 
    GROUP_OFFSET_Y, GROUP_EDITDATE, GROUP_REDLINES)
 Values
   (20001, 'A-Size Portrait  - Engineering - Redline - Drawing Info', 10001, 0, 17, 
    237, TO_DATE('11/15/2013 23:34:20', 'MM/DD/YYYY HH24:MI:SS'), 0);
Insert into GT_PLOT_GROUPS_DRI
   (GROUP_NO, GROUP_NAME, DRI_ID, USERPLACE, GROUP_OFFSET_X, 
    GROUP_OFFSET_Y, GROUP_EDITDATE, GROUP_REDLINES)
 Values
   (20001, 'A-Size Landscape - Engineering - Redline - Drawing Info', 20001, 0, 80.4, 
    173.3, TO_DATE('11/15/2013 23:34:20', 'MM/DD/YYYY HH24:MI:SS'), 0);
Insert into GT_PLOT_GROUPS_DRI
   (GROUP_NO, GROUP_NAME, DRI_ID, USERPLACE, GROUP_OFFSET_X, 
    GROUP_OFFSET_Y, GROUP_EDITDATE, GROUP_REDLINES)
 Values
   (20001, 'B-Size Portrait  - Engineering - Redline - Drawing Info', 30001, 0, 80.4, 
    389.3, TO_DATE('11/15/2013 23:34:20', 'MM/DD/YYYY HH24:MI:SS'), 0);
Insert into GT_PLOT_GROUPS_DRI
   (GROUP_NO, GROUP_NAME, DRI_ID, USERPLACE, GROUP_OFFSET_X, 
    GROUP_OFFSET_Y, GROUP_EDITDATE, GROUP_REDLINES)
 Values
   (20001, 'B-Size Landscape - Engineering - Redline - Drawing Info', 40001, 0, 232.8, 
    236.9, TO_DATE('11/15/2013 23:34:20', 'MM/DD/YYYY HH24:MI:SS'), 0);
Insert into GT_PLOT_GROUPS_DRI
   (GROUP_NO, GROUP_NAME, DRI_ID, USERPLACE, GROUP_OFFSET_X, 
    GROUP_OFFSET_Y, GROUP_EDITDATE, GROUP_REDLINES)
 Values
   (20001, 'C-Size Portrait  - Engineering - Redline - Drawing Info', 50001, 0, 232.8, 
    516.3, TO_DATE('11/15/2013 23:34:20', 'MM/DD/YYYY HH24:MI:SS'), 0);
Insert into GT_PLOT_GROUPS_DRI
   (GROUP_NO, GROUP_NAME, DRI_ID, USERPLACE, GROUP_OFFSET_X, 
    GROUP_OFFSET_Y, GROUP_EDITDATE, GROUP_REDLINES)
 Values
   (20001, 'C-Size Landscape - Engineering - Redline - Drawing Info', 60001, 0, 359.8, 
    389.3, TO_DATE('11/15/2013 23:34:20', 'MM/DD/YYYY HH24:MI:SS'), 0);
Insert into GT_PLOT_GROUPS_DRI
   (GROUP_NO, GROUP_NAME, DRI_ID, USERPLACE, GROUP_OFFSET_X, 
    GROUP_OFFSET_Y, GROUP_EDITDATE, GROUP_REDLINES)
 Values
   (20001, 'D-Size Portrait  - Engineering - Redline - Drawing Info', 70001, 0, 359.8, 
    821.1, TO_DATE('11/15/2013 23:34:20', 'MM/DD/YYYY HH24:MI:SS'), 0);
Insert into GT_PLOT_GROUPS_DRI
   (GROUP_NO, GROUP_NAME, DRI_ID, USERPLACE, GROUP_OFFSET_X, 
    GROUP_OFFSET_Y, GROUP_EDITDATE, GROUP_REDLINES)
 Values
   (20001, 'D-Size Landscape - Engineering - Redline - Drawing Info', 80001, 0, 664.6, 
    516.3, TO_DATE('11/15/2013 23:34:20', 'MM/DD/YYYY HH24:MI:SS'), 0);
Insert into GT_PLOT_GROUPS_DRI
   (GROUP_NO, GROUP_NAME, DRI_ID, USERPLACE, GROUP_OFFSET_X, 
    GROUP_OFFSET_Y, GROUP_EDITDATE, GROUP_REDLINES)
 Values
   (20001, 'E-Size Portrait  - Engineering - Redline - Drawing Info', 90001, 0, 664.6, 
    1075.1, TO_DATE('11/15/2013 23:34:20', 'MM/DD/YYYY HH24:MI:SS'), 0);
Insert into GT_PLOT_GROUPS_DRI
   (GROUP_NO, GROUP_NAME, DRI_ID, USERPLACE, GROUP_OFFSET_X, 
    GROUP_OFFSET_Y, GROUP_EDITDATE, GROUP_REDLINES)
 Values
   (20001, 'E-Size Landscape - Engineering - Redline - Drawing Info', 100001, 0, 918.6, 
    820.1, TO_DATE('11/15/2013 23:34:20', 'MM/DD/YYYY HH24:MI:SS'), 0);
Insert into GT_PLOT_GROUPS_DRI
   (GROUP_NO, GROUP_NAME, DRI_ID, USERPLACE, GROUP_OFFSET_X, 
    GROUP_OFFSET_Y, GROUP_EDITDATE, GROUP_REDLINES)
 Values
   (11, 'Map Frame Marker', 100001, 0, 0, 
    0, TO_DATE('11/15/2013 23:34:20', 'MM/DD/YYYY HH24:MI:SS'), 1);
Insert into GT_PLOT_GROUPS_DRI
   (GROUP_NO, GROUP_NAME, DRI_ID, USERPLACE, GROUP_OFFSET_X, 
    GROUP_OFFSET_Y, GROUP_EDITDATE, GROUP_REDLINES)
 Values
   (11, 'Map Frame Marker', 90001, 0, 0, 
    0, TO_DATE('11/15/2013 23:34:20', 'MM/DD/YYYY HH24:MI:SS'), 1);
Insert into GT_PLOT_GROUPS_DRI
   (GROUP_NO, GROUP_NAME, DRI_ID, USERPLACE, GROUP_OFFSET_X, 
    GROUP_OFFSET_Y, GROUP_EDITDATE, GROUP_REDLINES)
 Values
   (11, 'Map Frame Marker', 80001, 0, 0, 
    0, TO_DATE('11/15/2013 23:34:20', 'MM/DD/YYYY HH24:MI:SS'), 1);
Insert into GT_PLOT_GROUPS_DRI
   (GROUP_NO, GROUP_NAME, DRI_ID, USERPLACE, GROUP_OFFSET_X, 
    GROUP_OFFSET_Y, GROUP_EDITDATE, GROUP_REDLINES)
 Values
   (11, 'Map Frame Marker', 70001, 0, 0, 
    0, TO_DATE('11/15/2013 23:34:20', 'MM/DD/YYYY HH24:MI:SS'), 1);
Insert into GT_PLOT_GROUPS_DRI
   (GROUP_NO, GROUP_NAME, DRI_ID, USERPLACE, GROUP_OFFSET_X, 
    GROUP_OFFSET_Y, GROUP_EDITDATE, GROUP_REDLINES)
 Values
   (11, 'Map Frame Marker', 60001, 0, 0, 
    0, TO_DATE('11/15/2013 23:34:20', 'MM/DD/YYYY HH24:MI:SS'), 1);
Insert into GT_PLOT_GROUPS_DRI
   (GROUP_NO, GROUP_NAME, DRI_ID, USERPLACE, GROUP_OFFSET_X, 
    GROUP_OFFSET_Y, GROUP_EDITDATE, GROUP_REDLINES)
 Values
   (11, 'Map Frame Marker', 50001, 0, 0, 
    0, TO_DATE('11/15/2013 23:34:20', 'MM/DD/YYYY HH24:MI:SS'), 1);
Insert into GT_PLOT_GROUPS_DRI
   (GROUP_NO, GROUP_NAME, DRI_ID, USERPLACE, GROUP_OFFSET_X, 
    GROUP_OFFSET_Y, GROUP_EDITDATE, GROUP_REDLINES)
 Values
   (11, 'Map Frame Marker', 40001, 0, 0, 
    0, TO_DATE('11/15/2013 23:34:20', 'MM/DD/YYYY HH24:MI:SS'), 1);
Insert into GT_PLOT_GROUPS_DRI
   (GROUP_NO, GROUP_NAME, DRI_ID, USERPLACE, GROUP_OFFSET_X, 
    GROUP_OFFSET_Y, GROUP_EDITDATE, GROUP_REDLINES)
 Values
   (11, 'Map Frame Marker', 30001, 0, 0, 
    0, TO_DATE('11/15/2013 23:34:20', 'MM/DD/YYYY HH24:MI:SS'), 1);
Insert into GT_PLOT_GROUPS_DRI
   (GROUP_NO, GROUP_NAME, DRI_ID, USERPLACE, GROUP_OFFSET_X, 
    GROUP_OFFSET_Y, GROUP_EDITDATE, GROUP_REDLINES)
 Values
   (11, 'Map Frame Marker', 20001, 0, 0, 
    0, TO_DATE('11/15/2013 23:34:20', 'MM/DD/YYYY HH24:MI:SS'), 1);
Insert into GT_PLOT_GROUPS_DRI
   (GROUP_NO, GROUP_NAME, DRI_ID, USERPLACE, GROUP_OFFSET_X, 
    GROUP_OFFSET_Y, GROUP_EDITDATE, GROUP_REDLINES)
 Values
   (11, 'Map Frame Marker', 10001, 0, 0, 
    0, TO_DATE('11/15/2013 23:34:20', 'MM/DD/YYYY HH24:MI:SS'), 1);
Insert into GT_PLOT_GROUPS_DRI
   (GROUP_NO, GROUP_NAME, DRI_ID, USERPLACE, GROUP_OFFSET_X, 
    GROUP_OFFSET_Y, GROUP_EDITDATE, GROUP_REDLINES)
 Values
   (12, 'Map Frame Marker', 10001, 0, 0, 
    0, TO_DATE('11/15/2013 23:34:20', 'MM/DD/YYYY HH24:MI:SS'), 1);
Insert into GT_PLOT_GROUPS_DRI
   (GROUP_NO, GROUP_NAME, DRI_ID, USERPLACE, GROUP_OFFSET_X, 
    GROUP_OFFSET_Y, GROUP_EDITDATE, GROUP_REDLINES)
 Values
   (22, 'Map Frame Marker', 20001, 0, 0, 
    0, TO_DATE('11/15/2013 23:34:20', 'MM/DD/YYYY HH24:MI:SS'), 1);
Insert into GT_PLOT_GROUPS_DRI
   (GROUP_NO, GROUP_NAME, DRI_ID, USERPLACE, GROUP_OFFSET_X, 
    GROUP_OFFSET_Y, GROUP_EDITDATE, GROUP_REDLINES)
 Values
   (32, 'Map Frame Marker', 30001, 0, 0, 
    0, TO_DATE('11/15/2013 23:34:20', 'MM/DD/YYYY HH24:MI:SS'), 1);
Insert into GT_PLOT_GROUPS_DRI
   (GROUP_NO, GROUP_NAME, DRI_ID, USERPLACE, GROUP_OFFSET_X, 
    GROUP_OFFSET_Y, GROUP_EDITDATE, GROUP_REDLINES)
 Values
   (42, 'Map Frame Marker', 40001, 0, 0, 
    0, TO_DATE('11/15/2013 23:34:20', 'MM/DD/YYYY HH24:MI:SS'), 1);
Insert into GT_PLOT_GROUPS_DRI
   (GROUP_NO, GROUP_NAME, DRI_ID, USERPLACE, GROUP_OFFSET_X, 
    GROUP_OFFSET_Y, GROUP_EDITDATE, GROUP_REDLINES)
 Values
   (52, 'Map Frame Marker', 50001, 0, 0, 
    0, TO_DATE('11/15/2013 23:34:20', 'MM/DD/YYYY HH24:MI:SS'), 1);
Insert into GT_PLOT_GROUPS_DRI
   (GROUP_NO, GROUP_NAME, DRI_ID, USERPLACE, GROUP_OFFSET_X, 
    GROUP_OFFSET_Y, GROUP_EDITDATE, GROUP_REDLINES)
 Values
   (62, 'Map Frame Marker', 60001, 0, 0, 
    0, TO_DATE('11/15/2013 23:34:20', 'MM/DD/YYYY HH24:MI:SS'), 1);
Insert into GT_PLOT_GROUPS_DRI
   (GROUP_NO, GROUP_NAME, DRI_ID, USERPLACE, GROUP_OFFSET_X, 
    GROUP_OFFSET_Y, GROUP_EDITDATE, GROUP_REDLINES)
 Values
   (72, 'Map Frame Marker', 70001, 0, 0, 
    0, TO_DATE('11/15/2013 23:34:20', 'MM/DD/YYYY HH24:MI:SS'), 1);
Insert into GT_PLOT_GROUPS_DRI
   (GROUP_NO, GROUP_NAME, DRI_ID, USERPLACE, GROUP_OFFSET_X, 
    GROUP_OFFSET_Y, GROUP_EDITDATE, GROUP_REDLINES)
 Values
   (82, 'Map Frame Marker', 80001, 0, 0, 
    0, TO_DATE('11/15/2013 23:34:20', 'MM/DD/YYYY HH24:MI:SS'), 1);
Insert into GT_PLOT_GROUPS_DRI
   (GROUP_NO, GROUP_NAME, DRI_ID, USERPLACE, GROUP_OFFSET_X, 
    GROUP_OFFSET_Y, GROUP_EDITDATE, GROUP_REDLINES)
 Values
   (92, 'Map Frame Marker', 90001, 0, 0, 
    0, TO_DATE('11/15/2013 23:34:20', 'MM/DD/YYYY HH24:MI:SS'), 1);
Insert into GT_PLOT_GROUPS_DRI
   (GROUP_NO, GROUP_NAME, DRI_ID, USERPLACE, GROUP_OFFSET_X, 
    GROUP_OFFSET_Y, GROUP_EDITDATE, GROUP_REDLINES)
 Values
   (102, 'Map Frame Marker', 100001, 0, 0, 
    0, TO_DATE('11/15/2013 23:34:20', 'MM/DD/YYYY HH24:MI:SS'), 1);
Insert into GT_PLOT_GROUPS_DRI
   (GROUP_NO, GROUP_NAME, DRI_ID, USERPLACE, GROUP_OFFSET_X, 
    GROUP_OFFSET_Y, GROUP_EDITDATE, GROUP_REDLINES)
 Values
   (30001, 'A-Size Portrait  - Engineering - Redline - Drawing Info', 10001, 0, 170, 
    20, TO_DATE('08/01/2014 22:03:47', 'MM/DD/YYYY HH24:MI:SS'), 0);
Insert into GT_PLOT_GROUPS_DRI
   (GROUP_NO, GROUP_NAME, DRI_ID, USERPLACE, GROUP_OFFSET_X, 
    GROUP_OFFSET_Y, GROUP_EDITDATE, GROUP_REDLINES)
 Values
   (30001, 'A-Size Landscape - Engineering - Redline - Drawing Info', 20001, 0, 232.46, 
    20, TO_DATE('08/01/2014 22:03:47', 'MM/DD/YYYY HH24:MI:SS'), 0);
Insert into GT_PLOT_GROUPS_DRI
   (GROUP_NO, GROUP_NAME, DRI_ID, USERPLACE, GROUP_OFFSET_X, 
    GROUP_OFFSET_Y, GROUP_EDITDATE, GROUP_REDLINES)
 Values
   (30001, 'B-Size Portrait  - Engineering - Redline - Arb Info', 30001, 0, 267.46, 
    20, TO_DATE('08/01/2014 22:03:47', 'MM/DD/YYYY HH24:MI:SS'), 0);
Insert into GT_PLOT_GROUPS_DRI
   (GROUP_NO, GROUP_NAME, DRI_ID, USERPLACE, GROUP_OFFSET_X, 
    GROUP_OFFSET_Y, GROUP_EDITDATE, GROUP_REDLINES)
 Values
   (30001, 'B-Size Landscape - Engineering - Redline - Arb Info', 40001, 0, 359.8, 
    20, TO_DATE('08/01/2014 22:03:47', 'MM/DD/YYYY HH24:MI:SS'), 0);
Insert into GT_PLOT_GROUPS_DRI
   (GROUP_NO, GROUP_NAME, DRI_ID, USERPLACE, GROUP_OFFSET_X, 
    GROUP_OFFSET_Y, GROUP_EDITDATE, GROUP_REDLINES)
 Values
   (30001, 'C-Size Portrait  - Engineering - Redline - Arb Info', 50001, 0, 419.93, 
    20, TO_DATE('08/01/2014 22:03:47', 'MM/DD/YYYY HH24:MI:SS'), 0);
Insert into GT_PLOT_GROUPS_DRI
   (GROUP_NO, GROUP_NAME, DRI_ID, USERPLACE, GROUP_OFFSET_X, 
    GROUP_OFFSET_Y, GROUP_EDITDATE, GROUP_REDLINES)
 Values
   (30001, 'C-Size Landscape - Engineering - Redline - Arb Info', 60001, 0, 486.94, 
    20, TO_DATE('08/01/2014 22:03:47', 'MM/DD/YYYY HH24:MI:SS'), 0);
Insert into GT_PLOT_GROUPS_DRI
   (GROUP_NO, GROUP_NAME, DRI_ID, USERPLACE, GROUP_OFFSET_X, 
    GROUP_OFFSET_Y, GROUP_EDITDATE, GROUP_REDLINES)
 Values
   (30001, 'D-Size Portrait  - Engineering - Redline - Arb Info', 70001, 0, 546.86, 
    20, TO_DATE('08/01/2014 22:03:47', 'MM/DD/YYYY HH24:MI:SS'), 0);
Insert into GT_PLOT_GROUPS_DRI
   (GROUP_NO, GROUP_NAME, DRI_ID, USERPLACE, GROUP_OFFSET_X, 
    GROUP_OFFSET_Y, GROUP_EDITDATE, GROUP_REDLINES)
 Values
   (30001, 'D-Size Landscape - Engineering - Redline - Arb Info', 80001, 0, 791.6, 
    20, TO_DATE('08/01/2014 22:03:47', 'MM/DD/YYYY HH24:MI:SS'), 0);
Insert into GT_PLOT_GROUPS_DRI
   (GROUP_NO, GROUP_NAME, DRI_ID, USERPLACE, GROUP_OFFSET_X, 
    GROUP_OFFSET_Y, GROUP_EDITDATE, GROUP_REDLINES)
 Values
   (30001, 'E-Size Portrait  - Engineering - Redline - Arb Info', 90001, 0, 791.6, 
    20, TO_DATE('08/01/2014 22:03:47', 'MM/DD/YYYY HH24:MI:SS'), 0);
Insert into GT_PLOT_GROUPS_DRI
   (GROUP_NO, GROUP_NAME, DRI_ID, USERPLACE, GROUP_OFFSET_X, 
    GROUP_OFFSET_Y, GROUP_EDITDATE, GROUP_REDLINES)
 Values
   (30001, 'E-Size Landscape - Engineering - Redline - Arb Info', 100001, 0, 1045.6, 
    20, TO_DATE('08/01/2014 22:03:47', 'MM/DD/YYYY HH24:MI:SS'), 0);
COMMIT;
