ALTER TABLE GT_PLOT_REDLINES
 DROP PRIMARY KEY CASCADE;

DROP TABLE GT_PLOT_REDLINES CASCADE CONSTRAINTS;

CREATE TABLE GT_PLOT_REDLINES
(
  RL_NO                 NUMBER,
  GROUP_NO              NUMBER,
  RL_DATATYPE           VARCHAR2(30 BYTE),
  RL_COORDINATE_X1      NUMBER,
  RL_COORDINATE_Y1      NUMBER,
  RL_COORDINATE_X2      NUMBER,
  RL_COORDINATE_Y2      NUMBER,
  RL_STYLE_NUMBER       NUMBER,
  RL_TEXT_ALIGNMENT     NUMBER                  DEFAULT 0,
  RL_ROTATION           NUMBER                  DEFAULT 0,
  RL_TEXT               VARCHAR2(255 BYTE),
  RL_NAME               VARCHAR2(255 BYTE),
  RL_TEXT_DEFAULT       VARCHAR2(255 BYTE),
  RL_TEXT_FR            VARCHAR2(255 BYTE),
  RL_NAME_FR            VARCHAR2(255 BYTE),
  RL_TEXT_DEFAULT_FR    VARCHAR2(255 BYTE),
  RL_TEXT_TRIGGERED_BY  VARCHAR2(255 BYTE),
  RL_TEXT_ORDINAL       NUMBER,
  RL_USERINPUT          NUMBER                  DEFAULT 0,
  RL_EDITDATE           DATE                    NOT NULL
)
TABLESPACE GC_DATA_PRODUCT
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX PK_GT_PLOT_REDLINES_RL_NO ON GT_PLOT_REDLINES
(RL_NO)
LOGGING
TABLESPACE GC_DATA_PRODUCT
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE OR REPLACE TRIGGER M_T_BIUR_GTPLOTREDLN_EDATE 
BEFORE INSERT OR UPDATE ON GT_PLOT_REDLINES
FOR EACH ROW
BEGIN

  :NEW.RL_EDITDATE := SYSDATE;
END;
/


CREATE OR REPLACE TRIGGER M_T_BIUR_GT_PLOT_REDLINES 
BEFORE INSERT OR UPDATE
ON GT_PLOT_REDLINES
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
DECLARE
  refValue            NUMBER;
  invalid_reference   EXCEPTION;
  CURSOR curReference (newValue NUMBER) IS
    SELECT GROUP_NO
    FROM GT_PLOT_GROUPS_DRI
    WHERE GROUP_NO = newValue;
BEGIN

  OPEN curReference(:NEW.GROUP_NO);
  FETCH curReference INTO refValue;
  IF curReference%NOTFOUND THEN
    RAISE invalid_reference;
  END IF;
  CLOSE curReference;

EXCEPTION
  WHEN invalid_reference THEN
    CLOSE curReference;
    raise_application_error ( -20001, 'A reference to GT_PLOT_REDLINES.GROUP_NO=' || :NEW.GROUP_NO || ' does not exists in GT_PLOT_GROUPS_DRI.GROUP_NO');
  WHEN OTHERS THEN
    RAISE;
END M_T_BIUR_GT_PLOT_REDLINES;
/


CREATE OR REPLACE PUBLIC SYNONYM GT_PLOT_REDLINES FOR GT_PLOT_REDLINES;


ALTER TABLE GT_PLOT_REDLINES ADD (
  CONSTRAINT PK_GT_PLOT_REDLINES_RL_NO
  PRIMARY KEY
  (RL_NO)
  USING INDEX PK_GT_PLOT_REDLINES_RL_NO
  ENABLE VALIDATE);

GRANT SELECT ON GT_PLOT_REDLINES TO FINANCE;

GRANT SELECT ON GT_PLOT_REDLINES TO MARKETING;

GRANT SELECT ON GT_PLOT_REDLINES TO PUBLIC;

Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_NAME, RL_TEXT_DEFAULT, RL_TEXT_FR, RL_NAME_FR, 
    RL_TEXT_DEFAULT_FR, RL_TEXT_TRIGGERED_BY, RL_TEXT_ORDINAL, RL_USERINPUT, RL_EDITDATE)
 Values
   (20001001, 20001, 'Redline Lines', 0, 7.5, 
    122, 7.5, 5010, 0, 0, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, 0, TO_DATE('04/05/2013 22:02:05', 'MM/DD/YYYY HH24:MI:SS'));
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_NAME, RL_TEXT_DEFAULT, RL_TEXT_FR, RL_NAME_FR, 
    RL_TEXT_DEFAULT_FR, RL_TEXT_TRIGGERED_BY, RL_TEXT_ORDINAL, RL_USERINPUT, RL_EDITDATE)
 Values
   (20001002, 20001, 'Redline Lines', 0, 0, 
    182, 0, 5010, 0, 0, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, 0, TO_DATE('04/05/2013 22:02:05', 'MM/DD/YYYY HH24:MI:SS'));
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_NAME, RL_TEXT_DEFAULT, RL_TEXT_FR, RL_NAME_FR, 
    RL_TEXT_DEFAULT_FR, RL_TEXT_TRIGGERED_BY, RL_TEXT_ORDINAL, RL_USERINPUT, RL_EDITDATE)
 Values
   (20001003, 20001, 'Redline Lines', 182, 0, 
    182, 25.5, 5010, 0, 0, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, 0, TO_DATE('04/05/2013 22:02:05', 'MM/DD/YYYY HH24:MI:SS'));
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_NAME, RL_TEXT_DEFAULT, RL_TEXT_FR, RL_NAME_FR, 
    RL_TEXT_DEFAULT_FR, RL_TEXT_TRIGGERED_BY, RL_TEXT_ORDINAL, RL_USERINPUT, RL_EDITDATE)
 Values
   (20001004, 20001, 'Redline Lines', 0, 23, 
    182, 23, 5010, 0, 0, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, 0, TO_DATE('04/05/2013 22:02:05', 'MM/DD/YYYY HH24:MI:SS'));
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_NAME, RL_TEXT_DEFAULT, RL_TEXT_FR, RL_NAME_FR, 
    RL_TEXT_DEFAULT_FR, RL_TEXT_TRIGGERED_BY, RL_TEXT_ORDINAL, RL_USERINPUT, RL_EDITDATE)
 Values
   (20001005, 20001, 'Redline Lines', 60, 15, 
    182, 15, 5010, 0, 0, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, 0, TO_DATE('04/05/2013 22:02:05', 'MM/DD/YYYY HH24:MI:SS'));
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_NAME, RL_TEXT_DEFAULT, RL_TEXT_FR, RL_NAME_FR, 
    RL_TEXT_DEFAULT_FR, RL_TEXT_TRIGGERED_BY, RL_TEXT_ORDINAL, RL_USERINPUT, RL_EDITDATE)
 Values
   (20001006, 20001, 'Redline Lines', 182, 25.5, 
    0, 25.5, 5010, 0, 0, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, 0, TO_DATE('04/05/2013 22:02:05', 'MM/DD/YYYY HH24:MI:SS'));
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_NAME, RL_TEXT_DEFAULT, RL_TEXT_FR, RL_NAME_FR, 
    RL_TEXT_DEFAULT_FR, RL_TEXT_TRIGGERED_BY, RL_TEXT_ORDINAL, RL_USERINPUT, RL_EDITDATE)
 Values
   (20001007, 20001, 'Redline Lines', 60, 0, 
    60, 23, 5010, 0, 0, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, 0, TO_DATE('04/05/2013 22:02:05', 'MM/DD/YYYY HH24:MI:SS'));
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_NAME, RL_TEXT_DEFAULT, RL_TEXT_FR, RL_NAME_FR, 
    RL_TEXT_DEFAULT_FR, RL_TEXT_TRIGGERED_BY, RL_TEXT_ORDINAL, RL_USERINPUT, RL_EDITDATE)
 Values
   (20001008, 20001, 'Redline Lines', 0, 25.5, 
    0, 0, 5010, 0, 0, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, 0, TO_DATE('04/05/2013 22:02:05', 'MM/DD/YYYY HH24:MI:SS'));
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_NAME, RL_TEXT_DEFAULT, RL_TEXT_FR, RL_NAME_FR, 
    RL_TEXT_DEFAULT_FR, RL_TEXT_TRIGGERED_BY, RL_TEXT_ORDINAL, RL_USERINPUT, RL_EDITDATE)
 Values
   (20001009, 20001, 'Redline Lines', 152, 15, 
    152, 23, 5010, 0, 0, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, 0, TO_DATE('04/05/2013 22:02:05', 'MM/DD/YYYY HH24:MI:SS'));
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_NAME, RL_TEXT_DEFAULT, RL_TEXT_FR, RL_NAME_FR, 
    RL_TEXT_DEFAULT_FR, RL_TEXT_TRIGGERED_BY, RL_TEXT_ORDINAL, RL_USERINPUT, RL_EDITDATE)
 Values
   (20001010, 20001, 'Redline Lines', 122, 0, 
    122, 23, 5010, 0, 0, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, 0, TO_DATE('04/05/2013 22:02:05', 'MM/DD/YYYY HH24:MI:SS'));
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_NAME, RL_TEXT_DEFAULT, RL_TEXT_FR, RL_NAME_FR, 
    RL_TEXT_DEFAULT_FR, RL_TEXT_TRIGGERED_BY, RL_TEXT_ORDINAL, RL_USERINPUT, RL_EDITDATE)
 Values
   (20001011, 20001, 'Redline Lines', 29, 0, 
    29, 7.5, 5010, 0, 0, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, 0, TO_DATE('04/05/2013 22:02:05', 'MM/DD/YYYY HH24:MI:SS'));
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_NAME, RL_TEXT_DEFAULT, RL_TEXT_FR, RL_NAME_FR, 
    RL_TEXT_DEFAULT_FR, RL_TEXT_TRIGGERED_BY, RL_TEXT_ORDINAL, RL_USERINPUT, RL_EDITDATE)
 Values
   (20001012, 20001, 'Redline Text', 1, 1.5, 
    NULL, NULL, 5034, 1, 0, 
    'ISSUE DATE', NULL, NULL, 'DATE EMIS', NULL, 
    NULL, NULL, NULL, 0, TO_DATE('04/05/2013 22:02:05', 'MM/DD/YYYY HH24:MI:SS'));
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_NAME, RL_TEXT_DEFAULT, RL_TEXT_FR, RL_NAME_FR, 
    RL_TEXT_DEFAULT_FR, RL_TEXT_TRIGGERED_BY, RL_TEXT_ORDINAL, RL_USERINPUT, RL_EDITDATE)
 Values
   (20001013, 20001, 'Redline Text', 123, 1.5, 
    NULL, NULL, 5034, 1, 0, 
    'SIGNATURE', NULL, NULL, 'SIGNATURE', NULL, 
    NULL, NULL, NULL, 0, TO_DATE('04/05/2013 22:02:05', 'MM/DD/YYYY HH24:MI:SS'));
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_NAME, RL_TEXT_DEFAULT, RL_TEXT_FR, RL_NAME_FR, 
    RL_TEXT_DEFAULT_FR, RL_TEXT_TRIGGERED_BY, RL_TEXT_ORDINAL, RL_USERINPUT, RL_EDITDATE)
 Values
   (20001014, 20001, 'Redline Text', 61, 16.5, 
    NULL, NULL, 5034, 1, 0, 
    'CLLI', NULL, NULL, 'SUCAL', NULL, 
    NULL, NULL, NULL, 0, TO_DATE('04/05/2013 22:02:05', 'MM/DD/YYYY HH24:MI:SS'));
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_NAME, RL_TEXT_DEFAULT, RL_TEXT_FR, RL_NAME_FR, 
    RL_TEXT_DEFAULT_FR, RL_TEXT_TRIGGERED_BY, RL_TEXT_ORDINAL, RL_USERINPUT, RL_EDITDATE)
 Values
   (20001015, 20001, 'Redline Text', 153, 16.5, 
    NULL, NULL, 5034, 1, 0, 
    'PLAN', NULL, NULL, 'PLAN', NULL, 
    NULL, NULL, NULL, 0, TO_DATE('04/05/2013 22:02:05', 'MM/DD/YYYY HH24:MI:SS'));
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_NAME, RL_TEXT_DEFAULT, RL_TEXT_FR, RL_NAME_FR, 
    RL_TEXT_DEFAULT_FR, RL_TEXT_TRIGGERED_BY, RL_TEXT_ORDINAL, RL_USERINPUT, RL_EDITDATE)
 Values
   (20001016, 20001, 'Redline Text', 61, 20, 
    NULL, NULL, 5035, 1, 0, 
    '[SWITCH_CENTRE_CLLI]', NULL, NULL, '[SWITCH_CENTRE_CLLI]', NULL, 
    NULL, '[SWITCH_CENTRE_NAME]', 8, 0, TO_DATE('04/05/2013 22:02:05', 'MM/DD/YYYY HH24:MI:SS'));
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_NAME, RL_TEXT_DEFAULT, RL_TEXT_FR, RL_NAME_FR, 
    RL_TEXT_DEFAULT_FR, RL_TEXT_TRIGGERED_BY, RL_TEXT_ORDINAL, RL_USERINPUT, RL_EDITDATE)
 Values
   (20001017, 20001, 'Redline Text', 123, 12.3, 
    NULL, NULL, 5035, 1, 0, 
    '[ORIGINATOR_INFO]', 'Originator / Phone', NULL, '[ORIGINATOR_INFO]', 'Auteur / Telephone', 
    NULL, NULL, 2, 0, TO_DATE('04/05/2013 22:02:05', 'MM/DD/YYYY HH24:MI:SS'));
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_NAME, RL_TEXT_DEFAULT, RL_TEXT_FR, RL_NAME_FR, 
    RL_TEXT_DEFAULT_FR, RL_TEXT_TRIGGERED_BY, RL_TEXT_ORDINAL, RL_USERINPUT, RL_EDITDATE)
 Values
   (20001018, 20001, 'Redline Text', 61, 12.3, 
    NULL, NULL, 5035, 1, 0, 
    '[ROW_NUMBER]', NULL, NULL, '[ROW_NUMBER]', NULL, 
    NULL, NULL, 4, 0, TO_DATE('04/05/2013 22:02:05', 'MM/DD/YYYY HH24:MI:SS'));
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_NAME, RL_TEXT_DEFAULT, RL_TEXT_FR, RL_NAME_FR, 
    RL_TEXT_DEFAULT_FR, RL_TEXT_TRIGGERED_BY, RL_TEXT_ORDINAL, RL_USERINPUT, RL_EDITDATE)
 Values
   (20001019, 20001, 'Redline Text', 90, 20, 
    NULL, NULL, 5035, 1, 0, 
    '[SWITCH_CENTRE_NAME]', 'Switch Center Name', NULL, '[SWITCH_CENTRE_NAME]', 'Sucal', 
    NULL, '[SWITCH_CENTRE_CLLI]', 9, 0, TO_DATE('04/05/2013 22:02:05', 'MM/DD/YYYY HH24:MI:SS'));
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_NAME, RL_TEXT_DEFAULT, RL_TEXT_FR, RL_NAME_FR, 
    RL_TEXT_DEFAULT_FR, RL_TEXT_TRIGGERED_BY, RL_TEXT_ORDINAL, RL_USERINPUT, RL_EDITDATE)
 Values
   (20001020, 20001, 'Redline Text', 153, 20, 
    NULL, NULL, 5036, 1, 0, 
    '[PLAN_ID]', NULL, NULL, '[PLAN_ID]', NULL, 
    NULL, NULL, 1, 0, TO_DATE('04/05/2013 22:02:05', 'MM/DD/YYYY HH24:MI:SS'));
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_NAME, RL_TEXT_DEFAULT, RL_TEXT_FR, RL_NAME_FR, 
    RL_TEXT_DEFAULT_FR, RL_TEXT_TRIGGERED_BY, RL_TEXT_ORDINAL, RL_USERINPUT, RL_EDITDATE)
 Values
   (20001021, 20001, 'Redline Text', 123, 20, 
    NULL, NULL, 5036, 1, 0, 
    '[WORK_ORDER_ID]', NULL, NULL, '[WORK_ORDER_ID]', NULL, 
    NULL, NULL, 7, 0, TO_DATE('04/05/2013 22:02:05', 'MM/DD/YYYY HH24:MI:SS'));
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_NAME, RL_TEXT_DEFAULT, RL_TEXT_FR, RL_NAME_FR, 
    RL_TEXT_DEFAULT_FR, RL_TEXT_TRIGGERED_BY, RL_TEXT_ORDINAL, RL_USERINPUT, RL_EDITDATE)
 Values
   (20001022, 20001, 'Redline Text', 123, 9, 
    NULL, NULL, 5034, 1, 0, 
    'ORIGINATOR / PHONE', NULL, NULL, 'AUTEUR / TELEPHONE', NULL, 
    NULL, NULL, NULL, 0, TO_DATE('04/05/2013 22:02:05', 'MM/DD/YYYY HH24:MI:SS'));
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_NAME, RL_TEXT_DEFAULT, RL_TEXT_FR, RL_NAME_FR, 
    RL_TEXT_DEFAULT_FR, RL_TEXT_TRIGGERED_BY, RL_TEXT_ORDINAL, RL_USERINPUT, RL_EDITDATE)
 Values
   (20001023, 20001, 'Redline Text', 30, 5, 
    NULL, NULL, 5035, 1, 0, 
    '[REISSUE_DATE]', NULL, NULL, '[REISSUE_DATE]', NULL, 
    NULL, NULL, 6, 0, TO_DATE('04/05/2013 22:02:05', 'MM/DD/YYYY HH24:MI:SS'));
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_NAME, RL_TEXT_DEFAULT, RL_TEXT_FR, RL_NAME_FR, 
    RL_TEXT_DEFAULT_FR, RL_TEXT_TRIGGERED_BY, RL_TEXT_ORDINAL, RL_USERINPUT, RL_EDITDATE)
 Values
   (20001024, 20001, 'Redline Text', 1, 5, 
    NULL, NULL, 5035, 1, 0, 
    '[ISSUE_DATE]', NULL, NULL, '[ISSUE_DATE]', NULL, 
    NULL, NULL, 5, 0, TO_DATE('04/05/2013 22:02:05', 'MM/DD/YYYY HH24:MI:SS'));
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_NAME, RL_TEXT_DEFAULT, RL_TEXT_FR, RL_NAME_FR, 
    RL_TEXT_DEFAULT_FR, RL_TEXT_TRIGGERED_BY, RL_TEXT_ORDINAL, RL_USERINPUT, RL_EDITDATE)
 Values
   (20001025, 20001, 'Redline Text', 80, 24, 
    NULL, NULL, 5034, 1, 0, 
    'Copyright Bell Canada', NULL, NULL, 'Copyright Bell Canada', NULL, 
    NULL, NULL, NULL, 0, TO_DATE('04/05/2013 22:02:05', 'MM/DD/YYYY HH24:MI:SS'));
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_NAME, RL_TEXT_DEFAULT, RL_TEXT_FR, RL_NAME_FR, 
    RL_TEXT_DEFAULT_FR, RL_TEXT_TRIGGERED_BY, RL_TEXT_ORDINAL, RL_USERINPUT, RL_EDITDATE)
 Values
   (20001026, 20001, 'Redline Text', 90, 16.5, 
    NULL, NULL, 5034, 1, 0, 
    'SC', NULL, NULL, 'CC', NULL, 
    NULL, NULL, NULL, 0, TO_DATE('04/05/2013 22:02:05', 'MM/DD/YYYY HH24:MI:SS'));
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_NAME, RL_TEXT_DEFAULT, RL_TEXT_FR, RL_NAME_FR, 
    RL_TEXT_DEFAULT_FR, RL_TEXT_TRIGGERED_BY, RL_TEXT_ORDINAL, RL_USERINPUT, RL_EDITDATE)
 Values
   (20001027, 20001, 'Redline Text', 61, 9, 
    NULL, NULL, 5034, 1, 0, 
    'R/W', NULL, NULL, 'D/P', NULL, 
    NULL, NULL, NULL, 0, TO_DATE('04/05/2013 22:02:05', 'MM/DD/YYYY HH24:MI:SS'));
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_NAME, RL_TEXT_DEFAULT, RL_TEXT_FR, RL_NAME_FR, 
    RL_TEXT_DEFAULT_FR, RL_TEXT_TRIGGERED_BY, RL_TEXT_ORDINAL, RL_USERINPUT, RL_EDITDATE)
 Values
   (20001028, 20001, 'Redline Text', 30, 1.5, 
    NULL, NULL, 5034, 1, 0, 
    'REISSUE DATE', NULL, NULL, 'DATE REEMIS', NULL, 
    NULL, NULL, NULL, 0, TO_DATE('04/05/2013 22:02:05', 'MM/DD/YYYY HH24:MI:SS'));
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_NAME, RL_TEXT_DEFAULT, RL_TEXT_FR, RL_NAME_FR, 
    RL_TEXT_DEFAULT_FR, RL_TEXT_TRIGGERED_BY, RL_TEXT_ORDINAL, RL_USERINPUT, RL_EDITDATE)
 Values
   (20001029, 20001, 'Redline Text', 61, 5, 
    NULL, NULL, 5035, 1, 0, 
    '[ASSOCIATE_INFO]', 'Associate / Phone', NULL, '[ASSOCIATE_INFO]', 'Adjoint(e) / Telephone', 
    NULL, NULL, 3, 0, TO_DATE('04/05/2013 22:02:05', 'MM/DD/YYYY HH24:MI:SS'));
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_NAME, RL_TEXT_DEFAULT, RL_TEXT_FR, RL_NAME_FR, 
    RL_TEXT_DEFAULT_FR, RL_TEXT_TRIGGERED_BY, RL_TEXT_ORDINAL, RL_USERINPUT, RL_EDITDATE)
 Values
   (20001030, 20001, 'Redline Text', 61, 1.5, 
    NULL, NULL, 5034, 1, 0, 
    'ASSOCIATE / PHONE', NULL, NULL, 'ADJOINT(E) / TELEPHONE', NULL, 
    NULL, NULL, NULL, 0, TO_DATE('04/05/2013 22:02:05', 'MM/DD/YYYY HH24:MI:SS'));
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_NAME, RL_TEXT_DEFAULT, RL_TEXT_FR, RL_NAME_FR, 
    RL_TEXT_DEFAULT_FR, RL_TEXT_TRIGGERED_BY, RL_TEXT_ORDINAL, RL_USERINPUT, RL_EDITDATE)
 Values
   (20001031, 20001, 'Redline Text', 123, 16.5, 
    NULL, NULL, 5034, 1, 0, 
    'NETWORK#', NULL, NULL, 'PROJET', NULL, 
    NULL, NULL, NULL, 0, TO_DATE('04/05/2013 22:02:05', 'MM/DD/YYYY HH24:MI:SS'));
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_NAME, RL_TEXT_DEFAULT, RL_TEXT_FR, RL_NAME_FR, 
    RL_TEXT_DEFAULT_FR, RL_TEXT_TRIGGERED_BY, RL_TEXT_ORDINAL, RL_USERINPUT, RL_EDITDATE)
 Values
   (20001032, 20001, 'Redline Text', 1, 15, 
    NULL, NULL, 5034, 1, 0, 
    'ENGINEERING: This plan represents a Letter of Instruction.
The work will be completed according to cost/requirements
established in BCH-Vendor contracts and conform to schedules
determined by the individual BCH Companies.', NULL, NULL, 'Ingénierie: Ce plan fait office de lettre d''instruction.
Les travaux seront réalisés aux coûts et exigences établis
dans le contrat avec l''entrepreneur accrédité par BCH et
ce selon les délais fixés par la compagnie membre de BCH.', NULL, 
    NULL, NULL, NULL, 0, TO_DATE('06/07/2014 01:24:12', 'MM/DD/YYYY HH24:MI:SS'));
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_NAME, RL_TEXT_DEFAULT, RL_TEXT_FR, RL_NAME_FR, 
    RL_TEXT_DEFAULT_FR, RL_TEXT_TRIGGERED_BY, RL_TEXT_ORDINAL, RL_USERINPUT, RL_EDITDATE)
 Values
   (11001, 11, 'Redline Points', 17, 17, 
    NULL, NULL, 5020, 1, 0, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, 0, TO_DATE('04/05/2013 22:02:05', 'MM/DD/YYYY HH24:MI:SS'));
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_NAME, RL_TEXT_DEFAULT, RL_TEXT_FR, RL_NAME_FR, 
    RL_TEXT_DEFAULT_FR, RL_TEXT_TRIGGERED_BY, RL_TEXT_ORDINAL, RL_USERINPUT, RL_EDITDATE)
 Values
   (12001, 12, 'Redline Points', 199, 237, 
    NULL, NULL, 5020, 1, 0, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, 0, TO_DATE('04/05/2013 22:02:05', 'MM/DD/YYYY HH24:MI:SS'));
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_NAME, RL_TEXT_DEFAULT, RL_TEXT_FR, RL_NAME_FR, 
    RL_TEXT_DEFAULT_FR, RL_TEXT_TRIGGERED_BY, RL_TEXT_ORDINAL, RL_USERINPUT, RL_EDITDATE)
 Values
   (22001, 22, 'Redline Points', 262.46, 173.4, 
    NULL, NULL, 5020, 1, 0, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, 0, TO_DATE('04/05/2013 22:02:05', 'MM/DD/YYYY HH24:MI:SS'));
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_NAME, RL_TEXT_DEFAULT, RL_TEXT_FR, RL_NAME_FR, 
    RL_TEXT_DEFAULT_FR, RL_TEXT_TRIGGERED_BY, RL_TEXT_ORDINAL, RL_USERINPUT, RL_EDITDATE)
 Values
   (32001, 32, 'Redline Points', 262.46, 389.26, 
    NULL, NULL, 5020, 1, 0, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, 0, TO_DATE('04/05/2013 22:02:05', 'MM/DD/YYYY HH24:MI:SS'));
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_NAME, RL_TEXT_DEFAULT, RL_TEXT_FR, RL_NAME_FR, 
    RL_TEXT_DEFAULT_FR, RL_TEXT_TRIGGERED_BY, RL_TEXT_ORDINAL, RL_USERINPUT, RL_EDITDATE)
 Values
   (42001, 42, 'Redline Points', 354.8, 236.86, 
    NULL, NULL, 5020, 1, 0, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, 0, TO_DATE('04/05/2013 22:02:05', 'MM/DD/YYYY HH24:MI:SS'));
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_NAME, RL_TEXT_DEFAULT, RL_TEXT_FR, RL_NAME_FR, 
    RL_TEXT_DEFAULT_FR, RL_TEXT_TRIGGERED_BY, RL_TEXT_ORDINAL, RL_USERINPUT, RL_EDITDATE)
 Values
   (52001, 52, 'Redline Points', 414.93, 516.2, 
    NULL, NULL, 5020, 1, 0, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, 0, TO_DATE('04/05/2013 22:02:05', 'MM/DD/YYYY HH24:MI:SS'));
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_NAME, RL_TEXT_DEFAULT, RL_TEXT_FR, RL_NAME_FR, 
    RL_TEXT_DEFAULT_FR, RL_TEXT_TRIGGERED_BY, RL_TEXT_ORDINAL, RL_USERINPUT, RL_EDITDATE)
 Values
   (62001, 62, 'Redline Points', 481.94, 389.33, 
    NULL, NULL, 5020, 1, 0, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, 0, TO_DATE('04/05/2013 22:02:05', 'MM/DD/YYYY HH24:MI:SS'));
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_NAME, RL_TEXT_DEFAULT, RL_TEXT_FR, RL_NAME_FR, 
    RL_TEXT_DEFAULT_FR, RL_TEXT_TRIGGERED_BY, RL_TEXT_ORDINAL, RL_USERINPUT, RL_EDITDATE)
 Values
   (72001, 72, 'Redline Points', 541.86, 821.13, 
    NULL, NULL, 5020, 1, 0, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, 0, TO_DATE('04/05/2013 22:02:05', 'MM/DD/YYYY HH24:MI:SS'));
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_NAME, RL_TEXT_DEFAULT, RL_TEXT_FR, RL_NAME_FR, 
    RL_TEXT_DEFAULT_FR, RL_TEXT_TRIGGERED_BY, RL_TEXT_ORDINAL, RL_USERINPUT, RL_EDITDATE)
 Values
   (82001, 82, 'Redline Points', 786.6, 516.2, 
    NULL, NULL, 5020, 1, 0, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, 0, TO_DATE('04/05/2013 22:02:05', 'MM/DD/YYYY HH24:MI:SS'));
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_NAME, RL_TEXT_DEFAULT, RL_TEXT_FR, RL_NAME_FR, 
    RL_TEXT_DEFAULT_FR, RL_TEXT_TRIGGERED_BY, RL_TEXT_ORDINAL, RL_USERINPUT, RL_EDITDATE)
 Values
   (92001, 92, 'Redline Points', 786.6, 1075.1, 
    NULL, NULL, 5020, 1, 0, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, 0, TO_DATE('04/05/2013 22:02:05', 'MM/DD/YYYY HH24:MI:SS'));
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_NAME, RL_TEXT_DEFAULT, RL_TEXT_FR, RL_NAME_FR, 
    RL_TEXT_DEFAULT_FR, RL_TEXT_TRIGGERED_BY, RL_TEXT_ORDINAL, RL_USERINPUT, RL_EDITDATE)
 Values
   (102001, 102, 'Redline Points', 1040.6, 821.1, 
    NULL, NULL, 5020, 1, 0, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, 0, TO_DATE('04/05/2013 22:02:05', 'MM/DD/YYYY HH24:MI:SS'));
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_NAME, RL_TEXT_DEFAULT, RL_TEXT_FR, RL_NAME_FR, 
    RL_TEXT_DEFAULT_FR, RL_TEXT_TRIGGERED_BY, RL_TEXT_ORDINAL, RL_USERINPUT, RL_EDITDATE)
 Values
   (30001015, 30001, 'Redline Multi Text', 0, 0, 
    NULL, NULL, 5036, 1, 0, 
    'BEGIN GET_ARB_NOTES_PKG.POP_ARB_NOTES_TEMP_TABLE(?,?,?); END;', NULL, NULL, 'BEGIN GET_ARB_NOTES_PKG.POP_ARB_NOTES_TEMP_TABLE(?,?,?); END;', NULL, 
    NULL, NULL, NULL, 0, TO_DATE('08/01/2014 22:03:47', 'MM/DD/YYYY HH24:MI:SS'));
COMMIT;
