DROP TABLE GIS_STG.STG_TOWN_CODE CASCADE CONSTRAINTS;
CREATE TABLE GIS_STG.STG_TOWN_CODE 
   (	STG_TOWN_CODE_ID NUMBER GENERATED ALWAYS AS IDENTITY, 
	PROCESS_DT DATE, 
	PROCESS_RUN_ID NUMBER, 
	TOWN_C NUMBER(3,0), 
	TOWN_DESC_T VARCHAR2(20 BYTE), 
	CNTY1_C NUMBER(3,0), 
	CNTY2_C NUMBER(3,0), 
	CNTY3_C NUMBER(3,0), 
  CNTY4_C NUMBER(3,0), 
	TOWN_TAX_CODE NUMBER(4,0), 
	FRANCHISE_FEE_RATE NUMBER(8,6), 
	TAX_LOCATION VARCHAR2(7 BYTE), 
	AUD_CREATE_USR_ID VARCHAR2(30 BYTE) DEFAULT USER, 
	AUD_MOD_USR_ID VARCHAR2(30 BYTE), 
	AUD_CREATE_DT TIMESTAMP (6) DEFAULT SYSDATE, 
	AUD_MOD_DT TIMESTAMP (6)
   );