SET ECHO ON
SET LINESIZE 1000
SET PAGESIZE 300
SET TRIMSPOOL ON
SPOOL RESET_DEVICE_ID_SEQ_NETWORK.LOG

--************************BEFORE RUNNING MAKE SURE THAT THE SEQUENCE IS RESET************************************

ALTER TABLE B$SCADA_N DISABLE ALL TRIGGERS;

UPDATE GIS.B$SCADA_N
  SET DEVICE_ID = GIS.DEVICE_ID_SEQ.NEXTVAL
  WHERE LTT_ID = 0
  AND G3E_FNO IN (88, 90);
  
  
COMMIT;


ALTER TABLE B$SCADA_N DISABLE ALL TRIGGERS;
SPOOL OFF;