SET ECHO ON
SET LINESIZE 1000
SET PAGESIZE 300
SET TRIMSPOOL ON
SPOOL UPDATE_VOLT_Q_VAULT_ATTR.LOG

ALTER TABLE B$VAULT_N DISABLE ALL TRIGGERS;

UPDATE GIS.B$VAULT_N
SET VOLT_Q = 0
WHERE 1=1
    AND LTT_ID = 0
    AND VOLT_Q IS NULL;
    

COMMIT;
ALTER TABLE B$VAULT_N ENABLE ALL TRIGGERS;

SPOOL OFF;
    
