SET ECHO ON
SET LINESIZE 1000
SET PAGESIZE 300
SET TRIMSPOOL ON
SPOOL UPDATE_STATUS_OPERATED_CONNECTIVITY.LOG

ALTER TABLE B$CONNECTIVITY_N DISABLE ALL TRIGGERS;

UPDATE GIS.B$CONNECTIVITY_N
SET STATUS_OPERATED_C = 'CLOSED'
WHERE 1=1
    AND LTT_ID = 0
    AND STATUS_OPERATED_C IS NULL;
    

COMMIT;
ALTER TABLE B$CONNECTIVITY_N ENABLE ALL TRIGGERS;

SPOOL OFF;
    