
set echo on
set linesize 1000
set pagesize 300
set define off

whenever sqlerror exit -1
whenever oserror exit -1

spool c:\temp\AddCablePullTensionCommandSupportTables.log

--**************************************************************************************

--SCRIPT NAME: AddCablePullTensionCommandSupportTables.sql
--**************************************************************************************
-- AUTHOR		        : INGRNET\RPGABRYS
-- Date 	      	    : 14-JUL-2017
-- Jira NUMBER	  	    :
-- PRODUCT VERSION  	: 10.2.04
-- PRJ IDENTIFIER   	: G/TECHNOLOGY - ONCOR
-- PROGRAM DESC     	: Add tables to support the Cable Pull Tension custom command.
-- SOURCE DATABASE  	:
--**************************************************************************************
-- Script Body
--************************************************************************************** 

CREATE TABLE TOOLS_CPT_CABLE (
CINO				NUMBER GENERATED ALWAYS AS IDENTITY,
DESCRIPTION			VARCHAR2 (80),
VOLTAGE				VARCHAR2 (30),
TYPE				VARCHAR2 (30),
SIZE_MATERIAL		VARCHAR2 (30),
NUMBER_OF_PHASES	VARCHAR2 (30),
NUMBER_OF_CABLES	NUMBER,
CONFIGURATION		NUMBER (9),
NON_STD				VARCHAR2 (1),
OUTSIDE_DIAMETER	NUMBER,
WEIGHT_PER_FOOT		NUMBER,
MAX_SWBP			NUMBER,
MAX_TENSION			NUMBER,
SWBP_CHANGE_POINT	NUMBER,
MAX_LENGTH			NUMBER,
EDIT_DATE_DT		DATE
);
/

ALTER TABLE TOOLS_CPT_CABLE ADD CONSTRAINT M_P_TOOLS_CPT_CABLE PRIMARY KEY (CINO);

CREATE OR REPLACE PUBLIC SYNONYM TOOLS_CPT_CABLE FOR TOOLS_CPT_CABLE;

CREATE TRIGGER T_BIUR_TOOLS_CPT_CABLE_EDATE
BEFORE INSERT OR UPDATE ON TOOLS_CPT_CABLE
FOR EACH ROW
BEGIN

  :NEW.EDIT_DATE_DT := SYSDATE;
END;
/

CREATE TABLE TOOLS_CPT_CABLECONFIGURATION (
CCNO			NUMBER GENERATED ALWAYS AS IDENTITY,
CONFIGURATION	VARCHAR2 (10),
EDIT_DATE_DT	DATE
);
/

ALTER TABLE TOOLS_CPT_CABLECONFIGURATION ADD CONSTRAINT M_P_TOOLS_CPT_CABLECONFIG PRIMARY KEY (CCNO);

CREATE OR REPLACE PUBLIC SYNONYM TOOLS_CPT_CABLECONFIGURATION FOR TOOLS_CPT_CABLECONFIGURATION;

CREATE TRIGGER T_BIUR_TOOLS_CPT_CCONFIG_EDATE
BEFORE INSERT OR UPDATE ON TOOLS_CPT_CABLECONFIGURATION
FOR EACH ROW
BEGIN

  :NEW.EDIT_DATE_DT := SYSDATE;
END;
/
	

CREATE TABLE TOOLS_CPT_DUCTTRENCH (
DTNO					NUMBER GENERATED ALWAYS AS IDENTITY,
DESCRIPTION				VARCHAR2 (80),
INSIDE_DIAMETER			NUMBER,
NOMINAL_INSIDE_DIAMETER	NUMBER,
MIN_CLEARANCE			NUMBER (3,2),
STD_BEND_RADIUS			NUMBER (4,2),
EDIT_DATE_DT			DATE
);
/

ALTER TABLE TOOLS_CPT_DUCTTRENCH ADD CONSTRAINT M_P_TOOLS_CPT_DUCTTRENCH PRIMARY KEY (DTNO);

CREATE OR REPLACE PUBLIC SYNONYM TOOLS_CPT_DUCTTRENCH FOR TOOLS_CPT_DUCTTRENCH;

CREATE TRIGGER T_BIUR_TOOLS_CPT_DUCTTR_EDATE
BEFORE INSERT OR UPDATE ON TOOLS_CPT_DUCTTRENCH
FOR EACH ROW
BEGIN

  :NEW.EDIT_DATE_DT := SYSDATE;
END;
/


CREATE TABLE TOOLS_CPT_VALIDATION (
VINO			NUMBER GENERATED ALWAYS AS IDENTITY,
CABLE_ID		NUMBER (9),
DUCTTRENCH_ID	NUMBER (9),
MAX_DISTANCE	NUMBER,
EDIT_DATE_DT	DATE
);
/

ALTER TABLE TOOLS_CPT_VALIDATION ADD CONSTRAINT M_P_TOOLS_CPT_VALIDATION PRIMARY KEY (VINO);

CREATE OR REPLACE PUBLIC SYNONYM TOOLS_CPT_VALIDATION FOR TOOLS_CPT_VALIDATION;

CREATE TRIGGER T_BIUR_TOOLS_CPT_VAL_EDATE
BEFORE INSERT OR UPDATE ON TOOLS_CPT_VALIDATION
FOR EACH ROW
BEGIN

  :NEW.EDIT_DATE_DT := SYSDATE;
END;
/


CREATE TABLE TOOLS_VALIDATION (
WR_NBR					VARCHAR2 (30),
G3E_FID					NUMBER (10),
TOOL_NM					VARCHAR2 (30),
VALIDATION_STATUS_C		VARCHAR2 (20),
VALIDATION_PRIORITY_C	VARCHAR2 (2),
COMMENTS				VARCHAR2 (200),
EDIT_DATE_DT			DATE
);
/

CREATE OR REPLACE PUBLIC SYNONYM TOOLS_VALIDATION FOR TOOLS_VALIDATION;

CREATE TRIGGER T_BIUR_TOOLS_VALIDATION_EDATE
BEFORE INSERT OR UPDATE ON TOOLS_VALIDATION
FOR EACH ROW
BEGIN

  :NEW.EDIT_DATE_DT := SYSDATE;
END;
/


ALTER TABLE TOOLS_CPT_VALIDATION
ADD CONSTRAINT "M_R_TOOLS_CPT_VAL_CABLEID" 
	FOREIGN KEY ("CABLE_ID")
	REFERENCES "TOOLS_CPT_CABLE" ("CINO");
/

ALTER TABLE TOOLS_CPT_VALIDATION
ADD CONSTRAINT "M_R_TOOLS_CPT_VAL_DUCTTRENCHID" 
	FOREIGN KEY ("DUCTTRENCH_ID")
	REFERENCES "TOOLS_CPT_DUCTTRENCH" ("DTNO");
/


ALTER TABLE TOOLS_CPT_CABLE
ADD CONSTRAINT "M_R_TOOLS_CPT_CCONFIG_CONFIG" 
	FOREIGN KEY ("CONFIGURATION")
	REFERENCES "TOOLS_CPT_CABLECONFIGURATION" ("CCNO");
/

--**************************************************************************************
-- End Script Body
--**************************************************************************************