ALTER TABLE GT_PLOT_REDLINES
 DROP PRIMARY KEY CASCADE;

DROP TABLE GT_PLOT_REDLINES CASCADE CONSTRAINTS;

CREATE TABLE GT_PLOT_REDLINES
(
  RL_NO              NUMBER                         NULL,
  GROUP_NO           NUMBER                         NULL,
  RL_DATATYPE        VARCHAR2(30 BYTE)              NULL,
  RL_COORDINATE_X1   NUMBER                         NULL,
  RL_COORDINATE_Y1   NUMBER                         NULL,
  RL_COORDINATE_X2   NUMBER                         NULL,
  RL_COORDINATE_Y2   NUMBER                         NULL,
  RL_STYLE_NUMBER    NUMBER                         NULL,
  RL_TEXT_ALIGNMENT  NUMBER                     DEFAULT 0                         NULL,
  RL_ROTATION        NUMBER                     DEFAULT 0                         NULL,
  RL_TEXT            VARCHAR2(255 BYTE)             NULL,
  RL_USERINPUT       NUMBER                     DEFAULT 0                         NULL,
  RL_NAME            VARCHAR2(255 BYTE)             NULL,
  RL_TEXT_FR         VARCHAR2(255 BYTE)             NULL
)
TABLESPACE GTECH
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX PK_GT_PLOT_REDLINES_RL_NO ON GT_PLOT_REDLINES
(RL_NO)
LOGGING
TABLESPACE GTECH
NOPARALLEL;


CREATE OR REPLACE TRIGGER "M_T_BIUR_GT_PLOT_REDLINES" 
BEFORE INSERT OR UPDATE
ON GT_PLOT_REDLINES
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
DECLARE
  refValue            NUMBER;
  invalid_reference   EXCEPTION;
  CURSOR curReference (newValue NUMBER) IS
    SELECT GROUP_NO
    FROM GT_PLOT_GROUPS_DRI
    WHERE GROUP_NO = newValue;
BEGIN

  OPEN curReference(:NEW.GROUP_NO);
  FETCH curReference INTO refValue;
  IF curReference%NOTFOUND THEN
    RAISE invalid_reference;
  END IF;
  CLOSE curReference;

EXCEPTION
  WHEN invalid_reference THEN
    CLOSE curReference;
    raise_application_error ( -20001, 'A reference to GT_PLOT_REDLINES.GROUP_NO=' || :NEW.GROUP_NO || ' does not exists in GT_PLOT_GROUPS_DRI.GROUP_NO');
  WHEN OTHERS THEN
    RAISE;
END M_T_BIUR_GT_PLOT_REDLINES;
/
SHOW ERRORS;


ALTER TABLE GT_PLOT_REDLINES ADD (
  CONSTRAINT PK_GT_PLOT_REDLINES_RL_NO
 PRIMARY KEY
 (RL_NO)
    USING INDEX 
    TABLESPACE GTECH);

GRANT DELETE, INSERT, SELECT, UPDATE ON GT_PLOT_REDLINES TO ADMINISTRATOR;

GRANT SELECT ON GT_PLOT_REDLINES TO DESIGNER;

GRANT SELECT ON GT_PLOT_REDLINES TO FINANCE;

GRANT SELECT ON GT_PLOT_REDLINES TO MARKETING;

GRANT DELETE, INSERT, SELECT, UPDATE ON GT_PLOT_REDLINES TO SUPERVISOR;


SET DEFINE OFF;
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20007132, 20007, 'Redline Text', 185, 61, 
    NULL, NULL, 10003, 1, 0, 
    '[TOTAL_SHEETS]', 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20007133, 20007, 'Redline Text', 16, 2.5, 
    NULL, NULL, 10003, 1, 0, 
    'BILL OF MATERIALS', 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20007001, 20007, 'Redline Lines', 0, 0, 
    200.5, 0, 27302111, 0, 0, 
    NULL, 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20007002, 20007, 'Redline Lines', 70, 11, 
    159, 11, 27302111, 0, 0, 
    NULL, 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20007003, 20007, 'Redline Lines', 70, 18, 
    159, 18, 27302111, 0, 0, 
    NULL, 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20007004, 20007, 'Redline Lines', 70, 31.5, 
    159, 31.5, 27302111, 0, 0, 
    NULL, 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20007005, 20007, 'Redline Lines', 0, 42.5, 
    70, 42.5, 27302111, 0, 0, 
    NULL, 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20007006, 20007, 'Redline Lines', 0, 49, 
    70, 49, 27302111, 0, 0, 
    NULL, 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20007007, 20007, 'Redline Lines', 0, 54, 
    70, 54, 27302111, 0, 0, 
    NULL, 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20007008, 20007, 'Redline Lines', 0, 59, 
    70, 59, 27302111, 0, 0, 
    NULL, 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20007009, 20007, 'Redline Lines', 0, 64, 
    200.5, 64, 27302111, 0, 0, 
    NULL, 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20007010, 20007, 'Redline Lines', 159, 55, 
    200.5, 55, 27302111, 0, 0, 
    NULL, 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20007011, 20007, 'Redline Lines', 0, 0, 
    0, 64, 27302111, 0, 0, 
    NULL, 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20007012, 20007, 'Redline Lines', 70, 0, 
    70, 64, 27302111, 0, 0, 
    NULL, 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20007013, 20007, 'Redline Lines', 159, 0, 
    159, 64, 27302111, 0, 0, 
    NULL, 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20007014, 20007, 'Redline Lines', 8, 49, 
    8, 64, 27302111, 0, 0, 
    NULL, 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20007015, 20007, 'Redline Lines', 13, 49, 
    13, 64, 27302111, 0, 0, 
    NULL, 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20007016, 20007, 'Redline Lines', 20, 49, 
    20, 64, 27302111, 0, 0, 
    NULL, 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20010001, 20010, 'Redline Lines', 0, 0, 
    0, 263.525, 27302111, 0, 0, 
    NULL, 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20010002, 20010, 'Redline Lines', 0, 0, 
    105, 0, 27302111, 0, 0, 
    NULL, 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20010003, 20010, 'Redline Lines', 0, 263.525, 
    105, 263.525, 27302111, 0, 0, 
    NULL, 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20010004, 20010, 'Redline Lines', 105, 0, 
    105, 263.525, 27302111, 0, 0, 
    NULL, 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20011001, 20011, 'Redline Lines', 0, 0, 
    0, 415.925, 27302111, 0, 0, 
    NULL, 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20011004, 20011, 'Redline Lines', 105, 0, 
    105, 415.925, 27302111, 0, 0, 
    NULL, 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20011003, 20011, 'Redline Lines', 0, 415.925, 
    105, 415.925, 27302111, 0, 0, 
    NULL, 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20011002, 20011, 'Redline Lines', 0, 0, 
    105, 0, 27302111, 0, 0, 
    NULL, 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20012001, 20012, 'Redline Lines', 0, 0, 
    0, 542.925, 27302111, 0, 0, 
    NULL, 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20012002, 20012, 'Redline Lines', 0, 0, 
    105, 0, 27302111, 0, 0, 
    NULL, 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20012003, 20012, 'Redline Lines', 0, 542.925, 
    105, 542.925, 27302111, 0, 0, 
    NULL, 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20012004, 20012, 'Redline Lines', 105, 0, 
    105, 542.925, 27302111, 0, 0, 
    NULL, 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20013001, 20013, 'Redline Lines', 0, 0, 
    0, 847.725, 27302111, 0, 0, 
    NULL, 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20013002, 20013, 'Redline Lines', 0, 0, 
    105, 0, 27302111, 0, 0, 
    NULL, 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20013003, 20013, 'Redline Lines', 0, 847.725, 
    105, 847.725, 27302111, 0, 0, 
    NULL, 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20013004, 20013, 'Redline Lines', 105, 0, 
    105, 847.725, 27302111, 0, 0, 
    NULL, 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20014001, 20014, 'Redline Lines', 0, 0, 
    0, 200.025, 27302111, 0, 0, 
    NULL, 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20014002, 20014, 'Redline Lines', 0, 0, 
    105, 0, 27302111, 0, 0, 
    NULL, 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20014004, 20014, 'Redline Lines', 105, 0, 
    105, 200.025, 27302111, 0, 0, 
    NULL, 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20014003, 20014, 'Redline Lines', 0, 200.025, 
    105, 200.025, 27302111, 0, 0, 
    NULL, 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20015003, 20015, 'Redline Lines', 0, 415.925, 
    105, 415.925, 27302111, 0, 0, 
    NULL, 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20015004, 20015, 'Redline Lines', 105, 0, 
    105, 415.925, 27302111, 0, 0, 
    NULL, 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20015001, 20015, 'Redline Lines', 0, 0, 
    0, 415.925, 27302111, 0, 0, 
    NULL, 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20015002, 20015, 'Redline Lines', 0, 0, 
    105, 0, 27302111, 0, 0, 
    NULL, 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20101001, 20101, 'Redline Text', 12, 2, 
    NULL, NULL, 5034, 1, 0, 
    'NOTES:', 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20101002, 20101, 'Redline Text', 14, 5, 
    NULL, NULL, 5035, 5, 0, 
    '[NOTES]', 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (40004001, 40004, 'Redline Lines', 0, 7.5, 
    122, 7.5, 27302111, 0, 0, 
    NULL, 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (40004032, 40004, 'Redline Text', 1, 15, 
    NULL, NULL, 5034, 1, 0, 
    'ENGINEERING: This plan represents a Letter of Instruction.
The work will be completed according to cost/requirements
established in the Intergraph-Vendor contracts and conform
 to schedules determined by the Intergraph.', 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (40004003, 40004, 'Redline Lines', 182, 0, 
    182, 25.5, 27302111, 0, 0, 
    NULL, 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (40004004, 40004, 'Redline Lines', 0, 23, 
    182, 23, 27302111, 0, 0, 
    NULL, 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (40004005, 40004, 'Redline Lines', 60, 15, 
    182, 15, 27302111, 0, 0, 
    NULL, 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (40004006, 40004, 'Redline Lines', 182, 25.5, 
    0, 25.5, 27302111, 0, 0, 
    NULL, 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (40004007, 40004, 'Redline Lines', 60, 0, 
    60, 23, 27302111, 0, 0, 
    NULL, 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (40004008, 40004, 'Redline Lines', 0, 25.5, 
    0, 0, 27302111, 0, 0, 
    NULL, 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (40004009, 40004, 'Redline Lines', 152, 15, 
    152, 23, 27302111, 0, 0, 
    NULL, 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (40004010, 40004, 'Redline Lines', 122, 0, 
    122, 23, 27302111, 0, 0, 
    NULL, 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (40004011, 40004, 'Redline Lines', 29, 0, 
    29, 7.5, 27302111, 0, 0, 
    NULL, 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (40004012, 40004, 'Redline Text', 1, 1.5, 
    NULL, NULL, 5034, 1, 0, 
    'Place Date', 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (40004013, 40004, 'Redline Text', 123, 1.5, 
    NULL, NULL, 5034, 1, 0, 
    'SIGNATURE', 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (40004014, 40004, 'Redline Text', 61, 16.5, 
    NULL, NULL, 5034, 1, 0, 
    'District:', 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (40004015, 40004, 'Redline Text', 153, 16.5, 
    NULL, NULL, 5034, 1, 0, 
    'Scale', 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (40004016, 40004, 'Redline Text', 61, 20, 
    NULL, NULL, 5035, 1, 0, 
    '[TAX_DISTRICT]', 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (40004017, 40004, 'Redline Text', 123, 12.3, 
    NULL, NULL, 5035, 1, 0, 
    ' ', 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (40004018, 40004, 'Redline Text', 61, 12.3, 
    NULL, NULL, 5035, 1, 0, 
    '[JOB_MODIFY_NAME]', 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (40004019, 40004, 'Redline Text', 90, 20, 
    NULL, NULL, 5035, 1, 0, 
    '[REGION]', 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (40004020, 40004, 'Redline Text', 153, 20, 
    NULL, NULL, 5036, 1, 0, 
    '[SCALE]', 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (40004021, 40004, 'Redline Text', 123, 20, 
    NULL, NULL, 5036, 1, 0, 
    '[NAME]', 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (40004022, 40004, 'Redline Text', 123, 9, 
    NULL, NULL, 5034, 1, 0, 
    ' ', 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (40004023, 40004, 'Redline Text', 30, 5, 
    NULL, NULL, 5034, 1, 0, 
    '[JOB_MODIFY_DATE]', 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (40004024, 40004, 'Redline Text', 1, 5, 
    NULL, NULL, 5034, 1, 0, 
    '[JOB_PLACE_DATE]', 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (40004025, 40004, 'Redline Text', 80, 24, 
    NULL, NULL, 5034, 1, 0, 
    'Copyright Intergraph', 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (40004026, 40004, 'Redline Text', 90, 16.5, 
    NULL, NULL, 5034, 1, 0, 
    'Region', 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (40004027, 40004, 'Redline Text', 61, 9, 
    NULL, NULL, 5034, 1, 0, 
    'Job Name', 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (40004028, 40004, 'Redline Text', 30, 1.5, 
    NULL, NULL, 5034, 1, 0, 
    'Modify Date', 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (40004029, 40004, 'Redline Text', 61, 5, 
    NULL, NULL, 5035, 1, 0, 
    '[G3E_OWNER]', 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (40004030, 40004, 'Redline Text', 61, 1.5, 
    NULL, NULL, 5034, 1, 0, 
    'ASSOCIATE', 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (40004031, 40004, 'Redline Text', 123, 16.5, 
    NULL, NULL, 5034, 1, 0, 
    'Plot Name', 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (40004002, 40004, 'Redline Lines', 0, 0, 
    182, 0, 27302111, 0, 0, 
    NULL, 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (50004001, 50004, 'Redline Lines', 0, 7.5, 
    122, 7.5, 27302111, 0, 0, 
    NULL, 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (50004032, 50004, 'Redline Text', 1, 15, 
    NULL, NULL, 5034, 1, 0, 
    'ENGINEERING: This plan represents a Letter of Instruction.
The work will be completed according to cost/requirements
established in the Intergraph-Vendor contracts and conform
 to schedules determined by the Intergraph.', 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (50004003, 50004, 'Redline Lines', 182, 0, 
    182, 25.5, 27302111, 0, 0, 
    NULL, 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (50004004, 50004, 'Redline Lines', 0, 23, 
    182, 23, 27302111, 0, 0, 
    NULL, 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (50004005, 50004, 'Redline Lines', 60, 15, 
    182, 15, 27302111, 0, 0, 
    NULL, 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (50004006, 50004, 'Redline Lines', 182, 25.5, 
    0, 25.5, 27302111, 0, 0, 
    NULL, 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (50004007, 50004, 'Redline Lines', 60, 0, 
    60, 23, 27302111, 0, 0, 
    NULL, 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (50004008, 50004, 'Redline Lines', 0, 25.5, 
    0, 0, 27302111, 0, 0, 
    NULL, 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (50004009, 50004, 'Redline Lines', 152, 15, 
    152, 23, 27302111, 0, 0, 
    NULL, 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (50004010, 50004, 'Redline Lines', 122, 0, 
    122, 23, 27302111, 0, 0, 
    NULL, 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (50004011, 50004, 'Redline Lines', 29, 0, 
    29, 7.5, 27302111, 0, 0, 
    NULL, 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (50004012, 50004, 'Redline Text', 1, 1.5, 
    NULL, NULL, 5034, 1, 0, 
    'Place Date', 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (50004013, 50004, 'Redline Text', 123, 1.5, 
    NULL, NULL, 5034, 1, 0, 
    'SIGNATURE', 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (50004014, 50004, 'Redline Text', 61, 16.5, 
    NULL, NULL, 5034, 1, 0, 
    'District:', 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (50004015, 50004, 'Redline Text', 153, 16.5, 
    NULL, NULL, 5034, 1, 0, 
    'Scale', 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (50004016, 50004, 'Redline Text', 61, 20, 
    NULL, NULL, 5035, 1, 0, 
    '[TAX_DISTRICT]', 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (50004017, 50004, 'Redline Text', 123, 12.3, 
    NULL, NULL, 5035, 1, 0, 
    ' ', 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (50004018, 50004, 'Redline Text', 61, 12.3, 
    NULL, NULL, 5035, 1, 0, 
    '[JOB_MODIFY_NAME]', 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (50004019, 50004, 'Redline Text', 90, 20, 
    NULL, NULL, 5035, 1, 0, 
    '[REGION]', 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (50004020, 50004, 'Redline Text', 153, 20, 
    NULL, NULL, 5036, 1, 0, 
    '[SCALE]', 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (50004021, 50004, 'Redline Text', 123, 20, 
    NULL, NULL, 5036, 1, 0, 
    '[NAME]', 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (50004022, 50004, 'Redline Text', 123, 9, 
    NULL, NULL, 5034, 1, 0, 
    ' ', 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (50004023, 50004, 'Redline Text', 30, 5, 
    NULL, NULL, 5034, 1, 0, 
    '[JOB_MODIFY_DATE]', 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (50004024, 50004, 'Redline Text', 1, 5, 
    NULL, NULL, 5034, 1, 0, 
    '[JOB_PLACE_DATE]', 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (50004025, 50004, 'Redline Text', 80, 24, 
    NULL, NULL, 5034, 1, 0, 
    'Copyright Intergraph', 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (50004026, 50004, 'Redline Text', 90, 16.5, 
    NULL, NULL, 5034, 1, 0, 
    'Region', 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (50004027, 50004, 'Redline Text', 61, 9, 
    NULL, NULL, 5034, 1, 0, 
    'Job Name', 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (50004028, 50004, 'Redline Text', 30, 1.5, 
    NULL, NULL, 5034, 1, 0, 
    'Modify Date', 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (50004029, 50004, 'Redline Text', 61, 5, 
    NULL, NULL, 5035, 1, 0, 
    '[G3E_OWNER]', 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (50004030, 50004, 'Redline Text', 61, 1.5, 
    NULL, NULL, 5034, 1, 0, 
    'ASSOCIATE', 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (50004031, 50004, 'Redline Text', 123, 16.5, 
    NULL, NULL, 5034, 1, 0, 
    'Plot Name', 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (50004002, 50004, 'Redline Lines', 0, 0, 
    182, 0, 27302111, 0, 0, 
    NULL, 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20001001, 20001, 'Redline Lines', 0, 7.5, 
    122, 7.5, 27302111, 0, 0, 
    NULL, 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20001002, 20001, 'Redline Lines', 0, 0, 
    182, 0, 27302111, 0, 0, 
    NULL, 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20001003, 20001, 'Redline Lines', 182, 0, 
    182, 25.5, 27302111, 0, 0, 
    NULL, 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20001004, 20001, 'Redline Lines', 0, 23, 
    182, 23, 27302111, 0, 0, 
    NULL, 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20001005, 20001, 'Redline Lines', 60, 15, 
    182, 15, 27302111, 0, 0, 
    NULL, 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20001006, 20001, 'Redline Lines', 182, 25.5, 
    0, 25.5, 27302111, 0, 0, 
    NULL, 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20001007, 20001, 'Redline Lines', 60, 0, 
    60, 23, 27302111, 0, 0, 
    NULL, 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20001008, 20001, 'Redline Lines', 0, 25.5, 
    0, 0, 27302111, 0, 0, 
    NULL, 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20001009, 20001, 'Redline Lines', 152, 15, 
    152, 23, 27302111, 0, 0, 
    NULL, 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20001010, 20001, 'Redline Lines', 122, 0, 
    122, 23, 27302111, 0, 0, 
    NULL, 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20001011, 20001, 'Redline Lines', 29, 0, 
    29, 7.5, 27302111, 0, 0, 
    NULL, 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20001012, 20001, 'Redline Text', 1, 1.5, 
    NULL, NULL, 5034, 1, 0, 
    'Place Date', 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20001013, 20001, 'Redline Text', 123, 1.5, 
    NULL, NULL, 5034, 1, 0, 
    'SIGNATURE', 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20001014, 20001, 'Redline Text', 61, 16.5, 
    NULL, NULL, 5034, 1, 0, 
    'District:', 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20001015, 20001, 'Redline Text', 153, 16.5, 
    NULL, NULL, 5034, 1, 0, 
    'Scale', 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20001016, 20001, 'Redline Text', 61, 20, 
    NULL, NULL, 5035, 1, 0, 
    '[TAX_DISTRICT]', 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20001017, 20001, 'Redline Text', 123, 12.3, 
    NULL, NULL, 5035, 1, 0, 
    ' ', 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20001018, 20001, 'Redline Text', 61, 12.3, 
    NULL, NULL, 5035, 1, 0, 
    '[JOB_MODIFY_NAME]', 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20001019, 20001, 'Redline Text', 90, 20, 
    NULL, NULL, 5035, 1, 0, 
    '[REGION]', 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20001020, 20001, 'Redline Text', 153, 20, 
    NULL, NULL, 5036, 1, 0, 
    '[SCALE]', 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20001021, 20001, 'Redline Text', 123, 20, 
    NULL, NULL, 5036, 1, 0, 
    '[NAME]', 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20001022, 20001, 'Redline Text', 123, 9, 
    NULL, NULL, 5034, 1, 0, 
    ' ', 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20001023, 20001, 'Redline Text', 30, 5, 
    NULL, NULL, 5034, 1, 0, 
    '[JOB_MODIFY_DATE]', 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20001024, 20001, 'Redline Text', 1, 5, 
    NULL, NULL, 5034, 1, 0, 
    '[JOB_PLACE_DATE]', 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20001025, 20001, 'Redline Text', 80, 24, 
    NULL, NULL, 5034, 1, 0, 
    'Copyright Intergraph', 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20001026, 20001, 'Redline Text', 90, 16.5, 
    NULL, NULL, 5034, 1, 0, 
    'Region', 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20001027, 20001, 'Redline Text', 61, 9, 
    NULL, NULL, 5034, 1, 0, 
    'Job Name', 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20001028, 20001, 'Redline Text', 30, 1.5, 
    NULL, NULL, 5034, 1, 0, 
    'Modify Date', 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20001029, 20001, 'Redline Text', 61, 5, 
    NULL, NULL, 5035, 1, 0, 
    '[G3E_OWNER]', 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20001030, 20001, 'Redline Text', 61, 1.5, 
    NULL, NULL, 5034, 1, 0, 
    'ASSOCIATE', 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20001031, 20001, 'Redline Text', 123, 16.5, 
    NULL, NULL, 5034, 1, 0, 
    'Plot Name', 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20001032, 20001, 'Redline Text', 1, 15, 
    NULL, NULL, 5034, 1, 0, 
    'ENGINEERING: This plan represents a Letter of Instruction.
The work will be completed according to cost/requirements
established in the Intergraph-Vendor contracts and conform
 to schedules determined by the Intergraph.', 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20006001, 20006, 'Redline Lines', 0, 0, 
    105, 0, 27302111, 0, 0, 
    NULL, 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20006002, 20006, 'Redline Lines', 0, 7, 
    105, 7, 27302111, 0, 0, 
    NULL, 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20006003, 20006, 'Redline Lines', 0, 11, 
    105, 11, 27302111, 0, 0, 
    NULL, 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20006004, 20006, 'Redline Lines', 0, 15, 
    105, 15, 27302111, 0, 0, 
    NULL, 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20006005, 20006, 'Redline Lines', 0, 19, 
    105, 19, 27302111, 0, 0, 
    NULL, 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20006006, 20006, 'Redline Lines', 0, 23, 
    105, 23, 27302111, 0, 0, 
    NULL, 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20006007, 20006, 'Redline Lines', 0, 35.5, 
    105, 35.5, 27302111, 0, 0, 
    NULL, 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20006008, 20006, 'Redline Lines', 0, 43.75, 
    105, 43.75, 27302111, 0, 0, 
    NULL, 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20006009, 20006, 'Redline Lines', 0, 54.5, 
    105, 54.5, 27302111, 0, 0, 
    NULL, 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20006010, 20006, 'Redline Lines', 0, 94, 
    105, 94, 27302111, 0, 0, 
    NULL, 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20006011, 20006, 'Redline Lines', 0, 101.5, 
    105, 101.5, 27302111, 0, 0, 
    NULL, 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20006012, 20006, 'Redline Lines', 0, 109, 
    105, 109, 27302111, 0, 0, 
    NULL, 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20006013, 20006, 'Redline Lines', 0, 116.5, 
    105, 116.5, 27302111, 0, 0, 
    NULL, 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20006014, 20006, 'Redline Lines', 0, 124, 
    105, 124, 27302111, 0, 0, 
    NULL, 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20006015, 20006, 'Redline Lines', 0, 0, 
    0, 124, 27302111, 0, 0, 
    NULL, 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20006016, 20006, 'Redline Lines', 9.5, 7, 
    9.5, 23, 27302111, 0, 0, 
    NULL, 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20006017, 20006, 'Redline Lines', 13.5, 7, 
    13.5, 23, 27302111, 0, 0, 
    NULL, 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20006018, 20006, 'Redline Lines', 20.75, 7, 
    20.75, 23, 27302111, 0, 0, 
    NULL, 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20006019, 20006, 'Redline Lines', 35, 94, 
    35, 124, 27302111, 0, 0, 
    NULL, 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20006020, 20006, 'Redline Lines', 70, 94, 
    70, 124, 27302111, 0, 0, 
    NULL, 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20006021, 20006, 'Redline Lines', 105, 0, 
    105, 124, 27302111, 0, 0, 
    NULL, 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20006106, 20006, 'Redline Text', 0.5, 45.25, 
    NULL, NULL, 10001, 1, 0, 
    'Title :', 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20006100, 20006, 'Redline Text', 39, 2.5, 
    NULL, NULL, 10005, 1, 0, 
    'REVISIONS', 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20006101, 20006, 'Redline Text', 0.5, 8.5, 
    NULL, NULL, 10001, 1, 0, 
    'Date', 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20006102, 20006, 'Redline Text', 10, 8.5, 
    NULL, NULL, 10001, 1, 0, 
    'By', 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20006103, 20006, 'Redline Text', 14, 8.5, 
    NULL, NULL, 10001, 1, 0, 
    'App''d', 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20006104, 20006, 'Redline Text', 52, 8.5, 
    NULL, NULL, 10001, 1, 0, 
    'Remarks', 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20006105, 20006, 'Redline Text', 24, 38.5, 
    NULL, NULL, 10005, 1, 0, 
    'AS -', 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20006107, 20006, 'Redline Text', 13.5, 49.5, 
    NULL, NULL, 10005, 1, 0, 
    '[JOB_MODIFY_NAME]', 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20006108, 20006, 'Redline Text', 0.5, 56, 
    NULL, NULL, 10001, 1, 0, 
    'Description :', 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20006109, 20006, 'Redline Text', 21, 56, 
    NULL, NULL, 10000, 1, 0, 
    '[G3E_DESCRIPTION]', 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20006110, 20006, 'Redline Text', 0.5, 95.5, 
    NULL, NULL, 10001, 1, 0, 
    'Plot Name', 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20006111, 20006, 'Redline Text', 2.5, 98, 
    NULL, NULL, 10000, 1, 0, 
    '[NAME]', 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20006112, 20006, 'Redline Text', 35.5, 95.5, 
    NULL, NULL, 10001, 1, 0, 
    'Place Date', 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20006113, 20006, 'Redline Text', 37.5, 98, 
    NULL, NULL, 10000, 1, 0, 
    '[JOB_PLACE_DATE]', 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20006114, 20006, 'Redline Text', 70.5, 95.5, 
    NULL, NULL, 10001, 1, 0, 
    'Modify Date', 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20006115, 20006, 'Redline Text', 72.5, 98, 
    NULL, NULL, 10000, 1, 0, 
    '[JOB_MODIFY_DATE]', 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20006123, 20006, 'Redline Text', 2.5, 113, 
    NULL, NULL, 10000, 1, 0, 
    '[G3E_OWNER]', 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20006124, 20006, 'Redline Text', 35.5, 110.5, 
    NULL, NULL, 10001, 1, 0, 
    'Date Drawn :', 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20006125, 20006, 'Redline Text', 37.5, 113, 
    NULL, NULL, 10000, 1, 0, 
    '[SYSDATE]', 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20006126, 20006, 'Redline Text', 70.5, 110.5, 
    NULL, NULL, 10001, 1, 0, 
    'SIGNATURE', 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20006127, 20006, 'Redline Text', 0.5, 118, 
    NULL, NULL, 10001, 1, 0, 
    'Scale :', 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20006128, 20006, 'Redline Text', 2.5, 120.5, 
    NULL, NULL, 10000, 1, 0, 
    '[SCALE]', 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20006116, 20006, 'Redline Text', 0.5, 103, 
    NULL, NULL, 10001, 1, 0, 
    'District :', 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20006117, 20006, 'Redline Text', 2.5, 105.5, 
    NULL, NULL, 10000, 1, 0, 
    '[TAX_DISTRICT]', 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20006118, 20006, 'Redline Text', 35.5, 103, 
    NULL, NULL, 10001, 1, 0, 
    'Job Region', 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20006119, 20006, 'Redline Text', 37.5, 105.5, 
    NULL, NULL, 10000, 1, 0, 
    '[REGION]', 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20006120, 20006, 'Redline Text', 37.5, 108, 
    NULL, NULL, 10000, 1, 0, 
    ' ', 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20006121, 20006, 'Redline Text', 70.5, 103, 
    NULL, NULL, 10001, 1, 0, 
    'Autherized:', 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20006122, 20006, 'Redline Text', 0.5, 110.5, 
    NULL, NULL, 10001, 1, 0, 
    'Drawn By :', 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20006129, 20006, 'Redline Text', 70.5, 118.5, 
    NULL, NULL, 10003, 1, 0, 
    'Drawing Number', 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20006130, 20006, 'Redline Text', 78, 122, 
    NULL, NULL, 10003, 1, 0, 
    '[SHEET_NUM]', 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20006131, 20006, 'Redline Text', 84, 122, 
    NULL, NULL, 10003, 1, 0, 
    'OF', 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20006132, 20006, 'Redline Text', 92, 122, 
    NULL, NULL, 10003, 1, 0, 
    '[TOTAL_SHEETS]', 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20007017, 20007, 'Redline Lines', 200.5, 0, 
    200.5, 64, 27302111, 0, 0, 
    NULL, 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20007100, 20007, 'Redline Text', 25, 45, 
    NULL, NULL, 10005, 1, 0, 
    'REVISIONS', 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20007101, 20007, 'Redline Text', 0.5, 50.5, 
    NULL, NULL, 10001, 1, 0, 
    'Date', 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20007102, 20007, 'Redline Text', 8.5, 50.5, 
    NULL, NULL, 10001, 1, 0, 
    'By', 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20007103, 20007, 'Redline Text', 13.5, 50.5, 
    NULL, NULL, 10001, 1, 0, 
    'App''d', 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20007104, 20007, 'Redline Text', 37.5, 50.5, 
    NULL, NULL, 10001, 1, 0, 
    'Remarks', 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20007105, 20007, 'Redline Text', 84, 14, 
    NULL, NULL, 10005, 1, 0, 
    'AS -', 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20007106, 20007, 'Redline Text', 70.5, 19.5, 
    NULL, NULL, 10001, 1, 0, 
    'Title :', 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20007107, 20007, 'Redline Text', 79, 24.75, 
    NULL, NULL, 10005, 1, 0, 
    '[JOB_MODIFY_NAME]', 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20007108, 20007, 'Redline Text', 70.5, 33, 
    NULL, NULL, 10001, 1, 0, 
    'Description :', 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20007109, 20007, 'Redline Text', 84, 33, 
    NULL, NULL, 10000, 1, 0, 
    '[G3E_DESCRIPTION]', 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20007110, 20007, 'Redline Text', 159.5, 1.5, 
    NULL, NULL, 10001, 1, 0, 
    'Plot Name', 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20007111, 20007, 'Redline Text', 173, 1.5, 
    NULL, NULL, 10000, 1, 0, 
    '[NAME]', 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20007112, 20007, 'Redline Text', 159.5, 5.5, 
    NULL, NULL, 10001, 1, 0, 
    'Place Date', 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20007113, 20007, 'Redline Text', 173, 5.5, 
    NULL, NULL, 10000, 1, 0, 
    '[JOB_PLACE_DATE]', 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20007114, 20007, 'Redline Text', 159.5, 9.5, 
    NULL, NULL, 10001, 1, 0, 
    'Modify Date', 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20007115, 20007, 'Redline Text', 173, 9.5, 
    NULL, NULL, 10000, 1, 0, 
    '[JOB_MODIFY_DATE]', 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20007116, 20007, 'Redline Text', 159.5, 13.5, 
    NULL, NULL, 10001, 1, 0, 
    'District :', 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20007117, 20007, 'Redline Text', 173, 13.5, 
    NULL, NULL, 10000, 1, 0, 
    '[TAX_DISTRICT]', 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20007118, 20007, 'Redline Text', 159.5, 17.5, 
    NULL, NULL, 10001, 1, 0, 
    'Job Region', 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20007119, 20007, 'Redline Text', 173, 17.5, 
    NULL, NULL, 10000, 1, 0, 
    '[REGION]', 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20007120, 20007, 'Redline Text', 173, 20, 
    NULL, NULL, 10000, 1, 0, 
    ' ', 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20007121, 20007, 'Redline Text', 159.5, 24, 
    NULL, NULL, 10001, 1, 0, 
    'Drawn By :', 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20007122, 20007, 'Redline Text', 173, 24, 
    NULL, NULL, 10000, 1, 0, 
    '[G3E_OWNER]', 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20007123, 20007, 'Redline Text', 159.5, 28, 
    NULL, NULL, 10001, 1, 0, 
    'Date Drawn :', 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20007124, 20007, 'Redline Text', 173, 28, 
    NULL, NULL, 10000, 1, 0, 
    '[SYSDATE]', 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20007125, 20007, 'Redline Text', 159.5, 32, 
    NULL, NULL, 10001, 1, 0, 
    'Scale :', 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20007126, 20007, 'Redline Text', 173, 32, 
    NULL, NULL, 10000, 1, 0, 
    '[SCALE]', 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20007127, 20007, 'Redline Text', 159.5, 36, 
    NULL, NULL, 10001, 1, 0, 
    'Autherized:', 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20007128, 20007, 'Redline Text', 159.5, 40, 
    NULL, NULL, 10001, 1, 0, 
    'SIGNATURE', 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20007129, 20007, 'Redline Text', 159.5, 57, 
    NULL, NULL, 10003, 1, 0, 
    'Drawing Number', 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20007130, 20007, 'Redline Text', 172, 61, 
    NULL, NULL, 10003, 1, 0, 
    '[SHEET_NUM]', 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20007131, 20007, 'Redline Text', 178, 61, 
    NULL, NULL, 10003, 1, 0, 
    'OF', 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20002001, 20002, 'Redline Text', 0, 0, 
    NULL, NULL, 5033, 1, 0, 
    'Printed - Date:', 0, NULL, NULL);
Insert into GT_PLOT_REDLINES
   (RL_NO, GROUP_NO, RL_DATATYPE, RL_COORDINATE_X1, RL_COORDINATE_Y1, 
    RL_COORDINATE_X2, RL_COORDINATE_Y2, RL_STYLE_NUMBER, RL_TEXT_ALIGNMENT, RL_ROTATION, 
    RL_TEXT, RL_USERINPUT, RL_NAME, RL_TEXT_FR)
 Values
   (20002002, 20002, 'Redline Text', 15, 0, 
    NULL, NULL, 5034, 1, 0, 
    '[SYSDATE]', 0, NULL, NULL);
COMMIT;
