  CREATE TABLE "GIS_ONC"."OPERBNDY_LOOKUP" 
   ("SVCCTR_ID" NUMBER(10,0), 
	"DSTRCT_ID" NUMBER(10,0), 
	"DOC_ID" NUMBER(10,0), 
	"SVCCTR" VARCHAR2(3 BYTE), 
	"DSTRCT" VARCHAR2(3 BYTE), 
	"DOC" VARCHAR2(4 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GIS_TS" ;