SET ECHO ON
SET LINESIZE 1000
SET PAGESIZE 300
SET TRIMSPOOL ON
SPOOL RESET_DEVICE_ID_SEQ.LOG

DROP SEQUENCE GIS.DEVICE_ID_SEQ;

DECLARE
  MAX_DEVID_SEQ VARCHAR2 (200) ;
BEGIN

  SELECT   TO_CHAR (TRUNC (MAX (MODIFICATIONNUMBER)) + 1)
    INTO MAX_DEVID_SEQ
    FROM MODIFICATIONLOG;
  EXECUTE IMMEDIATE 'CREATE SEQUENCE GIS.DEVICE_ID_SEQ START WITH '|| MAX_DEVID_SEQ ||' MAXVALUE 999999999999999999999999999 MINVALUE 1 NOCYCLE CACHE 50 ORDER';

END;
/
DROP PUBLIC SYNONYM GIS.DEVICE_ID_SEQ;

CREATE OR REPLACE PUBLIC SYNONYM GIS.DEVICE_ID_SEQ FOR GIS.DEVICE_ID_SEQ;

GRANT ALTER ON GIS.DEVICE_ID_SEQ TO EVERYONE;

GRANT ALTER ON GIS.DEVICE_ID_SEQ TO FINANCE;

GRANT ALTER ON GIS.DEVICE_ID_SEQ TO MARKETING;

GRANT ALTER ON GIS.DEVICE_ID_SEQ TO SUPERVISOR;

GRANT ALTER ON GIS.DEVICE_ID_SEQ TO DESIGNER;

GRANT SELECT ON GIS.DEVICE_ID_SEQ TO EVERYONE;

GRANT SELECT ON GIS.DEVICE_ID_SEQ TO GIS_EXEC_ROLE;

GRANT SELECT ON GIS.DEVICE_ID_SEQ TO FINANCE;

GRANT SELECT ON GIS.DEVICE_ID_SEQ TO MARKETING;

GRANT SELECT ON GIS.DEVICE_ID_SEQ TO SUPERVISOR;

GRANT SELECT ON GIS.DEVICE_ID_SEQ TO DESIGNER;

GRANT SELECT ON GIS.DEVICE_ID_SEQ TO GIS_RW;

SPOOL OFF;