SET ECHO ON
SET LINESIZE 1000
SET PAGESIZE 300
SET TRIMSPOOL ON
SPOOL RESET_MODLOG_SEQ.LOG

DROP SEQUENCE GIS.G3E_MODLOG_SEQ;

DECLARE
  MAX_MODLOG_SEQ VARCHAR2 (200) ;
BEGIN

  SELECT   TO_CHAR (TRUNC (MAX (MODIFICATIONNUMBER)) + 1)
    INTO MAX_MODLOG_SEQ
    FROM MODIFICATIONLOG;
  EXECUTE IMMEDIATE 'CREATE SEQUENCE GIS.G3E_MODLOG_SEQ START WITH '|| MAX_MODLOG_SEQ ||' MAXVALUE 999999999999999999999999999 MINVALUE 1 NOCYCLE CACHE 50 ORDER';

END;
/
DROP PUBLIC SYNONYM GIS.G3E_MODLOG_SEQ;

CREATE OR REPLACE PUBLIC SYNONYM GIS.G3E_MODLOG_SEQ FOR GIS.G3E_MODLOG_SEQ;

GRANT SELECT ON GIS.G3E_MODLOG_SEQ TO DESIGNER;

GRANT SELECT ON GIS.G3E_MODLOG_SEQ TO FINANCE;

GRANT SELECT ON GIS.G3E_MODLOG_SEQ TO GIS_EXEC_ROLE;

GRANT SELECT ON GIS.G3E_MODLOG_SEQ TO GIS_RW;

GRANT SELECT ON GIS.G3E_MODLOG_SEQ TO MARKETING;

GRANT SELECT ON GIS.G3E_MODLOG_SEQ TO SUPERVISOR;

SPOOL OFF;