DROP TRIGGER "GIS_STG"."BIU_STG_CULIB_MULTI_CAT_TBL_TR";

CREATE OR REPLACE EDITIONABLE TRIGGER "GIS_STG"."BIU_STG_CULIB_MULTI_CAT_TBL_TR" 
BEFORE UPDATE ON GIS_STG.STG_CULIB_MULTIPLE_CATEGORY

FOR EACH ROW
BEGIN
  IF UPDATING THEN
	SELECT SYSDATE INTO :NEW.AUD_MOD_DT FROM dual;
	SELECT USER INTO :NEW.AUD_MOD_USR_ID FROM dual;
  END IF;
END;


/
ALTER TRIGGER "GIS_STG"."BIU_STG_CULIB_MULTI_CAT_TBL_TR" ENABLE;