CREATE OR REPLACE EDITIONABLE TRIGGER GIS_STG.BIU_STG_TRC_ACT_ATTACH_TR 
BEFORE UPDATE ON GIS_STG.STG_TRC_ACTIVE_ATTACHMENTS

FOR EACH ROW 
BEGIN 
  IF UPDATING THEN
	SELECT SYSDATE INTO :NEW.AUD_MOD_TS FROM dual;
	SELECT USER INTO :NEW.AUD_MOD_USR_ID FROM dual;
  END IF;
END;
/
