DECLARE
	TYPE SYS_GEN_PARAM_LIST_TYPE IS TABLE OF GIS_ONC.SYS_GENERALPARAMETER%ROWTYPE index by pls_integer;
	SYS_GEN_PARAM_LIST SYS_GEN_PARAM_LIST_TYPE;
	
	--Replacment Vars
	EDGEFRONTIER_HOST_NAME VARCHAR2(200) ; 	
	WRITEBACK_SERVICE_CONN_STR VARCHAR2(200);
	DOC_MANAGMENT_SP_URL VARCHAR2(200);
	DOC_MANAGMENT_REL_PATH VARCHAR2(200);
	DOC_MANAGMENT_ROOT_PATH VARCHAR2(200);
	rowCnt number := 0;
	FUNCTION EF_SERVICE_URL(
			v_HOST_NAME VARCHAR2,
			v_PORT VARCHAR2 )
		RETURN VARCHAR2
	IS
	BEGIN
		RETURN 'http://' || v_HOST_NAME || ':' || v_PORT || '/interface';
	END EF_SERVICE_URL;
BEGIN
	EDGEFRONTIER_HOST_NAME := '&EDGEFRONTIER_HOST_NAME';
	WRITEBACK_SERVICE_CONN_STR := '&WRITEBACK_SERVICE_CONN_STR';
	DOC_MANAGMENT_SP_URL := '&DOC_MANAGMENT_SP_URL';
	DOC_MANAGMENT_REL_PATH := '&DOC_MANAGMENT_REL_PATH';
	DOC_MANAGMENT_ROOT_PATH := '&DOC_MANAGMENT_ROOT_PATH';
	
	-- System Parameter Array
	SYS_GEN_PARAM_LIST(1).SUBSYSTEM_NAME := 'EdgeFrontier';
	SYS_GEN_PARAM_LIST(1).SUBSYSTEM_COMPONENT := 'GIS_CreateFieldTransaction';
	SYS_GEN_PARAM_LIST(1).PARAM_NAME := 'EF_URL';
	SYS_GEN_PARAM_LIST(1).PARAM_VALUE := EF_SERVICE_URL(EDGEFRONTIER_HOST_NAME,'8013');
	
	SYS_GEN_PARAM_LIST(2).SUBSYSTEM_NAME := 'EdgeFrontier';
	SYS_GEN_PARAM_LIST(2).SUBSYSTEM_COMPONENT := 'GIS_CreateUpdateJob';
	SYS_GEN_PARAM_LIST(2).PARAM_NAME := 'EF_URL';
	SYS_GEN_PARAM_LIST(2).PARAM_VALUE := EF_SERVICE_URL(EDGEFRONTIER_HOST_NAME,'8010');
	
	SYS_GEN_PARAM_LIST(3).SUBSYSTEM_NAME := 'EdgeFrontier';
	SYS_GEN_PARAM_LIST(3).SUBSYSTEM_COMPONENT := 'GIS_RequestBatch';
	SYS_GEN_PARAM_LIST(3).PARAM_NAME := 'EF_URL';
	SYS_GEN_PARAM_LIST(3).PARAM_VALUE :=  EF_SERVICE_URL(EDGEFRONTIER_HOST_NAME,'8012');
	
	SYS_GEN_PARAM_LIST(4).SUBSYSTEM_NAME := 'EdgeFrontier';
	SYS_GEN_PARAM_LIST(4).SUBSYSTEM_COMPONENT := 'GIS_UpdateWritebackStatus';
	SYS_GEN_PARAM_LIST(4).PARAM_NAME := 'EF_URL';
	SYS_GEN_PARAM_LIST(4).PARAM_VALUE := EF_SERVICE_URL(EDGEFRONTIER_HOST_NAME,'8011');
	
	SYS_GEN_PARAM_LIST(5).SUBSYSTEM_NAME := 'EdgeFrontier';
	SYS_GEN_PARAM_LIST(5).SUBSYSTEM_COMPONENT := 'NJUNS_CheckTicketStatus';
	SYS_GEN_PARAM_LIST(5).PARAM_NAME := 'EF_URL';
	SYS_GEN_PARAM_LIST(5).PARAM_VALUE := EF_SERVICE_URL(EDGEFRONTIER_HOST_NAME,'8050');
	
	SYS_GEN_PARAM_LIST(6).SUBSYSTEM_NAME := 'EdgeFrontier';
	SYS_GEN_PARAM_LIST(6).SUBSYSTEM_COMPONENT := 'NJUNS_MemberCodeUpdate';
	SYS_GEN_PARAM_LIST(6).PARAM_NAME := 'EF_URL';
	SYS_GEN_PARAM_LIST(6).PARAM_VALUE := EF_SERVICE_URL(EDGEFRONTIER_HOST_NAME,'8052');
	
	SYS_GEN_PARAM_LIST(7).SUBSYSTEM_NAME := 'EdgeFrontier';
	SYS_GEN_PARAM_LIST(7).SUBSYSTEM_COMPONENT := 'NJUNS_SubmitTicket';
	SYS_GEN_PARAM_LIST(7).PARAM_NAME := 'EF_URL';
	SYS_GEN_PARAM_LIST(7).PARAM_VALUE := EF_SERVICE_URL(EDGEFRONTIER_HOST_NAME,'8051');
	
	SYS_GEN_PARAM_LIST(8).SUBSYSTEM_NAME := 'EdgeFrontier';
	SYS_GEN_PARAM_LIST(8).SUBSYSTEM_COMPONENT := 'SendEmail';
	SYS_GEN_PARAM_LIST(8).PARAM_NAME := 'EF_URL';
	SYS_GEN_PARAM_LIST(8).PARAM_VALUE := EF_SERVICE_URL(EDGEFRONTIER_HOST_NAME,'8089');
	
	SYS_GEN_PARAM_LIST(9).SUBSYSTEM_NAME := 'EdgeFrontier';
	SYS_GEN_PARAM_LIST(9).SUBSYSTEM_COMPONENT := 'WMIS_SendBatchResults';
	SYS_GEN_PARAM_LIST(9).PARAM_NAME := 'EF_URL';
	SYS_GEN_PARAM_LIST(9).PARAM_VALUE := EF_SERVICE_URL(EDGEFRONTIER_HOST_NAME,'8030');
	
	SYS_GEN_PARAM_LIST(10).SUBSYSTEM_NAME := 'EdgeFrontier';
	SYS_GEN_PARAM_LIST(10).SUBSYSTEM_COMPONENT := 'WMIS_UpdateStatus';
	SYS_GEN_PARAM_LIST(10).PARAM_NAME := 'EF_URL';
	SYS_GEN_PARAM_LIST(10).PARAM_VALUE := EF_SERVICE_URL(EDGEFRONTIER_HOST_NAME,'8031');
	
	SYS_GEN_PARAM_LIST(11).SUBSYSTEM_NAME := 'EdgeFrontier';
	SYS_GEN_PARAM_LIST(11).SUBSYSTEM_COMPONENT := 'WMIS_WriteBack';
	SYS_GEN_PARAM_LIST(11).PARAM_NAME := 'EF_URL';
	SYS_GEN_PARAM_LIST(11).PARAM_VALUE := EF_SERVICE_URL(EDGEFRONTIER_HOST_NAME,'8032');
	
	SYS_GEN_PARAM_LIST(12).SUBSYSTEM_NAME := 'SEND_EMAIL';
	SYS_GEN_PARAM_LIST(12).SUBSYSTEM_COMPONENT := null;
	SYS_GEN_PARAM_LIST(12).PARAM_NAME := 'EF_URL';
	SYS_GEN_PARAM_LIST(12).PARAM_VALUE := EF_SERVICE_URL(EDGEFRONTIER_HOST_NAME,'8089');
	
	SYS_GEN_PARAM_LIST(13).SUBSYSTEM_NAME := 'WMIS';
	SYS_GEN_PARAM_LIST(13).SUBSYSTEM_COMPONENT := 'WMIS_UpdateStatus';
	SYS_GEN_PARAM_LIST(13).PARAM_NAME := 'EF_URL';
	SYS_GEN_PARAM_LIST(13).PARAM_VALUE := EF_SERVICE_URL(EDGEFRONTIER_HOST_NAME,'8031');
	
	SYS_GEN_PARAM_LIST(14).SUBSYSTEM_NAME := 'WMIS';
	SYS_GEN_PARAM_LIST(14).SUBSYSTEM_COMPONENT := 'WMIS_WRITERBACK';
	SYS_GEN_PARAM_LIST(14).PARAM_NAME := 'EF_URL';
	SYS_GEN_PARAM_LIST(14).PARAM_VALUE := EF_SERVICE_URL(EDGEFRONTIER_HOST_NAME,'8032');
	
	SYS_GEN_PARAM_LIST(15).SUBSYSTEM_NAME := 'WMIS';
	SYS_GEN_PARAM_LIST(15).SUBSYSTEM_COMPONENT := 'WMIS_WRITEBACK';
	SYS_GEN_PARAM_LIST(15).PARAM_NAME := 'ConnectionString';
	SYS_GEN_PARAM_LIST(15).PARAM_VALUE := WRITEBACK_SERVICE_CONN_STR;
	
	SYS_GEN_PARAM_LIST(16).SUBSYSTEM_NAME := 'GISAUTO_DEIS';
	SYS_GEN_PARAM_LIST(16).SUBSYSTEM_COMPONENT := 'URL';
	SYS_GEN_PARAM_LIST(16).PARAM_NAME := 'DEIS_RESPONSE_WEB_ADDRESS';
	SYS_GEN_PARAM_LIST(16).PARAM_VALUE := EF_SERVICE_URL(EDGEFRONTIER_HOST_NAME,'8061');	
	
	SYS_GEN_PARAM_LIST(17).SUBSYSTEM_NAME := 'TRC_IMPORT';
	SYS_GEN_PARAM_LIST(17).SUBSYSTEM_COMPONENT := 'LttUserConfig';
	SYS_GEN_PARAM_LIST(17).PARAM_NAME := 'LttUserConfig';
	SYS_GEN_PARAM_LIST(17).PARAM_VALUE := 'GIS';
	SYS_GEN_PARAM_LIST(17).PARAM_DESC := 	'Used by TRC_IMPORT Interface for short term transaction to get the correct GTech Configuration';	

	SYS_GEN_PARAM_LIST(18).SUBSYSTEM_NAME := 'Doc_Management';
	SYS_GEN_PARAM_LIST(18).SUBSYSTEM_COMPONENT := 'GT_SharePoint';
	SYS_GEN_PARAM_LIST(18).PARAM_NAME := 'SP_URL';
	SYS_GEN_PARAM_LIST(18).PARAM_VALUE := DOC_MANAGMENT_SP_URL;
	SYS_GEN_PARAM_LIST(18).PARAM_DESC := 	'SharePoint site URL';
	
	SYS_GEN_PARAM_LIST(19).SUBSYSTEM_NAME := 'Doc_Management';
	SYS_GEN_PARAM_LIST(19).SUBSYSTEM_COMPONENT := 'GT_SharePoint';
	SYS_GEN_PARAM_LIST(19).PARAM_NAME := 'ROOT_PATH';
	SYS_GEN_PARAM_LIST(19).PARAM_VALUE := DOC_MANAGMENT_ROOT_PATH;
	SYS_GEN_PARAM_LIST(19).PARAM_DESC := 	'Name of root site';
	
	SYS_GEN_PARAM_LIST(20).SUBSYSTEM_NAME := 'Doc_Management';
	SYS_GEN_PARAM_LIST(20).SUBSYSTEM_COMPONENT := 'GT_SharePoint';
	SYS_GEN_PARAM_LIST(20).PARAM_NAME := 'JOBWO_REL_PATH';
	SYS_GEN_PARAM_LIST(20).PARAM_VALUE := DOC_MANAGMENT_REL_PATH;
	SYS_GEN_PARAM_LIST(20).PARAM_DESC := 	'Path to Job Docs.';
	
--		SYS_GEN_PARAM_LIST(18).SUBSYSTEM_NAME := 'TRC_IMPORT';
--	SYS_GEN_PARAM_LIST(18).SUBSYSTEM_COMPONENT := 'ErrorLoggingMail';
--	SYS_GEN_PARAM_LIST(18).PARAM_NAME := 'AttachFromAddr';
--	SYS_GEN_PARAM_LIST(18).PARAM_VALUE := 'testemail';
--	SYS_GEN_PARAM_LIST(18).PARAM_DESC := 	'Used by TRC_IMPORT Interface to get destination email address for error messages';
    
    --Doc_Management	GT_SharePoint	SP_URL
	FOR I IN SYS_GEN_PARAM_LIST.FIRST..SYS_GEN_PARAM_LIST.LAST
	LOOP
		SELECT  COUNT( * )
			INTO ROWCNT
			FROM GIS_ONC.SYS_GENERALPARAMETER GP
			WHERE GP.SUBSYSTEM_NAME = SYS_GEN_PARAM_LIST(I).SUBSYSTEM_NAME
				AND NVL(GP.SUBSYSTEM_COMPONENT,'NULL') = NVL(SYS_GEN_PARAM_LIST(I).SUBSYSTEM_COMPONENT,'NULL')
				AND GP.PARAM_NAME = SYS_GEN_PARAM_LIST(I).PARAM_NAME;
		
			IF (ROWCNT = 0) THEN
				INSERT INTO GIS_ONC.SYS_GENERALPARAMETER VALUES SYS_GEN_PARAM_LIST(I);
				DBMS_OUTPUT.PUT_LINE('Insert SUBSYSTEM_NAME: '|| SYS_GEN_PARAM_LIST(I).SUBSYSTEM_NAME 
													|| ', SUBSYSTEM_COMPONENT: '  || SYS_GEN_PARAM_LIST(I).SUBSYSTEM_COMPONENT 
													|| ', PARAM_NAME: ' || SYS_GEN_PARAM_LIST(I).PARAM_NAME 
													|| ', PARAM_VALUE: ' ||SYS_GEN_PARAM_LIST(I).PARAM_VALUE
													|| ', PARAM_DESC: ' ||SYS_GEN_PARAM_LIST(I).PARAM_DESC);
			ELSIF (ROWCNT = 1) THEN
				
				DBMS_OUTPUT.PUT_LINE('Updated PARAM_VALUE for SUBSYSTEM_NAME: '|| SYS_GEN_PARAM_LIST(I).SUBSYSTEM_NAME 
													|| ', SUBSYSTEM_COMPONENT: '  || SYS_GEN_PARAM_LIST(I).SUBSYSTEM_COMPONENT 
													|| ', PARAM_NAME: ' || SYS_GEN_PARAM_LIST(I).PARAM_NAME 
													|| ', PARAM_VALUE: ' ||SYS_GEN_PARAM_LIST(I).PARAM_VALUE
													|| ', PARAM_DESC: ' ||SYS_GEN_PARAM_LIST(I).PARAM_DESC);
				UPDATE GIS_ONC.SYS_GENERALPARAMETER GP
					SET GP.PARAM_VALUE = SYS_GEN_PARAM_LIST(I).PARAM_VALUE
					WHERE GP.SUBSYSTEM_NAME = SYS_GEN_PARAM_LIST(I).SUBSYSTEM_NAME
						AND NVL(GP.SUBSYSTEM_COMPONENT,'NULL') = NVL(SYS_GEN_PARAM_LIST(I).SUBSYSTEM_COMPONENT,'NULL')
						AND GP.PARAM_NAME = SYS_GEN_PARAM_LIST(I).PARAM_NAME;
			else
				DBMS_OUTPUT.PUT_LINE('Error setting GIS_ONC.SYS_GENERALPARAMETER SUBSYSTEM_NAME: '|| SYS_GEN_PARAM_LIST(I).SUBSYSTEM_NAME 
													|| ', SUBSYSTEM_COMPONENT: '  || SYS_GEN_PARAM_LIST(I).SUBSYSTEM_COMPONENT 
													|| ', PARAM_NAME: ' || SYS_GEN_PARAM_LIST(I).PARAM_NAME 
													|| ', PARAM_VALUE: ' ||SYS_GEN_PARAM_LIST(I).PARAM_VALUE
													|| ', PARAM_DESC: ' ||SYS_GEN_PARAM_LIST(I).PARAM_DESC);
				RAISE_APPLICATION_ERROR (-20000, 'Error setting GIS_ONC.SYS_GENERALPARAMETER SUBSYSTEM_NAME: '|| SYS_GEN_PARAM_LIST(I).SUBSYSTEM_NAME 
													|| ', SUBSYSTEM_COMPONENT: '  || SYS_GEN_PARAM_LIST(I).SUBSYSTEM_COMPONENT 
													|| ', PARAM_NAME: ' || SYS_GEN_PARAM_LIST(I).PARAM_NAME );
			END IF;
					
		END LOOP;
	COMMIT;
END;
/