-- VIEWS FOUND IN MASTER SCRIPT

ALTER VIEW AMS_COLLECTORS_VW COMPILE;

ALTER VIEW AMS_ROUTERS_VW COMPILE;

ALTER VIEW AUTO_SWITCHGEARS_VW COMPILE;

ALTER VIEW AUTO_TRANSFORMER_VW COMPILE;

ALTER VIEW BREAKER_VW COMPILE;

ALTER VIEW CAPACITOR_VW COMPILE;

ALTER VIEW CONDUIT_VW COMPILE;

ALTER VIEW CONNECTIVITY_VW COMPILE;

ALTER VIEW FUSE_VW COMPILE;

ALTER VIEW GUY_VW COMPILE;

ALTER VIEW JUNCTION_POINT_VW COMPILE;

ALTER VIEW MANHOLE_VW COMPILE;

ALTER VIEW PADS_VW COMPILE;

ALTER VIEW POLE_VW COMPILE;

ALTER VIEW PRI_ENCLOSURE_VW COMPILE;

ALTER VIEW PRI_PULL_BOX_VW COMPILE;

ALTER VIEW PRI_SWITCHGEAR_VW COMPILE;

ALTER VIEW PRI_UG_COND_VW COMPILE;

ALTER VIEW PRIMARY_BOX_VW COMPILE;

ALTER VIEW RECLOSER_VW COMPILE;

ALTER VIEW RISER_VW COMPILE;

ALTER VIEW SEC_BOX_VW COMPILE;

ALTER VIEW SEC_ENCLOSURE_VW COMPILE;

ALTER VIEW SEC_SWITCHGEAR_VW COMPILE;

ALTER VIEW SECONDARY_CONNECTIVITY_VW COMPILE;

ALTER VIEW SERVICE_LINE_VW COMPILE;

ALTER VIEW SUBSTATION_BREAKER_VW COMPILE;

ALTER VIEW SUBSTATION_VW COMPILE;

ALTER VIEW TRANS_TOWER_VW COMPILE;

ALTER VIEW UG_TRANSFORMER_VW COMPILE;

ALTER VIEW VAULTS_VW COMPILE;

ALTER VIEW VOLTAGE_REGULATOR_VW COMPILE;

ALTER VIEW SEC_COND_VW COMPILE;

ALTER VIEW SEC_WIRE_VW COMPILE;

ALTER VIEW OH_XFMR_BANK_VW COMPILE;

ALTER VIEW OH_XFMR_UNIT_VW COMPILE;

ALTER VIEW PRI_OH_COND_VW COMPILE;

ALTER VIEW PRI_OH_WIRE_VW COMPILE;

ALTER VIEW OBERBNDY_COND_STRC_VW COMPILE;

ALTER VIEW OPERBNDY_FEEDER_VW COMPILE;

ALTER VIEW OPERBNDY_SVCCTR_VW COMPILE;

ALTER VIEW ATTACH_EQPT_VW COMPILE;

ALTER VIEW ATTACH_WIRELINE_VW COMPILE;

ALTER VIEW PRI_UG_WIRE_VW COMPILE;

ALTER VIEW WRVIEW_VOUCHER COMPILE;

ALTER VIEW STREETLIGHT_CONTROL_VW COMPILE;

ALTER VIEW SWITCH_VW COMPILE;

--OTHERS NOT IN MASTER SCRIPT

ALTER VIEW OH_TRANSFORMER_VW COMPILE;

ALTER VIEW PAD_MOUNT_XFMR_VW COMPILE;

ALTER VIEW PRIMARY_OVERHEAD_CONDUCTOR_VW COMPILE;


