UNDEFINE EDGEFRONTIER_HOST_NAME
UNDEFINE WRITEBACK_SERVICE_CONN_STR
UNDEFINE DOC_MANAGMENT_SP_URL
UNDEFINE DOC_MANAGMENT_REL_PATH
UNDEFINE DOC_MANAGMENT_ROOT_PATH

--tst

DEFINE EDGEFRONTIER_HOST_NAME = 'http://wv00776.test.corp.oncor.com:8032/interface'
DEFINE WRITEBACK_SERVICE_CONN_STR = 'User Id=gis;Password=giscrt#12345;Data Source=DGSCRT'
DEFINE DOC_MANAGMENT_SP_URL = '/sgi/infr/UCServices/Oncor%20F2G%20Gap%20Analysis/F2G Project/Development/Integration/Document Management/Job Documents'
DEFINE DOC_MANAGMENT_REL_PATH = '/sgi/infr/UCServices/Oncor%20F2G%20Gap%20Analysis/F2G Project/Development/Integration/Document'
DEFINE DOC_MANAGMENT_ROOT_PATH = 'ProjectDocuments'

