UNDEFINE EDGEFRONTIER_HOST_NAME
UNDEFINE WRITEBACK_SERVICE_CONN_STR
UNDEFINE DOC_MANAGMENT_SP_URL
UNDEFINE DOC_MANAGMENT_REL_PATH
UNDEFINE DOC_MANAGMENT_ROOT_PATH

--dev

DEFINE EDGEFRONTIER_HOST_NAME = 'wv00731.build.corp.oncor.com'
DEFINE WRITEBACK_SERVICE_CONN_STR = 'User Id=gis;Password=gisdev#12345;Data Source=DGSDEV'
DEFINE DOC_MANAGMENT_SP_URL = 'http://bfxintranet.corp.oncor.com/sites/aegis'
DEFINE DOC_MANAGMENT_REL_PATH = '/sites/aegis/ProjectDocuments/Job Documents'
DEFINE DOC_MANAGMENT_ROOT_PATH = 'ProjectDocuments'

