UNDEFINE EDGEFRONTIER_HOST_NAME
UNDEFINE WRITEBACK_SERVICE_CONN_STR
UNDEFINE DOC_MANAGMENT_SP_URL
UNDEFINE DOC_MANAGMENT_REL_PATH
UNDEFINE DOC_MANAGMENT_ROOT_PATH

--tst

DEFINE EDGEFRONTIER_HOST_NAME = 'http://wv00490.test.corp.oncor.com:8032/interface'
DEFINE WRITEBACK_SERVICE_CONN_STR = 'User Id=gis;Password=gistst1#12345;Data Source=DGSTST1'
DEFINE DOC_MANAGMENT_SP_URL = 'https://share.intergraph.com/sgi/infr/UCServices'
DEFINE DOC_MANAGMENT_REL_PATH = '/sgi/infr/UCServices/Oncor%20F2G%20Gap%20Analysis/F2G Project/Development/Integration/Document'
DEFINE DOC_MANAGMENT_ROOT_PATH = 'Oncor F2G Gap Analysis'

