
set echo on
set linesize 1000
set pagesize 300
set define off

whenever sqlerror exit -1
whenever oserror exit -1

spool c:\temp\PopulateStreetLightVoltageDropCommandSupportTables.log

--**************************************************************************************

--SCRIPT NAME: PopulateStreetLightVoltageDropCommandSupportTables.sql
--**************************************************************************************
-- AUTHOR		        : INGRNET\RPGABRYS
-- Date 	      	    : 
-- Jira NUMBER	  	    :
-- PRODUCT VERSION  	: 10.2.04
-- PRJ IDENTIFIER   	: G/TECHNOLOGY - ONCOR
-- PROGRAM DESC     	: Populate tables with test records to support the Street Light Voltage Drop custom command.
-- SOURCE DATABASE  	:
--**************************************************************************************
-- Script Body
--************************************************************************************** 

INSERT INTO TOOLS_SL_BALLAST (CU, DESCRIPTION, VOLTAGE, REGULATION, POWER_FACTOR, MAX_AMPS) VALUES ('', '175 W MV 120V', 120,0.05,0.5,5.8);
INSERT INTO TOOLS_SL_BALLAST (CU, DESCRIPTION, VOLTAGE, REGULATION, POWER_FACTOR, MAX_AMPS) VALUES ('', '175 W MV 240V', 240,0.05,0.5,3.2);
INSERT INTO TOOLS_SL_BALLAST (CU, DESCRIPTION, VOLTAGE, REGULATION, POWER_FACTOR, MAX_AMPS) VALUES ('', '400 W MV GL 120V', 120,0.05,0.5,7.6);
INSERT INTO TOOLS_SL_BALLAST (CU, DESCRIPTION, VOLTAGE, REGULATION, POWER_FACTOR, MAX_AMPS) VALUES ('', '400 W MV GL 240V', 240,0.05,0.5,7);
INSERT INTO TOOLS_SL_BALLAST (CU, DESCRIPTION, VOLTAGE, REGULATION, POWER_FACTOR, MAX_AMPS) VALUES ('', '400 W MV 120V', 120,0.1,0.9,4.3);
INSERT INTO TOOLS_SL_BALLAST (CU, DESCRIPTION, VOLTAGE, REGULATION, POWER_FACTOR, MAX_AMPS) VALUES ('', '400 W MV 240V', 240,0.1,0.9,2.1);
INSERT INTO TOOLS_SL_BALLAST (CU, DESCRIPTION, VOLTAGE, REGULATION, POWER_FACTOR, MAX_AMPS) VALUES ('', '400 W MV 480V', 480,0.1,0.9,1);
INSERT INTO TOOLS_SL_BALLAST (CU, DESCRIPTION, VOLTAGE, REGULATION, POWER_FACTOR, MAX_AMPS) VALUES ('', '1000 W MV 120V', 120,0.1,0.9,9.9);
INSERT INTO TOOLS_SL_BALLAST (CU, DESCRIPTION, VOLTAGE, REGULATION, POWER_FACTOR, MAX_AMPS) VALUES ('', '1000 W MV 240V', 240,0.1,0.9,4.9);
INSERT INTO TOOLS_SL_BALLAST (CU, DESCRIPTION, VOLTAGE, REGULATION, POWER_FACTOR, MAX_AMPS) VALUES ('', '1000 W MV 480V', 480,0.1,0.9,2.5);
INSERT INTO TOOLS_SL_BALLAST (CU, DESCRIPTION, VOLTAGE, REGULATION, POWER_FACTOR, MAX_AMPS) VALUES ('', '100 W HPS 120V', 120,0.05,0.5,3.2);
INSERT INTO TOOLS_SL_BALLAST (CU, DESCRIPTION, VOLTAGE, REGULATION, POWER_FACTOR, MAX_AMPS) VALUES ('', '100 W HPS 240V', 240,0.05,0.5,1.4);
INSERT INTO TOOLS_SL_BALLAST (CU, DESCRIPTION, VOLTAGE, REGULATION, POWER_FACTOR, MAX_AMPS) VALUES ('', '100 W HPS 480V', 480,0.1,0.9,0.2);
INSERT INTO TOOLS_SL_BALLAST (CU, DESCRIPTION, VOLTAGE, REGULATION, POWER_FACTOR, MAX_AMPS) VALUES ('', '150 W HPS 120V', 120,0.1,0.9,1.7);
INSERT INTO TOOLS_SL_BALLAST (CU, DESCRIPTION, VOLTAGE, REGULATION, POWER_FACTOR, MAX_AMPS) VALUES ('', '150 W HPS 240V', 240,0.1,0.9,0.9);
INSERT INTO TOOLS_SL_BALLAST (CU, DESCRIPTION, VOLTAGE, REGULATION, POWER_FACTOR, MAX_AMPS) VALUES ('', '150 W HPS 480V', 480,0.1,0.9,0.5);
INSERT INTO TOOLS_SL_BALLAST (CU, DESCRIPTION, VOLTAGE, REGULATION, POWER_FACTOR, MAX_AMPS) VALUES ('', '200 W HPS GL 120V', 120,0.05,0.5,6.5);
INSERT INTO TOOLS_SL_BALLAST (CU, DESCRIPTION, VOLTAGE, REGULATION, POWER_FACTOR, MAX_AMPS) VALUES ('', '200 W HPS GL 240V', 240,0.05,0.5,3.8);
INSERT INTO TOOLS_SL_BALLAST (CU, DESCRIPTION, VOLTAGE, REGULATION, POWER_FACTOR, MAX_AMPS) VALUES ('', '200 W HPS 120V', 120,0.1,0.9,2.4);
INSERT INTO TOOLS_SL_BALLAST (CU, DESCRIPTION, VOLTAGE, REGULATION, POWER_FACTOR, MAX_AMPS) VALUES ('', '200 W HPS 240V', 240,0.1,0.9,1.2);
INSERT INTO TOOLS_SL_BALLAST (CU, DESCRIPTION, VOLTAGE, REGULATION, POWER_FACTOR, MAX_AMPS) VALUES ('', '200 W HPS 480V', 480,0.1,0.9,0.6);
INSERT INTO TOOLS_SL_BALLAST (CU, DESCRIPTION, VOLTAGE, REGULATION, POWER_FACTOR, MAX_AMPS) VALUES ('', '250 W HPS 120V', 120,0.1,0.9,2.7);
INSERT INTO TOOLS_SL_BALLAST (CU, DESCRIPTION, VOLTAGE, REGULATION, POWER_FACTOR, MAX_AMPS) VALUES ('', '250 W HPS 240V', 240,0.1,0.9,1.4);
INSERT INTO TOOLS_SL_BALLAST (CU, DESCRIPTION, VOLTAGE, REGULATION, POWER_FACTOR, MAX_AMPS) VALUES ('', '250 W HPS 480V', 480,0.1,0.9,0.7);
INSERT INTO TOOLS_SL_BALLAST (CU, DESCRIPTION, VOLTAGE, REGULATION, POWER_FACTOR, MAX_AMPS) VALUES ('', '400 W HPS 120V', 120,0.1,0.9,4.4);
INSERT INTO TOOLS_SL_BALLAST (CU, DESCRIPTION, VOLTAGE, REGULATION, POWER_FACTOR, MAX_AMPS) VALUES ('', '400 W HPS 240V', 240,0.1,0.9,2.2);
INSERT INTO TOOLS_SL_BALLAST (CU, DESCRIPTION, VOLTAGE, REGULATION, POWER_FACTOR, MAX_AMPS) VALUES ('', '400 W HPS 480V', 480,0.1,0.9,1.1);
INSERT INTO TOOLS_SL_BALLAST (CU, DESCRIPTION, VOLTAGE, REGULATION, POWER_FACTOR, MAX_AMPS) VALUES ('', '1000 W HPS 120V', 120,0.1,0.9,9.9);
INSERT INTO TOOLS_SL_BALLAST (CU, DESCRIPTION, VOLTAGE, REGULATION, POWER_FACTOR, MAX_AMPS) VALUES ('', '1000 W HPS 240V', 240,0.1,0.9,4.9);
INSERT INTO TOOLS_SL_BALLAST (CU, DESCRIPTION, VOLTAGE, REGULATION, POWER_FACTOR, MAX_AMPS) VALUES ('', '1000 W HPS 480V', 480,0.1,0.9,2.5);
INSERT INTO TOOLS_SL_BALLAST (CU, DESCRIPTION, VOLTAGE, REGULATION, POWER_FACTOR, MAX_AMPS) VALUES ('', '150 W MHP 120V', 120,0.1,0.9,3.9);
INSERT INTO TOOLS_SL_BALLAST (CU, DESCRIPTION, VOLTAGE, REGULATION, POWER_FACTOR, MAX_AMPS) VALUES ('', '150 W MHP 240V', 240,0.1,0.9,1.9);
INSERT INTO TOOLS_SL_BALLAST (CU, DESCRIPTION, VOLTAGE, REGULATION, POWER_FACTOR, MAX_AMPS) VALUES ('', '150 W MHP 480V', 480,0.05,0.9,0.45);
INSERT INTO TOOLS_SL_BALLAST (CU, DESCRIPTION, VOLTAGE, REGULATION, POWER_FACTOR, MAX_AMPS) VALUES ('', '175 W MH 120V', 120,0.1,0.9,1.8);
INSERT INTO TOOLS_SL_BALLAST (CU, DESCRIPTION, VOLTAGE, REGULATION, POWER_FACTOR, MAX_AMPS) VALUES ('', '175 W MH 240V', 240,0.1,0.9,0.9);
INSERT INTO TOOLS_SL_BALLAST (CU, DESCRIPTION, VOLTAGE, REGULATION, POWER_FACTOR, MAX_AMPS) VALUES ('', '175 W MH 480V', 480,0.1,0.9,0.5);
INSERT INTO TOOLS_SL_BALLAST (CU, DESCRIPTION, VOLTAGE, REGULATION, POWER_FACTOR, MAX_AMPS) VALUES ('', '250 W MH 120V', 120,0.1,0.9,2.6);
INSERT INTO TOOLS_SL_BALLAST (CU, DESCRIPTION, VOLTAGE, REGULATION, POWER_FACTOR, MAX_AMPS) VALUES ('', '250 W MH 240V', 240,0.1,0.9,1.3);
INSERT INTO TOOLS_SL_BALLAST (CU, DESCRIPTION, VOLTAGE, REGULATION, POWER_FACTOR, MAX_AMPS) VALUES ('', '250 W MH 480V', 480,0.1,0.9,0.7);
INSERT INTO TOOLS_SL_BALLAST (CU, DESCRIPTION, VOLTAGE, REGULATION, POWER_FACTOR, MAX_AMPS) VALUES ('', '400 W MH 120V', 120,0.1,0.9,4.3);
INSERT INTO TOOLS_SL_BALLAST (CU, DESCRIPTION, VOLTAGE, REGULATION, POWER_FACTOR, MAX_AMPS) VALUES ('', '400 W MH 240V', 240,0.1,0.9,2.2);
INSERT INTO TOOLS_SL_BALLAST (CU, DESCRIPTION, VOLTAGE, REGULATION, POWER_FACTOR, MAX_AMPS) VALUES ('', '400 W MH 480V', 480,0.1,0.9,1.1);
INSERT INTO TOOLS_SL_BALLAST (CU, DESCRIPTION, VOLTAGE, REGULATION, POWER_FACTOR, MAX_AMPS) VALUES ('', '1000 W MH 120V', 120,0.1,0.9,10.4);
INSERT INTO TOOLS_SL_BALLAST (CU, DESCRIPTION, VOLTAGE, REGULATION, POWER_FACTOR, MAX_AMPS) VALUES ('', '1000 W MH 240V', 240,0.1,0.9,5.3);
INSERT INTO TOOLS_SL_BALLAST (CU, DESCRIPTION, VOLTAGE, REGULATION, POWER_FACTOR, MAX_AMPS) VALUES ('', '1000 W MH 480V', 480,0.1,0.9,2.6);

INSERT INTO TOOLS_SL_NOMINAL_VOLTAGE (VOLT_Q, DEFAULT_YN) VALUES ('120','Y');
INSERT INTO TOOLS_SL_NOMINAL_VOLTAGE (VOLT_Q, DEFAULT_YN) VALUES ('240','N');
INSERT INTO TOOLS_SL_NOMINAL_VOLTAGE (VOLT_Q, DEFAULT_YN) VALUES ('277','N');
INSERT INTO TOOLS_SL_NOMINAL_VOLTAGE (VOLT_Q, DEFAULT_YN) VALUES ('480','N');
--**************************************************************************************
-- End Script Body
--**************************************************************************************