CREATE TABLE GIS_STG.STG_TX811(
G3E_FID NUMBER(10,0), 
G3E_GEOMETRY SDO_GEOMETRY,
VERSION_TAG VARCHAR2(1 BYTE),
STATUS VARCHAR2(10 BYTE),
SVCCTR_C VARCHAR2(3 BYTE),
PROCESS_DATE TIMESTAMP(6),
AUD_CREATE_TS DATE,
AUD_CREATE_USR_ID VARCHAR2(10 BYTE),
AUD_MOD_TS DATE,
AUD_MOD_USR_ID VARCHAR2(10 BYTE))
;