CREATE OR REPLACE TRIGGER GIS_STG.BIU_STG_UTIL_THIRD_PARTY_TR
BEFORE UPDATE ON GIS_STG.STG_UTILITY_THIRD_PARTY

FOR EACH ROW 
BEGIN 
  IF UPDATING THEN
   
	SELECT SYSDATE INTO :NEW.AUD_MOD_DT FROM dual;
	SELECT USER INTO :NEW.AUD_MOD_USR_ID FROM dual;
  END IF;


END;
/