spool '&ENV_REFRESH_TARGET._ENVIRONMENT_DEPLOYMENT_VARIABLES_&SDATE..log'

SET TERMOUT OFF
SET VERIFY OFF

UNDEFINE DOC_MGMT_SP_URL
UNDEFINE EDF_HOST_NAME
UNDEFINE WMIS_WRTBCK_USER
UNDEFINE WMIS_WRTBCK_PASS
UNDEFINE WMIS_WRTBCK_SID
UNDEFINE GIS_PASS
UNDEFINE GIS_ONC_PASS
UNDEFINE GIS_STG_PASS
UNDEFINE GISAUTOMATOR_PASS
UNDEFINE EMAIL_FROM
UNDEFINE EMAIL_TO

--tst1
DEFINE GIS_PASS = 'gistst#12345'
DEFINE GIS_PASS

DEFINE GIS_ONC_PASS = 'gisonctst#12345'
DEFINE GIS_ONC_PASS

DEFINE GIS_STG_PASS = 'gisstgtst#12345'
DEFINE GIS_STG_PASS

DEFINE GISAUTOMATOR_PASS = 'GISAUTOMATOR#1'
DEFINE GISAUTOMATOR_PASS

DEFINE DOC_MGMT_SP_URL = 'http://bfxintranet.corp.oncor.com/sites/aegis'
DEFINE DOC_MGMT_SP_URL

DEFINE EDF_HOST_NAME = 'http://wv00490a.test.corp.oncor.com'
DEFINE EDF_HOST_NAME

DEFINE WMIS_WRTBCK_USER = 'GIS'
DEFINE WMIS_WRTBCK_USER

column myAliasWMISPASS NEW_VALUE WMIS_WRTBCK_PASS
select '&GIS_PASS' myAliasWMISPASS from dual; 
DEFINE WMIS_WRTBCK_PASS

column myAliasDBSID NEW_VALUE WMIS_WRTBCK_SID
select 'DGS&ENV_REFRESH_TARGET' myAliasDBSID from dual; 
DEFINE WMIS_WRTBCK_SID

DEFINE EMAIL_FROM = 'AEGISAutoBot@oncor.com'
DEFINE EMAIL_FROM

DEFINE EMAIL_TO = 'AEGISFixNDeploy@oncor.com'
DEFINE EMAIL_TO

SET TERMOUT ON
