DROP TABLE GIS_ONC.GIS_PURGE CASCADE CONSTRAINTS;
  CREATE TABLE GIS_ONC.GIS_PURGE
   (	"GIS_PURGE_ID" NUMBER GENERATED ALWAYS AS IDENTITY, 
	"SCHEMA_NM" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"TABLE_NM" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"PURGE_FREQUENCY" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"PURGE_RETENTION" NUMBER NOT NULL ENABLE, 
	"CALENDAR_TYPE_CD" VARCHAR2(1 BYTE) NOT NULL ENABLE, 
	"ACTIVE_FLAG" VARCHAR2(1 BYTE) DEFAULT 'Y' NOT NULL ENABLE, 
	"LAST_PURGED_DT" DATE, 
	"AUD_CREATE_USR_ID" VARCHAR2(30 BYTE), 
	"AUD_MOD_USR_ID" VARCHAR2(30 BYTE), 
	"AUD_CREATE_TS" TIMESTAMP (6), 
	"AUD_MOD_TS" TIMESTAMP (6)
   ) 
   ;
COMMIT;