spool STD_ENVIRONMENT_VARIABLES_&SDATE..log

SET TERMOUT OFF
SET VERIFY OFF

UNDEFINE ENVIRONMENT

UNDEFINE CBLE_TENS_FILENAME
UNDEFINE GUY_TEMPLATE_PATH
UNDEFINE ESI_ATTACHMENT_LOCN
UNDEFINE SAG_TEMPLATE_PATH
UNDEFINE SEC_CALC_REPORT_PATH
UNDEFINE STRTLGHT_MSLA_URL
UNDEFINE STRTLGHT_NO_MSLA_URL
UNDEFINE STRTLGHT_VOLT_DROP_REPORT_PATH

--tst1
column myAliasColumnName NEW_VALUE ENVIRONMENT
select 'ONCOR&ENV_REFRESH_TARGET' myAliasColumnName from dual; 
DEFINE ENVIRONMENT

column myAliasCBLE NEW_VALUE CBLE_TENS_FILENAME
select '\\enttstnas01\dis_ddcshare_dev\Mapfiles\&ENVIRONMENT\Support\Templates\DesignTools\DesignToolReports.xlsx' myAliasCBLE from dual; 
DEFINE CBLE_TENS_FILENAME

column myAliasGUY NEW_VALUE GUY_TEMPLATE_PATH
SELECT '\\ENTTSTNAS01\DIS_DDCSHARE_DEV\MAPFILES\&ENVIRONMENT\SUPPORT\TEMPLATES\DESIGNTOOLS\2010 GUYING PROGRAM 120110.XLS' myAliasGUY FROM DUAL; 
DEFINE GUY_TEMPLATE_PATH

column myAliasESI NEW_VALUE ESI_ATTACHMENT_LOCN
SELECT '\\ENTTSTNAS01\DIS_DDCSHARE_DEV\MAPFILES\&ENVIRONMENT\ESI' myAliasESI FROM DUAL; 
DEFINE ESI_ATTACHMENT_LOCN

column myAliasSAG NEW_VALUE SAG_TEMPLATE_PATH
SELECT '\\ENTTSTNAS01\DIS_DDCSHARE_DEV\MAPFILES\&ENVIRONMENT\SUPPORT\TEMPLATES\DESIGNTOOLS\SAGCLEARANCES2011 - NOT PROTECTED.XLSX' myAliasSAG FROM DUAL; 
DEFINE SAG_TEMPLATE_PATH

column myAliasSECCALC NEW_VALUE SEC_CALC_REPORT_PATH
SELECT '\\ENTTSTNAS01\DIS_DDCSHARE_DEV\MAPFILES\&ENVIRONMENT\SUPPORT\TEMPLATES\DESIGNTOOLS\DESIGNTOOLREPORTS.XLSX' myAliasSECCALC FROM DUAL; 
DEFINE SEC_CALC_REPORT_PATH

column myAliasSTRTMSLA NEW_VALUE STRTLGHT_MSLA_URL
SELECT '\\ENTTSTNAS01\DIS_DDCSHARE_DEV\MAPFILES\&ENVIRONMENT\SUPPORT\TEMPLATES\SUPPLEMENTALAGREEMENT\STREETLIGHTWITHMSLA.HTM' myAliasSTRTMSLA FROM DUAL; 
DEFINE STRTLGHT_MSLA_URL

column myAliasSTRTNO NEW_VALUE STRTLGHT_NO_MSLA_URL
SELECT '\\ENTTSTNAS01\DIS_DDCSHARE_DEV\MAPFILES\&ENVIRONMENT\SUPPORT\TEMPLATES\SUPPLEMENTALAGREEMENT\STREETLIGHTWITHWITHOUTMSLA.HTM' myAliasSTRTNO FROM DUAL; 
DEFINE STRTLGHT_NO_MSLA_URL

column myAliasSTRTVOLT NEW_VALUE STRTLGHT_VOLT_DROP_REPORT_PATH
SELECT '\\ENTTSTNAS01\DIS_DDCSHARE_DEV\MAPFILES\&ENVIRONMENT\SUPPORT\TEMPLATES\DESIGNTOOLS\DESIGNTOOLREPORTS.XLSX' myAliasSTRTVOLT FROM DUAL; 
DEFINE STRTLGHT_VOLT_DROP_REPORT_PATH

SET TERMOUT ON
