spool Update_G3E_DATACONNECTION_&SDATE..log

DECLARE
	PARAM_ENV_SOURCE VARCHAR2(20);
	PARAM_ENV_TARGET VARCHAR2(20);
    
BEGIN
    PARAM_ENV_SOURCE := 'ONCOR&ENV_REFRESH_SOURCE';
    PARAM_ENV_TARGET := 'ONCOR&ENV_REFRESH_TARGET';

    update GIS.g3e_dataconnection set
    g3e_username = PARAM_ENV_TARGET,
    g3e_location = PARAM_ENV_TARGET,
    G3E_SCHEMAOWNER = 'GIS'
    where g3e_location = PARAM_ENV_SOURCE;
    commit;

    --update GIS.G3E_DATACONNECTION set G3E_TYPE = 5 where G3E_USERNAME = PARAM_ENV_TARGET and G3E_LOCATION = PARAM_ENV_TARGET;
    --update GIS.G3E_DATACONNECTION set G3E_TYPE = 3 where  G3E_USERNAME = 'GIS' and G3E_LOCATION = 'GIS';
    --Commit;

    --update GIS.G3E_DATACONNECTION set G3E_TYPE = 1 where G3E_USERNAME = PARAM_ENV_TARGET and G3E_LOCATION = PARAM_ENV_TARGET;
    --commit;

	--COMMIT;
end;
/
