spool Update_G3E_CONFIGURATIONS_&SDATE..log

DECLARE

    PARAM_G3E_NEW_CONFIG VARCHAR2(10);
   	PARAM_G3E_OLD_CONFIG VARCHAR2(10);
    
BEGIN
    PARAM_G3E_NEW_CONFIG := 'ONCOR&ENV_REFRESH_TARGET';
    PARAM_G3E_OLD_CONFIG := 'ONCOR&ENV_REFRESH_SOURCE';

    update gis.g3e_configurations set G3E_CONFIGURATIONNAME = PARAM_G3E_NEW_CONFIG where G3E_CONFIGURATIONNAME = PARAM_G3E_OLD_CONFIG;

    commit;
end;
/
