/*-----------------------------------------------------------------------------
Create Table for CIS_CRIT_CUSTOMER to map CCB CIS_CUST_CD's to the GIS_CUST_TYPE
--This table is a static table to be manually loaded with pre-defined mappings
-----------------------------------------------------------------------------*/
DROP TABLE GIS_STG.CIS_CRIT_CUSTOMER;
CREATE TABLE GIS_STG.CIS_CRIT_CUSTOMER
  (
    CIS_CRIT_CUST_ID  NUMBER GENERATED ALWAYS AS IDENTITY,
    CIS_CUST_CD       VARCHAR2(16),
    CIS_CUST_DESC     VARCHAR2(255),
    GIS_CUST_TYPE     VARCHAR2(10),
    AUD_CREATE_USR_ID VARCHAR2(30)DEFAULT USER,
    AUD_MOD_USR_ID    VARCHAR2(30),
    AUD_CREATE_DT     TIMESTAMP(6) DEFAULT SYSDATE,
    AUD_MOD_DT        TIMESTAMP(6)
  ) ;
COMMIT;
GRANT SELECT, INSERT, UPDATE, DELETE ON GIS_STG.CIS_CRIT_CUSTOMER TO GIS_INFA;
CREATE OR REPLACE TRIGGER GIS_STG.BIU_CIS_CRIT_CUSTOMER_TR BEFORE
  UPDATE ON GIS_STG.CIS_CRIT_CUSTOMER FOR EACH ROW BEGIN IF UPDATING THEN
  SELECT SYSDATE INTO :NEW.AUD_CREATE_DT FROM dual;
  SELECT USER INTO :NEW.AUD_CREATE_USR_ID FROM dual;
END IF;
END;