DROP TABLE GIS_ONC.REFWMIS_VOUCHER_TYPE CASCADE CONSTRAINTS;
CREATE TABLE GIS_ONC.REFWMIS_VOUCHER_TYPE
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY, 
	"VOUCHER_TYPE_C" VARCHAR2(5 BYTE), 
	"VOUCHER_TYPE_DESC" VARCHAR2(30 BYTE), 
	"AUD_CREATE_USR_ID" VARCHAR2(30 BYTE), 
	"AUD_MOD_USR_ID" VARCHAR2(30 BYTE), 
	"AUD_CREATE_TS" TIMESTAMP (6), 
	"AUD_MOD_TS" TIMESTAMP (6)
  );
   
ALTER TABLE GIS_ONC.REFWMIS_VOUCHER_TYPE ADD CONSTRAINT REFWMIS_VOUCHER_TYPE_PK PRIMARY KEY (VOUCHER_TYPE_C);
COMMIT;