DROP TABLE GIS_ONC.REFWMIS_FERC_ACCOUNT CASCADE CONSTRAINTS;
CREATE TABLE GIS_ONC.REFWMIS_FERC_ACCOUNT
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY, 
	"PRIME_ACCT" NUMBER(3,0), 
	"SUB_ACCT" NUMBER(4,0), 
	"ACCT_DESC" VARCHAR2(30 BYTE), 
	"GRAPHIC_ACTIVITY_CODE" VARCHAR2(2 BYTE), 
	"AUD_CREATE_USR_ID" VARCHAR2(30 BYTE), 
	"AUD_MOD_USR_ID" VARCHAR2(30 BYTE), 
	"AUD_CREATE_TS" TIMESTAMP (6), 
	"AUD_MOD_TS" TIMESTAMP (6)
   );
   
ALTER TABLE GIS_ONC.REFWMIS_FERC_ACCOUNT ADD CONSTRAINT REFWMIS_FERC_ACCOUNT_PK PRIMARY KEY (PRIME_ACCT, SUB_ACCT, GRAPHIC_ACTIVITY_CODE);
COMMIT;