CREATE TABLE GISDEV.JU_CSVIMPORT_FORMAT
(
  CSV_COLUMN_NAME        VARCHAR2(50),
  COLUMN_ORDINAL         NUMBER(3),
  REQUIRED_CODE          VARCHAR2(1),
  GTECH_WIRELINE_FIELD   VARCHAR2(100),
  VALUE_LIST             VARCHAR2(100),
  GTECH_EQUIPMENT_FIELD  VARCHAR2(100),
  EQUIPMENT_VALUE_LIST   VARCHAR2(100)
)
RESULT_CACHE (MODE DEFAULT)
STORAGE    (
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
NOMONITORING;