DROP PACKAGE GET_ARB_NOTES_PKG;

CREATE OR REPLACE PACKAGE         "GET_ARB_NOTES_PKG" 
AS
   PROCEDURE CREATE_TEMP_TABLE;

   PROCEDURE DROP_TEMP_TABLE;

   PROCEDURE POP_ARB_NOTES_TEMP_TABLE (vJob_ID VARCHAR2, vPlan_Num VARCHAR2, bDetail Number);

END GET_ARB_NOTES_PKG;
 
 

/

CREATE OR REPLACE PUBLIC SYNONYM GET_ARB_NOTES_PKG FOR GET_ARB_NOTES_PKG;


GRANT EXECUTE ON GET_ARB_NOTES_PKG TO PUBLIC;

GRANT EXECUTE ON GET_ARB_NOTES_PKG TO SUPERVISOR2;
