set echo on
set linesize 1000
set pagesize 300
set trimspool on

spool c:\temp\CoreModel_Connectivity.log
--**************************************************************************************
-- SCRIPT NAME: CoreModel_Connectivity.sql
--**************************************************************************************
-- AUTHOR			    : INGRNET\RRADASE
-- DATE				    : 02-AUG-2018
-- PRJ IDENTIFIER	: G/TECHNOLOGY - ONCOR
-- PROGRAM DESC		: Connectivity metadata
--**************************************************************************************


--
-- NOTE: This script is arranged to behave as a master script, although it initially contains only relationships that have
--   changed over the course of system development.  Future changes to connectivity should be added to this script, and
--   ideally it should grow to include all connectivity relationships, eventually. (Rich Adase, 02-AUG-2018)
--


--
-- AUTOTRANSFORMER
--

  delete from G3E_NODEEDGECONN_ELEC where G3E_SOURCEFNO = 34;
  
  -- Bypass Point
  insert into G3E_NODEEDGECONN_ELEC (G3E_NECNO,G3E_SOURCEFNO,G3E_TRIGGERINGCNO,G3E_CONNECTINGFNO,G3E_CONNECTINGTRIGGERINGCNO,G3E_ENFORCEMENT,G3E_MAXOFFSET,G3E_OFFSETVALIDATIONPRIORITY,G3E_BREAKLINEAR,G3E_BREAKTOLERANCE,G3E_ALLOWINTERIORRELATION) 
    values (G3E_NODEEDGECONN_ELEC_SEQ.NEXTVAL,34,3403,40,78,1,-1,'P4',0,0.6,0);
  -- Elbow
  insert into G3E_NODEEDGECONN_ELEC (G3E_NECNO,G3E_SOURCEFNO,G3E_TRIGGERINGCNO,G3E_CONNECTINGFNO,G3E_CONNECTINGTRIGGERINGCNO,G3E_ENFORCEMENT,G3E_MAXOFFSET,G3E_OFFSETVALIDATIONPRIORITY,G3E_BREAKLINEAR,G3E_BREAKTOLERANCE,G3E_ALLOWINTERIORRELATION) 
    values (G3E_NODEEDGECONN_ELEC_SEQ.NEXTVAL,34,3403,41,78,1,-1,'P4',0,0.6,1);
  -- Isolation Point
  insert into G3E_NODEEDGECONN_ELEC (G3E_NECNO,G3E_SOURCEFNO,G3E_TRIGGERINGCNO,G3E_CONNECTINGFNO,G3E_CONNECTINGTRIGGERINGCNO,G3E_ENFORCEMENT,G3E_MAXOFFSET,G3E_OFFSETVALIDATIONPRIORITY,G3E_BREAKLINEAR,G3E_BREAKTOLERANCE,G3E_ALLOWINTERIORRELATION) 
    values (G3E_NODEEDGECONN_ELEC_SEQ.NEXTVAL,34,3403,6,78,1,-1,'P4',0,0.6,0);
  -- Phase Connector
  insert into G3E_NODEEDGECONN_ELEC (G3E_NECNO,G3E_SOURCEFNO,G3E_TRIGGERINGCNO,G3E_CONNECTINGFNO,G3E_CONNECTINGTRIGGERINGCNO,G3E_ENFORCEMENT,G3E_MAXOFFSET,G3E_OFFSETVALIDATIONPRIORITY,G3E_BREAKLINEAR,G3E_BREAKTOLERANCE,G3E_ALLOWINTERIORRELATION) 
    values (G3E_NODEEDGECONN_ELEC_SEQ.NEXTVAL,34,3403,42,78,1,-1,'P4',0,0.6,0);
  -- Primary Conductor - OH
  insert into G3E_NODEEDGECONN_ELEC (G3E_NECNO,G3E_SOURCEFNO,G3E_TRIGGERINGCNO,G3E_CONNECTINGFNO,G3E_CONNECTINGTRIGGERINGCNO,G3E_ENFORCEMENT,G3E_MAXOFFSET,G3E_OFFSETVALIDATIONPRIORITY,G3E_BREAKLINEAR,G3E_BREAKTOLERANCE,G3E_ALLOWINTERIORRELATION) 
    values (G3E_NODEEDGECONN_ELEC_SEQ.NEXTVAL,34,3403,8,803,1,-1,'P4',1,0.6,1);
  -- Primary Conductor - UG
  insert into G3E_NODEEDGECONN_ELEC (G3E_NECNO,G3E_SOURCEFNO,G3E_TRIGGERINGCNO,G3E_CONNECTINGFNO,G3E_CONNECTINGTRIGGERINGCNO,G3E_ENFORCEMENT,G3E_MAXOFFSET,G3E_OFFSETVALIDATIONPRIORITY,G3E_BREAKLINEAR,G3E_BREAKTOLERANCE,G3E_ALLOWINTERIORRELATION) 
    values (G3E_NODEEDGECONN_ELEC_SEQ.NEXTVAL,34,3403,9,903,1,-1,'P4',1,0.6,1);
  -- Primary Fuse - OH
  insert into G3E_NODEEDGECONN_ELEC (G3E_NECNO,G3E_SOURCEFNO,G3E_TRIGGERINGCNO,G3E_CONNECTINGFNO,G3E_CONNECTINGTRIGGERINGCNO,G3E_ENFORCEMENT,G3E_MAXOFFSET,G3E_OFFSETVALIDATIONPRIORITY,G3E_BREAKLINEAR,G3E_BREAKTOLERANCE,G3E_ALLOWINTERIORRELATION) 
    values (G3E_NODEEDGECONN_ELEC_SEQ.NEXTVAL,34,3403,11,1103,1,-1,'P4',0,0.6,0);
  -- Primary Fuse - UG
  insert into G3E_NODEEDGECONN_ELEC (G3E_NECNO,G3E_SOURCEFNO,G3E_TRIGGERINGCNO,G3E_CONNECTINGFNO,G3E_CONNECTINGTRIGGERINGCNO,G3E_ENFORCEMENT,G3E_MAXOFFSET,G3E_OFFSETVALIDATIONPRIORITY,G3E_BREAKLINEAR,G3E_BREAKTOLERANCE,G3E_ALLOWINTERIORRELATION)
    values (G3E_NODEEDGECONN_ELEC_SEQ.NEXTVAL,34,3403,38,1103,1,-1,'P4',0,0.6,0);
  -- Primary Switch - OH
  insert into G3E_NODEEDGECONN_ELEC (G3E_NECNO,G3E_SOURCEFNO,G3E_TRIGGERINGCNO,G3E_CONNECTINGFNO,G3E_CONNECTINGTRIGGERINGCNO,G3E_ENFORCEMENT,G3E_MAXOFFSET,G3E_OFFSETVALIDATIONPRIORITY,G3E_BREAKLINEAR,G3E_BREAKTOLERANCE,G3E_ALLOWINTERIORRELATION) 
    values (G3E_NODEEDGECONN_ELEC_SEQ.NEXTVAL,34,3403,13,1303,1,-1,'P4',0,0.6,0);

--
-- ELBOW
--

  delete from G3E_NODEEDGECONN_ELEC where G3E_SOURCEFNO = 41;


  -- Autotransformer
  insert into G3E_NODEEDGECONN_ELEC (G3E_NECNO,G3E_SOURCEFNO,G3E_TRIGGERINGCNO,G3E_CONNECTINGFNO,G3E_CONNECTINGTRIGGERINGCNO,G3E_ENFORCEMENT,G3E_MAXOFFSET,G3E_OFFSETVALIDATIONPRIORITY,G3E_BREAKLINEAR,G3E_BREAKTOLERANCE,G3E_ALLOWINTERIORRELATION) 
    values (G3E_NODEEDGECONN_ELEC_SEQ.NEXTVAL,41,78,34,3403,1,-1,'P4',0,0.6,0);
  -- Primary Enclosure
  insert into G3E_NODEEDGECONN_ELEC (G3E_NECNO,G3E_SOURCEFNO,G3E_TRIGGERINGCNO,G3E_CONNECTINGFNO,G3E_CONNECTINGTRIGGERINGCNO,G3E_ENFORCEMENT,G3E_MAXOFFSET,G3E_OFFSETVALIDATIONPRIORITY,G3E_BREAKLINEAR,G3E_BREAKTOLERANCE,G3E_ALLOWINTERIORRELATION) 
    values (G3E_NODEEDGECONN_ELEC_SEQ.NEXTVAL,41,78,5,502,1,-1,'P4',0,0.6,0);
  -- Primary Conductor - UG (geo)
  insert into G3E_NODEEDGECONN_ELEC (G3E_NECNO,G3E_SOURCEFNO,G3E_TRIGGERINGCNO,G3E_CONNECTINGFNO,G3E_CONNECTINGTRIGGERINGCNO,G3E_ENFORCEMENT,G3E_MAXOFFSET,G3E_OFFSETVALIDATIONPRIORITY,G3E_BREAKLINEAR,G3E_BREAKTOLERANCE,G3E_ALLOWINTERIORRELATION) 
    values (G3E_NODEEDGECONN_ELEC_SEQ.NEXTVAL,41,78,9,903,1,-1,'P4',0,0.6,1);
  -- Primary Conductor - UG (detail)
  insert into G3E_NODEEDGECONN_ELEC (G3E_NECNO,G3E_SOURCEFNO,G3E_TRIGGERINGCNO,G3E_CONNECTINGFNO,G3E_CONNECTINGTRIGGERINGCNO,G3E_ENFORCEMENT,G3E_MAXOFFSET,G3E_OFFSETVALIDATIONPRIORITY,G3E_BREAKLINEAR,G3E_BREAKTOLERANCE,G3E_ALLOWINTERIORRELATION) 
    values (G3E_NODEEDGECONN_ELEC_SEQ.NEXTVAL,41,79,9,909,1,-1,'P4',0,0.6,1);
  -- Transformer - UG (geo)
  insert into G3E_NODEEDGECONN_ELEC (G3E_NECNO,G3E_SOURCEFNO,G3E_TRIGGERINGCNO,G3E_CONNECTINGFNO,G3E_CONNECTINGTRIGGERINGCNO,G3E_ENFORCEMENT,G3E_MAXOFFSET,G3E_OFFSETVALIDATIONPRIORITY,G3E_BREAKLINEAR,G3E_BREAKTOLERANCE,G3E_ALLOWINTERIORRELATION) 
    values (G3E_NODEEDGECONN_ELEC_SEQ.NEXTVAL,41,78,60,6003,1,-1,'P4',0,0.6,0);
  -- Transformer - UG (detail)
  insert into G3E_NODEEDGECONN_ELEC (G3E_NECNO,G3E_SOURCEFNO,G3E_TRIGGERINGCNO,G3E_CONNECTINGFNO,G3E_CONNECTINGTRIGGERINGCNO,G3E_ENFORCEMENT,G3E_MAXOFFSET,G3E_OFFSETVALIDATIONPRIORITY,G3E_BREAKLINEAR,G3E_BREAKTOLERANCE,G3E_ALLOWINTERIORRELATION) 
    values (G3E_NODEEDGECONN_ELEC_SEQ.NEXTVAL,41,79,60,6005,1,-1,'P4',0,0.6,0);


spool off;
