DROP TABLE GIS_STG.STG_CULIB_MULTIPLE_CATEGORY CASCADE CONSTRAINTS;

CREATE TABLE GIS_STG.STG_CULIB_MULTIPLE_CATEGORY 
   (STG_CULIB_MC_TBL_ID NUMBER GENERATED ALWAYS AS IDENTITY, 
	PROCESS_DT DATE, 
	PROCESS_RUN_ID NUMBER, 
	CU_ID NVARCHAR2(15), 
	CU_CATEGORY_CODE NVARCHAR2(15), 
	AUD_CREATE_USR_ID NVARCHAR2(30), 
	AUD_MOD_USR_ID NVARCHAR2(30), 
	AUD_CREATE_DT TIMESTAMP (6), 
	AUD_MOD_DT TIMESTAMP (6));

GRANT INSERT, UPDATE, DELETE, SELECT ON GIS_STG.STG_CULIB_MULTIPLE_CATEGORY TO GIS_INFA;