DROP TABLE GIS_STG.STG_CULIB_CATEGORY CASCADE CONSTRAINTS;
  CREATE TABLE GIS_STG.STG_CULIB_CATEGORY 
   (
  STG_CULIB_CATEGORY_ID NUMBER GENERATED ALWAYS AS IDENTITY, 
	PROCESS_DT DATE, 
	PROCESS_RUN_ID NUMBER, 
	CU_CATEGORY_CODE VARCHAR2(15 BYTE), 
	CODE_DESC VARCHAR2(50 BYTE), 
	INCLUDE_ON_DESIGN_ORDER_YN VARCHAR2(1 BYTE), 
	INCLUDE_ON_CONSTR_ORDER_YN VARCHAR2(1 BYTE), 
	OK_TO_DELETE_YN VARCHAR2(1 BYTE), 
	INSULATING_VOLT_REQD_YN VARCHAR2(1 BYTE), 
	INSULATING_VOLT_EXCEED_OPER_YN VARCHAR2(1 BYTE), 
	USE_CODE VARCHAR2(1 BYTE), 
	TYPE_CODE VARCHAR2(1 BYTE), 
	INCLUDE_IN_PERSONALCU_YN VARCHAR2(1 BYTE), 
	AUD_CREATE_USR_ID VARCHAR2(30 BYTE) DEFAULT USER, 
	AUD_MOD_USR_ID VARCHAR2(30 BYTE), 
	AUD_CREATE_DT TIMESTAMP (6) DEFAULT SYSDATE, 
	AUD_MOD_DT TIMESTAMP (6)
   );
  COMMIT;