DROP TABLE GIS_STG.STG_CULIB_UNIT_ATTRIBUTE CASCADE CONSTRAINTS;
  CREATE TABLE GIS_STG.STG_CULIB_UNIT_ATTRIBUTE 
   (	STG_CULIB_UNIT_ATTR_TBL_ID NUMBER GENERATED ALWAYS AS IDENTITY, 
	PROCESS_DT DATE, 
	PROCESS_RUN_ID NUMBER, 
	CU_CATEGORY_CODE VARCHAR2(15 BYTE), 
	CU_ID VARCHAR2(15 BYTE), 
	CU_ATTRIBUTE_CODE VARCHAR2(20 BYTE), 
	CU_VALID_ATTR_ID NUMBER(10,0), 
	CU_VALID_VAL VARCHAR2(250 BYTE), 
	AUD_CREATE_USR_ID VARCHAR2(30 BYTE) DEFAULT USER, 
	AUD_MOD_USR_ID VARCHAR2(30 BYTE), 
	AUD_CREATE_DT TIMESTAMP (6) DEFAULT SYSDATE, 
	AUD_MOD_DT TIMESTAMP (6)
   );
COMMIT;   