 CREATE OR REPLACE FORCE EDITIONABLE VIEW "GIS_ONC"."OPERBNDY_FEEDER_VW" ("G3E_FID", "FEEDER_1_ID", "FEEDER_NBR", "SSTA_C", "G3E_GEOMETRY") AS 
  SELECT
    CN.G3E_FID,
    CN.FEEDER_1_ID,
    CN.FEEDER_NBR,
    CN.SSTA_C,
    OH.G3E_GEOMETRY
FROM GIS.CONNECTIVITY_N CN
INNER JOIN GIS.PRI_COND_OH_L OH
ON CN.G3E_FID = OH.G3E_FID
INNER JOIN GIS.COMMON_N COM
ON CN.G3E_FID = COM.G3E_FID
LEFT JOIN GIS_ONC.OPERBNDY_COND_STRC_VW CON
ON COM.OWNER1_ID = CON.G3E_FID
UNION ALL
SELECT
    CN.G3E_FID,
    CN.FEEDER_1_ID,
    CN.FEEDER_NBR,
    CN.SSTA_C,
    UG.G3E_GEOMETRY
FROM GIS.CONNECTIVITY_N CN
INNER JOIN GIS.PRI_COND_UG_L UG
ON CN.G3E_FID = UG.G3E_FID
INNER JOIN GIS.COMMON_N COM
ON CN.G3E_FID = COM.G3E_FID
INNER JOIN GIS_ONC.OPERBNDY_COND_STRC_VW CON
ON COM.OWNER1_ID = CON.G3E_FID;