CREATE OR REPLACE VIEW "GIS_ONC"."OPERBNDY_SVCCTR_VW" AS
SELECT 
  OB.OPERBNDY_ID,
  OA.G3E_GEOMETRY
FROM GIS.OPERBNDY_N OB
INNER JOIN GIS.OPERBNDY_AR OA
ON OB.G3E_FID = OA.G3E_FID
WHERE OB.OPERBNDY_TYPE = 'SVCCTR'
;