CREATE TABLE GIS_STG.STG_NJUNS_CODE_CNTY
  (
    STG_NJUNS_CODE_CNTY_ID NUMBER GENERATED ALWAYS AS IDENTITY,
    NJUNS_MEMBER           VARCHAR2(100),
    NJUNS_CODE             VARCHAR2(20),
    NJUNS_CODE_GUID        VARCHAR2(100),
    NJUNS_DESCRIPTION      VARCHAR2(100),
    NJUNS_STATE            VARCHAR2(20),
    NJUNS_COUNTY           VARCHAR2(50),
    INSERT_DT              DATE,
    PROCESS_FLAG           VARCHAR2(2),
    AUD_CREATE_USR_ID      VARCHAR2(30) DEFAULT USER,
    AUD_MOD_USR_ID         VARCHAR2(30),
    AUD_CREATE_DT          TIMESTAMP DEFAULT SYSDATE,
    AUD_MOD_DT             TIMESTAMP
  );
GRANT SELECT, INSERT, UPDATE, DELETE ON GIS_STG.STG_NJUNS_CODE_CNTY TO GIS_INFA;
