//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 
namespace CustomWriteBackLibrary {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.oncor.com/DIS")]
    [System.Xml.Serialization.XmlRootAttribute("RequestHeader", Namespace="http://www.oncor.com/DIS", IsNullable=false)]
    public partial class RequestHeaderType {
        
        private string sourceSystemField;
        
        private string transactionIdField;
        
        private string transactionTypeField;
        
        private string requestorField;
        
        private System.DateTime timestampField;
        
        private bool timestampFieldSpecified;
        
        /// <remarks/>
        public string SourceSystem {
            get {
                return this.sourceSystemField;
            }
            set {
                this.sourceSystemField = value;
            }
        }
        
        /// <remarks/>
        public string TransactionId {
            get {
                return this.transactionIdField;
            }
            set {
                this.transactionIdField = value;
            }
        }
        
        /// <remarks/>
        public string TransactionType {
            get {
                return this.transactionTypeField;
            }
            set {
                this.transactionTypeField = value;
            }
        }
        
        /// <remarks/>
        public string Requestor {
            get {
                return this.requestorField;
            }
            set {
                this.requestorField = value;
            }
        }
        /// <remarks/>
        public System.DateTime Timestamp {
            get {
                return this.timestampField;
            }
            set {
                this.timestampField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TimestampSpecified {
            get {
                return this.timestampFieldSpecified;
            }
            set {
                this.timestampFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.oncor.com/DIS")]
    [System.Xml.Serialization.XmlRootAttribute("ResultStatus", Namespace="http://www.oncor.com/DIS", IsNullable=false)]
    public partial class ResponseType {
        
        private string statusField;
        
        private string resultCodeField;
        
        private string[] errorMsgField;
        
        private System.DateTime timestampField;
        
        private bool timestampFieldSpecified;
        
        /// <remarks/>
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string ResultCode {
            get {
                return this.resultCodeField;
            }
            set {
                this.resultCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ErrorMsg")]
        public string[] ErrorMsg {
            get {
                return this.errorMsgField;
            }
            set {
                this.errorMsgField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Timestamp {
            get {
                return this.timestampField;
            }
            set {
                this.timestampField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TimestampSpecified {
            get {
                return this.timestampFieldSpecified;
            }
            set {
                this.timestampFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.oncor.com/DIS_WorkRequestService")]
    [System.Xml.Serialization.XmlRootAttribute("disWorkRequest", Namespace="http://www.oncor.com/DIS_WorkRequestService", IsNullable=false)]
    public partial class disWorkRequestType {
        
        private disWorkRequestRequestType disWorkRequestRequestField;
        
        private disWorkRequestResponseType disWorkRequestResponseField;
        
        /// <remarks/>
        public disWorkRequestRequestType disWorkRequestRequest {
            get {
                return this.disWorkRequestRequestField;
            }
            set {
                this.disWorkRequestRequestField = value;
            }
        }
        
        /// <remarks/>
        public disWorkRequestResponseType disWorkRequestResponse {
            get {
                return this.disWorkRequestResponseField;
            }
            set {
                this.disWorkRequestResponseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.oncor.com/DIS_WorkRequestService")]
    [System.Xml.Serialization.XmlRootAttribute("disWorkRequestRequest", Namespace="http://www.oncor.com/DIS_WorkRequestService", IsNullable=false)]
    public partial class disWorkRequestRequestType {
        
        private RequestHeaderType requestHeaderField;
        
        private WorkRequestType workRequestField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.oncor.com/DIS")]
        public RequestHeaderType RequestHeader {
            get {
                return this.requestHeaderField;
            }
            set {
                this.requestHeaderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.oncor.com/Work_Request")]
        public WorkRequestType WorkRequest {
            get {
                return this.workRequestField;
            }
            set {
                this.workRequestField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.oncor.com/Work_Request")]
    [System.Xml.Serialization.XmlRootAttribute("WorkRequest", Namespace="http://www.oncor.com/Work_Request", IsNullable=false)]
    public partial class WorkRequestType {
        
        private string wRNumberField;
        
        private string wRStatusField;
        
        private decimal percentDesignCompleteField;
        
        private bool percentDesignCompleteFieldSpecified;
        
        private decimal percentConstructionCompleteField;
        
        private bool percentConstructionCompleteFieldSpecified;
        
        private string crewHQField;
        
        private string mgmtActivityCodeField;
        
        private string wRTypeField;
        
        private System.DateTime constReadyDateField;
        
        private bool constReadyDateFieldSpecified;
        
        private System.DateTime custRequiredDateField;
        
        private bool custRequiredDateFieldSpecified;
        
        private string wRNameField;
        
        private string wRScopeField;
        
        private string houseNumberField;
        
        private string houseNumberFractField;
        
        private string leadingDirField;
        
        private string streetNameField;
        
        private string streetTypeField;
        
        private string trailingDirField;
        
        private string townField;
        
        private string countyField;
        
        private string designerAssignmentField;
        
        private string dualCertField;
        
        private string dualCertPwrCo1Field;
        
        private string dualCertPwrCo2Field;
        
        private decimal assocCostField;
        
        private bool assocCostFieldSpecified;
        
        private string electricInServiceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string WRNumber {
            get {
                return this.wRNumberField;
            }
            set {
                this.wRNumberField = value;
            }
        }
        
        /// <remarks/>
        public string WRStatus {
            get {
                return this.wRStatusField;
            }
            set {
                this.wRStatusField = value;
            }
        }
        
        /// <remarks/>
        public decimal PercentDesignComplete {
            get {
                return this.percentDesignCompleteField;
            }
            set {
                this.percentDesignCompleteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PercentDesignCompleteSpecified {
            get {
                return this.percentDesignCompleteFieldSpecified;
            }
            set {
                this.percentDesignCompleteFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal PercentConstructionComplete {
            get {
                return this.percentConstructionCompleteField;
            }
            set {
                this.percentConstructionCompleteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PercentConstructionCompleteSpecified {
            get {
                return this.percentConstructionCompleteFieldSpecified;
            }
            set {
                this.percentConstructionCompleteFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string CrewHQ {
            get {
                return this.crewHQField;
            }
            set {
                this.crewHQField = value;
            }
        }
        
        /// <remarks/>
        public string MgmtActivityCode {
            get {
                return this.mgmtActivityCodeField;
            }
            set {
                this.mgmtActivityCodeField = value;
            }
        }
        
        /// <remarks/>
        public string WRType {
            get {
                return this.wRTypeField;
            }
            set {
                this.wRTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime ConstReadyDate {
            get {
                return this.constReadyDateField;
            }
            set {
                this.constReadyDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ConstReadyDateSpecified {
            get {
                return this.constReadyDateFieldSpecified;
            }
            set {
                this.constReadyDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime CustRequiredDate {
            get {
                return this.custRequiredDateField;
            }
            set {
                this.custRequiredDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CustRequiredDateSpecified {
            get {
                return this.custRequiredDateFieldSpecified;
            }
            set {
                this.custRequiredDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string WRName {
            get {
                return this.wRNameField;
            }
            set {
                this.wRNameField = value;
            }
        }
        
        /// <remarks/>
        public string WRScope {
            get {
                return this.wRScopeField;
            }
            set {
                this.wRScopeField = value;
            }
        }
        
        /// <remarks/>
        public string HouseNumber {
            get {
                return this.houseNumberField;
            }
            set {
                this.houseNumberField = value;
            }
        }
        
        /// <remarks/>
        public string HouseNumberFract {
            get {
                return this.houseNumberFractField;
            }
            set {
                this.houseNumberFractField = value;
            }
        }
        
        /// <remarks/>
        public string LeadingDir {
            get {
                return this.leadingDirField;
            }
            set {
                this.leadingDirField = value;
            }
        }
        
        /// <remarks/>
        public string StreetName {
            get {
                return this.streetNameField;
            }
            set {
                this.streetNameField = value;
            }
        }
        
        /// <remarks/>
        public string StreetType {
            get {
                return this.streetTypeField;
            }
            set {
                this.streetTypeField = value;
            }
        }
        
        /// <remarks/>
        public string TrailingDir {
            get {
                return this.trailingDirField;
            }
            set {
                this.trailingDirField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string Town {
            get {
                return this.townField;
            }
            set {
                this.townField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string County {
            get {
                return this.countyField;
            }
            set {
                this.countyField = value;
            }
        }
        
        /// <remarks/>
        public string DesignerAssignment {
            get {
                return this.designerAssignmentField;
            }
            set {
                this.designerAssignmentField = value;
            }
        }
        
        /// <remarks/>
        public string DualCert {
            get {
                return this.dualCertField;
            }
            set {
                this.dualCertField = value;
            }
        }
        
        /// <remarks/>
        public string DualCertPwrCo1 {
            get {
                return this.dualCertPwrCo1Field;
            }
            set {
                this.dualCertPwrCo1Field = value;
            }
        }
        
        /// <remarks/>
        public string DualCertPwrCo2 {
            get {
                return this.dualCertPwrCo2Field;
            }
            set {
                this.dualCertPwrCo2Field = value;
            }
        }
        
        /// <remarks/>
        public decimal AssocCost {
            get {
                return this.assocCostField;
            }
            set {
                this.assocCostField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AssocCostSpecified {
            get {
                return this.assocCostFieldSpecified;
            }
            set {
                this.assocCostFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string ElectricInService {
            get {
                return this.electricInServiceField;
            }
            set {
                this.electricInServiceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.oncor.com/DIS_WorkRequestService")]
    [System.Xml.Serialization.XmlRootAttribute("disWorkRequestResponse", Namespace="http://www.oncor.com/DIS_WorkRequestService", IsNullable=false)]
    public partial class disWorkRequestResponseType {
        
        private ResponseType resultStatusField;
        
        private WorkRequestType workRequestField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.oncor.com/DIS")]
        public ResponseType ResultStatus {
            get {
                return this.resultStatusField;
            }
            set {
                this.resultStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.oncor.com/Work_Request")]
        public WorkRequestType WorkRequest {
            get {
                return this.workRequestField;
            }
            set {
                this.workRequestField = value;
            }
        }
    }
}
