DROP TABLE GIS_STG.STG_VINTAGE_YEAR CASCADE CONSTRAINTS;
CREATE TABLE GIS_STG.STG_VINTAGE_YEAR 
   (	STG_VINTAGE_YEAR_ID NUMBER GENERATED ALWAYS AS IDENTITY, 
	PROCESS_DT DATE, 
	PROCESS_RUN_ID NUMBER(15,0), 
	GIS_PROCESS_FLAG VARCHAR2(1 BYTE), 
	WR_NO NUMBER(8,0), 
	VINTAGE_YEAR NUMBER(4,0), 
	STATUS VARCHAR2(8 BYTE), 
	CAPARS_DT DATE, 
	DIS_DT DATE, 
	AUD_CREATE_USR_ID VARCHAR2(30 BYTE) DEFAULT USER, 
	AUD_MOD_USR_ID VARCHAR2(30 BYTE), 
	AUD_CREATE_DT TIMESTAMP (6) DEFAULT SYSDATE, 
	AUD_MOD_DT TIMESTAMP (6)
   )
   ;