//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 
namespace OncorTicketStatus {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.oncor.com/DIS")]
    [System.Xml.Serialization.XmlRootAttribute("RequestHeader", Namespace="http://www.oncor.com/DIS", IsNullable=false)]
    public partial class RequestHeaderType {
        
        private string sourceSystemField;
        
        private string transactionIdField;
        
        private string transactionTypeField;
        
        private string requestorField;
        
        private System.DateTime timestampField;
        
        private bool timestampFieldSpecified;
        
        /// <remarks/>
        public string SourceSystem {
            get {
                return this.sourceSystemField;
            }
            set {
                this.sourceSystemField = value;
            }
        }
        
        /// <remarks/>
        public string TransactionId {
            get {
                return this.transactionIdField;
            }
            set {
                this.transactionIdField = value;
            }
        }
        
        /// <remarks/>
        public string TransactionType {
            get {
                return this.transactionTypeField;
            }
            set {
                this.transactionTypeField = value;
            }
        }
        
        /// <remarks/>
        public string Requestor {
            get {
                return this.requestorField;
            }
            set {
                this.requestorField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Timestamp {
            get {
                return this.timestampField;
            }
            set {
                this.timestampField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TimestampSpecified {
            get {
                return this.timestampFieldSpecified;
            }
            set {
                this.timestampFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.oncor.com/DIS")]
    [System.Xml.Serialization.XmlRootAttribute("ResultStatus", Namespace="http://www.oncor.com/DIS", IsNullable=false)]
    public partial class ResponseType {
        
        private string statusField;
        
        private string resultCodeField;
        
        private string[] errorMsgField;
        
        private System.DateTime timestampField;
        
        private bool timestampFieldSpecified;
        
        /// <remarks/>
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string ResultCode {
            get {
                return this.resultCodeField;
            }
            set {
                this.resultCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ErrorMsg")]
        public string[] ErrorMsg {
            get {
                return this.errorMsgField;
            }
            set {
                this.errorMsgField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Timestamp {
            get {
                return this.timestampField;
            }
            set {
                this.timestampField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TimestampSpecified {
            get {
                return this.timestampFieldSpecified;
            }
            set {
                this.timestampFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.oncor.com/Ticket_Status")]
    [System.Xml.Serialization.XmlRootAttribute("TicketStatus", Namespace = "http://www.oncor.com/Ticket_Status", IsNullable = false)]
    public partial class TicketStatusType {
        
        private string njunsTicketIdField;
        
      //  private string ticketNumberField;
        
      //  private string ticketStatusField;
        
        /// <remarks/>
        public string NjunsTicketId {
            get {
                return this.njunsTicketIdField;
            }
            set {
                this.njunsTicketIdField = value;
            }
        }
        
        ///// <remarks/>
        //[System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        //public string TicketNumber {
        //    get {
        //        return this.ticketNumberField;
        //    }
        //    set {
        //        this.ticketNumberField = value;
        //    }
        //}
        
        /// <remarks/>
        //public string TicketStatus {
        //    get {
        //        return this.ticketStatusField;
        //    }
        //    set {
        //        this.ticketStatusField = value;
        //    }
        //}
    }
}
