  CREATE OR REPLACE FORCE EDITIONABLE VIEW "GIS_ONC"."ATTACH_WIRELINE_VW" ("STRUCTURE_ID", "OGGX_H", "OGGY_H", "G3E_FID", "G3E_CNO", "W_ABANDON_D", "W_ATTACHED_D", "W_ATTACHMENT_STATUS", "W_ATTACH_COMPANY", "W_ATTACH_HEIGHT_FT", "W_ATTACH_POSITION", "W_ATTACH_SOURCE_C", "W_ATTACH_TYPE", "W_AUDIT_D", "W_INIT_STR_TENSION", "W_MAINTAINER_1", "W_MAINTAINER_2", "W_MESSENGER_C", "W_OUTSIDE_DIAM", "W_PERMIT_NUMBER", "W_REMOVED_D", "G3E_GEOMETRY") AS 
  SELECT
CN.STRUCTURE_ID,
CN.OGGX_H,
CN.OGGY_H,
AEN.G3E_FID,
AEN.G3E_CNO,
AEN.W_ABANDON_D,
AEN.W_ATTACHED_D,
AEN.W_ATTACHMENT_STATUS,
AEN.W_ATTACH_COMPANY,
AEN.W_ATTACH_HEIGHT_FT,
AEN.W_ATTACH_POSITION,
AEN.W_ATTACH_SOURCE_C,
AEN.W_ATTACH_TYPE,
AEN.W_AUDIT_D,
AEN.W_INIT_STR_TENSION,
AEN.W_MAINTAINER_1,
AEN.W_MAINTAINER_2,
AEN.W_MESSENGER_C,
AEN.W_OUTSIDE_DIAM,
AEN.W_PERMIT_NUMBER,
AEN.W_REMOVED_D,
PL.G3E_GEOMETRY
FROM GIS.ATTACH_WIRELINE_N AEN
INNER JOIN GIS.COMMON_N CN
ON AEN.G3E_FID = CN.G3E_FID
INNER JOIN POLE_S PL
on AEN.G3E_FID = PL.G3E_FID and AEN.G3E_FNO = PL.G3E_FNO;