  CREATE OR REPLACE FORCE EDITIONABLE VIEW "GIS_ONC"."AUTO_XFMR_UNIT_VW" ("G3E_GEOMETRY", "OGGY_H", "OGGX_H", "OWNER1_ID", "G3E_FNO","FEATURE_STATE_C", "G3E_FID", "LOCATION", "STRUCTURE_ID", "FEEDER_1_ID", "SSTA_C", "PROTECTIVE_DEVICE_FID", "STATUS_OPERATED_C", "G3E_CNO", "PHASE_Q", "KVA_Q", "SEC_VOLTAGE_C", "PRI_VOLTAGE_C", "VOLT_1_Q", "COMPANY_ID", "PHASE_C") AS 
  SELECT 
  AXS.G3E_GEOMETRY,
  CN.OGGY_H,
  CN.OGGX_H,
  CN.OWNER1_ID,
  CN.G3E_FNO,
  CN.FEATURE_STATE_C,
  CN.G3E_FID,
  CN.LOCATION,
  CN.STRUCTURE_ID,
  CTN.FEEDER_1_ID,
  CTN.SSTA_C,
  CTN.PROTECTIVE_DEVICE_FID,
  CTN.STATUS_OPERATED_C,
  XUN.G3E_CNO,
  XUN.PHASE_Q,
  XUN.KVA_Q,
  XUN.SEC_VOLTAGE_C,
  XUN.PRI_VOLTAGE_C,
  CTN.VOLT_1_Q,
  XUN.COMPANY_ID,
  XUN.PHASE_C
FROM GIS.COMMON_N CN
INNER JOIN GIS.CONNECTIVITY_N CTN
ON CN.G3E_FID = CTN.G3E_FID
INNER JOIN GIS.AUTO_XFMR_UNIT_N XUN
ON CN.G3E_FID = XUN.G3E_FID
INNER JOIN GIS.AUTO_XFMR_S AXS
ON CN.G3E_FID = AXS.G3E_FID;