  CREATE OR REPLACE FORCE EDITIONABLE VIEW "GIS_ONC"."AUTO_XFMR_BANK_VW" ("BANK_CONFIG_C", "BANK_KVA_RATING_Q", "G3E_GEOMETRY","G3E_CNO", "OGGY_H", "OGGX_H", "OWNER1_ID", "G3E_FNO", "FEATURE_STATE_C", "G3E_FID", "LOCATION", "STRUCTURE_ID", "FEEDER_1_ID", "SSTA_C", "PROTECTIVE_DEVICE_FID", "STATUS_OPERATED_C", "VOLT_1_Q") AS 
  SELECT AXBN.BANK_CONFIG_C,
  AXBN.BANK_KVA_RATING_Q,
  AXS.G3E_GEOMETRY,
  AXBN.G3E_CNO,
  CN.OGGY_H,
  CN.OGGX_H,
  CN.OWNER1_ID,
  CN.G3E_FNO,
  CN.FEATURE_STATE_C,
  CN.G3E_FID,
  CN.LOCATION,
  CN.STRUCTURE_ID,
  CTN.FEEDER_1_ID,
  CTN.SSTA_C,
  CTN.PROTECTIVE_DEVICE_FID,
  CTN.STATUS_OPERATED_C,
  CTN.VOLT_1_Q
FROM GIS.COMMON_N CN
INNER JOIN GIS.CONNECTIVITY_N CTN
ON CN.G3E_FID = CTN.G3E_FID
INNER JOIN GIS.AUTO_XFMR_BANK_N AXBN
ON CN.G3E_FID = AXBN.G3E_FID
INNER JOIN GIS.AUTO_XFMR_S AXS
ON CN.G3E_FID = AXS.G3E_FID;