
  CREATE OR REPLACE FORCE EDITIONABLE VIEW "GIS_ONC"."BREAKER_VW" ("G3E_FID", "G3E_FNO", "STRUCTURE_ID", "STATUS_NORMAL_C", "SSTA_C", "VOLT_1_Q", "FEEDER_1_ID", "FEEDER_NBR", "SERVICE_CENTER_C", "G3E_GEOMETRY") AS 
  SELECT CN.G3E_FID,
  CN.G3E_FNO,
  CN.STRUCTURE_ID,
  CTN.STATUS_NORMAL_C,
  CTN.SSTA_C,
  CTN.VOLT_1_Q,
  CTN.FEEDER_1_ID,
  SBN.FEEDER_NBR,
  SBN.SERVICE_CENTER_C,
  SBS.G3E_GEOMETRY  
FROM GIS.COMMON_N CN
INNER JOIN GIS.CONNECTIVITY_N CTN
ON CN.G3E_FID = CTN.G3E_FID
INNER JOIN GIS.SUB_BREAKER_N SBN
ON CN.G3E_FID = SBN.G3E_FID
INNER JOIN GIS.SUB_BREAKER_S SBS
ON CN.G3E_FID = SBS.G3E_FID
;
