
  CREATE OR REPLACE FORCE EDITIONABLE VIEW "GIS_ONC"."CAPACITOR_VW" ("BANK_SIZE_Q", "G3E_GEOMETRY", "OGGY_H", "OGGX_H", "G3E_FNO", "FEATURE_STATE_C", "LONGITUDE", "OWNER1_ID", "G3E_FID", "LOCATION", "LATITUDE", "STRUCTURE_ID", "STATUS_NORMAL_C", "SSTA_C", "VOLT_1_Q", "PROTECTIVE_DEVICE_FID", "STATUS_OPERATED_C", "FEEDER_1_ID", "DEVICE_ID", "VINTAGE_YR") AS 
  SELECT CBN.BANK_SIZE_Q,
  CS.G3E_GEOMETRY,
  CN.OGGY_H,
  CN.OGGX_H,
  CN.G3E_FNO,
  CN.FEATURE_STATE_C,
  CN.LONGITUDE,
  CN.OWNER1_ID,
  CN.G3E_FID,
  CN.LOCATION,
  CN.LATITUDE,
  CN.STRUCTURE_ID,
  CTN.STATUS_NORMAL_C,
  CTN.SSTA_C,
  CTN.VOLT_1_Q,
  CTN.PROTECTIVE_DEVICE_FID,
  CTN.STATUS_OPERATED_C,
  CTN.FEEDER_1_ID,
  SC.DEVICE_ID,
  CUN.VINTAGE_YR
FROM GIS.COMMON_N CN
INNER JOIN GIS.CONNECTIVITY_N CTN
ON CN.G3E_FID = CTN.G3E_FID
INNER JOIN GIS.SCADA_N SC
ON CN.G3E_FID = SC.G3E_FID
INNER JOIN GIS.CAPACITOR_S CS
ON CN.G3E_FID = CS.G3E_FID
INNER JOIN GIS.CAPACITOR_BANK_N CBN
ON CN.G3E_FID = CBN.G3E_FID
INNER JOIN GIS.COMP_UNIT_N CUN
ON CN.G3E_FID = CUN.G3E_FID;
