
  CREATE OR REPLACE FORCE EDITIONABLE VIEW "GIS_ONC"."CONDUIT_VW" ("OGGY_H", "OGGX_H", "OWNER1_ID", "G3E_FNO", "FEATURE_STATE_C", "LONGITUDE", "G3E_FID", "LOCATION", "LATITUDE", "STRUCTURE_ID", "G3E_GEOMETRY", "MATERIAL_C", "SIZE_Q", "USE_C") AS 
  SELECT CN.OGGY_H,
  CN.OGGX_H,
  CN.OWNER1_ID,
  CN.G3E_FNO,
  CN.FEATURE_STATE_C,
  CN.LONGITUDE,
  CN.G3E_FID,
  CN.LOCATION,
  CN.LATITUDE,
  CN.STRUCTURE_ID,
  CL.G3E_GEOMETRY,
  CDN.MATERIAL_C,
  CDN.SIZE_Q,
  CDN.USE_C
FROM GIS.COMMON_N CN
INNER JOIN GIS.CONDUIT_L CL
ON CN.G3E_FID = CL.G3E_FID
INNER JOIN GIS.CONDUIT_N CDN
ON CN.G3E_FID = CDN.G3E_FID;
