  CREATE OR REPLACE FORCE EDITIONABLE VIEW "GIS_ONC"."CONNECTIVITY_VW" ("G3E_FNO", "SSTA_C", "PROTECTIVE_DEVICE_FID", "VOLT_1_Q", "STATUS_OPERATED_C", "NODE_2_ID", "NODE_1_ID", "FEEDER_1_ID") AS 
  SELECT CN.G3E_FNO,
  CTN.SSTA_C,
  CTN.PROTECTIVE_DEVICE_FID,
  CTN.VOLT_1_Q,
  CTN.STATUS_OPERATED_C,
  CTN.NODE_2_ID,
  CTN.NODE_1_ID,
  CTN.FEEDER_1_ID
FROM GIS.COMMON_N CN
INNER JOIN GIS.CONNECTIVITY_N CTN
ON CN.G3E_FID = CTN.G3E_FID;
