
  CREATE OR REPLACE FORCE EDITIONABLE VIEW "GIS_ONC"."FUSE_VW" ("OGGY_H", "OGGX_H", "FEATURE_STATE_C", "G3E_FNO", "LONGITUDE", "OWNER1_ID", "G3E_FID", "LOCATION", "LATITUDE", "STRUCTURE_ID", "STATUS_NORMAL_C", "FEEDER_1_ID", "SSTA_C", "PROTECTIVE_DEVICE_FID", "STATUS_OPERATED_C", "VOLT_1_Q", "LINK_SIZE_C", "DEVICE_ID", "SWGEAR_OWNED", "VINTAGE_YR", "G3E_GEOMETRY") AS 
  SELECT CN.OGGY_H,
  CN.OGGX_H,
  CN.FEATURE_STATE_C,
  CN.G3E_FNO,
  CN.LONGITUDE,
  CN.OWNER1_ID,
  CN.G3E_FID,
  CN.LOCATION,
  CN.LATITUDE,
  CN.STRUCTURE_ID,
  CTN.STATUS_NORMAL_C,
  CTN.FEEDER_1_ID,
  CTN.SSTA_C,
  CTN.PROTECTIVE_DEVICE_FID,
  CTN.STATUS_OPERATED_C,
  CTN.VOLT_1_Q,
  PFUN.LINK_SIZE_C,
  SN.DEVICE_ID,
  PFBN.SWGEAR_OWNED,
  CUN.VINTAGE_YR,
  PFS.G3E_GEOMETRY
FROM GIS.COMMON_N CN
INNER JOIN GIS.CONNECTIVITY_N CTN
ON CN.G3E_FID = CTN.G3E_FID
INNER JOIN GIS.PRI_FUSE_BANK_N PFBN
ON CN.G3E_FID = PFBN.G3E_FID
INNER JOIN GIS.PRI_FUSE_UNIT_N PFUN
ON CN.G3E_FID = PFUN.G3E_FID
INNER JOIN GIS.PRI_FUSE_S PFS
ON CN.G3E_FID = PFS.G3E_FID
INNER JOIN GIS.SCADA_N SN
ON CN.G3E_FID = SN.G3E_FID
INNER JOIN GIS.COMP_UNIT_N CUN
ON CN.G3E_FID = CUN.G3E_FID;
