
  CREATE OR REPLACE FORCE EDITIONABLE VIEW "GIS_ONC"."GUY_VW" ("OGGY_H", "OGGX_H", "OWNER1_ID", "G3E_FNO", "FEATURE_STATE_C", "LONGITUDE", "G3E_FID", "LOCATION", "LATITUDE", "STRUCTURE_ID", "G3E_GEOMETRY", "TYPE_C", "SIZE_C") AS 
  SELECT CN.OGGY_H,
  CN.OGGX_H,
  CN.OWNER1_ID,
  CN.G3E_FNO,
  CN.FEATURE_STATE_C,
  CN.LONGITUDE,
  CN.G3E_FID,
  CN.LOCATION,
  CN.LATITUDE,
  CN.STRUCTURE_ID,
  GL.G3E_GEOMETRY,
  GN.TYPE_C,
  GN.SIZE_C
FROM GIS.COMMON_N CN
INNER JOIN GIS.GUY_L GL
ON CN.G3E_FID = GL.G3E_FID
INNER JOIN GIS.GUY_N GN
ON CN.G3E_FID = GN.G3E_FID;
