 CREATE OR REPLACE FORCE EDITIONABLE VIEW "GIS_ONC"."JUNCTION_POINT_VW" ("OGGY_H", "OGGX_H", "OWNER1_ID", "G3E_FNO", "FEATURE_STATE_C", "LONGITUDE", "G3E_FID",  "LOCATION", "LATITUDE", "STRUCTURE_ID", "G3E_GEOMETRY") AS 
  SELECT COMMON_N.OGGY_H,
  COMMON_N.OGGX_H,
  COMMON_N.OWNER1_ID,
  COMMON_N.G3E_FNO,
  COMMON_N.FEATURE_STATE_C,
  COMMON_N.LONGITUDE,
  COMMON_N.G3E_FID,
  COMMON_N.LOCATION,
  COMMON_N.LATITUDE,
  COMMON_N.STRUCTURE_ID,
  JUNCTIONPT_S.G3E_GEOMETRY
FROM GIS.COMMON_N 
INNER JOIN GIS.JUNCTIONPT_S 
ON COMMON_N.G3E_FID = JUNCTIONPT_S.G3E_FID;
;