  CREATE OR REPLACE FORCE EDITIONABLE VIEW "GIS_ONC"."OH_XFMR_BANK_VW" ("CONFIG_PRI_C", "CONFIG_SEC_C", "BANK_KVA_Q", "OGGY_H", "OGGX_H", "OWNER1_ID", "G3E_FNO", "G3E_CNO", "FEATURE_STATE_C", "G3E_FID", "LOCATION", "STRUCTURE_ID", "FEEDER_1_ID", "SSTA_C", "PROTECTIVE_DEVICE_FID", "STATUS_OPERATED_C", "STATUS_NORMAL_C", "NETWORK_ID", "G3E_GEOMETRY") AS 
  SELECT XOBN.CONFIG_PRI_C,
          XOBN.CONFIG_SEC_C,
          XOBN.BANK_KVA_Q,
          CN.OGGY_H,
          CN.OGGX_H,
          CN.OWNER1_ID,
          CN.G3E_FNO,
          XOBN.G3E_CNO,
          CN.FEATURE_STATE_C,
          CN.G3E_FID,
          CN.LOCATION,
          CN.STRUCTURE_ID,
          CTN.FEEDER_1_ID,
          CTN.SSTA_C,
          CTN.PROTECTIVE_DEVICE_FID,
          CTN.STATUS_OPERATED_C,
          CTN.STATUS_NORMAL_C,
          CTN.NETWORK_ID,
          XOS.G3E_GEOMETRY
     FROM GIS.COMMON_N CN
          INNER JOIN GIS.CONNECTIVITY_N CTN
             ON CN.G3E_FID = CTN.G3E_FID
          INNER JOIN GIS.XFMR_OH_BANK_N XOBN
             ON CN.G3E_FID = XOBN.G3E_FID
          INNER JOIN GIS.XFMR_OH_S XOS
             ON CN.G3E_FID = XOS.G3E_FID;