CREATE OR REPLACE FORCE EDITIONABLE VIEW "GIS_ONC"."OH_XFMR_UNIT_VW" ("G3E_FID", "G3E_FNO", "G3E_CNO", "G3E_GEOMETRY", "PHASE_Q", "KVA_Q", "COMPANY_ID", "VOLT_PRI_Q", "VOLT_SEC_Q", "PHASE_C") AS 
  SELECT
          CN.G3E_FID,
          CN.G3E_FNO,
          XOUN.G3E_CNO,
          XOS.G3E_GEOMETRY,
          XOUN.PHASE_Q,
          XOUN.KVA_Q,
          XOUN.COMPANY_ID,
          XOUN.VOLT_PRI_Q,
          XOUN.VOLT_SEC_Q,
          XOUN.PHASE_C
     FROM GIS.COMMON_N CN
          INNER JOIN GIS.CONNECTIVITY_N CTN
             ON CN.G3E_FID = CTN.G3E_FID
          INNER JOIN GIS.XFMR_OH_UNIT_N XOUN
             ON CN.G3E_FID = XOUN.G3E_FID
          INNER JOIN GIS.XFMR_OH_S XOS
             ON CN.G3E_FID = XOS.G3E_FID;
