
  CREATE OR REPLACE FORCE EDITIONABLE VIEW "GIS_ONC"."POLE_VW" ("OGGY_H", "OGGX_H", "G3E_FNO", "OWNER1_ID", "LONGITUDE", "FEATURE_STATE_C", "G3E_FID", "LOCATION", "LATITUDE", "STRUCTURE_ID", "MATERIAL_C", "HEIGHT_Q", "CLASS_C", "OWNING_COMPANY_C", "G3E_GEOMETRY", "VINTAGE_YR") AS 
  SELECT CN.OGGY_H,
  CN.OGGX_H,
  CN.G3E_FNO,
  CN.OWNER1_ID,
  CN.LONGITUDE,
  CN.FEATURE_STATE_C,
  CN.G3E_FID,
  CN.LOCATION,
  CN.LATITUDE,
  CN.STRUCTURE_ID,
  PL.MATERIAL_C,
  PL.HEIGHT_Q,
  PL.CLASS_C,
  PL.OWNING_COMPANY_C,
  PS.G3E_GEOMETRY,
  CUN.VINTAGE_YR
FROM GIS.COMMON_N CN
INNER JOIN GIS.POLE_S PS
ON CN.G3E_FID = PS.G3E_FID
INNER JOIN GIS.COMP_UNIT_N CUN
ON CN.G3E_FID = CUN.G3E_FID
INNER JOIN GIS.POLE_N PL
ON CN.G3E_FID = PL.G3E_FID;
