
  CREATE OR REPLACE FORCE EDITIONABLE VIEW "GIS_ONC"."PRI_OH_WIRE_VW" ("G3E_FID", "G3E_FNO", "G3E_CNO", "PHASE_POS_C", "TYPE_C", "PHASE_C", "SIZE_C", "G3E_GEOMETRY") AS 
  SELECT
          CN.G3E_FID,
          CN.G3E_FNO,
          POWN.G3E_CNO,
          POWN.PHASE_POS_C,
          POWN.TYPE_C,
          POWN.PHASE_C,
          POWN.SIZE_C,
          PCOL.G3E_GEOMETRY
     FROM GIS.COMMON_N CN
          INNER JOIN GIS.PRI_COND_OH_N PCON
             ON CN.G3E_FID = PCON.G3E_FID
          INNER JOIN GIS.PRI_WIRE_OH_N POWN
             ON CN.G3E_FID = POWN.G3E_FID
          INNER JOIN GIS.PRI_COND_OH_L PCOL
             ON CN.G3E_FID = PCOL.G3E_FID;
