
  CREATE OR REPLACE FORCE EDITIONABLE VIEW "GIS_ONC"."PRI_PULL_BOX_VW" ("OGGY_H", "OGGX_H", "OWNER1_ID", "G3E_FNO", "FEATURE_STATE_C", "LONGITUDE", "G3E_FID", "LOCATION", "LATITUDE", "STRUCTURE_ID", "G3E_GEOMETRY", "PHASE_Q", "CONTINUOUS_CURRENT_Q", "VOLTAGE_RTG_Q", "FACTILITY_FRONT_C") AS 
  SELECT CN.OGGY_H,
  CN.OGGX_H,
  CN.OWNER1_ID,
  CN.G3E_FNO,
  CN.FEATURE_STATE_C,
  CN.LONGITUDE,
  CN.G3E_FID,
  CN.LOCATION,
  CN.LATITUDE,
  CN.STRUCTURE_ID,
  PES.G3E_GEOMETRY,
  PEN.PHASE_Q,
  PEN.CONTINUOUS_CURRENT_Q,
  PEN.VOLT_RTG_Q,
  PEN.FACILITY_FRONT_C
FROM GIS.COMMON_N CN
INNER JOIN GIS.PRI_ENCLOSURE_S PES
ON CN.G3E_FID = PES.G3E_FID
INNER JOIN GIS.PRI_ENCLOSURE_N PEN
ON CN.G3E_FID = PEN.G3E_FID;
