  CREATE OR REPLACE FORCE EDITIONABLE VIEW "GIS_ONC"."PRI_UG_WIRE_VW" ("G3E_FNO", "G3E_FID", "G3E_CNO", "G3E_GEOMETRY", "TYPE_C", "INSULATION_VOLT_Q", "PHASE_C", "SIZE_C") AS 
  SELECT 
  CN.G3E_FNO,
  CN.G3E_FID,
  PWN.G3E_CNO,
  PCU.G3E_GEOMETRY,
  PWN.TYPE_C,
  PWN.INSULATION_VOLT_Q,
  PWN.PHASE_C,
  PWN.SIZE_C
FROM GIS.COMMON_N CN
INNER JOIN GIS.PRI_COND_UG_L PCU
ON CN.G3E_FID = PCU.G3E_FID
INNER JOIN GIS.PRI_WIRE_UG_N PWN
ON CN.G3E_FID = PWN.G3E_FID;