  CREATE OR REPLACE FORCE EDITIONABLE VIEW "GIS_ONC"."PRI_OH_COND_VW" ("OWNER1_ID", "OWNER2_ID", "FEATURE_STATE_C", "G3E_FNO", "G3E_FID", "G3E_CNO", "STRUCTURE_ID", "STATUS_NORMAL_C", "PROTECTIVE_DEVICE_FID", "NETWORK_ID", "FEEDER_1_ID", "SSTA_C", "STATUS_OPERATED_C", "LENGTH_ACTUAL_Q", "VOLT_1_Q", "WIRE_Q", "PHASE_Q", "VINTAGE_YR", "G3E_GEOMETRY") AS 
  SELECT CN.OWNER1_ID,
          CN.OWNER2_ID,
          CN.FEATURE_STATE_C,
          CN.G3E_FNO,
          CN.G3E_FID,
          PCON.G3E_CNO,
          CN.STRUCTURE_ID,
          CTN.STATUS_NORMAL_C,
          CTN.PROTECTIVE_DEVICE_FID,
          CTN.NETWORK_ID,
          CTN.FEEDER_1_ID,
          CTN.SSTA_C,
          CTN.STATUS_OPERATED_C,
          CTN.LENGTH_ACTUAL_Q,
          CTN.VOLT_1_Q,
          PCON.WIRE_Q,
          PCON.PHASE_Q,
          CUN.VINTAGE_YR,
          PCOL.G3E_GEOMETRY
     FROM GIS.PRI_COND_OH_N PCON
          INNER JOIN GIS.COMMON_N CN 
             ON PCON.G3E_FID = CN.G3E_FID
          INNER JOIN GIS.COMP_UNIT_N CUN
             ON PCON.G3E_FID = CUN.G3E_FID
          INNER JOIN GIS.CONNECTIVITY_N CTN
             ON PCON.G3E_FID = CTN.G3E_FID
          INNER JOIN GIS.PRI_COND_OH_L PCOL
             ON PCON.G3E_FID = PCOL.G3E_FID;