
  CREATE OR REPLACE FORCE EDITIONABLE VIEW "GIS_ONC"."RISER_VW" ("TYPE_C", "USE_C", "OGGY_H", "OGGX_H", "OWNER1_ID", "G3E_FNO", "FEATURE_STATE_C", "LONGITUDE", "G3E_FID", "LOCATION", "LATITUDE", "STRUCTURE_ID", "G3E_GEOMETRY") AS 
  SELECT RN.TYPE_C,
  RN.USE_C,
  CN.OGGY_H,
  CN.OGGX_H,
  CN.OWNER1_ID,
  CN.G3E_FNO,
  CN.FEATURE_STATE_C,
  CN.LONGITUDE,
  CN.G3E_FID,
  CN.LOCATION,
  CN.LATITUDE,
  CN.STRUCTURE_ID,
  RS.G3E_GEOMETRY
FROM GIS.COMMON_N CN
INNER JOIN GIS.RISER_N RN
ON CN.G3E_FID = RN.G3E_FID
INNER JOIN GIS.RISER_S RS
ON CN.G3E_FID = RS.G3E_FID;
