
  CREATE OR REPLACE FORCE EDITIONABLE VIEW "GIS_ONC"."SEC_ENCLOSURE_VW" ("OGGY_H", "OGGX_H", "OWNER1_ID", "G3E_FNO", "FEATURE_STATE_C", "LONGITUDE", "G3E_FID", "LOCATION", "LATITUDE", "STRUCTURE_ID", "G3E_GEOMETRY", "PHASE_Q", "CONTINUOUS_CURRENT_Q") AS 
  SELECT CN.OGGY_H,
  CN.OGGX_H,
  CN.OWNER1_ID,
  CN.G3E_FNO,
  CN.FEATURE_STATE_C,
  CN.LONGITUDE,
  CN.G3E_FID,
  CN.LOCATION,
  CN.LATITUDE,
  CN.STRUCTURE_ID,
  SES.G3E_GEOMETRY,
  SEN.PHASE_Q,
  SEN.CONTINUOUS_CURRENT_Q
FROM GIS.COMMON_N CN
INNER JOIN GIS.SEC_ENCLOSURE_S SES
ON CN.G3E_FID = SES.G3E_FID
INNER JOIN GIS.SEC_ENCLOSURE_N SEN
ON CN.G3E_FID = SEN.G3E_FID;
