
  CREATE OR REPLACE FORCE EDITIONABLE VIEW "GIS_ONC"."SEC_BOX_VW" ("OGGY_H", "OGGX_H", "OWNER1_ID", "G3E_FNO", "FEATURE_STATE_C", "LONGITUDE", "G3E_FID", "LOCATION", "LATITUDE", "STRUCTURE_ID", "G3E_GEOMETRY", "TYPE_C", "MATERIAL_C", "SIZE_C", "USE_C") AS 
  SELECT CN.OGGY_H,
  CN.OGGX_H,
  CN.OWNER1_ID,
  CN.G3E_FNO,
  CN.FEATURE_STATE_C,
  CN.LONGITUDE,
  CN.G3E_FID,
  CN.LOCATION,
  CN.LATITUDE,
  CN.STRUCTURE_ID,
  SBS.G3E_GEOMETRY,
  SBN.TYPE_C,
  SBN.MATERIAL_C,
  SBN.SIZE_C,
  SBN.USE_C
FROM GIS.COMMON_N CN
INNER JOIN GIS.SEC_BOX_S SBS
ON CN.G3E_FID = SBS.G3E_FID
INNER JOIN GIS.SEC_BOX_N SBN
ON CN.G3E_FID = SBN.G3E_FID;
