
  CREATE OR REPLACE FORCE EDITIONABLE VIEW "GIS_ONC"."SEC_SWITCHGEAR_VW" ("OGGY_H", "OGGX_H", "OWNER1_ID", "G3E_FNO", "FEATURE_STATE_C", "LONGITUDE", "G3E_FID", "LOCATION", "LATITUDE", "STRUCTURE_ID", "TYPE_C", "VINTAGE_YR", "G3E_GEOMETRY") AS 
  SELECT CN.OGGY_H,
  CN.OGGX_H,
  CN.OWNER1_ID,
  CN.G3E_FNO,
  CN.FEATURE_STATE_C,
  CN.LONGITUDE,
  CN.G3E_FID,
  CN.LOCATION,
  CN.LATITUDE,
  CN.STRUCTURE_ID,
  PSN.TYPE_C,
  CUN.VINTAGE_YR,
  SSP.G3E_GEOMETRY
FROM GIS.COMMON_N CN
INNER JOIN GIS.SECSWGEAR_N PSN
ON CN.G3E_FID = PSN.G3E_FID
INNER JOIN GIS.SECSWGEAR_DP SSP
ON CN.G3E_FID = SSP.G3E_FID
LEFT JOIN GIS.COMP_UNIT_N CUN
ON CN.G3E_FID = CUN.G3E_FID;
