  CREATE OR REPLACE FORCE EDITIONABLE VIEW "GIS_ONC"."SECONDARY_CONNECTIVITY_VW" ("G3E_FNO", "NODE_1_ID", "NODE_2_ID") AS 
  SELECT CN.G3E_FNO,
  CTN.NODE_1_ID,
  CTN.NODE_2_ID
FROM GIS.COMMON_N CN
INNER JOIN GIS.CONNECTIVITY_N CTN
ON CN.G3E_FID = CTN.G3E_FID;