
  CREATE OR REPLACE FORCE EDITIONABLE VIEW "GIS_ONC"."SUBSTATION_BREAKER_VW" ("OGGY_H", "OGGX_H", "OWNER1_ID", "G3E_FNO", "FEATURE_STATE_C", "LONGITUDE", "G3E_FID", "LOCATION", "LATITUDE", "STRUCTURE_ID", "PROTECTIVE_DEVICE_FID", "STATUS_OPERATED_C", "NETWORK_ID", "FEEDER_1_ID", "SSTA_C", "VINTAGE_YR", "G3E_GEOMETRY") AS 
  SELECT CN.OGGY_H,
  CN.OGGX_H,
  CN.OWNER1_ID,
  CN.G3E_FNO,
  CN.FEATURE_STATE_C,
  CN.LONGITUDE,
  CN.G3E_FID,
  CN.LOCATION,
  CN.LATITUDE,
  CN.STRUCTURE_ID,
  CTN.PROTECTIVE_DEVICE_FID,
  CTN.STATUS_OPERATED_C,
  CTN.NETWORK_ID,
  CTN.FEEDER_1_ID,
  CTN.SSTA_C,
  CUN.VINTAGE_YR,
  SBS.G3E_GEOMETRY
FROM GIS.COMMON_N CN
INNER JOIN GIS.SUB_BREAKER_S SBS
ON CN.G3E_FID = SBS.G3E_FID
INNER JOIN GIS.COMP_UNIT_N CUN
ON CN.G3E_FID = CUN.G3E_FID
INNER JOIN GIS.CONNECTIVITY_N  CTN
ON CN.G3E_FID = CTN.G3E_FID;
