  CREATE OR REPLACE FORCE EDITIONABLE VIEW "GIS_ONC"."SUBSTATION_VW" ("OGGY_H", "OGGX_H", "OWNER1_ID", "G3E_FNO", "FEATURE_STATE_C", "LONGITUDE", "G3E_FID",  "LOCATION", "LATITUDE", "STRUCTURE_ID",  "SUBSTATION_NM", "SUBSTATION_C", "G3E_GEOMETRY") AS 
  SELECT CN.OGGY_H,
  CN.OGGX_H,
  CN.OWNER1_ID,
  CN.G3E_FNO,
  CN.FEATURE_STATE_C,
  CN.LONGITUDE,
  CN.G3E_FID,
  CN.LOCATION,
  CN.LATITUDE,
  CN.STRUCTURE_ID, 
  SN.SUBSTATION_NM,
  SN.SUBSTATION_C,
  SS.G3E_GEOMETRY
FROM GIS.COMMON_N CN
INNER JOIN GIS.SUBSTATION_N SN
ON CN.G3E_FID = SN.G3E_FID
INNER JOIN GIS.SUBSTATION_S SS
ON CN.G3E_FID = SS.G3E_FID
;