
  CREATE OR REPLACE FORCE EDITIONABLE VIEW "GIS_ONC"."SWITCH_VW" ("OGGY_H", "OGGX_H", "FEATURE_STATE_C", "G3E_FNO", "OWNER1_ID", "LONGITUDE", "G3E_FID", "LOCATION", "LATITUDE", "STRUCTURE_ID", "STATUS_NORMAL_C", "CAPABLE_YN", "ENABLED_YN", "FEEDER_1_ID", "SSTA_C", "VOLT_1_Q", "PROTECTIVE_DEVICE_FID", "STATUS_OPERATED_C", "DEVICE_ID", "TYPE_C", "G3E_GEOMETRY", "VINTAGE_YR") AS 
  SELECT CN.OGGY_H,
  CN.OGGX_H,
  CN.FEATURE_STATE_C,
  CN.G3E_FNO,
  CN.OWNER1_ID,
  CN.LONGITUDE,
  CN.G3E_FID,
  CN.LOCATION,
  CN.LATITUDE,
  CN.STRUCTURE_ID,
  CTN.STATUS_NORMAL_C,
  SN.CAPABLE_YN,
  SN.ENABLED_YN,
  CTN.FEEDER_1_ID,
  CTN.SSTA_C,
  CTN.VOLT_1_Q,
  CTN.PROTECTIVE_DEVICE_FID,
  CTN.STATUS_OPERATED_C,
  SN.DEVICE_ID,
  PSBN.TYPE_C,
  PSS.G3E_GEOMETRY,
  CUN.VINTAGE_YR
FROM GIS.COMMON_N CN
INNER JOIN GIS.PRI_SWITCH_S PSS
ON CN.G3E_FID = PSS.G3E_FID
LEFT JOIN GIS.COMP_UNIT_N CUN
ON CN.G3E_FID = CUN.G3E_FID
INNER JOIN GIS.CONNECTIVITY_N CTN
ON CN.G3E_FID = CTN.G3E_FID
INNER JOIN GIS.PRI_SWITCH_BANK_N PSBN
ON CN.G3E_FID = PSBN.G3E_FID
INNER JOIN GIS.SCADA_N SN
ON CN.G3E_FID = SN.G3E_FID;
