  CREATE OR REPLACE FORCE EDITIONABLE VIEW "GIS_ONC"."TRANS_TOWER_VW" ("OGGY_H", "OGGX_H", "OWNER1_ID", "G3E_FNO", "FEATURE_STATE_C", "LONGITUDE", "G3E_FID",  "LOCATION", "LATITUDE", "STRUCTURE_ID",  "G3E_GEOMETRY") AS 
  SELECT CN.OGGY_H,
  CN.OGGX_H,
  CN.OWNER1_ID,
  CN.G3E_FNO,
  CN.FEATURE_STATE_C,
  CN.LONGITUDE,
  CN.G3E_FID,
  CN.LOCATION,
  CN.LATITUDE,
  CN.STRUCTURE_ID,
  TTS.G3E_GEOMETRY
FROM GIS.COMMON_N CN
INNER JOIN GIS.TRANS_TOWER_S TTS
ON CN.G3E_FID = TTS.G3E_FID;