
  CREATE OR REPLACE FORCE EDITIONABLE VIEW "GIS_ONC"."VAULTS_VW" ("OGGY_H", "OGGX_H", "OWNER1_ID", "G3E_FNO", "FEATURE_STATE_C", "LONGITUDE", "G3E_FID", "LOCATION", "LATITUDE", "STRUCTURE_ID", "VINTAGE_YR", "G3E_GEOMETRY") AS 
  SELECT CN.OGGY_H,
  CN.OGGX_H,
  CN.OWNER1_ID,
  CN.G3E_FNO,
  CN.FEATURE_STATE_C,
  CN.LONGITUDE,
  CN.G3E_FID,
  CN.LOCATION,
  CN.LATITUDE,
  CN.STRUCTURE_ID,
  CUN.VINTAGE_YR,
  VS.G3E_GEOMETRY
FROM GIS.COMMON_N CN
INNER JOIN GIS.VAULT_S VS
ON CN.G3E_FID = VS.G3E_FID
INNER JOIN GIS.COMP_UNIT_N CUN
ON CN.G3E_FID = CUN.G3E_FID;
