CREATE TABLE "GIS_STG"."STG_B$AIRPORT_AR"
   ("G3E_ID" NUMBER(10,0) DEFAULT ON NULL "GIS"."AIRPORT_AR_SEQ"."NEXTVAL" NOT NULL ENABLE,
   	"G3E_FNO" NUMBER(5,0), 
	"G3E_CNO" NUMBER(5,0), 
	"G3E_FID" NUMBER(10,0), 
	"G3E_CID" NUMBER(10,0), 
	"G3E_GEOMETRY" "SDO_GEOMETRY", 
	"LTT_ID" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"LTT_STATUS" VARCHAR2(6 BYTE), 
	"LTT_DATE" DATE, 
	"LTT_TID" NUMBER);
-------------------------------------------------------------------------------------	
CREATE TABLE "GIS_STG"."STG_B$AIRPORT_N"
   ("G3E_ID" NUMBER(10,0) DEFAULT ON NULL "GIS"."AIRPORT_N_SEQ"."NEXTVAL" NOT NULL ENABLE,
   	"G3E_FNO" NUMBER(5,0),
	"G3E_CNO" NUMBER(5,0),
	"G3E_FID" NUMBER(10,0), 
	"G3E_CID" NUMBER(10,0), 
	"LTT_ID" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"LTT_STATUS" VARCHAR2(6 BYTE), 
	"LTT_DATE" DATE, 
	"LTT_TID" NUMBER, 
	"NAME" VARCHAR2(100 BYTE), 
	"ID" NUMBER(20,0), 
	"FEATTYP" NUMBER(10,0), 
	"FEATAREA" NUMBER(10,0), 
	"FEATPERIM" NUMBER(10,0), 
	"NAMELC" VARCHAR2(20 BYTE), 
	"DISPLATTYP" VARCHAR2(20 BYTE), 
	"DISPLTYP" VARCHAR2(20 BYTE), 
	"CLASS" VARCHAR2(20 BYTE), 
	"IMPORT" VARCHAR2(20 BYTE), 
	"ACRON" VARCHAR2(20 BYTE));
-------------------------------------------------------------------------------------
CREATE TABLE "GIS_STG"."STG_B$AIRPORT_T"
   ("G3E_ID" NUMBER(10,0) DEFAULT ON NULL "GIS"."AIRPORT_T_SEQ"."NEXTVAL" NOT NULL ENABLE,
   	"G3E_FNO" NUMBER(5,0),
	"G3E_CNO" NUMBER(5,0),
	"G3E_FID" NUMBER(10,0), 
	"G3E_CID" NUMBER(10,0), 
	"G3E_GEOMETRY" "SDO_GEOMETRY", 
	"G3E_ALIGNMENT" NUMBER(5,0) DEFAULT 1, 
	"LTT_ID" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"LTT_STATUS" VARCHAR2(6 BYTE), 
	"LTT_DATE" DATE, 
	"LTT_TID" NUMBER);
-------------------------------------------------------------------------------------   
CREATE TABLE "GIS_STG"."STG_B$BUILDING_CL_AR"
   ("G3E_ID" NUMBER(10,0) DEFAULT ON NULL "GIS"."BUILDING_CL_AR_SEQ"."NEXTVAL" NOT NULL ENABLE,
   	"G3E_FNO" NUMBER(5,0), 
	"G3E_CNO" NUMBER(5,0), 
	"G3E_FID" NUMBER(10,0), 
	"G3E_CID" NUMBER(10,0), 
	"G3E_GEOMETRY" "MDSYS"."SDO_GEOMETRY" , 
	"LTT_ID" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"LTT_STATUS" VARCHAR2(6 BYTE), 
	"LTT_DATE" DATE, 
	"LTT_TID" NUMBER);
-------------------------------------------------------------------------------------   
CREATE TABLE "GIS_STG"."STG_B$BUILDING_CL_N"
   ("G3E_ID" NUMBER(10,0) DEFAULT ON NULL "GIS"."BUILDING_CL_N_SEQ"."NEXTVAL" NOT NULL ENABLE,
   	"G3E_FNO" NUMBER(5,0), 
	"G3E_CNO" NUMBER(5,0), 
	"G3E_FID" NUMBER(10,0), 
	"G3E_CID" NUMBER(10,0), 
	"LTT_ID" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"LTT_STATUS" VARCHAR2(6 BYTE), 
	"LTT_DATE" DATE, 
	"LTT_TID" NUMBER, 
	"ID" NUMBER(20,0), 
	"FEATTYP" NUMBER(10,0), 
	"FEATAREA" NUMBER(10,0), 
	"FEATPERIM" NUMBER(10,0), 
	"BUILDCLASS" NUMBER(4,0), 
	"BUILDSTOR" VARCHAR2(20 BYTE), 
	"COVERFL" VARCHAR2(20 BYTE));
-------------------------------------------------------------------------------------   
CREATE TABLE "GIS_STG"."STG_B$BUILDING_CL_T"
   ("G3E_ID" NUMBER(10,0) DEFAULT ON NULL "GIS"."BUILDING_CL_T_SEQ"."NEXTVAL" NOT NULL ENABLE,
   	"G3E_FNO" NUMBER(5,0), 
	"G3E_CNO" NUMBER(5,0), 
	"G3E_FID" NUMBER(10,0), 
	"G3E_CID" NUMBER(10,0), 
	"G3E_GEOMETRY" "SDO_GEOMETRY", 
	"G3E_ALIGNMENT" NUMBER(5,0) DEFAULT 1, 
	"LTT_ID" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"LTT_STATUS" VARCHAR2(6 BYTE), 
	"LTT_DATE" DATE, 
	"LTT_TID" NUMBER);
-------------------------------------------------------------------------------------   
CREATE TABLE "GIS_STG"."STG_B$CENSUS_BNDY_AR"
   ("G3E_ID" NUMBER(10,0) DEFAULT ON NULL "GIS"."CENSUS_BNDY_AR_SEQ"."NEXTVAL" NOT NULL ENABLE,
   	"G3E_FNO" NUMBER(5,0),
	"G3E_CNO" NUMBER(5,0),
	"G3E_FID" NUMBER(10,0),
	"G3E_CID" NUMBER(10,0),
	"G3E_GEOMETRY" "MDSYS"."SDO_GEOMETRY" , 
	"LTT_ID" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"LTT_STATUS" VARCHAR2(6 BYTE), 
	"LTT_DATE" DATE, 
	"LTT_TID" NUMBER);
-------------------------------------------------------------------------------------   
CREATE TABLE "GIS_STG"."STG_B$CENSUS_BNDY_N"
   ("G3E_ID" NUMBER(10,0) DEFAULT ON NULL "GIS"."CENSUS_BNDY_N_SEQ"."NEXTVAL" NOT NULL ENABLE,
   	"G3E_FNO" NUMBER(5,0),
	"G3E_CNO" NUMBER(5,0),
	"G3E_FID" NUMBER(10,0),
	"G3E_CID" NUMBER(10,0),
	"LTT_ID" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"LTT_STATUS" VARCHAR2(6 BYTE), 
	"LTT_DATE" DATE, 
	"LTT_TID" NUMBER, 
	"ID" NUMBER(20,0), 
	"FEATTYP" NUMBER(10,0), 
	"FEATAREA" NUMBER(10,0), 
	"FEATPERIM" NUMBER(10,0), 
	"CODE" NUMBER(20,0), 
	"NAMELC" VARCHAR2(30 BYTE), 
	"URBANAREA" VARCHAR2(30 BYTE));
-------------------------------------------------------------------------------------   
CREATE TABLE "GIS_STG"."STG_B$CENSUS_BNDY_T"
   ("G3E_ID" NUMBER(10,0) DEFAULT ON NULL "GIS"."CENSUS_BNDY_T_SEQ"."NEXTVAL" NOT NULL ENABLE,
   	"G3E_FNO" NUMBER(5,0),
	"G3E_CNO" NUMBER(5,0),
	"G3E_FID" NUMBER(10,0),
	"G3E_CID" NUMBER(10,0),
	"G3E_GEOMETRY" "SDO_GEOMETRY", 
	"G3E_ALIGNMENT" NUMBER(5,0) DEFAULT 1, 
	"LTT_ID" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"LTT_STATUS" VARCHAR2(6 BYTE), 
	"LTT_DATE" DATE, 
	"LTT_TID" NUMBER);
-------------------------------------------------------------------------------------   
CREATE TABLE "GIS_STG"."STG_B$CERT_BNDY_AR"
   ("G3E_ID" NUMBER(10,0) DEFAULT ON NULL "GIS"."CERT_BNDY_AR_SEQ"."NEXTVAL" NOT NULL ENABLE,
   	"G3E_FNO" NUMBER(5,0),
	"G3E_CNO" NUMBER(5,0),
	"G3E_FID" NUMBER(10,0),
	"G3E_CID" NUMBER(10,0),
	"G3E_GEOMETRY" "SDO_GEOMETRY", 
	"LTT_ID" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"LTT_STATUS" VARCHAR2(6 BYTE), 
	"LTT_DATE" DATE, 
	"LTT_TID" NUMBER);
-------------------------------------------------------------------------------------   
CREATE TABLE "GIS_STG"."STG_B$CERT_BNDY_N"
   ("G3E_ID" NUMBER(10,0) DEFAULT ON NULL "GIS"."CERT_BNDY_N_SEQ"."NEXTVAL" NOT NULL ENABLE,
   	"G3E_FNO" NUMBER(5,0),
	"G3E_CNO" NUMBER(5,0),
	"G3E_FID" NUMBER(10,0),
	"G3E_CID" NUMBER(10,0),
	"PUC_NAME1" VARCHAR2(30 BYTE), 
	"CERT_TYPE" VARCHAR2(10 BYTE), 
	"COMBINED_P" VARCHAR2(30 BYTE), 
	"PUC_NAME2" VARCHAR2(30 BYTE), 
	"PUC_NAME3" VARCHAR2(30 BYTE), 
	"PUC_NAME4" VARCHAR2(30 BYTE), 
	"SHAPE_AREA" NUMBER(20,0), 
	"SHAPE_LEN" NUMBER(20,0), 
	"COUNTY" VARCHAR2(30 BYTE), 
	"FIPS" VARCHAR2(30 BYTE), 
	"LTT_ID" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"LTT_STATUS" VARCHAR2(6 BYTE), 
	"LTT_DATE" DATE, 
	"LTT_TID" NUMBER);
-------------------------------------------------------------------------------------   
CREATE TABLE "GIS_STG"."STG_B$COUNTY_AR"
   ("G3E_ID" NUMBER(10,0) DEFAULT ON NULL "GIS"."COUNTY_AR_SEQ"."NEXTVAL" NOT NULL ENABLE,
   	"G3E_FNO" NUMBER(5,0),
	"G3E_CNO" NUMBER(5,0),
	"G3E_FID" NUMBER(10,0),
	"G3E_CID" NUMBER(10,0),
	"G3E_GEOMETRY" "MDSYS"."SDO_GEOMETRY" , 
	"LTT_ID" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"LTT_STATUS" VARCHAR2(6 BYTE), 
	"LTT_DATE" DATE, 
	"LTT_TID" NUMBER);
-------------------------------------------------------------------------------------
CREATE TABLE "GIS_STG"."STG_B$COUNTY_N"
   ("G3E_ID" NUMBER(10,0) DEFAULT ON NULL "GIS"."COUNTY_N_SEQ"."NEXTVAL" NOT NULL ENABLE,
   	"G3E_FNO" NUMBER(5,0),
	"G3E_CNO" NUMBER(5,0),
	"G3E_FID" NUMBER(10,0),
	"G3E_CID" NUMBER(10,0),
	"LTT_ID" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"LTT_STATUS" VARCHAR2(6 BYTE), 
	"LTT_DATE" DATE, 
	"LTT_TID" NUMBER, 
	"ID" VARCHAR2(10 BYTE), 
	"FEATTYP" NUMBER(5,0), 
	"ORDER00" VARCHAR2(66 BYTE), 
	"ORDER01" VARCHAR2(30 BYTE), 
	"ORDER02" VARCHAR2(30 BYTE), 
	"ORDER03" VARCHAR2(30 BYTE), 
	"ORDER04" VARCHAR2(30 BYTE), 
	"ORDER05" VARCHAR2(30 BYTE), 
	"ORDER06" VARCHAR2(30 BYTE), 
	"ORDER07" VARCHAR2(30 BYTE), 
	"ORDER08" VARCHAR2(10 BYTE), 
	"FEATAREA" NUMBER(20,0), 
	"FEATPERIM" NUMBER(20,0), 
	"NAME" VARCHAR2(30 BYTE), 
	"NAMELC" VARCHAR2(10 BYTE), 
	"POPCLASS" NUMBER(2,0), 
	"POP" NUMBER(10,0), 
	"CITYCENTER" NUMBER(20,0));
-------------------------------------------------------------------------------------
CREATE TABLE "GIS_STG"."STG_B$COUNTY_T"
   ("G3E_ID" NUMBER(10,0) DEFAULT ON NULL "GIS"."COUNTY_T_SEQ"."NEXTVAL" NOT NULL ENABLE,
   	"G3E_FNO" NUMBER(5,0),
	"G3E_CNO" NUMBER(5,0),
	"G3E_FID" NUMBER(10,0),
	"G3E_CID" NUMBER(10,0),
	"G3E_GEOMETRY" "SDO_GEOMETRY", 
	"G3E_ALIGNMENT" NUMBER(5,0) DEFAULT 1, 
	"LTT_ID" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"LTT_STATUS" VARCHAR2(6 BYTE), 
	"LTT_DATE" DATE, 
	"LTT_TID" NUMBER);
-------------------------------------------------------------------------------------
CREATE TABLE "GIS_STG"."STG_B$HYPERLINK_N"
   ("G3E_ID" NUMBER(10,0) DEFAULT ON NULL "GIS"."HYPERLINK_N_SEQ"."NEXTVAL" NOT NULL ENABLE,
   	"G3E_FNO" NUMBER(5,0),
	"G3E_CNO" NUMBER(5,0),
	"G3E_FID" NUMBER(10,0),
	"G3E_CID" NUMBER(10,0),
	"HYPERLINK_T" VARCHAR2(256 BYTE), 
	"DESCRIPTION_T" VARCHAR2(80 BYTE), 
	"TYPE_C" VARCHAR2(30 BYTE), 
	"LTT_ID" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"LTT_STATUS" VARCHAR2(6 BYTE), 
	"LTT_DATE" DATE, 
	"LTT_TID" NUMBER, 
	"FILENAME_T" VARCHAR2(80 BYTE));
-------------------------------------------------------------------------------------
CREATE TABLE "GIS_STG"."STG_B$INSTITUTION_N"
   ("G3E_ID" NUMBER(10,0) DEFAULT ON NULL "GIS"."INSTITUTION_N_SEQ"."NEXTVAL" NOT NULL ENABLE,
   	"G3E_FNO" NUMBER(5,0),
	"G3E_CNO" NUMBER(5,0),
	"G3E_FID" NUMBER(10,0),
	"G3E_CID" NUMBER(10,0),
	"LTT_ID" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"LTT_STATUS" VARCHAR2(6 BYTE), 
	"LTT_DATE" DATE, 
	"LTT_TID" NUMBER, 
	"ID" NUMBER(20,0), 
	"NAME" VARCHAR2(80 BYTE), 
	"FEATTYP" NUMBER(10,0), 
	"PACKAGE" NUMBER(10,0), 
	"SUBCAT" NUMBER(10,0), 
	"IMPORT" NUMBER(10,0), 
	"STNAME" VARCHAR2(30 BYTE), 
	"HSNUM" NUMBER(10,0), 
	"POSTCODE" VARCHAR2(30 BYTE), 
	"LOCNAME" VARCHAR2(30 BYTE), 
	"LANCD" VARCHAR2(30 BYTE), 
	"TELNUM" VARCHAR2(30 BYTE), 
	"TEL_TYPE" VARCHAR2(30 BYTE), 
	"FAXNUM" VARCHAR2(30 BYTE), 
	"EMAIL" VARCHAR2(30 BYTE), 
	"HTTP" VARCHAR2(250 BYTE), 
	"BRANDNAME" VARCHAR2(30 BYTE), 
	"COMPNAME" VARCHAR2(30 BYTE), 
	"CLTRPELID" NUMBER(20,0), 
	"RELPOS" NUMBER(10,3), 
	"EXTPOIID" NUMBER(20,0), 
	"ADDRPID" NUMBER(20,0), 
	"POSACCUR" VARCHAR2(30 BYTE), 
	"GAL" VARCHAR2(30 BYTE), 
	"CONT_SRC" VARCHAR2(30 BYTE), 
	"CONT_MOD" VARCHAR2(30 BYTE));
-------------------------------------------------------------------------------------
CREATE TABLE "GIS_STG"."STG_B$INSTITUTION_S"
   ("G3E_ID" NUMBER(10,0) DEFAULT ON NULL "GIS"."INSTITUTION_S_SEQ"."NEXTVAL" NOT NULL ENABLE,
   	"G3E_FNO" NUMBER(5,0),
	"G3E_CNO" NUMBER(5,0),
	"G3E_FID" NUMBER(10,0),
	"G3E_CID" NUMBER(10,0),
	"G3E_GEOMETRY" "MDSYS"."SDO_GEOMETRY" , 
	"LTT_ID" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"LTT_STATUS" VARCHAR2(6 BYTE), 
	"LTT_DATE" DATE, 
	"LTT_TID" NUMBER);
-------------------------------------------------------------------------------------
CREATE TABLE "GIS_STG"."STG_B$INSTITUTION_T"
   ("G3E_ID" NUMBER(10,0) DEFAULT ON NULL "GIS"."INSTITUTION_T_SEQ"."NEXTVAL" NOT NULL ENABLE,
   	"G3E_FNO" NUMBER(5,0),
	"G3E_CNO" NUMBER(5,0),
	"G3E_FID" NUMBER(10,0),
	"G3E_CID" NUMBER(10,0),
	"G3E_GEOMETRY" "MDSYS"."SDO_GEOMETRY" , 
	"G3E_ALIGNMENT" NUMBER(5,0) DEFAULT 1, 
	"LTT_ID" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"LTT_STATUS" VARCHAR2(6 BYTE), 
	"LTT_DATE" DATE, 
	"LTT_TID" NUMBER);
-------------------------------------------------------------------------------------
CREATE TABLE "GIS_STG"."STG_B$LANDMARK_AR"
   ("G3E_ID" NUMBER(10,0) DEFAULT ON NULL "GIS"."LANDMARK_AR_SEQ"."NEXTVAL" NOT NULL ENABLE,
   	"G3E_FNO" NUMBER(5,0),
	"G3E_CNO" NUMBER(5,0),
	"G3E_FID" NUMBER(10,0),
	"G3E_CID" NUMBER(10,0),
	"G3E_GEOMETRY" "MDSYS"."SDO_GEOMETRY" , 
	"LTT_ID" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"LTT_STATUS" VARCHAR2(6 BYTE), 
	"LTT_DATE" DATE, 
	"LTT_TID" NUMBER);
-------------------------------------------------------------------------------------
CREATE TABLE "GIS_STG"."STG_B$LANDMARK_N"
   ("G3E_ID" NUMBER(10,0) DEFAULT ON NULL "GIS"."LANDMARK_N_SEQ"."NEXTVAL" NOT NULL ENABLE,
   	"G3E_FNO" NUMBER(5,0),
	"G3E_CNO" NUMBER(5,0),
	"G3E_FID" NUMBER(10,0),
	"G3E_CID" NUMBER(10,0),
	"LTT_ID" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"LTT_STATUS" VARCHAR2(6 BYTE), 
	"LTT_DATE" DATE, 
	"LTT_TID" NUMBER, 
	"ID" NUMBER(20,0), 
	"NAME" VARCHAR2(100 BYTE), 
	"FEATTYP" NUMBER(10,0), 
	"FEATAREA" NUMBER(10,0), 
	"FEATPERIM" NUMBER(10,0), 
	"NAMELC" VARCHAR2(30 BYTE), 
	"URBANAREA" VARCHAR2(30 BYTE), 
	"DISPLATTYP" VARCHAR2(30 BYTE), 
	"DISPLTYP" VARCHAR2(30 BYTE), 
	"EXTPOIID" VARCHAR2(30 BYTE), 
	"MUNID" VARCHAR2(30 BYTE), 
	"EMAIL" VARCHAR2(30 BYTE), 
	"POSTCODE" VARCHAR2(30 BYTE), 
	"STNAME" VARCHAR2(30 BYTE), 
	"FAXNUM" VARCHAR2(30 BYTE), 
	"RELPOS" VARCHAR2(30 BYTE), 
	"HTTP" VARCHAR2(30 BYTE), 
	"ADDRPID" VARCHAR2(30 BYTE), 
	"TELNUM" VARCHAR2(30 BYTE), 
	"ACRON" VARCHAR2(30 BYTE), 
	"SUBCAT" VARCHAR2(30 BYTE), 
	"ARNAMELC" VARCHAR2(30 BYTE), 
	"MUNCD" VARCHAR2(30 BYTE), 
	"MUNNAME" VARCHAR2(30 BYTE), 
	"POSACCUR" VARCHAR2(30 BYTE), 
	"IMPORT" VARCHAR2(30 BYTE), 
	"GAL" VARCHAR2(30 BYTE), 
	"BUANAME" VARCHAR2(30 BYTE), 
	"CLASS" VARCHAR2(30 BYTE), 
	"STNAMELC" VARCHAR2(30 BYTE), 
	"HSNUM" VARCHAR2(30 BYTE), 
	"COMPNAME" VARCHAR2(30 BYTE), 
	"CLTRPELID" VARCHAR2(30 BYTE));
-------------------------------------------------------------------------------------
CREATE TABLE "GIS_STG"."STG_B$LANDMARK_T"
   ("G3E_ID" NUMBER(10,0) DEFAULT ON NULL "GIS"."LANDMARK_T_SEQ"."NEXTVAL" NOT NULL ENABLE,
   	"G3E_FNO" NUMBER(5,0),
	"G3E_CNO" NUMBER(5,0),
	"G3E_FID" NUMBER(10,0),
	"G3E_CID" NUMBER(10,0),
	"G3E_GEOMETRY" "MDSYS"."SDO_GEOMETRY" , 
	"G3E_ALIGNMENT" NUMBER(5,0) DEFAULT 1, 
	"LTT_ID" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"LTT_STATUS" VARCHAR2(6 BYTE), 
	"LTT_DATE" DATE, 
	"LTT_TID" NUMBER);
-------------------------------------------------------------------------------------
CREATE TABLE "GIS_STG"."STG_B$MUNICIPALITY_AR"
   ("G3E_ID" NUMBER(10,0) DEFAULT ON NULL "GIS"."MUNICIPALITY_AR_SEQ"."NEXTVAL" NOT NULL ENABLE,
   	"G3E_FNO" NUMBER(5,0),
	"G3E_CNO" NUMBER(5,0),
	"G3E_FID" NUMBER(10,0),
	"G3E_CID" NUMBER(10,0),
	"G3E_GEOMETRY" "MDSYS"."SDO_GEOMETRY" , 
	"LTT_ID" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"LTT_STATUS" VARCHAR2(6 BYTE), 
	"LTT_DATE" DATE, 
	"LTT_TID" NUMBER);
-------------------------------------------------------------------------------------
CREATE TABLE "GIS_STG"."STG_B$MUNICIPALITY_N"
   ("G3E_ID" NUMBER(10,0) DEFAULT ON NULL "GIS"."MUNICIPALITY_N_SEQ"."NEXTVAL" NOT NULL ENABLE,
   	"G3E_FNO" NUMBER(5,0),
	"G3E_CNO" NUMBER(5,0),
	"G3E_FID" NUMBER(10,0),
	"G3E_CID" NUMBER(10,0),
	"LTT_ID" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"LTT_STATUS" VARCHAR2(6 BYTE), 
	"LTT_DATE" DATE, 
	"LTT_TID" NUMBER, 
	"FIPSSTCO" VARCHAR2(5 BYTE), 
	"STATE" VARCHAR2(30 BYTE), 
	"COUNTY" VARCHAR2(66 BYTE), 
	"CITY_NAME" VARCHAR2(30 BYTE), 
	"CITY_TYPE" VARCHAR2(30 BYTE), 
	"ST_PL_FIPS" VARCHAR2(10 BYTE), 
	"PL_FIPS" VARCHAR2(5 BYTE), 
	"CLASS_CODE" VARCHAR2(5 BYTE), 
	"INC_FLAG" VARCHAR2(5 BYTE), 
	"DT_ANX" VARCHAR2(6 BYTE), 
	"DT_UPD" VARCHAR2(6 BYTE), 
	"DT_VRF" VARCHAR2(6 BYTE), 
	"GNIS_CODE" VARCHAR2(15 BYTE));
-------------------------------------------------------------------------------------
CREATE TABLE "GIS_STG"."STG_B$OPERBNDY_AR"
   ("G3E_ID" NUMBER(10,0) DEFAULT ON NULL "GIS"."OPERBNDY_AR_SEQ"."NEXTVAL" NOT NULL ENABLE,
   	"G3E_FNO" NUMBER(5,0),
	"G3E_CNO" NUMBER(5,0),
	"G3E_FID" NUMBER(10,0),
	"G3E_CID" NUMBER(10,0),
	"G3E_GEOMETRY" "MDSYS"."SDO_GEOMETRY" , 
	"LTT_ID" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"LTT_STATUS" VARCHAR2(6 BYTE), 
	"LTT_DATE" DATE, 
	"LTT_TID" NUMBER);
-------------------------------------------------------------------------------------
CREATE TABLE "GIS_STG"."STG_B$OPERBNDY_N"
   ("G3E_ID" NUMBER(10,0) DEFAULT ON NULL "GIS"."OPERBNDY_N_SEQ"."NEXTVAL" NOT NULL ENABLE,
   	"G3E_FNO" NUMBER(5,0),
	"G3E_CNO" NUMBER(5,0),
	"G3E_FID" NUMBER(10,0),
	"G3E_CID" NUMBER(10,0),
	"OPERBNDY_TYPE" VARCHAR2(10 BYTE), 
	"OWNER_FID" NUMBER(10,0) DEFAULT 0, 
	"OWNER_FNO" NUMBER(10,0) DEFAULT 0, 
	"LTT_ID" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"LTT_STATUS" VARCHAR2(6 BYTE), 
	"LTT_DATE" DATE, 
	"LTT_TID" NUMBER, 
	"OPERBNDY_CODE" VARCHAR2(10 BYTE), 
	"OPERBNDY_ID" NUMBER(10,0), 
	"OPERBNDY_NM" VARCHAR2(50 BYTE));
-------------------------------------------------------------------------------------
CREATE TABLE "GIS_STG"."STG_B$OPERBNDY_T"
   ("G3E_ID" NUMBER(10,0) DEFAULT ON NULL "GIS"."OPERBNDY_T_SEQ"."NEXTVAL" NOT NULL ENABLE,
   	"G3E_FNO" NUMBER(5,0),
	"G3E_CNO" NUMBER(5,0),
	"G3E_FID" NUMBER(10,0),
	"G3E_CID" NUMBER(10,0),
	"G3E_GEOMETRY" "SDO_GEOMETRY", 
	"G3E_ALIGNMENT" NUMBER(5,0) DEFAULT 1, 
	"LTT_ID" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"LTT_STATUS" VARCHAR2(6 BYTE), 
	"LTT_DATE" DATE, 
	"LTT_TID" NUMBER);
-------------------------------------------------------------------------------------
CREATE TABLE "GIS_STG"."STG_B$PARCEL_CL_AR"
   ("G3E_ID" NUMBER(10,0) DEFAULT ON NULL "GIS"."PARCEL_CL_AR_SEQ"."NEXTVAL" NOT NULL ENABLE,
   	"G3E_FNO" NUMBER(5,0),
	"G3E_CNO" NUMBER(5,0),
	"G3E_FID" NUMBER(10,0),
	"G3E_CID" NUMBER(10,0),
	"G3E_GEOMETRY" "MDSYS"."SDO_GEOMETRY" , 
	"LTT_ID" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"LTT_STATUS" VARCHAR2(6 BYTE), 
	"LTT_DATE" DATE, 
	"LTT_TID" NUMBER);
-------------------------------------------------------------------------------------
CREATE TABLE "GIS_STG"."STG_B$PARCEL_CL_N"
   ("G3E_ID" NUMBER(10,0) DEFAULT ON NULL "GIS"."PARCEL_CL_N_SEQ"."NEXTVAL" NOT NULL ENABLE,
    "G3E_FNO" NUMBER(5,0),
	"G3E_CNO" NUMBER(5,0),
	"G3E_FID" NUMBER(10,0),
	"G3E_CID" NUMBER(10,0),
	"ACCT_NO" VARCHAR2(15 BYTE), 
	"ADDR" VARCHAR2(50 BYTE), 
	"APN" VARCHAR2(45 BYTE), 
	"APN2" VARCHAR2(45 BYTE), 
	"APN_SEQ_NO" VARCHAR2(45 BYTE), 
	"CITY" VARCHAR2(45 BYTE), 
	"CNTY_CODE" VARCHAR2(10 BYTE), 
	"FIPS_CODE" VARCHAR2(20 BYTE), 
	"FRM_APN" VARCHAR2(45 BYTE), 
	"LATITUDE" NUMBER(20,12), 
	"LONGITUDE" NUMBER(20,12), 
	"MAIL_CC" VARCHAR2(30 BYTE), 
	"MAIL_CITY" VARCHAR2(40 BYTE), 
	"MAIL_DIR" VARCHAR2(30 BYTE), 
	"MAIL_MODE" VARCHAR2(30 BYTE), 
	"MAIL_NBR" VARCHAR2(30 BYTE), 
	"MAIL_NBR2" VARCHAR2(30 BYTE), 
	"MAIL_NBRPX" VARCHAR2(30 BYTE), 
	"MAIL_NBRSX" VARCHAR2(30 BYTE), 
	"MAIL_OPT" VARCHAR2(10 BYTE), 
	"MAIL_QDRT" VARCHAR2(30 BYTE), 
	"MAIL_STATE" VARCHAR2(2 BYTE), 
	"MAIL_STR" VARCHAR2(30 BYTE), 
	"MAIL_UNIT" VARCHAR2(30 BYTE), 
	"MAIL_ZIP" VARCHAR2(10 BYTE), 
	"MAP_REF1" VARCHAR2(45 BYTE), 
	"MAP_REF2" VARCHAR2(45 BYTE), 
	"ORIG_APN" VARCHAR2(30 BYTE), 
	"OWN1_FRST" VARCHAR2(45 BYTE), 
	"OWN1_LAST" VARCHAR2(60 BYTE), 
	"OWN2_FRST" VARCHAR2(60 BYTE), 
	"OWN2_LAST" VARCHAR2(60 BYTE), 
	"OWN_CP_IND" VARCHAR2(1 BYTE), 
	"PARCEL_ID" VARCHAR2(30 BYTE), 
	"PLUS" VARCHAR2(30 BYTE), 
	"STATE" VARCHAR2(5 BYTE), 
	"STATE_CODE" VARCHAR2(10 BYTE), 
	"STD_ADDR" VARCHAR2(50 BYTE), 
	"STD_CITY" VARCHAR2(45 BYTE), 
	"STD_PLUS" VARCHAR2(30 BYTE), 
	"STD_STATE" VARCHAR2(5 BYTE), 
	"STD_ZIP" VARCHAR2(10 BYTE), 
	"TH_BRO_MAP" VARCHAR2(30 BYTE), 
	"TYPE_CODE" VARCHAR2(30 BYTE), 
	"UNFRM_APN" VARCHAR2(45 BYTE), 
	"ZIP" VARCHAR2(10 BYTE), 
	"LTT_ID" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"LTT_STATUS" VARCHAR2(6 BYTE), 
	"LTT_DATE" DATE, 
	"LTT_TID" NUMBER);
-------------------------------------------------------------------------------------
CREATE TABLE "GIS_STG"."STG_B$PARCEL_CL_S"
   ("G3E_ID" NUMBER(10,0) DEFAULT ON NULL "GIS"."PARCEL_CL_S_SEQ"."NEXTVAL" NOT NULL ENABLE,
    "G3E_FNO" NUMBER(5,0),
	"G3E_CNO" NUMBER(5,0),
	"G3E_FID" NUMBER(10,0),
	"G3E_CID" NUMBER(10,0),
	"G3E_GEOMETRY" "SDO_GEOMETRY", 
	"LTT_ID" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"LTT_STATUS" VARCHAR2(6 BYTE), 
	"LTT_DATE" DATE, 
	"LTT_TID" NUMBER);
-------------------------------------------------------------------------------------
CREATE TABLE "GIS_STG"."STG_B$PARCEL_CL_T"
   ("G3E_ID" NUMBER(10,0) DEFAULT ON NULL "GIS"."PARCEL_CL_T_SEQ"."NEXTVAL" NOT NULL ENABLE,
   	"G3E_FNO" NUMBER(5,0),
	"G3E_CNO" NUMBER(5,0),
	"G3E_FID" NUMBER(10,0),
	"G3E_CID" NUMBER(10,0),
	"G3E_GEOMETRY" "SDO_GEOMETRY", 
	"G3E_ALIGNMENT" NUMBER(5,0) DEFAULT 1, 
	"LTT_ID" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"LTT_STATUS" VARCHAR2(6 BYTE), 
	"LTT_DATE" DATE, 
	"LTT_TID" NUMBER);
-------------------------------------------------------------------------------------
CREATE TABLE "GIS_STG"."STG_B$PIPELINE_CL_LN"
   ("G3E_ID" NUMBER(10,0) DEFAULT ON NULL "GIS"."PIPELINE_CL_LN_SEQ"."NEXTVAL" NOT NULL ENABLE,
	"G3E_FNO" NUMBER(5,0),
	"G3E_CNO" NUMBER(5,0),
	"G3E_FID" NUMBER(10,0),
	"G3E_CID" NUMBER(10,0),
	"G3E_GEOMETRY" "MDSYS"."SDO_GEOMETRY" , 
	"LTT_ID" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"LTT_STATUS" VARCHAR2(6 BYTE), 
	"LTT_DATE" DATE, 
	"LTT_TID" NUMBER);
-------------------------------------------------------------------------------------
CREATE TABLE "GIS_STG"."STG_B$PIPELINE_CL_N"
   ("G3E_ID" NUMBER(10,0) DEFAULT ON NULL "GIS"."PIPELINE_CL_N_SEQ"."NEXTVAL" NOT NULL ENABLE,
	"G3E_FNO" NUMBER(5,0),
	"G3E_CNO" NUMBER(5,0),
	"G3E_FID" NUMBER(10,0),
	"G3E_CID" NUMBER(10,0),
	"LTT_ID" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"LTT_STATUS" VARCHAR2(6 BYTE), 
	"LTT_DATE" DATE, 
	"LTT_TID" NUMBER, 
	"TPMS_ID" NUMBER(10,0), 
	"OPER_LINK" NUMBER(8,0), 
	"OPS_ID" NUMBER(10,0), 
	"P5_NUM" VARCHAR2(10 BYTE), 
	"OPER_NM" VARCHAR2(40 BYTE), 
	"SYS_NM" VARCHAR2(40 BYTE), 
	"SUBSYS_NM" VARCHAR2(40 BYTE), 
	"T4PERMIT" NUMBER(10,0), 
	"DIAMETER" NUMBER(6,2), 
	"COMMODITY1" VARCHAR2(3 BYTE), 
	"COMMODITY2" VARCHAR2(3 BYTE), 
	"COMMODITY3" VARCHAR2(3 BYTE), 
	"CMDTY_DESC" VARCHAR2(40 BYTE), 
	"INTERSTATE" VARCHAR2(1 BYTE), 
	"STATUS_CD" VARCHAR2(1 BYTE), 
	"QUALITY_CD" VARCHAR2(1 BYTE), 
	"SYSTYPE" VARCHAR2(1 BYTE), 
	"COUNTY" VARCHAR2(3 BYTE), 
	"COM_CARRIE" VARCHAR2(1 BYTE), 
	"PLINE_ID" VARCHAR2(40 BYTE), 
	"SYS_ID" NUMBER(10,0), 
	"NPMS_SYS_I" NUMBER(8,0), 
	"ALBERS_MIL" NUMBER(19,10), 
	"LENGTH" NUMBER(19,8));
-------------------------------------------------------------------------------------
CREATE TABLE "GIS_STG"."STG_B$PIPELINE_CL_T"
   ("G3E_ID" NUMBER(10,0) DEFAULT ON NULL "GIS"."PIPELINE_CL_T_SEQ"."NEXTVAL" NOT NULL ENABLE,
	"G3E_FNO" NUMBER(5,0),
	"G3E_CNO" NUMBER(5,0),
	"G3E_FID" NUMBER(10,0),
	"G3E_CID" NUMBER(10,0),
	"G3E_GEOMETRY" "SDO_GEOMETRY", 
	"G3E_ALIGNMENT" NUMBER(5,0) DEFAULT 1, 
	"LTT_ID" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"LTT_STATUS" VARCHAR2(6 BYTE), 
	"LTT_DATE" DATE, 
	"LTT_TID" NUMBER);
-------------------------------------------------------------------------------------
CREATE TABLE "GIS_STG"."STG_B$POLITICALBNDY_AR"
   ("G3E_ID" NUMBER(10,0) DEFAULT ON NULL "GIS"."POLITICALBNDY_AR_SEQ"."NEXTVAL" NOT NULL ENABLE,
	"G3E_FNO" NUMBER(5,0),
	"G3E_CNO" NUMBER(5,0),
	"G3E_FID" NUMBER(10,0),
	"G3E_CID" NUMBER(10,0),
	"G3E_GEOMETRY" "SDO_GEOMETRY", 
	"LTT_ID" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"LTT_STATUS" VARCHAR2(6 BYTE), 
	"LTT_DATE" DATE, 
	"LTT_TID" NUMBER);
-------------------------------------------------------------------------------------
CREATE TABLE "GIS_STG"."STG_B$POLITICALBNDY_N"
   ("G3E_ID" NUMBER(10,0) DEFAULT ON NULL "GIS"."POLITICALBNDY_N_SEQ"."NEXTVAL" NOT NULL ENABLE,
	"G3E_FNO" NUMBER(5,0),
	"G3E_CNO" NUMBER(5,0),
	"G3E_FID" NUMBER(10,0),
	"G3E_CID" NUMBER(10,0),
	"TYPE" VARCHAR2(10 BYTE), 
	"NAME" VARCHAR2(50 BYTE), 
	"DATE_LOADED" DATE, 
	"LTT_ID" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"LTT_STATUS" VARCHAR2(6 BYTE), 
	"LTT_DATE" DATE, 
	"LTT_TID" NUMBER);
-------------------------------------------------------------------------------------
CREATE TABLE "GIS_STG"."STG_B$POLITICALBNDY_T"
   ("G3E_ID" NUMBER(10,0) DEFAULT ON NULL "GIS"."POLITICALBNDY_T_SEQ"."NEXTVAL" NOT NULL ENABLE,
	"G3E_FNO" NUMBER(5,0),
	"G3E_CNO" NUMBER(5,0),
	"G3E_FID" NUMBER(10,0),
	"G3E_CID" NUMBER(10,0),
	"G3E_GEOMETRY" "SDO_GEOMETRY", 
	"G3E_ALIGNMENT" NUMBER(5,0) DEFAULT 1, 
	"LTT_ID" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"LTT_STATUS" VARCHAR2(6 BYTE), 
	"LTT_DATE" DATE, 
	"LTT_TID" NUMBER);
-------------------------------------------------------------------------------------
CREATE TABLE "GIS_STG"."STG_B$RAILROAD_LN"
   ("G3E_ID" NUMBER(10,0) DEFAULT ON NULL "GIS"."RAILROAD_LN_SEQ"."NEXTVAL" NOT NULL ENABLE,
	"G3E_FNO" NUMBER(5,0),
	"G3E_CNO" NUMBER(5,0),
	"G3E_FID" NUMBER(10,0),
	"G3E_CID" NUMBER(10,0),
	"G3E_GEOMETRY" "MDSYS"."SDO_GEOMETRY" , 
	"LTT_ID" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"LTT_STATUS" VARCHAR2(6 BYTE), 
	"LTT_DATE" DATE, 
	"LTT_TID" NUMBER);
-------------------------------------------------------------------------------------
CREATE TABLE "GIS_STG"."STG_B$RAILROAD_N"
   ("G3E_ID" NUMBER(10,0) DEFAULT ON NULL "GIS"."RAILROAD_N_SEQ"."NEXTVAL" NOT NULL ENABLE,
	"G3E_FNO" NUMBER(5,0),
	"G3E_CNO" NUMBER(5,0),
	"G3E_FID" NUMBER(10,0),
	"G3E_CID" NUMBER(10,0),
	"LTT_ID" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"LTT_STATUS" VARCHAR2(6 BYTE), 
	"LTT_DATE" DATE, 
	"LTT_TID" NUMBER, 
	"ID" NUMBER(20,0), 
	"NAME" VARCHAR2(80 BYTE), 
	"FEATTYP" NUMBER(10,0), 
	"F_JNCTID" NUMBER(20,0), 
	"F_JNCTTYP" NUMBER(3,0), 
	"T_JNCTID" NUMBER(20,0), 
	"T_JNCTTYP" NUMBER(3,0), 
	"METERS" NUMBER(10,3), 
	"NAMELC" VARCHAR2(80 BYTE), 
	"F_ELEV" NUMBER(3,0), 
	"T_ELEV" NUMBER(3,0), 
	"DISPCLASS" NUMBER(3,0), 
	"PARTSTRUC" NUMBER(3,0));
-------------------------------------------------------------------------------------
CREATE TABLE "GIS_STG"."STG_B$RAILROAD_T"
   ("G3E_ID" NUMBER(10,0) DEFAULT ON NULL "GIS"."RAILROAD_T_SEQ"."NEXTVAL" NOT NULL ENABLE,
	"G3E_FNO" NUMBER(5,0),
	"G3E_CNO" NUMBER(5,0),
	"G3E_FID" NUMBER(10,0),
	"G3E_CID" NUMBER(10,0),
	"G3E_GEOMETRY" "SDO_GEOMETRY", 
	"G3E_ALIGNMENT" NUMBER(5,0) DEFAULT 1, 
	"LTT_ID" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"LTT_STATUS" VARCHAR2(6 BYTE), 
	"LTT_DATE" DATE, 
	"LTT_TID" NUMBER);
-------------------------------------------------------------------------------------
CREATE TABLE "GIS_STG"."STG_B$RESTRICTED_AR"
   ("G3E_ID" NUMBER(10,0) DEFAULT ON NULL "GIS"."RESTRICTED_AR_SEQ"."NEXTVAL" NOT NULL ENABLE,
	"G3E_FNO" NUMBER(5,0),
	"G3E_CNO" NUMBER(5,0),
	"G3E_FID" NUMBER(10,0),
	"G3E_CID" NUMBER(10,0),
	"G3E_GEOMETRY" "MDSYS"."SDO_GEOMETRY" , 
	"LTT_ID" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"LTT_STATUS" VARCHAR2(6 BYTE), 
	"LTT_DATE" DATE, 
	"LTT_TID" NUMBER);
-------------------------------------------------------------------------------------
CREATE TABLE "GIS_STG"."STG_B$RESTRICTED_N"
   ("G3E_ID" NUMBER(10,0) DEFAULT ON NULL "GIS"."RESTRICTED_N_SEQ"."NEXTVAL" NOT NULL ENABLE,
	"G3E_FNO" NUMBER(5,0),
	"G3E_CNO" NUMBER(5,0),
	"G3E_FID" NUMBER(10,0),
	"G3E_CID" NUMBER(10,0),
	"NAME" VARCHAR2(30 BYTE), 
	"TYPE" VARCHAR2(30 BYTE), 
	"LTT_ID" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"LTT_STATUS" VARCHAR2(6 BYTE), 
	"LTT_DATE" DATE, 
	"LTT_TID" NUMBER, 
	"AUTH_ROLE" VARCHAR2(30 BYTE), 
	"AUTH_WR_LIST" VARCHAR2(1000 BYTE));
-------------------------------------------------------------------------------------
CREATE TABLE "GIS_STG"."STG_B$ROW_LN"
   ("G3E_ID" NUMBER(10,0) DEFAULT ON NULL "GIS"."ROW_LN_SEQ"."NEXTVAL" NOT NULL ENABLE,
	"G3E_FNO" NUMBER(5,0),
	"G3E_CNO" NUMBER(5,0),
	"G3E_FID" NUMBER(10,0),
	"G3E_CID" NUMBER(10,0),
	"G3E_GEOMETRY" "MDSYS"."SDO_GEOMETRY" , 
	"LTT_ID" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"LTT_STATUS" VARCHAR2(6 BYTE), 
	"LTT_DATE" DATE, 
	"LTT_TID" NUMBER);
-------------------------------------------------------------------------------------
CREATE TABLE "GIS_STG"."STG_B$ROW_N"
   ("G3E_ID" NUMBER(10,0) DEFAULT ON NULL "GIS"."ROW_N_SEQ"."NEXTVAL" NOT NULL ENABLE,
	"G3E_FNO" NUMBER(5,0),
	"G3E_CNO" NUMBER(5,0),
	"G3E_FID" NUMBER(10,0),
	"G3E_CID" NUMBER(10,0),
	"TYPE" VARCHAR2(10 BYTE), 
	"RIGHT_OF_WAY_WIDTH" NUMBER(4,0), 
	"LTT_ID" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"LTT_STATUS" VARCHAR2(6 BYTE), 
	"LTT_DATE" DATE, 
	"LTT_TID" NUMBER);
-------------------------------------------------------------------------------------
CREATE TABLE "GIS_STG"."STG_B$STREETNAME_CL_N"
   ("G3E_ID" NUMBER(10,0) DEFAULT ON NULL "GIS"."STREETNAME_CL_N_SEQ"."NEXTVAL" NOT NULL ENABLE,
	"G3E_FNO" NUMBER(5,0),
	"G3E_CNO" NUMBER(5,0),
	"G3E_FID" NUMBER(10,0),
	"G3E_CID" NUMBER(10,0),
	"PREFIX" VARCHAR2(10 BYTE), 
	"PRETYPE" VARCHAR2(10 BYTE), 
	"NAME" VARCHAR2(100 BYTE), 
	"TYPE" VARCHAR2(20 BYTE), 
	"SUFFIX" VARCHAR2(10 BYTE), 
	"NM_TYPE" NUMBER(3,0), 
	"SHIELD" VARCHAR2(2 BYTE), 
	"HWY_NUM" VARCHAR2(10 BYTE), 
	"FT_DIR" VARCHAR2(2 BYTE), 
	"TF_DIR" VARCHAR2(2 BYTE), 
	"LTT_ID" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"LTT_STATUS" VARCHAR2(6 BYTE), 
	"LTT_DATE" DATE, 
	"LTT_TID" NUMBER);
-------------------------------------------------------------------------------------
CREATE TABLE "GIS_STG"."STG_B$TAXDISTRICT_AR"
   ("G3E_ID" NUMBER(10,0) DEFAULT ON NULL "GIS"."TAXDISTRICT_AR_SEQ"."NEXTVAL" NOT NULL ENABLE,
	"G3E_FNO" NUMBER(5,0),
	"G3E_CNO" NUMBER(5,0),
	"G3E_FID" NUMBER(10,0),
	"G3E_CID" NUMBER(10,0),
	"G3E_GEOMETRY" "MDSYS"."SDO_GEOMETRY" , 
	"LTT_ID" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"LTT_STATUS" VARCHAR2(6 BYTE), 
	"LTT_DATE" DATE, 
	"LTT_TID" NUMBER);
-------------------------------------------------------------------------------------
CREATE TABLE "GIS_STG"."STG_B$TAXDISTRICT_N"
   ("G3E_ID" NUMBER(10,0) DEFAULT ON NULL "GIS"."TAXDISTRICT_N_SEQ"."NEXTVAL" NOT NULL ENABLE,
	"G3E_FNO" NUMBER(5,0),
	"G3E_CNO" NUMBER(5,0),
	"G3E_FID" NUMBER(10,0),
	"G3E_CID" NUMBER(10,0),
	"LTT_ID" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"LTT_STATUS" VARCHAR2(6 BYTE), 
	"LTT_DATE" DATE, 
	"LTT_TID" NUMBER, 
	"JURID" NUMBER(10,0), 
	"ENTITYID" VARCHAR2(50 BYTE), 
	"FIPSSTCO" NUMBER(10,0), 
	"JURTYPE" VARCHAR2(30 BYTE), 
	"SPCJURTYPE" VARCHAR2(30 BYTE), 
	"JURCODE" VARCHAR2(30 BYTE), 
	"JURNAME" VARCHAR2(50 BYTE), 
	"STATECODE" VARCHAR2(30 BYTE), 
	"COUNTYCODE" VARCHAR2(30 BYTE), 
	"SHEETCODE" VARCHAR2(30 BYTE), 
	"SHEETNAME" VARCHAR2(80 BYTE), 
	"PROPCLASS" VARCHAR2(30 BYTE), 
	"ASSESSID" NUMBER(10,0), 
	"COLLECTID" NUMBER(10,0), 
	"TAXYEAR" NUMBER(4,0), 
	"TAXYRNOTES" VARCHAR2(50 BYTE), 
	"JURNOTES" VARCHAR2(50 BYTE), 
	"MAPPED" NUMBER(4,0), 
	"UPDATED" DATE, 
	"GEOID" NUMBER(10,0), 
	"GEOTAXYEAR" NUMBER(4,0), 
	"GEONOTES" VARCHAR2(50 BYTE), 
	"GEOLANDBAS" VARCHAR2(30 BYTE), 
	"GEOUPDATED" DATE);
-------------------------------------------------------------------------------------
CREATE TABLE "GIS_STG"."STG_B$TAXDISTRICT_T"
   ("G3E_ID" NUMBER(10,0) DEFAULT ON NULL "GIS"."TAXDISTRICT_T_SEQ"."NEXTVAL" NOT NULL ENABLE,
	"G3E_FNO" NUMBER(5,0),
	"G3E_CNO" NUMBER(5,0),
	"G3E_FID" NUMBER(10,0),
	"G3E_CID" NUMBER(10,0),
	"G3E_GEOMETRY" "SDO_GEOMETRY", 
	"G3E_ALIGNMENT" NUMBER(5,0) DEFAULT 1, 
	"LTT_ID" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"LTT_STATUS" VARCHAR2(6 BYTE), 
	"LTT_DATE" DATE, 
	"LTT_TID" NUMBER);
-------------------------------------------------------------------------------------
CREATE TABLE "GIS_STG"."STG_B$TELECOMBNDY_AR"
   ("G3E_ID" NUMBER(10,0) DEFAULT ON NULL "GIS"."TELECOMBNDY_AR_SEQ"."NEXTVAL" NOT NULL ENABLE,
	"G3E_FNO" NUMBER(5,0),
	"G3E_CNO" NUMBER(5,0),
	"G3E_FID" NUMBER(10,0),
	"G3E_CID" NUMBER(10,0),
	"G3E_GEOMETRY" "MDSYS"."SDO_GEOMETRY" , 
	"LTT_ID" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"LTT_STATUS" VARCHAR2(6 BYTE), 
	"LTT_DATE" DATE, 
	"LTT_TID" NUMBER);
-------------------------------------------------------------------------------------
CREATE TABLE "GIS_STG"."STG_B$TELECOMBNDY_N"
   ("G3E_ID" NUMBER(10,0) DEFAULT ON NULL "GIS"."TELECOMBNDY_N_SEQ"."NEXTVAL" NOT NULL ENABLE,
	"G3E_FNO" NUMBER(5,0),
	"G3E_CNO" NUMBER(5,0),
	"G3E_FID" NUMBER(10,0),
	"G3E_CID" NUMBER(10,0),
	"RADIO_SYSTEM_C" VARCHAR2(10 BYTE), 
	"ANTENNA_HEIGHT" NUMBER(10,0), 
	"ANTENNA_LOCATION" VARCHAR2(30 BYTE), 
	"ANTENNA_TYPE" VARCHAR2(30 BYTE), 
	"COVERAGE" VARCHAR2(30 BYTE), 
	"EIRP" VARCHAR2(30 BYTE), 
	"FREQUENCY" NUMBER(10,0), 
	"SIGNAL_STRENGTH" NUMBER(10,0), 
	"LTT_ID" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"LTT_STATUS" VARCHAR2(6 BYTE), 
	"LTT_DATE" DATE, 
	"LTT_TID" NUMBER);
-------------------------------------------------------------------------------------   
CREATE TABLE "GIS_STG"."STG_B$TELECOMBNDY_T"
   ("G3E_ID" NUMBER(10,0) DEFAULT ON NULL "GIS"."TELECOMBNDY_T_SEQ"."NEXTVAL" NOT NULL ENABLE,
	"G3E_FNO" NUMBER(5,0),
	"G3E_CNO" NUMBER(5,0),
	"G3E_FID" NUMBER(10,0),
	"G3E_CID" NUMBER(10,0),
	"G3E_GEOMETRY" "SDO_GEOMETRY", 
	"G3E_ALIGNMENT" NUMBER(5,0) DEFAULT 1, 
	"LTT_ID" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"LTT_STATUS" VARCHAR2(6 BYTE), 
	"LTT_DATE" DATE, 
	"LTT_TID" NUMBER);
-------------------------------------------------------------------------------------   
CREATE TABLE "GIS_STG"."STG_B$TEXAS_SECTION_AR"
   ("G3E_ID" NUMBER(10,0) DEFAULT ON NULL "GIS"."TEXAS_SECTION_AR_SEQ"."NEXTVAL" NOT NULL ENABLE,
	"G3E_FNO" NUMBER(5,0),
	"G3E_CNO" NUMBER(5,0),
	"G3E_FID" NUMBER(10,0),
	"G3E_CID" NUMBER(10,0),
	"G3E_GEOMETRY" "MDSYS"."SDO_GEOMETRY" , 
	"LTT_ID" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"LTT_STATUS" VARCHAR2(6 BYTE), 
	"LTT_DATE" DATE, 
	"LTT_TID" NUMBER);
-------------------------------------------------------------------------------------   
CREATE TABLE "GIS_STG"."STG_B$TEXAS_SECTION_N"
   ("G3E_ID" NUMBER(10,0) DEFAULT ON NULL "GIS"."TEXAS_SECTION_N_SEQ"."NEXTVAL" NOT NULL ENABLE,
	"G3E_FNO" NUMBER(5,0),
	"G3E_CNO" NUMBER(5,0),
	"G3E_FID" NUMBER(10,0),
	"G3E_CID" NUMBER(10,0),
	"LTT_ID" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"LTT_STATUS" VARCHAR2(6 BYTE), 
	"LTT_DATE" DATE, 
	"LTT_TID" NUMBER, 
	"BAYNUM" VARCHAR2(20 BYTE), 
	"BAYID" VARCHAR2(10 BYTE), 
	"TRACTNUM" NUMBER(5,0), 
	"AREA" NUMBER(20,15), 
	"PERIMETER" NUMBER(20,15), 
	"BAYTRACT_" NUMBER(5,0), 
	"BAYTRACT_I" NUMBER(5,0), 
	"SHAPE_LENG" NUMBER(20,15), 
	"SHAPE_AREA" NUMBER(20,15));
-------------------------------------------------------------------------------------   
CREATE TABLE "GIS_STG"."STG_B$TEXAS_SECTION_T"
   ("G3E_ID" NUMBER(10,0) DEFAULT ON NULL "GIS"."TEXAS_SECTION_T_SEQ"."NEXTVAL" NOT NULL ENABLE,
	"G3E_FNO" NUMBER(5,0),
	"G3E_CNO" NUMBER(5,0),
	"G3E_FID" NUMBER(10,0),
	"G3E_CID" NUMBER(10,0),
	"G3E_GEOMETRY" "SDO_GEOMETRY", 
	"G3E_ALIGNMENT" NUMBER(5,0) DEFAULT 1, 
	"LTT_ID" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"LTT_STATUS" VARCHAR2(6 BYTE), 
	"LTT_DATE" DATE, 
	"LTT_TID" NUMBER);
-------------------------------------------------------------------------------------   
CREATE TABLE "GIS_STG"."STG_B$THIRD_PARTY_AR"
   ("G3E_ID" NUMBER(10,0) DEFAULT ON NULL "GIS"."THIRD_PARTY_AR_SEQ"."NEXTVAL" NOT NULL ENABLE,
	"G3E_FNO" NUMBER(5,0),
	"G3E_CNO" NUMBER(5,0),
	"G3E_FID" NUMBER(10,0),
	"G3E_CID" NUMBER(10,0),
	"G3E_GEOMETRY" "MDSYS"."SDO_GEOMETRY" , 
	"LTT_ID" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"LTT_STATUS" VARCHAR2(6 BYTE), 
	"LTT_DATE" DATE, 
	"LTT_TID" NUMBER);
-------------------------------------------------------------------------------------   
CREATE TABLE "GIS_STG"."STG_B$THIRD_PARTY_N"
   ("G3E_ID" NUMBER(10,0) DEFAULT ON NULL "GIS"."THIRD_PARTY_N_SEQ"."NEXTVAL" NOT NULL ENABLE,
	"G3E_FNO" NUMBER(5,0),
	"G3E_CNO" NUMBER(5,0),
	"G3E_FID" NUMBER(10,0),
	"G3E_CID" NUMBER(10,0),
	"LTT_ID" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"LTT_STATUS" VARCHAR2(6 BYTE), 
	"LTT_DATE" DATE, 
	"LTT_TID" NUMBER, 
	"AREA_NAME" VARCHAR2(30 BYTE), 
	"AREA_TYPE" VARCHAR2(80 BYTE), 
	"PROVIDER_N" VARCHAR2(80 BYTE));
-------------------------------------------------------------------------------------   
CREATE TABLE "GIS_STG"."STG_B$THIRD_PARTY_T"
   ("G3E_ID" NUMBER(10,0) DEFAULT ON NULL "GIS"."THIRD_PARTY_T_SEQ"."NEXTVAL" NOT NULL ENABLE,
   	"G3E_FNO" NUMBER(5,0),
	"G3E_CNO" NUMBER(5,0),
	"G3E_FID" NUMBER(10,0),
	"G3E_CID" NUMBER(10,0),
	"G3E_GEOMETRY" "SDO_GEOMETRY", 
	"G3E_ALIGNMENT" NUMBER(5,0) DEFAULT 1, 
	"LTT_ID" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"LTT_STATUS" VARCHAR2(6 BYTE), 
	"LTT_DATE" DATE, 
	"LTT_TID" NUMBER);
-------------------------------------------------------------------------------------   
CREATE TABLE "GIS_STG"."STG_B$TRANSIT_N"
   ("G3E_ID" NUMBER(10,0) DEFAULT ON NULL "GIS"."TRANSIT_N_SEQ"."NEXTVAL" NOT NULL ENABLE,
   	"G3E_FNO" NUMBER(5,0),
	"G3E_CNO" NUMBER(5,0),
	"G3E_FID" NUMBER(10,0),
	"G3E_CID" NUMBER(10,0),
	"LTT_ID" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"LTT_STATUS" VARCHAR2(6 BYTE), 
	"LTT_DATE" DATE, 
	"LTT_TID" NUMBER, 
	"ID" NUMBER(20,0), 
	"NAME" VARCHAR2(80 BYTE), 
	"FEATTYP" NUMBER(5,0), 
	"PACKAGE" NUMBER(5,0), 
	"SUBCAT" NUMBER(10,0), 
	"IMPORT" VARCHAR2(30 BYTE), 
	"STNAME" VARCHAR2(30 BYTE), 
	"HSNUM" VARCHAR2(10 BYTE), 
	"POSTCODE" VARCHAR2(10 BYTE), 
	"LOCNAME" VARCHAR2(30 BYTE), 
	"LANCD" VARCHAR2(30 BYTE), 
	"TELNUM" VARCHAR2(30 BYTE), 
	"TEL_TYPE" VARCHAR2(30 BYTE), 
	"FAXNUM" VARCHAR2(30 BYTE), 
	"EMAIL" VARCHAR2(30 BYTE), 
	"HTTP" VARCHAR2(80 BYTE), 
	"BRANDNAME" VARCHAR2(30 BYTE), 
	"COMPNAME" VARCHAR2(30 BYTE), 
	"CLTRPELID" NUMBER(20,0), 
	"RELPOS" NUMBER(10,3), 
	"EXTPOIID" NUMBER(20,0), 
	"ADDRPID" VARCHAR2(30 BYTE), 
	"POSACCUR" VARCHAR2(30 BYTE), 
	"GAL" VARCHAR2(30 BYTE), 
	"CONT_SRC" VARCHAR2(30 BYTE), 
	"CONT_MOD" VARCHAR2(30 BYTE));
-------------------------------------------------------------------------------------   
CREATE TABLE "GIS_STG"."STG_B$TRANSIT_S"
   ("G3E_ID" NUMBER(10,0) DEFAULT ON NULL "GIS"."TRANSIT_S_SEQ"."NEXTVAL" NOT NULL ENABLE,
   	"G3E_FNO" NUMBER(5,0),
	"G3E_CNO" NUMBER(5,0),
	"G3E_FID" NUMBER(10,0),
	"G3E_CID" NUMBER(10,0),
	"G3E_GEOMETRY" "MDSYS"."SDO_GEOMETRY" , 
	"LTT_ID" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"LTT_STATUS" VARCHAR2(6 BYTE), 
	"LTT_DATE" DATE, 
	"LTT_TID" NUMBER);
-------------------------------------------------------------------------------------   
CREATE TABLE "GIS_STG"."STG_B$TRANSIT_T"
   ("G3E_ID" NUMBER(10,0) DEFAULT ON NULL "GIS"."TRANSIT_T_SEQ"."NEXTVAL" NOT NULL ENABLE,
   	"G3E_FNO" NUMBER(5,0),
	"G3E_CNO" NUMBER(5,0),
	"G3E_FID" NUMBER(10,0),
	"G3E_CID" NUMBER(10,0),
	"G3E_GEOMETRY" "MDSYS"."SDO_GEOMETRY" , 
	"G3E_ALIGNMENT" NUMBER(5,0) DEFAULT 1, 
	"LTT_ID" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"LTT_STATUS" VARCHAR2(6 BYTE), 
	"LTT_DATE" DATE, 
	"LTT_TID" NUMBER);
-------------------------------------------------------------------------------------   
CREATE TABLE "GIS_STG"."STG_B$TXSTATE_AR"
   ("G3E_ID" NUMBER(10,0) DEFAULT ON NULL "GIS"."TXSTATE_AR_SEQ"."NEXTVAL" NOT NULL ENABLE,
   	"G3E_FNO" NUMBER(5,0),
	"G3E_CNO" NUMBER(5,0),
	"G3E_FID" NUMBER(10,0),
	"G3E_CID" NUMBER(10,0),
	"G3E_GEOMETRY" "MDSYS"."SDO_GEOMETRY" , 
	"LTT_ID" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"LTT_STATUS" VARCHAR2(6 BYTE), 
	"LTT_DATE" DATE, 
	"LTT_TID" NUMBER);
-------------------------------------------------------------------------------------   
CREATE TABLE "GIS_STG"."STG_B$TXSTATE_N"
   ("G3E_ID" NUMBER(10,0) DEFAULT ON NULL "GIS"."TXSTATE_N_SEQ"."NEXTVAL" NOT NULL ENABLE,
   	"G3E_FNO" NUMBER(5,0),
	"G3E_CNO" NUMBER(5,0),
	"G3E_FID" NUMBER(10,0),
	"G3E_CID" NUMBER(10,0),
	"LTT_ID" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"LTT_STATUS" VARCHAR2(6 BYTE), 
	"LTT_DATE" DATE, 
	"LTT_TID" NUMBER, 
	"ID" NUMBER(20,0), 
	"NAME" VARCHAR2(30 BYTE), 
	"NAMELC" VARCHAR2(10 BYTE), 
	"FEATTYP" NUMBER(5,0), 
	"FEATAREA" NUMBER(20,0), 
	"FEATPERIM" NUMBER(10,0), 
	"ORDER00" VARCHAR2(10 BYTE), 
	"ORDER01" VARCHAR2(10 BYTE));
-------------------------------------------------------------------------------------   
CREATE TABLE "GIS_STG"."STG_B$ZIPCODE_AR"
   ("G3E_ID" NUMBER(10,0) DEFAULT ON NULL "GIS"."ZIPCODE_AR_SEQ"."NEXTVAL" NOT NULL ENABLE,
   	"G3E_FNO" NUMBER(5,0),
	"G3E_CNO" NUMBER(5,0),
	"G3E_FID" NUMBER(10,0),
	"G3E_CID" NUMBER(10,0),
	"G3E_GEOMETRY" "MDSYS"."SDO_GEOMETRY" , 
	"LTT_ID" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"LTT_STATUS" VARCHAR2(6 BYTE), 
	"LTT_DATE" DATE, 
	"LTT_TID" NUMBER);
-------------------------------------------------------------------------------------   
CREATE TABLE "GIS_STG"."STG_B$ZIPCODE_N"
   ("G3E_ID" NUMBER(10,0) DEFAULT ON NULL "GIS"."ZIPCODE_N_SEQ"."NEXTVAL" NOT NULL ENABLE,
	"G3E_FNO" NUMBER(5,0),
	"G3E_CNO" NUMBER(5,0),
	"G3E_FID" NUMBER(10,0),
	"G3E_CID" NUMBER(10,0),
	"LTT_ID" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"LTT_STATUS" VARCHAR2(6 BYTE), 
	"LTT_DATE" DATE, 
	"LTT_TID" NUMBER, 
	"ID" NUMBER(20,0), 
	"FEATTYP" NUMBER(5,0), 
	"FEATAREA" NUMBER(10,0), 
	"FEATPERIM" NUMBER(10,0), 
	"POSTCODE" NUMBER(5,0));
-------------------------------------------------------------------------------------   
CREATE TABLE "GIS_STG"."STG_B$ZIPCODE_T"
   ("G3E_ID" NUMBER(10,0) DEFAULT ON NULL "GIS"."ZIPCODE_T_SEQ"."NEXTVAL" NOT NULL ENABLE,
    "G3E_FNO" NUMBER(5,0),
	"G3E_CNO" NUMBER(5,0),
	"G3E_FID" NUMBER(10,0),
	"G3E_CID" NUMBER(10,0),
	"G3E_GEOMETRY" "SDO_GEOMETRY", 
	"G3E_ALIGNMENT" NUMBER(5,0) DEFAULT 1, 
	"LTT_ID" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"LTT_STATUS" VARCHAR2(6 BYTE), 
	"LTT_DATE" DATE, 
	"LTT_TID" NUMBER);
-------------------------------------------------------------------------------------
CREATE TABLE "GIS_STG"."STG_B$LAND_AUDIT_N" 
   ("G3E_ID" NUMBER(10,0) DEFAULT ON NULL "GIS"."LAND_AUDIT_N_SEQ"."NEXTVAL" NOT NULL ENABLE, 
	"G3E_FNO" NUMBER(5,0), 
	"G3E_CNO" NUMBER(5,0), 
	"G3E_FID" NUMBER(10,0), 
	"G3E_CID" NUMBER(10,0), 
	"CREATED_BY" VARCHAR2(30 BYTE), 
	"CREATED_DATE" DATE, 
	"LAST_EDITED_BY" VARCHAR2(30 BYTE), 
	"LAST_EDITED_DATE" DATE, 
	"SOURCE" VARCHAR2(50 BYTE), 
	"STAGE" VARCHAR2(50 BYTE) DEFAULT 'Accepted', 
	"LTT_ID" NUMBER DEFAULT 0, 
	"LTT_STATUS" VARCHAR2(6 BYTE), 
	"LTT_DATE" DATE, 
	"LTT_TID" NUMBER
   );
-------------------------------------------------------------------------------------
-------------------------------CREATE TABLE GIS_STG.STG_B$HYDROLOGY_AR---------------
CREATE TABLE "GIS_STG"."STG_B$HYDROLOGY_AR" 
   ("G3E_ID" NUMBER(10,0) DEFAULT ON NULL "GIS"."HYDROLOGY_AR_SEQ"."NEXTVAL" NOT NULL ENABLE, 
	"G3E_FNO" NUMBER(5,0), 
	"G3E_CNO" NUMBER(5,0), 
	"G3E_FID" NUMBER(10,0), 
	"G3E_CID" NUMBER(10,0), 
	"G3E_GEOMETRY" "SDO_GEOMETRY", 
	"LTT_ID" NUMBER DEFAULT 0, 
	"LTT_STATUS" VARCHAR2(6 BYTE), 
	"LTT_DATE" DATE, 
	"LTT_TID" NUMBER
   );
-------------------------------------------------------------------------------------
-------------------------------CREATE TABLE GIS_STG.STG_B$HYDROLOGY_LN---------------
CREATE TABLE "GIS_STG"."STG_B$HYDROLOGY_LN" 
   ("G3E_ID" NUMBER(10,0) DEFAULT ON NULL "GIS"."HYDROLOGY_LN_SEQ"."NEXTVAL" NOT NULL ENABLE, 
	"G3E_FNO" NUMBER(5,0), 
	"G3E_CNO" NUMBER(5,0), 
	"G3E_FID" NUMBER(10,0), 
	"G3E_CID" NUMBER(10,0), 
	"G3E_GEOMETRY" "SDO_GEOMETRY", 
	"LTT_ID" NUMBER DEFAULT 0, 
	"LTT_STATUS" VARCHAR2(6 BYTE), 
	"LTT_DATE" DATE, 
	"LTT_TID" NUMBER
   );
-------------------------------------------------------------------------------------
-------------------------------CREATE TABLE GIS_STG.STG_B$HYDROLOGY_N----------------
CREATE TABLE "GIS_STG"."STG_B$HYDROLOGY_N"
   ("G3E_ID" NUMBER(10,0) DEFAULT ON NULL "GIS"."HYDROLOGY_N_SEQ"."NEXTVAL" NOT NULL ENABLE, 
	"G3E_FNO" NUMBER(5,0), 
	"G3E_CNO" NUMBER(5,0), 
	"G3E_FID" NUMBER(10,0), 
	"G3E_CID" NUMBER(10,0), 
	"LTT_ID" NUMBER DEFAULT 0, 
	"LTT_STATUS" VARCHAR2(6 BYTE), 
	"LTT_DATE" DATE, 
	"LTT_TID" NUMBER, 
	"ID" NUMBER(20,0), 
	"NAME" VARCHAR2(80 BYTE), 
	"FEATTYP" NUMBER(10,0), 
	"FEATAREA" NUMBER(10,0), 
	"FEATPERIM" NUMBER(10,0), 
	"DISPCLASS" NUMBER(20,0), 
	"NAMELC" VARCHAR2(30 BYTE), 
	"METERS" VARCHAR2(30 BYTE)
   );
-------------------------------------------------------------------------------------
-------------------------------CREATE TABLE GIS_STG.STG_B$HYDROLOGY_T----------------
CREATE TABLE "GIS_STG"."STG_B$HYDROLOGY_T" 
   ("G3E_ID" NUMBER(10,0) DEFAULT ON NULL "GIS"."HYDROLOGY_T_SEQ"."NEXTVAL" NOT NULL ENABLE, 
	"G3E_FNO" NUMBER(5,0), 
	"G3E_CNO" NUMBER(5,0), 
	"G3E_FID" NUMBER(10,0), 
	"G3E_CID" NUMBER(10,0), 
	"G3E_GEOMETRY" "SDO_GEOMETRY", 
	"G3E_ALIGNMENT" NUMBER(5,0) DEFAULT 1, 
	"LTT_ID" NUMBER DEFAULT 0, 
	"LTT_STATUS" VARCHAR2(6 BYTE), 
	"LTT_DATE" DATE,
	"LTT_TID" NUMBER
   );
-------------------------------------------------------------------------------------
-------------------------------CREATE TABLE GIS_STG.STG_B$STREETCTR_CL_T---------------
CREATE TABLE "GIS_STG"."STG_B$STREETCTR_CL_T" 
   ("G3E_ID" NUMBER(10,0) DEFAULT ON NULL "GIS"."STREETCTR_CL_T_SEQ"."NEXTVAL" NOT NULL ENABLE,
	"G3E_FNO" NUMBER(5,0) , 
	"G3E_CNO" NUMBER(5,0) , 
	"G3E_FID" NUMBER(10,0) , 
	"G3E_CID" NUMBER(10,0) , 
	"G3E_GEOMETRY" "SDO_GEOMETRY", 
	"G3E_ALIGNMENT" NUMBER(5,0) DEFAULT 1, 
	"LTT_ID" NUMBER DEFAULT 0 , 
	"LTT_STATUS" VARCHAR2(6 BYTE), 
	"LTT_DATE" DATE, 
	"LTT_TID" NUMBER
   );
-------------------------------------------------------------------------------------
-------------------------------CREATE TABLE GIS_STG.STG_B$STREETCTR_CL_N---------------
CREATE TABLE "GIS_STG"."STG_B$STREETCTR_CL_N" 
   ("G3E_ID" NUMBER(10,0) DEFAULT ON NULL "GIS"."STREETCTR_CL_N_SEQ"."NEXTVAL" NOT NULL ENABLE,
	"G3E_FNO" NUMBER(5,0) , 
	"G3E_CNO" NUMBER(5,0) , 
	"G3E_FID" NUMBER(10,0) , 
	"G3E_CID" NUMBER(10,0) , 
	"LTT_ID" NUMBER DEFAULT 0 , 
	"LTT_STATUS" VARCHAR2(6 BYTE), 
	"LTT_DATE" DATE, 
	"LTT_TID" NUMBER, 
	"ID" NUMBER(20,0), 
	"FULLNAME" VARCHAR2(80 BYTE), 
	"NAMETYP" VARCHAR2(80 BYTE), 
	"L_F_ADD" NUMBER(10,0), 
	"L_T_ADD" NUMBER(10,0), 
	"R_F_ADD" NUMBER(10,0), 
	"R_T_ADD" NUMBER(10,0), 
	"SHIELDNUM" VARCHAR2(30 BYTE), 
	"ADA" VARCHAR2(30 BYTE), 
	"BACKRD" VARCHAR2(30 BYTE), 
	"CARRIAGE" VARCHAR2(30 BYTE), 
	"CHARGE" VARCHAR2(30 BYTE), 
	"CONSTATUS" VARCHAR2(30 BYTE), 
	"DYNSPEED" VARCHAR2(30 BYTE), 
	"FEATTYP" VARCHAR2(30 BYTE), 
	"FOW" VARCHAR2(30 BYTE), 
	"FRC" VARCHAR2(30 BYTE), 
	"FREEWAY" VARCHAR2(30 BYTE), 
	"FT" VARCHAR2(30 BYTE), 
	"F_BP" VARCHAR2(30 BYTE), 
	"F_ELEV" VARCHAR2(30 BYTE), 
	"F_JNCTID" VARCHAR2(30 BYTE), 
	"F_JNCTTYP" VARCHAR2(30 BYTE), 
	"KPH" VARCHAR2(30 BYTE), 
	"LANES" VARCHAR2(30 BYTE), 
	"L_ADDRID" NUMBER(20,0), 
	"L_APNAME" VARCHAR2(30 BYTE), 
	"L_AXON" VARCHAR2(30 BYTE), 
	"L_F_F_ADD" NUMBER(20,0), 
	"L_F_I" NUMBER(20,0), 
	"L_INTM" VARCHAR2(30 BYTE), 
	"L_LAXON" VARCHAR2(30 BYTE), 
	"L_LAXONLC" VARCHAR2(30 BYTE), 
	"L_LAXORD" VARCHAR2(30 BYTE), 
	"L_ORDER00" VARCHAR2(30 BYTE), 
	"L_ORDER01" VARCHAR2(30 BYTE), 
	"L_ORDER08" VARCHAR2(30 BYTE), 
	"L_PC" NUMBER(10,0), 
	"L_PCEXT" NUMBER(10,0), 
	"L_STRUCT" NUMBER(10,0), 
	"L_T_F_ADD" NUMBER(10,0), 
	"L_T_I" NUMBER(10,0), 
	"METERS" NUMBER(10,0), 
	"MINUTES" NUMBER(10,0), 
	"NAME" VARCHAR2(30 BYTE), 
	"NAMEFORM" VARCHAR2(30 BYTE), 
	"NAMEKEY" VARCHAR2(30 BYTE), 
	"NAMELC" VARCHAR2(30 BYTE), 
	"NAMEPREFIX" VARCHAR2(30 BYTE), 
	"NAMERANK" VARCHAR2(30 BYTE), 
	"NAMESUFFIX" VARCHAR2(30 BYTE), 
	"NET2CLASS" VARCHAR2(30 BYTE), 
	"NETBCLASS" VARCHAR2(30 BYTE), 
	"NETCLASS" VARCHAR2(30 BYTE), 
	"NTHRUTRAF" VARCHAR2(30 BYTE), 
	"ONEWAY" VARCHAR2(30 BYTE), 
	"PARTSTRUC" VARCHAR2(30 BYTE), 
	"PJ" VARCHAR2(30 BYTE), 
	"POSACCUR" VARCHAR2(30 BYTE), 
	"PREDIR" VARCHAR2(30 BYTE), 
	"PRETYPE" VARCHAR2(30 BYTE), 
	"PRIVATERD" VARCHAR2(30 BYTE), 
	"PROCSTAT" VARCHAR2(30 BYTE), 
	"RAMP" VARCHAR2(30 BYTE), 
	"RDCOND" VARCHAR2(30 BYTE), 
	"RECTYP" VARCHAR2(30 BYTE), 
	"ROUGHRD" VARCHAR2(30 BYTE), 
	"RTEDIR" VARCHAR2(30 BYTE), 
	"RTEDIRVD" VARCHAR2(30 BYTE), 
	"RTETYP" VARCHAR2(30 BYTE), 
	"R_ADDRID" NUMBER(20,0), 
	"R_APNAME" VARCHAR2(30 BYTE), 
	"R_AXON" VARCHAR2(30 BYTE), 
	"R_F_F_ADD" NUMBER(10,0), 
	"R_F_I" NUMBER(10,0), 
	"R_INTM" VARCHAR2(30 BYTE), 
	"R_LAXON" VARCHAR2(30 BYTE), 
	"R_LAXONLC" VARCHAR2(30 BYTE), 
	"R_LAXORD" VARCHAR2(30 BYTE), 
	"R_ORDER00" VARCHAR2(30 BYTE), 
	"R_ORDER01" VARCHAR2(30 BYTE), 
	"R_ORDER08" VARCHAR2(30 BYTE), 
	"R_PC" VARCHAR2(30 BYTE), 
	"R_PCEXT" VARCHAR2(30 BYTE), 
	"R_STRUCT" VARCHAR2(30 BYTE), 
	"R_T_F_ADD" NUMBER(10,0), 
	"R_T_I" NUMBER(10,0), 
	"SLIPRD" VARCHAR2(30 BYTE), 
	"SOL" VARCHAR2(30 BYTE), 
	"SPEEDCAT" VARCHAR2(30 BYTE), 
	"STUBBLE" VARCHAR2(30 BYTE), 
	"SUFDIR" VARCHAR2(30 BYTE), 
	"SUFTYPE" VARCHAR2(30 BYTE), 
	"TOLLRD" VARCHAR2(30 BYTE), 
	"TRANS" VARCHAR2(30 BYTE), 
	"T_BP" VARCHAR2(30 BYTE), 
	"T_ELEV" VARCHAR2(30 BYTE), 
	"T_JNCTID" VARCHAR2(30 BYTE), 
	"T_JNCTTYP" VARCHAR2(30 BYTE)
   ) ;
-------------------------------------------------------------------------------------
-------------------------------CREATE TABLE GIS_STG.STG_B$STREETCTR_CL_LN---------------
CREATE TABLE "GIS_STG"."STG_B$STREETCTR_CL_LN"
   ("G3E_ID" NUMBER(10,0) DEFAULT ON NULL "GIS"."STREETCTR_CL_LN_SEQ"."NEXTVAL" NOT NULL ENABLE,
	"G3E_FNO" NUMBER(5,0) , 
	"G3E_CNO" NUMBER(5,0) , 
	"G3E_FID" NUMBER(10,0) , 
	"G3E_CID" NUMBER(10,0) , 
	"G3E_GEOMETRY" "MDSYS"."SDO_GEOMETRY" , 
	"LTT_ID" NUMBER DEFAULT 0 , 
	"LTT_STATUS" VARCHAR2(6 BYTE), 
	"LTT_DATE" DATE, 
	"LTT_TID" NUMBER
   );   
---------------------------------------------------------------------------------------
-------------------------------CREATE TABLE GIS_STG.STG_B$DEM_LN-----------------------
CREATE TABLE "GIS_STG"."STG_B$DEM_LN" 
   ("G3E_ID" NUMBER(10,0) DEFAULT ON NULL "GIS"."DEM_LN_SEQ"."NEXTVAL" NOT NULL ENABLE,
	"G3E_FNO" NUMBER(5,0) , 
	"G3E_CNO" NUMBER(5,0) , 
	"G3E_FID" NUMBER(10,0) , 
	"G3E_CID" NUMBER(10,0) , 
	"G3E_GEOMETRY" "SDO_GEOMETRY" , 
	"LTT_ID" NUMBER DEFAULT 0, 
	"LTT_STATUS" VARCHAR2(6 BYTE), 
	"LTT_DATE" DATE, 
	"LTT_TID" NUMBER);
---------------------------------------------------------------------------------------
-------------------------------CREATE TABLE GIS_STG.STG_B$DEM_N------------------------
CREATE TABLE "GIS_STG"."STG_B$DEM_N" 
   ("G3E_ID" NUMBER(10,0) DEFAULT ON NULL "GIS"."DEM_N_SEQ"."NEXTVAL" NOT NULL ENABLE,
	"G3E_FNO" NUMBER(5,0) , 
	"G3E_CNO" NUMBER(5,0) , 
	"G3E_FID" NUMBER(10,0) , 
	"G3E_CID" NUMBER(10,0) , 
	"LTT_ID" NUMBER DEFAULT 0, 
	"LTT_STATUS" VARCHAR2(6 BYTE), 
	"LTT_DATE" DATE, 
	"LTT_TID" NUMBER, 
	"DATA_SECUR" NUMBER(10,0), 
	"CONTOURUNI" NUMBER(10,0), 
	"CONTOURINT" NUMBER(10,0), 
	"DISTRIBUTI" VARCHAR2(10 BYTE), 
	"SOURCE_DAT" VARCHAR2(100 BYTE), 
	"CONTOURELE" NUMBER(10,0), 
	"SOURCE_ORI" VARCHAR2(150 BYTE), 
	"LOADDATE" DATE, 
	"PERMANENT" VARCHAR2(100 BYTE), 
	"SOURCE_FEA" VARCHAR2(50 BYTE), 
	"SOURCE_D_1" VARCHAR2(120 BYTE), 
	"FCODE" VARCHAR2(10 BYTE), 
	"SHAPE_LENG" NUMBER(20,11));   
-------------------------------------------------------------------------------------
------------------Grants to 'GIS_FME_STT' User on the stage tables-------------------
-------------------------------------------------------------------------------------
grant select, insert, update, delete on GIS_STG.STG_B$AIRPORT_AR to "GIS_FME_STT";
grant select, insert, update, delete on GIS_STG.STG_B$AIRPORT_N to "GIS_FME_STT";
grant select, insert, update, delete on GIS_STG.STG_B$AIRPORT_T to "GIS_FME_STT";
grant select, insert, update, delete on GIS_STG.STG_B$BUILDING_CL_AR to "GIS_FME_STT";
grant select, insert, update, delete on GIS_STG.STG_B$BUILDING_CL_N to "GIS_FME_STT";
grant select, insert, update, delete on GIS_STG.STG_B$BUILDING_CL_T to "GIS_FME_STT";
grant select, insert, update, delete on GIS_STG.STG_B$CENSUS_BNDY_AR to "GIS_FME_STT";
grant select, insert, update, delete on GIS_STG.STG_B$CENSUS_BNDY_N to "GIS_FME_STT";
grant select, insert, update, delete on GIS_STG.STG_B$CENSUS_BNDY_T to "GIS_FME_STT";
grant select, insert, update, delete on GIS_STG.STG_B$CERT_BNDY_AR to "GIS_FME_STT";
grant select, insert, update, delete on GIS_STG.STG_B$CERT_BNDY_N to "GIS_FME_STT";
grant select, insert, update, delete on GIS_STG.STG_B$COUNTY_AR to "GIS_FME_STT";
grant select, insert, update, delete on GIS_STG.STG_B$COUNTY_N to "GIS_FME_STT";
grant select, insert, update, delete on GIS_STG.STG_B$COUNTY_T to "GIS_FME_STT";
grant select, insert, update, delete on GIS_STG.STG_B$HYDROLOGY_AR to "GIS_FME_STT";
grant select, insert, update, delete on GIS_STG.STG_B$HYDROLOGY_LN to "GIS_FME_STT";
grant select, insert, update, delete on GIS_STG.STG_B$HYDROLOGY_N to "GIS_FME_STT";
grant select, insert, update, delete on GIS_STG.STG_B$HYDROLOGY_T to "GIS_FME_STT";
grant select, insert, update, delete on GIS_STG.STG_B$HYPERLINK_N to "GIS_FME_STT";
grant select, insert, update, delete on GIS_STG.STG_B$INSTITUTION_N to "GIS_FME_STT";
grant select, insert, update, delete on GIS_STG.STG_B$INSTITUTION_S to "GIS_FME_STT";
grant select, insert, update, delete on GIS_STG.STG_B$INSTITUTION_T to "GIS_FME_STT";
grant select, insert, update, delete on GIS_STG.STG_B$LANDMARK_AR to "GIS_FME_STT";
grant select, insert, update, delete on GIS_STG.STG_B$LANDMARK_N to "GIS_FME_STT";
grant select, insert, update, delete on GIS_STG.STG_B$LANDMARK_T to "GIS_FME_STT";
grant select, insert, update, delete on GIS_STG.STG_B$LAND_AUDIT_N to "GIS_FME_STT";
grant select, insert, update, delete on GIS_STG.STG_B$MUNICIPALITY_AR to "GIS_FME_STT";
grant select, insert, update, delete on GIS_STG.STG_B$MUNICIPALITY_N to "GIS_FME_STT";
grant select, insert, update, delete on GIS_STG.STG_B$OPERBNDY_AR to "GIS_FME_STT";
grant select, insert, update, delete on GIS_STG.STG_B$OPERBNDY_N to "GIS_FME_STT";
grant select, insert, update, delete on GIS_STG.STG_B$OPERBNDY_T to "GIS_FME_STT";
grant select, insert, update, delete on GIS_STG.STG_B$PARCEL_CL_AR to "GIS_FME_STT";
grant select, insert, update, delete on GIS_STG.STG_B$PARCEL_CL_N to "GIS_FME_STT";
grant select, insert, update, delete on GIS_STG.STG_B$PARCEL_CL_S to "GIS_FME_STT";
grant select, insert, update, delete on GIS_STG.STG_B$PARCEL_CL_T to "GIS_FME_STT";
grant select, insert, update, delete on GIS_STG.STG_B$PIPELINE_CL_LN to "GIS_FME_STT";
grant select, insert, update, delete on GIS_STG.STG_B$PIPELINE_CL_N to "GIS_FME_STT";
grant select, insert, update, delete on GIS_STG.STG_B$PIPELINE_CL_T to "GIS_FME_STT";
grant select, insert, update, delete on GIS_STG.STG_B$POLITICALBNDY_AR to "GIS_FME_STT";
grant select, insert, update, delete on GIS_STG.STG_B$POLITICALBNDY_N to "GIS_FME_STT";
grant select, insert, update, delete on GIS_STG.STG_B$POLITICALBNDY_T to "GIS_FME_STT";
grant select, insert, update, delete on GIS_STG.STG_B$RAILROAD_LN to "GIS_FME_STT";
grant select, insert, update, delete on GIS_STG.STG_B$RAILROAD_N to "GIS_FME_STT";
grant select, insert, update, delete on GIS_STG.STG_B$RAILROAD_T to "GIS_FME_STT";
grant select, insert, update, delete on GIS_STG.STG_B$RESTRICTED_AR to "GIS_FME_STT";
grant select, insert, update, delete on GIS_STG.STG_B$RESTRICTED_N to "GIS_FME_STT";
grant select, insert, update, delete on GIS_STG.STG_B$ROW_LN to "GIS_FME_STT";
grant select, insert, update, delete on GIS_STG.STG_B$ROW_N to "GIS_FME_STT";
grant select, insert, update, delete on GIS_STG.STG_B$STREETCTR_CL_LN to "GIS_FME_STT";
grant select, insert, update, delete on GIS_STG.STG_B$STREETCTR_CL_N to "GIS_FME_STT";
grant select, insert, update, delete on GIS_STG.STG_B$STREETCTR_CL_T to "GIS_FME_STT";
grant select, insert, update, delete on GIS_STG.STG_B$STREETNAME_CL_N to "GIS_FME_STT";
grant select, insert, update, delete on GIS_STG.STG_B$TAXDISTRICT_AR to "GIS_FME_STT";
grant select, insert, update, delete on GIS_STG.STG_B$TAXDISTRICT_N to "GIS_FME_STT";
grant select, insert, update, delete on GIS_STG.STG_B$TAXDISTRICT_T to "GIS_FME_STT";
grant select, insert, update, delete on GIS_STG.STG_B$TELECOMBNDY_AR to "GIS_FME_STT";
grant select, insert, update, delete on GIS_STG.STG_B$TELECOMBNDY_N to "GIS_FME_STT";
grant select, insert, update, delete on GIS_STG.STG_B$TELECOMBNDY_T to "GIS_FME_STT";
grant select, insert, update, delete on GIS_STG.STG_B$TEXAS_SECTION_AR to "GIS_FME_STT";
grant select, insert, update, delete on GIS_STG.STG_B$TEXAS_SECTION_N to "GIS_FME_STT";
grant select, insert, update, delete on GIS_STG.STG_B$TEXAS_SECTION_T to "GIS_FME_STT";
grant select, insert, update, delete on GIS_STG.STG_B$THIRD_PARTY_AR to "GIS_FME_STT";
grant select, insert, update, delete on GIS_STG.STG_B$THIRD_PARTY_N to "GIS_FME_STT";
grant select, insert, update, delete on GIS_STG.STG_B$THIRD_PARTY_T to "GIS_FME_STT";
grant select, insert, update, delete on GIS_STG.STG_B$TRANSIT_N to "GIS_FME_STT";
grant select, insert, update, delete on GIS_STG.STG_B$TRANSIT_S to "GIS_FME_STT";
grant select, insert, update, delete on GIS_STG.STG_B$TRANSIT_T to "GIS_FME_STT";
grant select, insert, update, delete on GIS_STG.STG_B$TXSTATE_AR to "GIS_FME_STT";
grant select, insert, update, delete on GIS_STG.STG_B$TXSTATE_N to "GIS_FME_STT";
grant select, insert, update, delete on GIS_STG.STG_B$ZIPCODE_AR to "GIS_FME_STT";
grant select, insert, update, delete on GIS_STG.STG_B$ZIPCODE_N to "GIS_FME_STT";
grant select, insert, update, delete on GIS_STG.STG_B$ZIPCODE_T to "GIS_FME_STT";
grant select, insert, update, delete on GIS_STG.STG_B$DEM_LN to "GIS_FME_STT";
grant select, insert, update, delete on GIS_STG.STG_B$DEM_N to "GIS_FME_STT";