DROP PUBLIC SYNONYM WRVIEW_CU;
CREATE OR REPLACE VIEW GIS_ONC.WRVIEW_CU
AS
	SELECT wp.WR_NBR AS WR_NBR,
				 wp.WP_NBR AS WP_NBR,
				 cu.WM_SEQ AS CU_SEQ_NBR,
				 cu.CU_C AS CU_C,
				 cu.MACRO_CU_C AS MACRO_CU_C,
				 cu.ACTIVITY_C AS ACTIVITY_C,
				 DECODE(cu.LENGTH_FLAG, 'L', cu.QTY_LENGTH_Q, 1) AS QTY_LENGTH_Q,
				 cu.VINTAGE_YR AS VINTAGE_YR,
				 'C' AS LABOR_CLASS_C,
				 cu.CIAC_C AS CIAC_C
		FROM WORKPOINT_N wp
				 JOIN WORKPOINT_CU_N cu
					 ON wp.G3E_FID = cu.G3E_FID
				 JOIN (SELECT ROWNUM AS NUM
								 FROM DUAL
							 CONNECT BY ROWNUM <= 100) n
					 ON DECODE(cu.LENGTH_FLAG, 'L', 1, cu.QTY_LENGTH_Q) >= n.NUM;
CREATE PUBLIC SYNONYM WRVIEW_CU FOR GIS_ONC.WRVIEW_CU;