SET ECHO ON
SET LINESIZE 1000
SET PAGESIZE 300
SET TRIMSPOOL ON
SPOOL ACTIVITY_CODE_UPDATE.LOG

ALTER TABLE B$COMP_UNIT_N DISABLE ALL TRIGGERS;

UPDATE B$COMP_UNIT_N CU
SET CU.ACTIVITY_C = NULL
  WHERE CU.ACTIVITY_C = 'C'
    AND CU.LTT_ID     = 0
    AND EXISTS
    (SELECT   1
      FROM B$COMMON_N C
      WHERE CU.G3E_FID        = C.G3E_FID
        AND (C.FEATURE_STATE_C = 'CLS' OR C.FEATURE_STATE_C = 'CLOSED')
        AND C.LTT_ID          = 0
    ) ;
    
COMMIT;

ALTER TABLE B$COMP_UNIT_N ENABLE ALL TRIGGERS;



SPOOL OFF;