'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class NewPlotWindow
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Intergraph.GTechnology.GTPlot.NewPlotWindow", GetType(NewPlotWindow).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Active Map Window Scale.
        '''</summary>
        Friend Shared ReadOnly Property ActiveMapWindowScale() As String
            Get
                Return ResourceManager.GetString("ActiveMapWindowScale", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Selected to Insert Active Map Window but a Map Window is not active..
        '''</summary>
        Friend Shared ReadOnly Property cmdCreatePlotWindows_Click_MapWindowNotActive() As String
            Get
                Return ResourceManager.GetString("cmdCreatePlotWindows_Click_MapWindowNotActive", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The named plot {0}  already exists.  Please provide a different {1}..
        '''</summary>
        Friend Shared ReadOnly Property cmdCreatePlotWindows_Click_NamedPlotAlreadyExists() As String
            Get
                Return ResourceManager.GetString("cmdCreatePlotWindows_Click_NamedPlotAlreadyExists", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Named Plot Already Exists.
        '''</summary>
        Friend Shared ReadOnly Property cmdCreatePlotWindows_Click_NamedPlotAlreadyExistsTitle() As String
            Get
                Return ResourceManager.GetString("cmdCreatePlotWindows_Click_NamedPlotAlreadyExistsTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please provide a {0}..
        '''</summary>
        Friend Shared ReadOnly Property cmdCreatePlotWindows_Click_PleaseProvidePlotName() As String
            Get
                Return ResourceManager.GetString("cmdCreatePlotWindows_Click_PleaseProvidePlotName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Plot Name.
        '''</summary>
        Friend Shared ReadOnly Property cmdCreatePlotWindows_Click_PlotNameTitle() As String
            Get
                Return ResourceManager.GetString("cmdCreatePlotWindows_Click_PlotNameTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Map Background White.
        '''</summary>
        Friend Shared ReadOnly Property DataGridViewAttributes1_ForceMapBackgroundToWhite() As String
            Get
                Return ResourceManager.GetString("DataGridViewAttributes1_ForceMapBackgroundToWhite", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Legend.
        '''</summary>
        Friend Shared ReadOnly Property DataGridViewAttributes1_Legend() As String
            Get
                Return ResourceManager.GetString("DataGridViewAttributes1_Legend", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Paper Orientation.
        '''</summary>
        Friend Shared ReadOnly Property DataGridViewAttributes1_PaperOrientation() As String
            Get
                Return ResourceManager.GetString("DataGridViewAttributes1_PaperOrientation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Paper Size.
        '''</summary>
        Friend Shared ReadOnly Property DataGridViewAttributes1_PaperSize() As String
            Get
                Return ResourceManager.GetString("DataGridViewAttributes1_PaperSize", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Type.
        '''</summary>
        Friend Shared ReadOnly Property DataGridViewAttributes1_Type() As String
            Get
                Return ResourceManager.GetString("DataGridViewAttributes1_Type", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fit Work Plan Boundary.
        '''</summary>
        Friend Shared ReadOnly Property FitWorkPlanBoundary() As String
            Get
                Return ResourceManager.GetString("FitWorkPlanBoundary", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Queries.
        '''</summary>
        Friend Shared ReadOnly Property InsertMapFrames_KeyMapAppendQueryGroup() As String
            Get
                Return ResourceManager.GetString("InsertMapFrames_KeyMapAppendQueryGroup", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Plot Boundary.
        '''</summary>
        Friend Shared ReadOnly Property InsertMapFrames_KeyMapAppendQueryName() As String
            Get
                Return ResourceManager.GetString("InsertMapFrames_KeyMapAppendQueryName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  - Inserting: {0}.
        '''</summary>
        Friend Shared ReadOnly Property InsertMapFrames_SetStatusBarText_Inserting() As String
            Get
                Return ResourceManager.GetString("InsertMapFrames_SetStatusBarText_Inserting", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  - Inserting: {0}: Highlight Plot Boundary..
        '''</summary>
        Friend Shared ReadOnly Property InsertMapFrames_SetStatusBarText_Inserting_HighlightPlotBoundary() As String
            Get
                Return ResourceManager.GetString("InsertMapFrames_SetStatusBarText_Inserting_HighlightPlotBoundary", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to - Inserting: {0}: Formations..
        '''</summary>
        Friend Shared ReadOnly Property InsertMapFrames_SetStatusBarText_Inserting_InsertingFormations() As String
            Get
                Return ResourceManager.GetString("InsertMapFrames_SetStatusBarText_Inserting_InsertingFormations", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  - Inserting: {0}: Load Legend..
        '''</summary>
        Friend Shared ReadOnly Property InsertMapFrames_SetStatusBarText_Inserting_LoadLegend() As String
            Get
                Return ResourceManager.GetString("InsertMapFrames_SetStatusBarText_Inserting_LoadLegend", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  - Inserting: {0}: Rotating Map View..
        '''</summary>
        Friend Shared ReadOnly Property InsertMapFrames_SetStatusBarText_Inserting_RotateMapView() As String
            Get
                Return ResourceManager.GetString("InsertMapFrames_SetStatusBarText_Inserting_RotateMapView", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  - Inserting: {0}: Window Plot Boundary..
        '''</summary>
        Friend Shared ReadOnly Property InsertMapFrames_SetStatusBarText_Inserting_WindowPlotBoundary() As String
            Get
                Return ResourceManager.GetString("InsertMapFrames_SetStatusBarText_Inserting_WindowPlotBoundary", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  - Inserting: {0}-{1}.
        '''</summary>
        Friend Shared ReadOnly Property InsertObjects_SetStatusBarText_Inserting() As String
            Get
                Return ResourceManager.GetString("InsertObjects_SetStatusBarText_Inserting", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;Active Job not set&gt;.
        '''</summary>
        Friend Shared ReadOnly Property Load_SetStatusBarText_ActiveJobNotSet() As String
            Get
                Return ResourceManager.GetString("Load_SetStatusBarText_ActiveJobNotSet", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Getting Active Job&apos;s Owner.
        '''</summary>
        Friend Shared ReadOnly Property Load_SetStatusBarText_GetActiveJobOwner() As String
            Get
                Return ResourceManager.GetString("Load_SetStatusBarText_GetActiveJobOwner", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Getting active session information.
        '''</summary>
        Friend Shared ReadOnly Property Load_SetStatusBarText_GetActiveSessionInfo() As String
            Get
                Return ResourceManager.GetString("Load_SetStatusBarText_GetActiveSessionInfo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Launching {0}.
        '''</summary>
        Friend Shared ReadOnly Property Load_SetStatusBarText_Launching() As String
            Get
                Return ResourceManager.GetString("Load_SetStatusBarText_Launching", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Loading User Defined Plot defaults.
        '''</summary>
        Friend Shared ReadOnly Property Load_SetStatusBarText_LoadingUserDefinedPlotDefaults() As String
            Get
                Return ResourceManager.GetString("Load_SetStatusBarText_LoadingUserDefinedPlotDefaults", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;not set&gt;.
        '''</summary>
        Friend Shared ReadOnly Property Load_SetStatusBarText_NotSet() As String
            Get
                Return ResourceManager.GetString("Load_SetStatusBarText_NotSet", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Populating user picklist with users that have plot boundaries placed.
        '''</summary>
        Friend Shared ReadOnly Property Load_SetStatusBarText_PopulateUserPicklist() As String
            Get
                Return ResourceManager.GetString("Load_SetStatusBarText_PopulateUserPicklist", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Populating user&apos;s jobs having plot boundaries.
        '''</summary>
        Friend Shared ReadOnly Property Load_SetStatusBarText_PopulateUsersJobs() As String
            Get
                Return ResourceManager.GetString("Load_SetStatusBarText_PopulateUsersJobs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Updating button states.
        '''</summary>
        Friend Shared ReadOnly Property Load_SetStatusBarText_UpdateButtonStates() As String
            Get
                Return ResourceManager.GetString("Load_SetStatusBarText_UpdateButtonStates", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The active job does not have its {0} defined..
        '''</summary>
        Friend Shared ReadOnly Property Load_SetStatusBarText_UserNotDefined() As String
            Get
                Return ResourceManager.GetString("Load_SetStatusBarText_UserNotDefined", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Updating available plot boundaries.
        '''</summary>
        Friend Shared ReadOnly Property SetStatusBarText_UpdateAvailablePlotBoundaries() As String
            Get
                Return ResourceManager.GetString("SetStatusBarText_UpdateAvailablePlotBoundaries", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Adding &quot;{0}&quot;.
        '''</summary>
        Friend Shared ReadOnly Property SetStatusBarText_UpdateAvailablePlotBoundaries_Adding() As String
            Get
                Return ResourceManager.GetString("SetStatusBarText_UpdateAvailablePlotBoundaries_Adding", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Locating formations.
        '''</summary>
        Friend Shared ReadOnly Property SetStatusBarText_UpdateAvailablePlotBoundaries_LocatingFormations() As String
            Get
                Return ResourceManager.GetString("SetStatusBarText_UpdateAvailablePlotBoundaries_LocatingFormations", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Named plot already exists! Rename or Delete existing named plot to re-create..
        '''</summary>
        Friend Shared ReadOnly Property UpdateAvailablePlotBoundaries_oTreeNode_ToolTipText() As String
            Get
                Return ResourceManager.GetString("UpdateAvailablePlotBoundaries_oTreeNode_ToolTipText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Auto Insert Formations.
        '''</summary>
        Friend Shared ReadOnly Property UpdatePlotBoundaryInfo_AutoInsertFormations() As String
            Get
                Return ResourceManager.GetString("UpdatePlotBoundaryInfo_AutoInsertFormations", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fit Boundary.
        '''</summary>
        Friend Shared ReadOnly Property UpdatePlotBoundaryInfo_FitBoundary() As String
            Get
                Return ResourceManager.GetString("UpdatePlotBoundaryInfo_FitBoundary", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Map Background White.
        '''</summary>
        Friend Shared ReadOnly Property UpdatePlotBoundaryInfo_ForceMapBackgroundToWhite() As String
            Get
                Return ResourceManager.GetString("UpdatePlotBoundaryInfo_ForceMapBackgroundToWhite", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Formations.
        '''</summary>
        Friend Shared ReadOnly Property UpdatePlotBoundaryInfo_Formations() As String
            Get
                Return ResourceManager.GetString("UpdatePlotBoundaryInfo_Formations", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Legend.
        '''</summary>
        Friend Shared ReadOnly Property UpdatePlotBoundaryInfo_Legend() As String
            Get
                Return ResourceManager.GetString("UpdatePlotBoundaryInfo_Legend", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Legend Overrides.
        '''</summary>
        Friend Shared ReadOnly Property UpdatePlotBoundaryInfo_LegendOverrides() As String
            Get
                Return ResourceManager.GetString("UpdatePlotBoundaryInfo_LegendOverrides", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Map Frame.
        '''</summary>
        Friend Shared ReadOnly Property UpdatePlotBoundaryInfo_MapFrame() As String
            Get
                Return ResourceManager.GetString("UpdatePlotBoundaryInfo_MapFrame", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Map Scale.
        '''</summary>
        Friend Shared ReadOnly Property UpdatePlotBoundaryInfo_MapScale() As String
            Get
                Return ResourceManager.GetString("UpdatePlotBoundaryInfo_MapScale", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Name.
        '''</summary>
        Friend Shared ReadOnly Property UpdatePlotBoundaryInfo_Name() As String
            Get
                Return ResourceManager.GetString("UpdatePlotBoundaryInfo_Name", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Paper Orientation.
        '''</summary>
        Friend Shared ReadOnly Property UpdatePlotBoundaryInfo_PaperOrientation() As String
            Get
                Return ResourceManager.GetString("UpdatePlotBoundaryInfo_PaperOrientation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Paper Size.
        '''</summary>
        Friend Shared ReadOnly Property UpdatePlotBoundaryInfo_PaperSize() As String
            Get
                Return ResourceManager.GetString("UpdatePlotBoundaryInfo_PaperSize", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Plot Boundary Info.
        '''</summary>
        Friend Shared ReadOnly Property UpdatePlotBoundaryInfo_PlotBoundaryInfo() As String
            Get
                Return ResourceManager.GetString("UpdatePlotBoundaryInfo_PlotBoundaryInfo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Style Substitutions.
        '''</summary>
        Friend Shared ReadOnly Property UpdatePlotBoundaryInfo_StyleSubstitutions() As String
            Get
                Return ResourceManager.GetString("UpdatePlotBoundaryInfo_StyleSubstitutions", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Type.
        '''</summary>
        Friend Shared ReadOnly Property UpdatePlotBoundaryInfo_Type() As String
            Get
                Return ResourceManager.GetString("UpdatePlotBoundaryInfo_Type", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
