SET ECHO ON
SET LINESIZE 1000
SET PAGESIZE 300
SET TRIMSPOOL ON
SET SERVEROUTPUT OFF
SPOOL OGG_LATLONG_STG_TEMP.LOG


CREATE TABLE GIS.OGG_LATLONG_STG_TEMP
    (
    "G3E_FNO" NUMBER (5,0) NOT NULL ENABLE
    ,"G3E_CNO" NUMBER (5,0) NOT NULL ENABLE
    ,"G3E_FID" NUMBER (10,0) NOT NULL ENABLE
    ,"G3E_GEOMETRY" "MDSYS"."SDO_GEOMETRY"
    ,"LTT_ID"     NUMBER DEFAULT 0 NOT NULL ENABLE
    ,"LTT_TID"    NUMBER
    ,OGGX      NUMBER 
    ,OGGY       NUMBER 
    ,"POINT_GEOMETRY" "MDSYS"."SDO_GEOMETRY"
    ,LAT     NUMBER 
    ,LNG    NUMBER   
    ) ;

CREATE INDEX GIS.IDX_OGG_LATLONG_TEMP_FNO ON GIS.OGG_LATLONG_STG_TEMP (G3E_FNO);
CREATE INDEX GIS.IDX_OGG_LATLONG_TEMP_FID ON GIS.OGG_LATLONG_STG_TEMP (G3E_FID);
CREATE INDEX GIS.IDX_OGG_LATLONG_TEMP_LTTID ON GIS.OGG_LATLONG_STG_TEMP (LTT_ID);