SET ECHO ON
SET LINESIZE 1000
SET PAGESIZE 300
SET TRIMSPOOL ON
SET SERVEROUTPUT OFF
SPOOL OGG_LATLONG_COMMON_UPDATE.LOG 

ALTER TABLE GIS.B$COMMON_N DISABLE ALL TRIGGERS; 

UPDATE GIS.B$COMMON_N COMM
  SET
    (
      COMM.OGGX_H
    ,COMM.OGGY_H
    ,COMM.LATITUDE
    ,COMM.LONGITUDE
    )
    =
    (SELECT   TRUNC (OGGX) OGGX_H
      ,TRUNC (OGGY) OGGY_H
      ,TRUNC (LAT,2) LAT
      ,TRUNC (LNG,2) LNG
      FROM GIS.OGG_LATLONG_STG_TEMP GEO
      WHERE 1           = 1
        AND GEO.G3E_FID = COMM.G3E_FID
        AND GEO.G3E_FNO = COMM.G3E_FNO
        AND GEO.LTT_ID  = COMM.LTT_ID
    )
  WHERE 1 = 1
    AND EXISTS
    (SELECT   1
      FROM GIS.OGG_LATLONG_STG_TEMP GEO
      WHERE 1           = 1
        AND GEO.G3E_FID = COMM.G3E_FID
        AND GEO.G3E_FNO = COMM.G3E_FNO
        AND GEO.LTT_ID  = COMM.LTT_ID
    )
    AND COMM.LTT_ID  = 0
    AND COMM.G3E_CID = 1;
COMMIT;

ALTER TABLE GIS.B$COMMON_N ENABLE ALL TRIGGERS;


SPOOL OFF;
