set echo on
set linesize 1000
set pagesize 300
set trimspool on
SET SERVEROUTPUT OFF
SPOOL OGG_LATLONG_CLEANUP.LOG

DROP INDEX GIS.IDX_OGG_LATLONG_TEMP_FNO;
DROP INDEX GIS.IDX_OGG_LATLONG_TEMP_FID;
DROP INDEX GIS.IDX_OGG_LATLONG_TEMP_LTTID;


DROP TABLE GIS.OGG_LATLONG_STG_TEMP;


spool off;