CREATE OR REPLACE FORCE EDITIONABLE VIEW "GIS_ONC"."DEIS_TRANSFORMER_PHASE_VW" ("G3E_FNO","G3E_CNO","G3E_FID","G3E_CID","COMPANY_ID","PHASE_C","CHANGE_OPERATION","CHANGE_DATE")
AS
WITH XFMR AS
		(SELECT  T.G3E_FNO
			,T.G3E_CNO
			,T.G3E_FID
			,T.G3E_CID
			,T.COMPANY_ID
			,T.PHASE_C
			,'CREATE' CHANGE_OPERATION
			,TO_DATE('01/01/2000','dd/MM/yyyy') CHANGE_DATE
			FROM AUTO_XFMR_UNIT_N T
			WHERE 1 = 1
				AND COALESCE(T.COMPANY_ID,'*') <> '*'
		UNION ALL
		SELECT  T.G3E_FNO
			,T.G3E_CNO
			,T.G3E_FID
			,T.G3E_CID
			,T.COMPANY_ID
			,T.PHASE_C
			,'CREATE' CHANGE_OPERATION
			,TO_DATE('01/01/2000','dd/MM/yyyy') CHANGE_DATE
			FROM XFMR_OH_UNIT_N T
			WHERE 1 = 1
				AND COALESCE(T.COMPANY_ID,'*') <> '*'
		UNION ALL
		SELECT  T.G3E_FNO
			,T.G3E_CNO
			,T.G3E_FID
			,T.G3E_CID
			,T.COMPANY_ID
			,C1.PHASE_ALPHA PHASE_C
			,'CREATE' CHANGE_OPERATION
			,TO_DATE('01/01/2000','dd/MM/yyyy') CHANGE_DATE
			FROM XFMR_UG_UNIT_N T
			INNER JOIN CONNECTIVITY_N C1 ON T.G3E_FID = C1.G3E_FID AND T.G3E_CID = C1.G3E_CID
			WHERE 1 = 1
				AND COALESCE(T.COMPANY_ID,'*') <> '*'
		)
	,HIST AS
		( SELECT DISTINCT G3E_FNO
			,G3E_FID
			,G3E_CNO
			,AH.G3E_CID
			,FIRST_VALUE(AH.CHANGE_OPERATION) OVER (PARTITION BY G3E_FNO,G3E_FID,AH.G3E_CID ORDER BY CHANGE_DATE DESC) CHANGE_OPERATION
			,FIRST_VALUE(AH.CHANGE_DATE) OVER (PARTITION BY G3E_FNO,G3E_FID,AH.G3E_CID ORDER BY CHANGE_DATE DESC) CHANGE_DATE
				--,MAX(CHANGE_DATE) MAX_CHANGE_DATE
			FROM ASSET_HISTORY AH
			WHERE
				(
					G3E_FNO = 34
					AND G3E_CNO = 3402
				)
				OR
				(
					G3E_FNO = 59
					AND G3E_CNO = 5902
				)
				OR
				(
					G3E_FNO = 60
					AND G3E_CNO = 6002 --IN ( 6002,11)
				)
		)
	SELECT  COALESCE(H.G3E_FNO,T.G3E_FNO) G3E_FNO
		,COALESCE(H.G3E_CNO,T.G3E_CNO) G3E_CNO
		,COALESCE(H.G3E_FID,T.G3E_FID) G3E_FID
		,COALESCE(H.G3E_CID,T.G3E_CID) G3E_CID
		,T.COMPANY_ID COMPANY_ID
		,T.PHASE_C PHASE_C
		,COALESCE(H.CHANGE_OPERATION,T.CHANGE_OPERATION) CHANGE_OPERATION
		,COALESCE(H.CHANGE_DATE,T.CHANGE_DATE) CHANGE_DATE
		FROM XFMR T
		FULL OUTER JOIN HIST H ON T.G3E_FNO = H.G3E_FNO AND T.G3E_CNO = H.G3E_CNO AND T.G3E_FID = H.G3E_FID AND T.G3E_CID = H.G3E_CID
		WHERE
			(
				T.G3E_FID IS NOT NULL
				OR H.CHANGE_OPERATION = 'DELETE'
			);

GRANT SELECT ON GIS.ASSET_HISTORY TO GIS_ONC WITH GRANT OPTION;
GRANT SELECT ON GIS.G3E_OWNERSHIP TO GIS_ONC WITH GRANT OPTION;
GRANT SELECT ON GIS_ONC.DEIS_STRUCTURES_VW TO GIS_INFA;
GRANT SELECT ON GIS_ONC.DEIS_TRANSFORMER_PHASE_VW TO GIS_INFA;
/