CREATE OR REPLACE TRIGGER GIS_STG.BIU_STG_VCHR_CONT_TYPE_TBL_TR 
BEFORE UPDATE ON GIS_STG.STG_VOUCHER_CONTRIBUTION_TYPE

FOR EACH ROW 
BEGIN 
  IF UPDATING THEN
   
	SELECT SYSDATE INTO :NEW.AUD_MOD_DT FROM dual;
	SELECT USER INTO :NEW.AUD_MOD_USR_ID FROM dual;
  END IF;

END;
/