set echo on
set linesize 1000
set pagesize 300
set trimspool on
SPOOL STLT_SCHEDULE_INSERTS.LOG

TRUNCATE TABLE GIS_ONC.STLT_SCHEDULE_VL;

INSERT INTO GIS_ONC.STLT_SCHEDULE_VL  (RATE_SCHEDULE) VALUES ('A') ;
INSERT INTO GIS_ONC.STLT_SCHEDULE_VL  (RATE_SCHEDULE) VALUES ('B') ;
INSERT INTO GIS_ONC.STLT_SCHEDULE_VL  (RATE_SCHEDULE) VALUES ('C') ;
INSERT INTO GIS_ONC.STLT_SCHEDULE_VL  (RATE_SCHEDULE) VALUES ('D') ;
INSERT INTO GIS_ONC.STLT_SCHEDULE_VL  (RATE_SCHEDULE) VALUES ('I') ;
INSERT INTO GIS_ONC.STLT_SCHEDULE_VL  (RATE_SCHEDULE) VALUES ('P') ;
INSERT INTO GIS_ONC.STLT_SCHEDULE_VL  (RATE_SCHEDULE) VALUES ('R') ;
INSERT INTO GIS_ONC.STLT_SCHEDULE_VL  (RATE_SCHEDULE) VALUES ('T') ;
INSERT INTO GIS_ONC.STLT_SCHEDULE_VL  (RATE_SCHEDULE) VALUES ('Z') ;

COMMIT;

spool off;