set echo on
set linesize 1000
set pagesize 300
set trimspool on

spool c:\temp\StyleRules_PrimaryFuse.log
--**************************************************************************************
-- SCRIPT NAME: StyleRules_PrimaryFuse.sql
--**************************************************************************************
-- AUTHOR			    : INGRNET\RRADASE
-- DATE				    : 10-MAR-2018
-- PRODUCT VERSION	: 10.3.0
-- PRJ IDENTIFIER	: G/TECHNOLOGY - ONCOR
-- PROGRAM DESC		: Styles and style rules for Primary Fuse
--**************************************************************************************
-- Modified:
--  17-JUL-2018, Rich Adase -- SME symbology review
--**************************************************************************************

alter trigger M_T_AUDR_G3E_STYLERULE_RULE disable;
alter trigger M_T_AUD_G3E_STYLERULE_RULE disable;

declare
  TYPE numArray IS TABLE OF NUMBER INDEX BY PLS_INTEGER;
  arrSNO  numArray;
  i       PLS_INTEGER;
begin
  select distinct G3E_SNO
    bulk collect into arrSNO
    from G3E_STYLERULE 
    where G3E_RULE in ('Primary Fuse Symbol', 'Primary Fuse Symbol - OMS'
                      ,'Primary Fuse - OH Symbol-SGO'
                      ,'Primary Fuse - OH Detail Symbol'
                      ,'Primary Fuse - OH Symbol'
                      ,'Primary Fuse - OH Detail Symbol');
  
  delete from G3E_STYLERULE where G3E_RULE = 'Primary Fuse Symbol';
  delete from G3E_STYLERULE where G3E_RULE = 'Primary Fuse Symbol - OMS';
  
  delete from G3E_STYLERULE where G3E_RULE = 'Primary Fuse - OH Symbol-SGO'; -- obsolete
  delete from G3E_STYLERULE where G3E_RULE = 'Primary Fuse - OH Detail Symbol'; -- obsolete
  delete from G3E_STYLERULE where G3E_RULE = 'Primary Fuse - OH Symbol'; -- obsolete
  delete from G3E_STYLERULE where G3E_RULE = 'Primary Fuse - OH Detail Symbol'; -- obsolete
  
  for i in 1..arrSNO.COUNT loop
    delete from G3E_POINTSTYLE where G3E_SNO = arrSNO(i);
    delete from G3E_STYLE where G3E_SNO = arrSNO(i);
  end loop;
end;
/

alter trigger M_T_AUDR_G3E_STYLERULE_RULE enable;
alter trigger M_T_AUD_G3E_STYLERULE_RULE enable;

-- Point styles

insert into G3E_POINTSTYLE(G3E_SNO,G3E_USERNAME,G3E_FONTNAME,G3E_SYMBOL,G3E_COLOR,G3E_SIZE,G3E_ALIGNMENT,G3E_ROTATION,G3E_USEMASK,G3E_MASKSYMBOL,G3E_PLOTREDLINE,G3E_STYLEUNITS) values (11701,'Primary Fuse Symbol - PPI SGO','AEGIS Device',CHR(66),10158079,3,0,0,0,null,0,1);
insert into G3E_POINTSTYLE(G3E_SNO,G3E_USERNAME,G3E_FONTNAME,G3E_SYMBOL,G3E_COLOR,G3E_SIZE,G3E_ALIGNMENT,G3E_ROTATION,G3E_USEMASK,G3E_MASKSYMBOL,G3E_PLOTREDLINE,G3E_STYLEUNITS) values (11702,'Primary Fuse Symbol - PPR SGO','AEGIS Device',CHR(66),14540253,3,0,0,0,null,0,1);
insert into G3E_POINTSTYLE(G3E_SNO,G3E_USERNAME,G3E_FONTNAME,G3E_SYMBOL,G3E_COLOR,G3E_SIZE,G3E_ALIGNMENT,G3E_ROTATION,G3E_USEMASK,G3E_MASKSYMBOL,G3E_PLOTREDLINE,G3E_STYLEUNITS) values (11703,'Primary Fuse Symbol - OSR SGO','AEGIS Device',CHR(66),5921370,3,0,0,0,null,0,1);
insert into G3E_POINTSTYLE(G3E_SNO,G3E_USERNAME,G3E_FONTNAME,G3E_SYMBOL,G3E_COLOR,G3E_SIZE,G3E_ALIGNMENT,G3E_ROTATION,G3E_USEMASK,G3E_MASKSYMBOL,G3E_PLOTREDLINE,G3E_STYLEUNITS) values (11704,'Primary Fuse Symbol - OPEN SGO','AEGIS Device',CHR(66),65280,3,0,0,0,null,0,1);
insert into G3E_POINTSTYLE(G3E_SNO,G3E_USERNAME,G3E_FONTNAME,G3E_SYMBOL,G3E_COLOR,G3E_SIZE,G3E_ALIGNMENT,G3E_ROTATION,G3E_USEMASK,G3E_MASKSYMBOL,G3E_PLOTREDLINE,G3E_STYLEUNITS) values (11705,'Primary Fuse Symbol - CLOSED SGO','AEGIS Device',CHR(66),255,3,0,0,0,null,0,1);
insert into G3E_POINTSTYLE(G3E_SNO,G3E_USERNAME,G3E_FONTNAME,G3E_SYMBOL,G3E_COLOR,G3E_SIZE,G3E_ALIGNMENT,G3E_ROTATION,G3E_USEMASK,G3E_MASKSYMBOL,G3E_PLOTREDLINE,G3E_STYLEUNITS) values (11706,'Primary Fuse Symbol - PPI OPEN','AEGIS Device',CHR(67),10158079,12,0,0,0,null,0,1);
insert into G3E_POINTSTYLE(G3E_SNO,G3E_USERNAME,G3E_FONTNAME,G3E_SYMBOL,G3E_COLOR,G3E_SIZE,G3E_ALIGNMENT,G3E_ROTATION,G3E_USEMASK,G3E_MASKSYMBOL,G3E_PLOTREDLINE,G3E_STYLEUNITS) values (11707,'Primary Fuse Symbol - PPI CLOSED','AEGIS Device',CHR(65),10158079,12,0,0,0,null,0,1);
insert into G3E_POINTSTYLE(G3E_SNO,G3E_USERNAME,G3E_FONTNAME,G3E_SYMBOL,G3E_COLOR,G3E_SIZE,G3E_ALIGNMENT,G3E_ROTATION,G3E_USEMASK,G3E_MASKSYMBOL,G3E_PLOTREDLINE,G3E_STYLEUNITS) values (11708,'Primary Fuse Symbol - PPR OPEN','AEGIS Device',CHR(67),14540253,12,0,0,0,null,0,1);
insert into G3E_POINTSTYLE(G3E_SNO,G3E_USERNAME,G3E_FONTNAME,G3E_SYMBOL,G3E_COLOR,G3E_SIZE,G3E_ALIGNMENT,G3E_ROTATION,G3E_USEMASK,G3E_MASKSYMBOL,G3E_PLOTREDLINE,G3E_STYLEUNITS) values (11709,'Primary Fuse Symbol - PPR CLOSED','AEGIS Device',CHR(65),14540253,12,0,0,0,null,0,1);
insert into G3E_POINTSTYLE(G3E_SNO,G3E_USERNAME,G3E_FONTNAME,G3E_SYMBOL,G3E_COLOR,G3E_SIZE,G3E_ALIGNMENT,G3E_ROTATION,G3E_USEMASK,G3E_MASKSYMBOL,G3E_PLOTREDLINE,G3E_STYLEUNITS) values (11710,'Primary Fuse Symbol - OSR OPEN','AEGIS Device',CHR(67),5921370,12,0,0,0,null,0,1);
insert into G3E_POINTSTYLE(G3E_SNO,G3E_USERNAME,G3E_FONTNAME,G3E_SYMBOL,G3E_COLOR,G3E_SIZE,G3E_ALIGNMENT,G3E_ROTATION,G3E_USEMASK,G3E_MASKSYMBOL,G3E_PLOTREDLINE,G3E_STYLEUNITS) values (11711,'Primary Fuse Symbol - OSR CLOSED','AEGIS Device',CHR(65),5921370,12,0,0,0,null,0,1);
insert into G3E_POINTSTYLE(G3E_SNO,G3E_USERNAME,G3E_FONTNAME,G3E_SYMBOL,G3E_COLOR,G3E_SIZE,G3E_ALIGNMENT,G3E_ROTATION,G3E_USEMASK,G3E_MASKSYMBOL,G3E_PLOTREDLINE,G3E_STYLEUNITS) values (11712,'Primary Fuse Symbol - OPEN','AEGIS Device',CHR(67),65280,12,0,0,0,null,0,1);
insert into G3E_POINTSTYLE(G3E_SNO,G3E_USERNAME,G3E_FONTNAME,G3E_SYMBOL,G3E_COLOR,G3E_SIZE,G3E_ALIGNMENT,G3E_ROTATION,G3E_USEMASK,G3E_MASKSYMBOL,G3E_PLOTREDLINE,G3E_STYLEUNITS) values (11713,'Primary Fuse Symbol - CLOSED','AEGIS Device',CHR(65),255,12,0,0,0,null,0,1);


-- Style rules - GIS

insert into G3E_STYLERULE(G3E_SRROWNO,G3E_SRNO,G3E_RULE,G3E_FILTER,G3E_FILTERORDINAL,G3E_SNO,G3E_DESCRIPTION) values (1110101,11101,'Primary Fuse Symbol','SWGEAR_OWNED = ''Y'' and FEATURE_STATE_C in (''PPI'',''ABI'')',1,11701,'Primary Fuse Symbol - PPI SGO');
insert into G3E_STYLERULE(G3E_SRROWNO,G3E_SRNO,G3E_RULE,G3E_FILTER,G3E_FILTERORDINAL,G3E_SNO,G3E_DESCRIPTION) values (1110102,11101,'Primary Fuse Symbol','SWGEAR_OWNED = ''Y'' and FEATURE_STATE_C in (''PPR'',''ABR'',''PPA'',''ABA'')',2,11702,'Primary Fuse Symbol - PPR SGO');
insert into G3E_STYLERULE(G3E_SRROWNO,G3E_SRNO,G3E_RULE,G3E_FILTER,G3E_FILTERORDINAL,G3E_SNO,G3E_DESCRIPTION) values (1110103,11101,'Primary Fuse Symbol','SWGEAR_OWNED = ''Y'' and FEATURE_STATE_C in (''OSR'',''OSA'')',3,11703,'Primary Fuse Symbol - OSR SGO');
insert into G3E_STYLERULE(G3E_SRROWNO,G3E_SRNO,G3E_RULE,G3E_FILTER,G3E_FILTERORDINAL,G3E_SNO,G3E_DESCRIPTION) values (1110104,11101,'Primary Fuse Symbol','SWGEAR_OWNED = ''Y'' and STATUS_NORMAL_C=''OPEN''',4,11704,'Primary Fuse Symbol - OPEN SGO');
insert into G3E_STYLERULE(G3E_SRROWNO,G3E_SRNO,G3E_RULE,G3E_FILTER,G3E_FILTERORDINAL,G3E_SNO,G3E_DESCRIPTION) values (1110105,11101,'Primary Fuse Symbol','SWGEAR_OWNED = ''Y''',5,11705,'Primary Fuse Symbol - CLOSED SGO');
insert into G3E_STYLERULE(G3E_SRROWNO,G3E_SRNO,G3E_RULE,G3E_FILTER,G3E_FILTERORDINAL,G3E_SNO,G3E_DESCRIPTION) values (1110106,11101,'Primary Fuse Symbol','FEATURE_STATE_C in (''PPI'',''ABI'') and STATUS_NORMAL_C=''OPEN''',6,11706,'Primary Fuse Symbol - PPI OPEN');
insert into G3E_STYLERULE(G3E_SRROWNO,G3E_SRNO,G3E_RULE,G3E_FILTER,G3E_FILTERORDINAL,G3E_SNO,G3E_DESCRIPTION) values (1110107,11101,'Primary Fuse Symbol','FEATURE_STATE_C in (''PPI'',''ABI'')',7,11707,'Primary Fuse Symbol - PPI CLOSED');
insert into G3E_STYLERULE(G3E_SRROWNO,G3E_SRNO,G3E_RULE,G3E_FILTER,G3E_FILTERORDINAL,G3E_SNO,G3E_DESCRIPTION) values (1110108,11101,'Primary Fuse Symbol','FEATURE_STATE_C in (''PPR'',''ABR'',''PPA'',''ABA'') and STATUS_NORMAL_C=''OPEN''',8,11708,'Primary Fuse Symbol - PPR OPEN');
insert into G3E_STYLERULE(G3E_SRROWNO,G3E_SRNO,G3E_RULE,G3E_FILTER,G3E_FILTERORDINAL,G3E_SNO,G3E_DESCRIPTION) values (1110109,11101,'Primary Fuse Symbol','FEATURE_STATE_C in (''PPR'',''ABR'',''PPA'',''ABA'')',9,11709,'Primary Fuse Symbol - PPR CLOSED');
insert into G3E_STYLERULE(G3E_SRROWNO,G3E_SRNO,G3E_RULE,G3E_FILTER,G3E_FILTERORDINAL,G3E_SNO,G3E_DESCRIPTION) values (1110110,11101,'Primary Fuse Symbol','FEATURE_STATE_C in (''OSR'',''OSA'') and STATUS_NORMAL_C=''OPEN''',10,11710,'Primary Fuse Symbol - OSR OPEN');
insert into G3E_STYLERULE(G3E_SRROWNO,G3E_SRNO,G3E_RULE,G3E_FILTER,G3E_FILTERORDINAL,G3E_SNO,G3E_DESCRIPTION) values (1110111,11101,'Primary Fuse Symbol','FEATURE_STATE_C in (''OSR'',''OSA'') ',11,11711,'Primary Fuse Symbol - OSR CLOSED');
insert into G3E_STYLERULE(G3E_SRROWNO,G3E_SRNO,G3E_RULE,G3E_FILTER,G3E_FILTERORDINAL,G3E_SNO,G3E_DESCRIPTION) values (1110112,11101,'Primary Fuse Symbol','STATUS_NORMAL_C=''OPEN''',12,11712,'Primary Fuse Symbol - OPEN');
insert into G3E_STYLERULE(G3E_SRROWNO,G3E_SRNO,G3E_RULE,G3E_FILTER,G3E_FILTERORDINAL,G3E_SNO,G3E_DESCRIPTION) values (1110199,11101,'Primary Fuse Symbol','',99,11713,'Primary Fuse Symbol - CLOSED');


-- Style rules - OMS

insert into G3E_STYLERULE(G3E_SRROWNO,G3E_SRNO,G3E_RULE,G3E_FILTER,G3E_FILTERORDINAL,G3E_SNO,G3E_DESCRIPTION) values (1120101,11201,'Primary Fuse Symbol - OMS','SWGEAR_OWNED = ''Y'' and FEATURE_STATE_C in (''PPI'',''ABI'')',1,11701,'Primary Fuse Symbol - PPI SGO');
insert into G3E_STYLERULE(G3E_SRROWNO,G3E_SRNO,G3E_RULE,G3E_FILTER,G3E_FILTERORDINAL,G3E_SNO,G3E_DESCRIPTION) values (1120102,11201,'Primary Fuse Symbol - OMS','SWGEAR_OWNED = ''Y'' and FEATURE_STATE_C in (''PPR'',''ABR'',''PPA'',''ABA'')',2,11702,'Primary Fuse Symbol - PPR SGO');
insert into G3E_STYLERULE(G3E_SRROWNO,G3E_SRNO,G3E_RULE,G3E_FILTER,G3E_FILTERORDINAL,G3E_SNO,G3E_DESCRIPTION) values (1120103,11201,'Primary Fuse Symbol - OMS','SWGEAR_OWNED = ''Y'' and FEATURE_STATE_C in (''OSR'',''OSA'')',3,11703,'Primary Fuse Symbol - OSR SGO');
insert into G3E_STYLERULE(G3E_SRROWNO,G3E_SRNO,G3E_RULE,G3E_FILTER,G3E_FILTERORDINAL,G3E_SNO,G3E_DESCRIPTION) values (1120104,11201,'Primary Fuse Symbol - OMS','SWGEAR_OWNED = ''Y'' and STATUS_NORMAL_C=''OPEN''',4,11704,'Primary Fuse Symbol - OPEN SGO');
insert into G3E_STYLERULE(G3E_SRROWNO,G3E_SRNO,G3E_RULE,G3E_FILTER,G3E_FILTERORDINAL,G3E_SNO,G3E_DESCRIPTION) values (1120105,11201,'Primary Fuse Symbol - OMS','SWGEAR_OWNED = ''Y''',5,11705,'Primary Fuse Symbol - CLOSED SGO');
insert into G3E_STYLERULE(G3E_SRROWNO,G3E_SRNO,G3E_RULE,G3E_FILTER,G3E_FILTERORDINAL,G3E_SNO,G3E_DESCRIPTION) values (1120106,11201,'Primary Fuse Symbol - OMS','FEATURE_STATE_C in (''PPI'',''ABI'') and STATUS_NORMAL_C=''OPEN''',6,11706,'Primary Fuse Symbol - PPI OPEN');
insert into G3E_STYLERULE(G3E_SRROWNO,G3E_SRNO,G3E_RULE,G3E_FILTER,G3E_FILTERORDINAL,G3E_SNO,G3E_DESCRIPTION) values (1120107,11201,'Primary Fuse Symbol - OMS','FEATURE_STATE_C in (''PPI'',''ABI'')',7,11707,'Primary Fuse Symbol - PPI CLOSED');
insert into G3E_STYLERULE(G3E_SRROWNO,G3E_SRNO,G3E_RULE,G3E_FILTER,G3E_FILTERORDINAL,G3E_SNO,G3E_DESCRIPTION) values (1120108,11201,'Primary Fuse Symbol - OMS','FEATURE_STATE_C in (''PPR'',''ABR'',''PPA'',''ABA'') and STATUS_NORMAL_C=''OPEN''',8,11708,'Primary Fuse Symbol - PPR OPEN');
insert into G3E_STYLERULE(G3E_SRROWNO,G3E_SRNO,G3E_RULE,G3E_FILTER,G3E_FILTERORDINAL,G3E_SNO,G3E_DESCRIPTION) values (1120109,11201,'Primary Fuse Symbol - OMS','FEATURE_STATE_C in (''PPR'',''ABR'',''PPA'',''ABA'')',9,11709,'Primary Fuse Symbol - PPR CLOSED');
insert into G3E_STYLERULE(G3E_SRROWNO,G3E_SRNO,G3E_RULE,G3E_FILTER,G3E_FILTERORDINAL,G3E_SNO,G3E_DESCRIPTION) values (1120110,11201,'Primary Fuse Symbol - OMS','FEATURE_STATE_C in (''OSR'',''OSA'') and STATUS_NORMAL_C=''OPEN''',10,11710,'Primary Fuse Symbol - OSR OPEN');
insert into G3E_STYLERULE(G3E_SRROWNO,G3E_SRNO,G3E_RULE,G3E_FILTER,G3E_FILTERORDINAL,G3E_SNO,G3E_DESCRIPTION) values (1120111,11201,'Primary Fuse Symbol - OMS','FEATURE_STATE_C in (''OSR'',''OSA'') ',11,11711,'Primary Fuse Symbol - OSR CLOSED');
insert into G3E_STYLERULE(G3E_SRROWNO,G3E_SRNO,G3E_RULE,G3E_FILTER,G3E_FILTERORDINAL,G3E_SNO,G3E_DESCRIPTION) values (1120112,11201,'Primary Fuse Symbol - OMS','STATUS_NORMAL_C=''OPEN''',12,11712,'Primary Fuse Symbol - OPEN');
insert into G3E_STYLERULE(G3E_SRROWNO,G3E_SRNO,G3E_RULE,G3E_FILTER,G3E_FILTERORDINAL,G3E_SNO,G3E_DESCRIPTION) values (1120199,11201,'Primary Fuse Symbol - OMS','',99,11713,'Primary Fuse Symbol - CLOSED');

spool off;
