set echo on
set linesize 1000
set pagesize 300
set trimspool on

spool c:\temp\StyleRules_SecondaryFuse.log
--**************************************************************************************
-- SCRIPT NAME: StyleRules_SecondaryFuse.sql
--**************************************************************************************
-- AUTHOR			    : INGRNET\RRADASE
-- DATE				    : 10-MAR-2018
-- PRODUCT VERSION	: 10.3.0
-- PRJ IDENTIFIER	: G/TECHNOLOGY - ONCOR
-- PROGRAM DESC		: Styles and style rules for Secondary Fuse
--**************************************************************************************
-- Modified:
--  17-JUL-2018, Rich Adase -- SME symbology review
--**************************************************************************************

alter trigger M_T_AUDR_G3E_STYLERULE_RULE disable;
alter trigger M_T_AUD_G3E_STYLERULE_RULE disable;

declare
  TYPE numArray IS TABLE OF NUMBER INDEX BY PLS_INTEGER;
  arrSNO  numArray;
  i       PLS_INTEGER;
begin
  select distinct G3E_SNO
    bulk collect into arrSNO
    from G3E_STYLERULE
    where G3E_RULE in ('Secondary Fuse Detail Symbol', 'Secondary Fuse Detail Symbol - OMS');
  
  delete from G3E_STYLERULE where G3E_RULE = 'Secondary Fuse Detail Symbol';
  delete from G3E_STYLERULE where G3E_RULE = 'Secondary Fuse Detail Symbol - OMS';
  
  for i in 1..arrSNO.COUNT loop
    delete from G3E_POINTSTYLE where G3E_SNO = arrSNO(i);
    delete from G3E_STYLE where G3E_SNO = arrSNO(i);
  end loop;
end;
/

alter trigger M_T_AUDR_G3E_STYLERULE_RULE enable;
alter trigger M_T_AUD_G3E_STYLERULE_RULE enable;

-- Point styles

insert into G3E_POINTSTYLE(G3E_SNO,G3E_USERNAME,G3E_FONTNAME,G3E_SYMBOL,G3E_COLOR,G3E_SIZE,G3E_ALIGNMENT,G3E_ROTATION,G3E_USEMASK,G3E_MASKSYMBOL,G3E_PLOTREDLINE,G3E_STYLEUNITS) values (161101,'Secondary Fuse Detail - VLINK Closed PPI','AEGIS Device',CHR(68),10158079,12,1,0,0,null,0,1);
insert into G3E_POINTSTYLE(G3E_SNO,G3E_USERNAME,G3E_FONTNAME,G3E_SYMBOL,G3E_COLOR,G3E_SIZE,G3E_ALIGNMENT,G3E_ROTATION,G3E_USEMASK,G3E_MASKSYMBOL,G3E_PLOTREDLINE,G3E_STYLEUNITS) values (161102,'Secondary Fuse Detail - VLINK Closed PPR','AEGIS Device',CHR(68),14540253,12,1,0,0,null,0,1);
insert into G3E_POINTSTYLE(G3E_SNO,G3E_USERNAME,G3E_FONTNAME,G3E_SYMBOL,G3E_COLOR,G3E_SIZE,G3E_ALIGNMENT,G3E_ROTATION,G3E_USEMASK,G3E_MASKSYMBOL,G3E_PLOTREDLINE,G3E_STYLEUNITS) values (161103,'Secondary Fuse Detail - VLINK Closed OSR','AEGIS Device',CHR(68),5921370,12,1,0,0,null,0,1);
insert into G3E_POINTSTYLE(G3E_SNO,G3E_USERNAME,G3E_FONTNAME,G3E_SYMBOL,G3E_COLOR,G3E_SIZE,G3E_ALIGNMENT,G3E_ROTATION,G3E_USEMASK,G3E_MASKSYMBOL,G3E_PLOTREDLINE,G3E_STYLEUNITS) values (161104,'Secondary Fuse Detail - VLINK Closed','AEGIS Device',CHR(68),255,12,1,0,0,null,0,1);
insert into G3E_POINTSTYLE(G3E_SNO,G3E_USERNAME,G3E_FONTNAME,G3E_SYMBOL,G3E_COLOR,G3E_SIZE,G3E_ALIGNMENT,G3E_ROTATION,G3E_USEMASK,G3E_MASKSYMBOL,G3E_PLOTREDLINE,G3E_STYLEUNITS) values (161105,'Secondary Fuse Detail - VLINK Open PPI','AEGIS Device',CHR(69),10158079,12,1,0,0,null,0,1);
insert into G3E_POINTSTYLE(G3E_SNO,G3E_USERNAME,G3E_FONTNAME,G3E_SYMBOL,G3E_COLOR,G3E_SIZE,G3E_ALIGNMENT,G3E_ROTATION,G3E_USEMASK,G3E_MASKSYMBOL,G3E_PLOTREDLINE,G3E_STYLEUNITS) values (161106,'Secondary Fuse Detail - VLINK Open PPR','AEGIS Device',CHR(69),14540253,12,1,0,0,null,0,1);
insert into G3E_POINTSTYLE(G3E_SNO,G3E_USERNAME,G3E_FONTNAME,G3E_SYMBOL,G3E_COLOR,G3E_SIZE,G3E_ALIGNMENT,G3E_ROTATION,G3E_USEMASK,G3E_MASKSYMBOL,G3E_PLOTREDLINE,G3E_STYLEUNITS) values (161107,'Secondary Fuse Detail - VLINK Open OSR','AEGIS Device',CHR(69),5921370,12,1,0,0,null,0,1);
insert into G3E_POINTSTYLE(G3E_SNO,G3E_USERNAME,G3E_FONTNAME,G3E_SYMBOL,G3E_COLOR,G3E_SIZE,G3E_ALIGNMENT,G3E_ROTATION,G3E_USEMASK,G3E_MASKSYMBOL,G3E_PLOTREDLINE,G3E_STYLEUNITS) values (161108,'Secondary Fuse Detail - VLINK Open','AEGIS Device',CHR(69),65280,12,1,0,0,null,0,1);
insert into G3E_POINTSTYLE(G3E_SNO,G3E_USERNAME,G3E_FONTNAME,G3E_SYMBOL,G3E_COLOR,G3E_SIZE,G3E_ALIGNMENT,G3E_ROTATION,G3E_USEMASK,G3E_MASKSYMBOL,G3E_PLOTREDLINE,G3E_STYLEUNITS) values (161109,'Secondary Fuse Detail - Closed PPI','AEGIS Device',CHR(65),10158079,12,1,0,0,null,0,1);
insert into G3E_POINTSTYLE(G3E_SNO,G3E_USERNAME,G3E_FONTNAME,G3E_SYMBOL,G3E_COLOR,G3E_SIZE,G3E_ALIGNMENT,G3E_ROTATION,G3E_USEMASK,G3E_MASKSYMBOL,G3E_PLOTREDLINE,G3E_STYLEUNITS) values (161110,'Secondary Fuse Detail - Closed PPR','AEGIS Device',CHR(65),14540253,12,1,0,0,null,0,1);
insert into G3E_POINTSTYLE(G3E_SNO,G3E_USERNAME,G3E_FONTNAME,G3E_SYMBOL,G3E_COLOR,G3E_SIZE,G3E_ALIGNMENT,G3E_ROTATION,G3E_USEMASK,G3E_MASKSYMBOL,G3E_PLOTREDLINE,G3E_STYLEUNITS) values (161111,'Secondary Fuse Detail - Closed OSR','AEGIS Device',CHR(65),5921370,12,1,0,0,null,0,1);
insert into G3E_POINTSTYLE(G3E_SNO,G3E_USERNAME,G3E_FONTNAME,G3E_SYMBOL,G3E_COLOR,G3E_SIZE,G3E_ALIGNMENT,G3E_ROTATION,G3E_USEMASK,G3E_MASKSYMBOL,G3E_PLOTREDLINE,G3E_STYLEUNITS) values (161112,'Secondary Fuse Detail - Closed','AEGIS Device',CHR(65),255,12,1,0,0,null,0,1);
insert into G3E_POINTSTYLE(G3E_SNO,G3E_USERNAME,G3E_FONTNAME,G3E_SYMBOL,G3E_COLOR,G3E_SIZE,G3E_ALIGNMENT,G3E_ROTATION,G3E_USEMASK,G3E_MASKSYMBOL,G3E_PLOTREDLINE,G3E_STYLEUNITS) values (161113,'Secondary Fuse Detail - Open PPI','AEGIS Device',CHR(67),10158079,12,1,0,0,null,0,1);
insert into G3E_POINTSTYLE(G3E_SNO,G3E_USERNAME,G3E_FONTNAME,G3E_SYMBOL,G3E_COLOR,G3E_SIZE,G3E_ALIGNMENT,G3E_ROTATION,G3E_USEMASK,G3E_MASKSYMBOL,G3E_PLOTREDLINE,G3E_STYLEUNITS) values (161114,'Secondary Fuse Detail - Open PPR','AEGIS Device',CHR(67),14540253,12,1,0,0,null,0,1);
insert into G3E_POINTSTYLE(G3E_SNO,G3E_USERNAME,G3E_FONTNAME,G3E_SYMBOL,G3E_COLOR,G3E_SIZE,G3E_ALIGNMENT,G3E_ROTATION,G3E_USEMASK,G3E_MASKSYMBOL,G3E_PLOTREDLINE,G3E_STYLEUNITS) values (161115,'Secondary Fuse Detail - Open OSR','AEGIS Device',CHR(67),5921370,12,1,0,0,null,0,1);
insert into G3E_POINTSTYLE(G3E_SNO,G3E_USERNAME,G3E_FONTNAME,G3E_SYMBOL,G3E_COLOR,G3E_SIZE,G3E_ALIGNMENT,G3E_ROTATION,G3E_USEMASK,G3E_MASKSYMBOL,G3E_PLOTREDLINE,G3E_STYLEUNITS) values (161116,'Secondary Fuse Detail - Open','AEGIS Device',CHR(67),65280,12,1,0,0,null,0,1);
insert into G3E_POINTSTYLE(G3E_SNO,G3E_USERNAME,G3E_FONTNAME,G3E_SYMBOL,G3E_COLOR,G3E_SIZE,G3E_ALIGNMENT,G3E_ROTATION,G3E_USEMASK,G3E_MASKSYMBOL,G3E_PLOTREDLINE,G3E_STYLEUNITS) values (161199,'Secondary Fuse Detail Default','AEGIS Device',CHR(67),65535,12,1,0,0,null,0,1);


-- Style rules - GIS

insert into G3E_STYLERULE(G3E_SRROWNO,G3E_SRNO,G3E_RULE,G3E_FILTER,G3E_FILTERORDINAL,G3E_SNO,G3E_DESCRIPTION) values (16110101,161101,'Secondary Fuse Detail Symbol','Secondary Fuse Bank Attributes.Link Type = ''V-LINK'' and STATUS_NORMAL_C=''CLOSED'' and FEATURE_STATE_C in (''PPI'',''ABI'') ',1,161101,'Secondary Fuse Detail - VLINK Closed PPI');
insert into G3E_STYLERULE(G3E_SRROWNO,G3E_SRNO,G3E_RULE,G3E_FILTER,G3E_FILTERORDINAL,G3E_SNO,G3E_DESCRIPTION) values (16110102,161101,'Secondary Fuse Detail Symbol','Secondary Fuse Bank Attributes.Link Type = ''V-LINK'' and STATUS_NORMAL_C=''CLOSED'' and FEATURE_STATE_C in (''PPR'',''ABR'',''PPA'',''ABA'') ',2,161102,'Secondary Fuse Detail - VLINK Closed PPR');
insert into G3E_STYLERULE(G3E_SRROWNO,G3E_SRNO,G3E_RULE,G3E_FILTER,G3E_FILTERORDINAL,G3E_SNO,G3E_DESCRIPTION) values (16110103,161101,'Secondary Fuse Detail Symbol','Secondary Fuse Bank Attributes.Link Type = ''V-LINK'' and STATUS_NORMAL_C=''CLOSED'' and FEATURE_STATE_C in (''OSR'',''OSA'')',3,161103,'Secondary Fuse Detail - VLINK Closed OSR');
insert into G3E_STYLERULE(G3E_SRROWNO,G3E_SRNO,G3E_RULE,G3E_FILTER,G3E_FILTERORDINAL,G3E_SNO,G3E_DESCRIPTION) values (16110104,161101,'Secondary Fuse Detail Symbol','Secondary Fuse Bank Attributes.Link Type = ''V-LINK'' and STATUS_NORMAL_C=''CLOSED''',4,161104,'Secondary Fuse Detail - VLINK Closed');
insert into G3E_STYLERULE(G3E_SRROWNO,G3E_SRNO,G3E_RULE,G3E_FILTER,G3E_FILTERORDINAL,G3E_SNO,G3E_DESCRIPTION) values (16110105,161101,'Secondary Fuse Detail Symbol','Secondary Fuse Bank Attributes.Link Type = ''V-LINK'' and STATUS_NORMAL_C=''OPEN'' and FEATURE_STATE_C in (''PPI'',''ABI'') ',5,161105,'Secondary Fuse Detail - VLINK Open PPI');
insert into G3E_STYLERULE(G3E_SRROWNO,G3E_SRNO,G3E_RULE,G3E_FILTER,G3E_FILTERORDINAL,G3E_SNO,G3E_DESCRIPTION) values (16110106,161101,'Secondary Fuse Detail Symbol','Secondary Fuse Bank Attributes.Link Type = ''V-LINK'' and STATUS_NORMAL_C=''OPEN'' and FEATURE_STATE_C in (''PPR'',''ABR'',''PPA'',''ABA'') ',6,161106,'Secondary Fuse Detail - VLINK Open PPR');
insert into G3E_STYLERULE(G3E_SRROWNO,G3E_SRNO,G3E_RULE,G3E_FILTER,G3E_FILTERORDINAL,G3E_SNO,G3E_DESCRIPTION) values (16110107,161101,'Secondary Fuse Detail Symbol','Secondary Fuse Bank Attributes.Link Type = ''V-LINK''  and STATUS_NORMAL_C=''OPEN'' and FEATURE_STATE_C in (''OSR'',''OSA'')',7,161107,'Secondary Fuse Detail - VLINK Open OSR');
insert into G3E_STYLERULE(G3E_SRROWNO,G3E_SRNO,G3E_RULE,G3E_FILTER,G3E_FILTERORDINAL,G3E_SNO,G3E_DESCRIPTION) values (16110108,161101,'Secondary Fuse Detail Symbol','Secondary Fuse Bank Attributes.Link Type = ''V-LINK''  and STATUS_NORMAL_C=''OPEN''',8,161108,'Secondary Fuse Detail - VLINK Open');
insert into G3E_STYLERULE(G3E_SRROWNO,G3E_SRNO,G3E_RULE,G3E_FILTER,G3E_FILTERORDINAL,G3E_SNO,G3E_DESCRIPTION) values (16110109,161101,'Secondary Fuse Detail Symbol','STATUS_NORMAL_C=''CLOSED'' and FEATURE_STATE_C in (''PPI'',''ABI'')',9,161109,'Secondary Fuse Detail - Closed PPI');
insert into G3E_STYLERULE(G3E_SRROWNO,G3E_SRNO,G3E_RULE,G3E_FILTER,G3E_FILTERORDINAL,G3E_SNO,G3E_DESCRIPTION) values (16110110,161101,'Secondary Fuse Detail Symbol','STATUS_NORMAL_C=''CLOSED'' and FEATURE_STATE_C in (''PPR'',''ABR'',''PPA'',''ABA'')',10,161110,'Secondary Fuse Detail - Closed PPR');
insert into G3E_STYLERULE(G3E_SRROWNO,G3E_SRNO,G3E_RULE,G3E_FILTER,G3E_FILTERORDINAL,G3E_SNO,G3E_DESCRIPTION) values (16110111,161101,'Secondary Fuse Detail Symbol','STATUS_NORMAL_C=''CLOSED'' and FEATURE_STATE_C in (''OSR'',''OSA'')',11,161111,'Secondary Fuse Detail - Closed OSR');
insert into G3E_STYLERULE(G3E_SRROWNO,G3E_SRNO,G3E_RULE,G3E_FILTER,G3E_FILTERORDINAL,G3E_SNO,G3E_DESCRIPTION) values (16110112,161101,'Secondary Fuse Detail Symbol','STATUS_NORMAL_C=''CLOSED''',12,161112,'Secondary Fuse Detail - Closed');
insert into G3E_STYLERULE(G3E_SRROWNO,G3E_SRNO,G3E_RULE,G3E_FILTER,G3E_FILTERORDINAL,G3E_SNO,G3E_DESCRIPTION) values (16110113,161101,'Secondary Fuse Detail Symbol','STATUS_NORMAL_C=''OPEN'' and FEATURE_STATE_C in (''PPI'',''ABI'')',13,161113,'Secondary Fuse Detail - Open PPI');
insert into G3E_STYLERULE(G3E_SRROWNO,G3E_SRNO,G3E_RULE,G3E_FILTER,G3E_FILTERORDINAL,G3E_SNO,G3E_DESCRIPTION) values (16110114,161101,'Secondary Fuse Detail Symbol','STATUS_NORMAL_C=''OPEN'' and FEATURE_STATE_C in (''PPR'',''ABR'',''PPA'',''ABA'')',14,161114,'Secondary Fuse Detail - Open PPR');
insert into G3E_STYLERULE(G3E_SRROWNO,G3E_SRNO,G3E_RULE,G3E_FILTER,G3E_FILTERORDINAL,G3E_SNO,G3E_DESCRIPTION) values (16110115,161101,'Secondary Fuse Detail Symbol','STATUS_NORMAL_C=''OPEN'' and FEATURE_STATE_C in (''OSR'',''OSA'')',15,161115,'Secondary Fuse Detail - Open OSR');
insert into G3E_STYLERULE(G3E_SRROWNO,G3E_SRNO,G3E_RULE,G3E_FILTER,G3E_FILTERORDINAL,G3E_SNO,G3E_DESCRIPTION) values (16110116,161101,'Secondary Fuse Detail Symbol','STATUS_NORMAL_C=''OPEN''',16,161116,'Secondary Fuse Detail - Open');
insert into G3E_STYLERULE(G3E_SRROWNO,G3E_SRNO,G3E_RULE,G3E_FILTER,G3E_FILTERORDINAL,G3E_SNO,G3E_DESCRIPTION) values (16110199,161101,'Secondary Fuse Detail Symbol','',99,161199,'Secondary Fuse Detail Default');


-- Style rules - OMS

insert into G3E_STYLERULE(G3E_SRROWNO,G3E_SRNO,G3E_RULE,G3E_FILTER,G3E_FILTERORDINAL,G3E_SNO,G3E_DESCRIPTION) values (16120101,161201,'Secondary Fuse Detail Symbol - OMS','Secondary Fuse Bank Attributes.Link Type = ''V-LINK'' and STATUS_NORMAL_C=''CLOSED'' and FEATURE_STATE_C in (''PPI'',''ABI'') ',1,161101,'Secondary Fuse Detail - VLINK Closed PPI');
insert into G3E_STYLERULE(G3E_SRROWNO,G3E_SRNO,G3E_RULE,G3E_FILTER,G3E_FILTERORDINAL,G3E_SNO,G3E_DESCRIPTION) values (16120102,161201,'Secondary Fuse Detail Symbol - OMS','Secondary Fuse Bank Attributes.Link Type = ''V-LINK'' and STATUS_NORMAL_C=''CLOSED'' and FEATURE_STATE_C in (''PPR'',''ABR'',''PPA'',''ABA'') ',2,161102,'Secondary Fuse Detail - VLINK Closed PPR');
insert into G3E_STYLERULE(G3E_SRROWNO,G3E_SRNO,G3E_RULE,G3E_FILTER,G3E_FILTERORDINAL,G3E_SNO,G3E_DESCRIPTION) values (16120103,161201,'Secondary Fuse Detail Symbol - OMS','Secondary Fuse Bank Attributes.Link Type = ''V-LINK'' and STATUS_NORMAL_C=''CLOSED'' and FEATURE_STATE_C in (''OSR'',''OSA'')',3,161103,'Secondary Fuse Detail - VLINK Closed OSR');
insert into G3E_STYLERULE(G3E_SRROWNO,G3E_SRNO,G3E_RULE,G3E_FILTER,G3E_FILTERORDINAL,G3E_SNO,G3E_DESCRIPTION) values (16120104,161201,'Secondary Fuse Detail Symbol - OMS','Secondary Fuse Bank Attributes.Link Type = ''V-LINK'' and STATUS_NORMAL_C=''CLOSED''',4,161104,'Secondary Fuse Detail - VLINK Closed');
insert into G3E_STYLERULE(G3E_SRROWNO,G3E_SRNO,G3E_RULE,G3E_FILTER,G3E_FILTERORDINAL,G3E_SNO,G3E_DESCRIPTION) values (16120105,161201,'Secondary Fuse Detail Symbol - OMS','Secondary Fuse Bank Attributes.Link Type = ''V-LINK'' and STATUS_NORMAL_C=''OPEN'' and FEATURE_STATE_C in (''PPI'',''ABI'') ',5,161105,'Secondary Fuse Detail - VLINK Open PPI');
insert into G3E_STYLERULE(G3E_SRROWNO,G3E_SRNO,G3E_RULE,G3E_FILTER,G3E_FILTERORDINAL,G3E_SNO,G3E_DESCRIPTION) values (16120106,161201,'Secondary Fuse Detail Symbol - OMS','Secondary Fuse Bank Attributes.Link Type = ''V-LINK'' and STATUS_NORMAL_C=''OPEN'' and FEATURE_STATE_C in (''PPR'',''ABR'',''PPA'',''ABA'') ',6,161106,'Secondary Fuse Detail - VLINK Open PPR');
insert into G3E_STYLERULE(G3E_SRROWNO,G3E_SRNO,G3E_RULE,G3E_FILTER,G3E_FILTERORDINAL,G3E_SNO,G3E_DESCRIPTION) values (16120107,161201,'Secondary Fuse Detail Symbol - OMS','Secondary Fuse Bank Attributes.Link Type = ''V-LINK''  and STATUS_NORMAL_C=''OPEN'' and FEATURE_STATE_C in (''OSR'',''OSA'')',7,161107,'Secondary Fuse Detail - VLINK Open OSR');
insert into G3E_STYLERULE(G3E_SRROWNO,G3E_SRNO,G3E_RULE,G3E_FILTER,G3E_FILTERORDINAL,G3E_SNO,G3E_DESCRIPTION) values (16120108,161201,'Secondary Fuse Detail Symbol - OMS','Secondary Fuse Bank Attributes.Link Type = ''V-LINK''  and STATUS_NORMAL_C=''OPEN''',8,161108,'Secondary Fuse Detail - VLINK Open');
insert into G3E_STYLERULE(G3E_SRROWNO,G3E_SRNO,G3E_RULE,G3E_FILTER,G3E_FILTERORDINAL,G3E_SNO,G3E_DESCRIPTION) values (16120109,161201,'Secondary Fuse Detail Symbol - OMS','STATUS_NORMAL_C=''CLOSED'' and FEATURE_STATE_C in (''PPI'',''ABI'')',9,161109,'Secondary Fuse Detail - Closed PPI');
insert into G3E_STYLERULE(G3E_SRROWNO,G3E_SRNO,G3E_RULE,G3E_FILTER,G3E_FILTERORDINAL,G3E_SNO,G3E_DESCRIPTION) values (16120110,161201,'Secondary Fuse Detail Symbol - OMS','STATUS_NORMAL_C=''CLOSED'' and FEATURE_STATE_C in (''PPR'',''ABR'',''PPA'',''ABA'')',10,161110,'Secondary Fuse Detail - Closed PPR');
insert into G3E_STYLERULE(G3E_SRROWNO,G3E_SRNO,G3E_RULE,G3E_FILTER,G3E_FILTERORDINAL,G3E_SNO,G3E_DESCRIPTION) values (16120111,161201,'Secondary Fuse Detail Symbol - OMS','STATUS_NORMAL_C=''CLOSED'' and FEATURE_STATE_C in (''OSR'',''OSA'')',11,161111,'Secondary Fuse Detail - Closed OSR');
insert into G3E_STYLERULE(G3E_SRROWNO,G3E_SRNO,G3E_RULE,G3E_FILTER,G3E_FILTERORDINAL,G3E_SNO,G3E_DESCRIPTION) values (16120112,161201,'Secondary Fuse Detail Symbol - OMS','STATUS_NORMAL_C=''CLOSED''',12,161112,'Secondary Fuse Detail - Closed');
insert into G3E_STYLERULE(G3E_SRROWNO,G3E_SRNO,G3E_RULE,G3E_FILTER,G3E_FILTERORDINAL,G3E_SNO,G3E_DESCRIPTION) values (16120113,161201,'Secondary Fuse Detail Symbol - OMS','STATUS_NORMAL_C=''OPEN'' and FEATURE_STATE_C in (''PPI'',''ABI'')',13,161113,'Secondary Fuse Detail - Open PPI');
insert into G3E_STYLERULE(G3E_SRROWNO,G3E_SRNO,G3E_RULE,G3E_FILTER,G3E_FILTERORDINAL,G3E_SNO,G3E_DESCRIPTION) values (16120114,161201,'Secondary Fuse Detail Symbol - OMS','STATUS_NORMAL_C=''OPEN'' and FEATURE_STATE_C in (''PPR'',''ABR'',''PPA'',''ABA'')',14,161114,'Secondary Fuse Detail - Open PPR');
insert into G3E_STYLERULE(G3E_SRROWNO,G3E_SRNO,G3E_RULE,G3E_FILTER,G3E_FILTERORDINAL,G3E_SNO,G3E_DESCRIPTION) values (16120115,161201,'Secondary Fuse Detail Symbol - OMS','STATUS_NORMAL_C=''OPEN'' and FEATURE_STATE_C in (''OSR'',''OSA'')',15,161115,'Secondary Fuse Detail - Open OSR');
insert into G3E_STYLERULE(G3E_SRROWNO,G3E_SRNO,G3E_RULE,G3E_FILTER,G3E_FILTERORDINAL,G3E_SNO,G3E_DESCRIPTION) values (16120116,161201,'Secondary Fuse Detail Symbol - OMS','STATUS_NORMAL_C=''OPEN''',16,161116,'Secondary Fuse Detail - Open');
insert into G3E_STYLERULE(G3E_SRROWNO,G3E_SRNO,G3E_RULE,G3E_FILTER,G3E_FILTERORDINAL,G3E_SNO,G3E_DESCRIPTION) values (16120199,161201,'Secondary Fuse Detail Symbol - OMS','',99,161199,'Secondary Fuse Detail Default');


spool off;
