
set echo on
set linesize 1000
set pagesize 300
set trimspool on

spool c:\temp\SysAccess_GrantToRolesAndSchemas.log
--**************************************************************************************
--SCRIPT NAME: SysAccess_GrantToRolesAndSchemas.sql
--**************************************************************************************
-- AUTHOR         : INGRNET\RRADASE
-- DATE           : 15-JUN-2018
-- PRODUCT VERSION	: 10.3
-- PRJ IDENTIFIER	: G/TECHNOLOGY - ONCOR
-- PROGRAM DESC		: Grant permissions to functional roles and other schemas
--**************************************************************************************
--
--  !!!   NOTE: RUN AS SYS USER WITH SYSDBA PRIVILEGES   !!!
--
--**************************************************************************************


--
-- SELECT PRIVILEGES
--

grant SELECT on GIS.ASSET_HISTORY           to PRIV_EDIT;

grant SELECT on GIS.CUSELECT_USERPREF       to PRIV_EDIT;
grant SELECT on GIS.V_CUSELECTION_ACU_VL    to PRIV_EDIT;
grant SELECT on GIS.V_CUSELECTION_AMCU_VL   to PRIV_EDIT;
grant SELECT on GIS.V_CUSELECTION_CU_VL     to PRIV_EDIT;
grant SELECT on GIS.V_CUSELECTION_MCU_VL    to PRIV_EDIT;

grant SELECT,INSERT,UPDATE on GIS_ONC.COMMAND_LOG to EVERYONE;
grant DELETE on GIS_ONC.COMMAND_LOG to PRIV_SUPPORT;

grant SELECT on GIS_ONC.CULIB_ATTRIBUTE     to PRIV_EDIT;
grant SELECT on GIS_ONC.CULIB_CATEGORY      to PRIV_EDIT;
grant SELECT on GIS_ONC.CULIB_MACRO         to PRIV_EDIT;
grant SELECT on GIS_ONC.CULIB_MACROUNIT     to PRIV_EDIT;
grant SELECT on GIS_ONC.CULIB_MATERIAL      to PRIV_EDIT;
grant SELECT on GIS_ONC.CULIB_UNIT          to PRIV_EDIT;
grant SELECT on GIS_ONC.CULIB_UNITATTRIBUTE to PRIV_EDIT;
grant SELECT on GIS_ONC.CULIB_UNITMATERIAL  to PRIV_EDIT;
grant SELECT on GIS_ONC.WR_VALIDATION_RULE  to PRIV_EDIT;

grant SELECT on GIS_ONC.CULIB_ATTRIBUTE     to GIS WITH GRANT OPTION;
grant SELECT on GIS_ONC.CULIB_CATEGORY      to GIS WITH GRANT OPTION;
grant SELECT on GIS_ONC.CULIB_MACRO         to GIS WITH GRANT OPTION;
grant SELECT on GIS_ONC.CULIB_MACROUNIT     to GIS WITH GRANT OPTION;
grant SELECT on GIS_ONC.CULIB_MATERIAL      to GIS WITH GRANT OPTION;
grant SELECT on GIS_ONC.CULIB_UNIT          to GIS WITH GRANT OPTION;
grant SELECT on GIS_ONC.CULIB_UNITATTRIBUTE to GIS WITH GRANT OPTION;
grant SELECT on GIS_ONC.CULIB_UNITMATERIAL  to GIS WITH GRANT OPTION;

GRANT SELECT ON CULIB_ATTRIBUTE TO GIS_ONC;
GRANT SELECT ON CULIB_UNIT TO GIS_ONC;
GRANT SELECT ON CULIB_UNITATTRIBUTE TO GIS_ONC;
GRANT SELECT ON FUSE_COORDINATION TO EVERYONE;
GRANT SELECT ON FUSE_COORDINATION TO PRIV_EDIT;
GRANT SELECT ON STG_VINTAGE_YEAR TO ADMINISTRATOR;
GRANT SELECT ON WR_VALIDATION_RULE TO PRIV_EDIT;
GRANT SELECT, INSERT, DELETE, UPDATE ON CUSELECT_USERPREF TO GIS_ONC;
GRANT SELECT, INSERT, UPDATE ON G3E_JOB TO GIS_ONC;

GRANT SELECT ON G3E_JOB TO GIS_ONC WITH GRANT OPTION;
GRANT SELECT ON GC_ROOM_I TO DESIGNER;
GRANT SELECT ON GC_ROOM_I TO SUPERVISOR;
GRANT SELECT ON GIS.B$COMMON_N TO GIS_ONC WITH GRANT OPTION;
GRANT SELECT ON LTT_IDENTIFIERS TO GIS_ONC WITH GRANT OPTION;
GRANT SELECT ON SYS_GENERALPARAMETER TO GIS_ONC WITH GRANT OPTION;
GRANT SELECT ON VL_FORMATION_DUCT_SIZE TO DESIGNER,FINANCE,MARKETING;
GRANT SELECT ON VL_FORMATION_DUCT_TYPE TO DESIGNER,FINANCE,MARKETING;
GRANT SELECT ON VL_NETWORK_NBR TO DESIGNER,FINANCE,MARKETING;
GRANT SELECT ON VL_SWITCH_BUSHING_TYPE TO DESIGNER,FINANCE,MARKETING;
GRANT SELECT ON VL_SWITCH_MEDIUM_TYPE TO DESIGNER,FINANCE,MARKETING;
GRANT SELECT, UPDATE ON GIS.B$PREMISE_N TO GIS_ONC WITH GRANT OPTION;
GRANT SELECT, UPDATE ON GIS.B$STREETLIGHT_N TO GIS_ONC WITH GRANT OPTION;
GRANT SELECT, UPDATE ON STLT_ACCOUNT TO GIS_ONC WITH GRANT OPTION;
GRANT SELECT,INSERT,UPDATE,DELETE ON VL_FORMATION_DUCT_SIZE TO SUPERVISOR,ADMINISTRATOR;
GRANT SELECT,INSERT,UPDATE,DELETE ON VL_FORMATION_DUCT_TYPE TO SUPERVISOR,ADMINISTRATOR;
GRANT SELECT,INSERT,UPDATE,DELETE ON VL_NETWORK_NBR TO SUPERVISOR,ADMINISTRATOR;
GRANT SELECT,INSERT,UPDATE,DELETE ON VL_SWITCH_BUSHING_TYPE TO SUPERVISOR,ADMINISTRATOR;
GRANT SELECT,INSERT,UPDATE,DELETE ON VL_SWITCH_MEDIUM_TYPE TO SUPERVISOR,ADMINISTRATOR;

--
-- EXECUTE PRIVILEGES
--
grant EXECUTE on GIS.LBM_UTL to PRIV_MGMT_LAND;
GRANT EXECUTE ON G3E_MANAGEMODLOG TO GIS_ONC WITH GRANT OPTION;

grant EXECUTE on GIS_STG.MAXIMO_IMPORT to GIS;
GRANT EXECUTE ON GISPKG_WMIS_ACCOUNTING TO ADMINISTRATOR;
GRANT EXECUTE ON GISPKG_WMIS_CULIBRARY TO PRIV_SUPPORT, PRIV_ADMIN;
GRANT EXECUTE ON GISPKG_WMIS_WR TO ADMINISTRATOR;

spool off;
