
set echo on
set linesize 1000
set pagesize 300
set trimspool on

exec adm_support.set_start(2666, 'ONCOR-JIRA1777-FiberDesignLegend.sql');
spool c:\temp\2666-20180618-ONCOR-JIRA1777-FiberDesignLegend.log
--**************************************************************************************
--SCRIPT NAME: 2666-20180618-ONCOR-JIRA1777-FiberDesignLegend.sql
--**************************************************************************************
-- AUTHOR			: INGRNET\PVKURELL
-- DATE				: 18-JUN-2018
-- CYCLE			: 00.03.07
-- JIRA NUMBER		: 1777
-- PRODUCT VERSION	: 10.3
-- PRJ IDENTIFIER	: G/TECHNOLOGY - ONCOR
-- PROGRAM DESC	    : UPDATE FIBER Legend to fix error while loading fiber legend
-- SOURCE DATABASE	:
--**************************************************************************************
-- Script Body
--**************************************************************************************


UPDATE G3E_LD_LEGFIBER SET G3E_FILTER='LOCATABLE_YN = ''Y''' WHERE G3E_LENO=560000;
UPDATE G3E_LD_LEGFIBER SET G3E_FILTER='LOCATABLE_YN = ''N''' WHERE G3E_LENO=560010;
UPDATE G3E_LD_LEGFIBER SET G3E_FILTER='LOCATABLE_YN = ''Y''' WHERE G3E_LENO=560100;
UPDATE G3E_LD_LEGFIBER SET G3E_FILTER='LOCATABLE_YN = ''N''' WHERE G3E_LENO=560110;
UPDATE G3E_LD_LEGFIBER SET G3E_FILTER='LOCATABLE_YN = ''Y''' WHERE G3E_LENO=560200;
UPDATE G3E_LD_LEGFIBER SET G3E_FILTER='LOCATABLE_YN = ''N''' WHERE G3E_LENO=560210;
UPDATE G3E_LD_LEGFIBER SET G3E_FILTER='LOCATABLE_YN = ''Y''' WHERE G3E_LENO=560300;
UPDATE G3E_LD_LEGFIBER SET G3E_FILTER='LOCATABLE_YN = ''N''' WHERE G3E_LENO=560310;
UPDATE G3E_LD_LEGFIBER SET G3E_FILTER='LOCATABLE_YN = ''Y''' WHERE G3E_LENO=565001;
UPDATE G3E_LD_LEGFIBER SET G3E_FILTER='LOCATABLE_YN = ''N''' WHERE G3E_LENO=565011;
UPDATE G3E_LD_LEGFIBER SET G3E_FILTER='LOCATABLE_YN = ''Y''' WHERE G3E_LENO=565101;
UPDATE G3E_LD_LEGFIBER SET G3E_FILTER='LOCATABLE_YN = ''N''' WHERE G3E_LENO=565111;
UPDATE G3E_LD_LEGFIBER SET G3E_FILTER='STAGE IN (''Accepted'',''Pending'')' WHERE G3E_LENO=2010000;
UPDATE G3E_LD_LEGFIBER SET G3E_FILTER='STAGE IN (''Accepted'',''Pending'')' WHERE G3E_LENO=2010100;
UPDATE G3E_LD_LEGFIBER SET G3E_FILTER='STAGE IN (''Accepted'',''Pending'')' WHERE G3E_LENO=2020000;
UPDATE G3E_LD_LEGFIBER SET G3E_FILTER='STAGE IN (''Accepted'',''Pending'')' WHERE G3E_LENO=2030100;
UPDATE G3E_LD_LEGFIBER SET G3E_FILTER='STAGE IN (''Accepted'',''Pending'')' WHERE G3E_LENO=2030200;
UPDATE G3E_LD_LEGFIBER SET G3E_FILTER='STAGE IN (''Accepted'',''Pending'')' WHERE G3E_LENO=2040100;
UPDATE G3E_LD_LEGFIBER SET G3E_FILTER='STAGE IN (''Accepted'',''Pending'')' WHERE G3E_LENO=2040200;
UPDATE G3E_LD_LEGFIBER SET G3E_FILTER='STAGE IN (''Accepted'',''Pending'')' WHERE G3E_LENO=2060100;
UPDATE G3E_LD_LEGFIBER SET G3E_FILTER='STAGE IN (''Accepted'',''Pending'')' WHERE G3E_LENO=2060200;
UPDATE G3E_LD_LEGFIBER SET G3E_FILTER='STAGE IN (''Accepted'',''Pending'')' WHERE G3E_LENO=2080000;
UPDATE G3E_LD_LEGFIBER SET G3E_FILTER='STAGE IN (''Accepted'',''Pending'')' WHERE G3E_LENO=2080100;
UPDATE G3E_LD_LEGFIBER SET G3E_FILTER='STAGE IN (''Accepted'',''Pending'')' WHERE G3E_LENO=2090000;
UPDATE G3E_LD_LEGFIBER SET G3E_FILTER='STAGE IN (''Accepted'',''Pending'')' WHERE G3E_LENO=2090100;
UPDATE G3E_LD_LEGFIBER SET G3E_FILTER='STAGE IN (''Accepted'',''Pending'')' WHERE G3E_LENO=2110000;
UPDATE G3E_LD_LEGFIBER SET G3E_FILTER='STAGE IN (''Accepted'',''Pending'')' WHERE G3E_LENO=2110100;
UPDATE G3E_LD_LEGFIBER SET G3E_FILTER='STAGE IN (''Accepted'',''Pending'')' WHERE G3E_LENO=2120000;
UPDATE G3E_LD_LEGFIBER SET G3E_FILTER='STAGE IN (''Accepted'',''Pending'')' WHERE G3E_LENO=2120100;
UPDATE G3E_LD_LEGFIBER SET G3E_FILTER='STAGE IN (''Accepted'',''Pending'')' WHERE G3E_LENO=2130000;
UPDATE G3E_LD_LEGFIBER SET G3E_FILTER='STAGE IN (''Accepted'',''Pending'')' WHERE G3E_LENO=2130100;
UPDATE G3E_LD_LEGFIBER SET G3E_FILTER='STAGE IN (''Accepted'',''Pending'')' WHERE G3E_LENO=2140000;
UPDATE G3E_LD_LEGFIBER SET G3E_FILTER='STAGE IN (''Accepted'',''Pending'')' WHERE G3E_LENO=2140100;
UPDATE G3E_LD_LEGFIBER SET G3E_FILTER='STAGE IN (''Accepted'',''Pending'')' WHERE G3E_LENO=2150000;
UPDATE G3E_LD_LEGFIBER SET G3E_FILTER='STAGE IN (''Accepted'',''Pending'')' WHERE G3E_LENO=2150100;
UPDATE G3E_LD_LEGFIBER SET G3E_FILTER='STAGE IN (''Accepted'',''Pending'')' WHERE G3E_LENO=2160000;
UPDATE G3E_LD_LEGFIBER SET G3E_FILTER='STAGE IN (''Accepted'',''Pending'')' WHERE G3E_LENO=2160100;
UPDATE G3E_LD_LEGFIBER SET G3E_FILTER='STAGE IN (''Accepted'',''Pending'')' WHERE G3E_LENO=2170000;
UPDATE G3E_LD_LEGFIBER SET G3E_FILTER='STAGE IN (''Accepted'',''Pending'')' WHERE G3E_LENO=2170200;
UPDATE G3E_LD_LEGFIBER SET G3E_FILTER='STAGE IN (''Accepted'',''Pending'')' WHERE G3E_LENO=2180000;
UPDATE G3E_LD_LEGFIBER SET G3E_FILTER='STAGE IN (''Accepted'',''Pending'')' WHERE G3E_LENO=2210000;
UPDATE G3E_LD_LEGFIBER SET G3E_FILTER='STAGE IN (''Accepted'',''Pending'')' WHERE G3E_LENO=2210100;
UPDATE G3E_LD_LEGFIBER SET G3E_FILTER='STAGE IN (''Accepted'',''Pending'')' WHERE G3E_LENO=2210200;
UPDATE G3E_LD_LEGFIBER SET G3E_FILTER='STAGE IN (''Accepted'',''Pending'')' WHERE G3E_LENO=2220000;
UPDATE G3E_LD_LEGFIBER SET G3E_FILTER='STAGE IN (''Accepted'',''Pending'')' WHERE G3E_LENO=2220100;
UPDATE G3E_LD_LEGFIBER SET G3E_FILTER='STAGE IN (''Accepted'',''Pending'')' WHERE G3E_LENO=2230000;
UPDATE G3E_LD_LEGFIBER SET G3E_FILTER='STAGE IN (''Accepted'',''Pending'')' WHERE G3E_LENO=2230100;
UPDATE G3E_LD_LEGFIBER SET G3E_FILTER='STAGE IN (''Accepted'',''Pending'')' WHERE G3E_LENO=2230200;
UPDATE G3E_LD_LEGFIBER SET G3E_FILTER='STAGE IN (''Accepted'',''Pending'')' WHERE G3E_LENO=2230300;
UPDATE G3E_LD_LEGFIBER SET G3E_FILTER='STAGE IN (''Accepted'',''Pending'')' WHERE G3E_LENO=2240000;
UPDATE G3E_LD_LEGFIBER SET G3E_FILTER='STAGE IN (''Accepted'',''Pending'')' WHERE G3E_LENO=2240100;
UPDATE G3E_LD_LEGFIBER SET G3E_FILTER='STAGE IN (''Accepted'',''Pending'')' WHERE G3E_LENO=2240200;
UPDATE G3E_LD_LEGFIBER SET G3E_FILTER='STAGE IN (''Accepted'',''Pending'')' WHERE G3E_LENO=2240300;
UPDATE G3E_LD_LEGFIBER SET G3E_FILTER='STAGE IN (''Accepted'',''Pending'')' WHERE G3E_LENO=2270000;
UPDATE G3E_LD_LEGFIBER SET G3E_FILTER='STAGE IN (''Accepted'',''Pending'')' WHERE G3E_LENO=2270100;
UPDATE G3E_LD_LEGFIBER SET G3E_FILTER='STAGE IN (''Accepted'',''Pending'')' WHERE G3E_LENO=2280000;
UPDATE G3E_LD_LEGFIBER SET G3E_FILTER='STAGE IN (''Accepted'',''Pending'')' WHERE G3E_LENO=2280100;
UPDATE G3E_LD_LEGFIBER SET G3E_FILTER='STAGE IN (''Accepted'',''Pending'')' WHERE G3E_LENO=2290000;
UPDATE G3E_LD_LEGFIBER SET G3E_FILTER='STAGE IN (''Accepted'',''Pending'')' WHERE G3E_LENO=2290100;
UPDATE G3E_LD_LEGFIBER SET G3E_FILTER='STAGE IN (''Accepted'',''Pending'')' WHERE G3E_LENO=2300000;
UPDATE G3E_LD_LEGFIBER SET G3E_FILTER='STAGE IN (''Accepted'',''Pending'')' WHERE G3E_LENO=2310000;
UPDATE G3E_LD_LEGFIBER SET G3E_FILTER='STAGE IN (''Accepted'',''Pending'')' WHERE G3E_LENO=2310100;
UPDATE G3E_LD_LEGFIBER SET G3E_FILTER='STAGE IN (''Accepted'',''Pending'')' WHERE G3E_LENO=2320000;
UPDATE G3E_LD_LEGFIBER SET G3E_FILTER='STAGE IN (''Accepted'',''Pending'')' WHERE G3E_LENO=2320100;
UPDATE G3E_LD_LEGFIBER SET G3E_FILTER='STAGE IN (''Accepted'',''Pending'')' WHERE G3E_LENO=2330000;
UPDATE G3E_LD_LEGFIBER SET G3E_FILTER='STAGE IN (''Accepted'',''Pending'')' WHERE G3E_LENO=2330100;
UPDATE G3E_LD_LEGFIBER SET G3E_FILTER='STAGE IN (''Accepted'',''Pending'')' WHERE G3E_LENO=2340000;
UPDATE G3E_LD_LEGFIBER SET G3E_FILTER='STAGE IN (''Accepted'',''Pending'')' WHERE G3E_LENO=2350000;
UPDATE G3E_LD_LEGFIBER SET G3E_FILTER='STAGE IN (''Accepted'',''Pending'')' WHERE G3E_LENO=2350001;
UPDATE G3E_LD_LEGFIBER SET G3E_FILTER='STAGE IN (''Accepted'',''Pending'')' WHERE G3E_LENO=2360000;
UPDATE G3E_LD_LEGFIBER SET G3E_FILTER='STAGE IN (''Accepted'',''Pending'')' WHERE G3E_LENO=2380000;


Update G3E_LDC_LEGFIBER Set G3e_Legenditem='V_VIRTUALPTI_S',G3e_Username='Isolation Point Symbol' where G3e_Legenditem='V_ISOLATION_S';
Update G3E_LDC_LEGFIBER Set G3e_Legenditem='V_VIRTUALPTI_ML' where G3e_Legenditem='V_ISOLATION_ML';
Update G3E_LDC_LEGFIBER Set G3e_Legenditem='V_VIRTUALPTI_LL' where G3e_Legenditem='V_ISOLATION_LL';
Update G3E_LDC_LEGFIBER Set G3e_Legenditem='Accepted/Pending',G3e_Username='Accepted/Pending' where G3e_Legenditem='Accepted/Under Review';

COMMIT;

--**************************************************************************************
-- End Script Body
--**************************************************************************************
spool off;
exec adm_support.set_finish(2666);


