
set echo on
set linesize 1000
set pagesize 300
set trimspool on

spool c:\temp\SysAccess_FeatureRoles.log
--**************************************************************************************
--SCRIPT NAME: SysAccess_FeatureRoles.sql
--**************************************************************************************
-- AUTHOR         		: INGRNET\PVKURELL
-- DATE           		: 05-July-2018
-- PRODUCT VERSION		: 10.3
-- PRJ IDENTIFIER		: G/TECHNOLOGY - ONCOR
-- PROGRAM DESC			: Update Edit and Delete roles for all feature class
-- SOURCE DATABASE		:
--**************************************************************************************
-- Modified:
--  18-JUL-2018, Rich Adase - Changed Work Point delete role to PRIV_DESIGN_ALL
--**************************************************************************************

---*** AMS Collector FNO: 150 *******
Update G3E_FEATURE  Set G3E_SELECTROLE='EVERYONE',G3E_EDITROLE='PRIV_EDIT',G3E_DELETEROLE='PRIV_SUPPORT' Where G3E_FNO=150;

---*** AMS Router FNO: 152 *******
Update G3E_FEATURE  Set G3E_SELECTROLE='EVERYONE',G3E_EDITROLE='PRIV_EDIT',G3E_DELETEROLE='PRIV_SUPPORT' Where G3E_FNO=152;

---*** Area Light FNO: 61 *******
Update G3E_FEATURE  Set G3E_SELECTROLE='EVERYONE',G3E_EDITROLE='PRIV_EDIT',G3E_DELETEROLE='PRIV_SUPPORT' Where G3E_FNO=61;

---*** Arrestor FNO: 33 *******
Update G3E_FEATURE  Set G3E_SELECTROLE='EVERYONE',G3E_EDITROLE='PRIV_EDIT',G3E_DELETEROLE='PRIV_SUPPORT' Where G3E_FNO=33;

---*** Autotransformer FNO: 34 *******
Update G3E_FEATURE  Set G3E_SELECTROLE='EVERYONE',G3E_EDITROLE='PRIV_EDIT',G3E_DELETEROLE='PRIV_SUPPORT' Where G3E_FNO=34;

---*** Bypass Point FNO: 40 *******
Update G3E_FEATURE  Set G3E_SELECTROLE='EVERYONE',G3E_EDITROLE='PRIV_EDIT',G3E_DELETEROLE='PRIV_DESIGN_ALL' Where G3E_FNO=40;

---*** Bypass Point - Network FNO: 80 *******
Update G3E_FEATURE  Set G3E_SELECTROLE='EVERYONE',G3E_EDITROLE='PRIV_DESIGN_NET',G3E_DELETEROLE='PRIV_DESIGN_NET' Where G3E_FNO=80;

---*** CES Battery FNO: 158 *******
Update G3E_FEATURE  Set G3E_SELECTROLE='EVERYONE',G3E_EDITROLE='PRIV_EDIT',G3E_DELETEROLE='PRIV_SUPPORT' Where G3E_FNO=158;

---*** Capacitor FNO: 4 *******
Update G3E_FEATURE  Set G3E_SELECTROLE='EVERYONE',G3E_EDITROLE='PRIV_EDIT',G3E_DELETEROLE='PRIV_SUPPORT' Where G3E_FNO=4;

---*** Conduit FNO: 104 *******
Update G3E_FEATURE  Set G3E_SELECTROLE='EVERYONE',G3E_EDITROLE='PRIV_EDIT',G3E_DELETEROLE='PRIV_SUPPORT' Where G3E_FNO=104;

---*** Corrections Tag FNO: 184 *******
Update G3E_FEATURE  Set G3E_SELECTROLE='EVERYONE',G3E_EDITROLE='PRIV_EDIT',G3E_DELETEROLE='PRIV_DESIGN_ALL' Where G3E_FNO=184;

---*** DA Fiber Modem FNO: 159 *******
Update G3E_FEATURE  Set G3E_SELECTROLE='EVERYONE',G3E_EDITROLE='PRIV_EDIT',G3E_DELETEROLE='PRIV_SUPPORT' Where G3E_FNO=159;

---*** DA Radio FNO: 151 *******
Update G3E_FEATURE  Set G3E_SELECTROLE='EVERYONE',G3E_EDITROLE='PRIV_EDIT',G3E_DELETEROLE='PRIV_SUPPORT' Where G3E_FNO=151;

---*** DOC Note FNO: 219 *******
Update G3E_FEATURE  Set G3E_SELECTROLE='EVERYONE',G3E_EDITROLE='PRIV_EDIT',G3E_DELETEROLE='PRIV_DESIGN_ALL' Where G3E_FNO=219;

---*** Design Area FNO: 8100 *******
Update G3E_FEATURE  Set G3E_SELECTROLE='EVERYONE',G3E_EDITROLE='PRIV_EDIT',G3E_DELETEROLE='PRIV_DESIGN_ALL' Where G3E_FNO=8100;

---*** Duct FNO: 2300 *******
Update G3E_FEATURE  Set G3E_SELECTROLE='EVERYONE',G3E_EDITROLE='PRIV_EDIT',G3E_DELETEROLE='PRIV_SUPPORT' Where G3E_FNO=2300;

---*** Duct Bank FNO: 2200 *******
Update G3E_FEATURE  Set G3E_SELECTROLE='EVERYONE',G3E_EDITROLE='PRIV_EDIT',G3E_DELETEROLE='PRIV_SUPPORT' Where G3E_FNO=2200;

---*** Easement FNO: 220 *******
Update G3E_FEATURE  Set G3E_SELECTROLE='EVERYONE',G3E_EDITROLE='PRIV_EDIT',G3E_DELETEROLE='PRIV_DESIGN_ALL' Where G3E_FNO=220;

---*** Elbow FNO: 41 *******
Update G3E_FEATURE  Set G3E_SELECTROLE='EVERYONE',G3E_EDITROLE='PRIV_EDIT',G3E_DELETEROLE='PRIV_DESIGN_ALL' Where G3E_FNO=41;

---*** Elbow - Network FNO: 81 *******
Update G3E_FEATURE  Set G3E_SELECTROLE='EVERYONE',G3E_EDITROLE='PRIV_DESIGN_NET',G3E_DELETEROLE='PRIV_DESIGN_NET' Where G3E_FNO=81;

---*** Electronic Marker FNO: 118 *******
Update G3E_FEATURE  Set G3E_SELECTROLE='EVERYONE',G3E_EDITROLE='PRIV_EDIT',G3E_DELETEROLE='PRIV_SUPPORT' Where G3E_FNO=118;

---*** Fault Indicator FNO: 7 *******
Update G3E_FEATURE  Set G3E_SELECTROLE='EVERYONE',G3E_EDITROLE='PRIV_EDIT',G3E_DELETEROLE='PRIV_SUPPORT' Where G3E_FNO=7;

---*** Foreign Communications Cable FNO: 7203 *******
Update G3E_FEATURE  Set G3E_SELECTROLE='EVERYONE',G3E_EDITROLE='PRIV_EDIT',G3E_DELETEROLE='PRIV_DESIGN_ALL' Where G3E_FNO=7203;

---*** Foreign Electric Cable FNO: 186 *******
Update G3E_FEATURE  Set G3E_SELECTROLE='EVERYONE',G3E_EDITROLE='PRIV_EDIT',G3E_DELETEROLE='PRIV_DESIGN_ALL' Where G3E_FNO=186;

---*** Formation FNO: 2400 *******
Update G3E_FEATURE  Set G3E_SELECTROLE='EVERYONE',G3E_EDITROLE='PRIV_EDIT',G3E_DELETEROLE='PRIV_SUPPORT' Where G3E_FNO=2400;

---*** Fuse Saver FNO: 37 *******
Update G3E_FEATURE  Set G3E_SELECTROLE='EVERYONE',G3E_EDITROLE='PRIV_EDIT',G3E_DELETEROLE='PRIV_SUPPORT' Where G3E_FNO=37;

---*** Guy FNO: 105 *******
Update G3E_FEATURE  Set G3E_SELECTROLE='EVERYONE',G3E_EDITROLE='PRIV_EDIT',G3E_DELETEROLE='PRIV_SUPPORT' Where G3E_FNO=105;

---*** Inner Duct FNO: 2100 *******
Update G3E_FEATURE  Set G3E_SELECTROLE='EVERYONE',G3E_EDITROLE='PRIV_EDIT',G3E_DELETEROLE='PRIV_DESIGN_ALL' Where G3E_FNO=2100;

---*** Isolation Point FNO: 6 *******
Update G3E_FEATURE  Set G3E_SELECTROLE='EVERYONE',G3E_EDITROLE='PRIV_EDIT',G3E_DELETEROLE='PRIV_DESIGN_ALL' Where G3E_FNO=6;

---*** Isolation Point - Network FNO: 82 *******
Update G3E_FEATURE  Set G3E_SELECTROLE='EVERYONE',G3E_EDITROLE='PRIV_DESIGN_NET',G3E_DELETEROLE='PRIV_DESIGN_NET' Where G3E_FNO=82;

---*** Junction Point FNO: 2500 *******
Update G3E_FEATURE  Set G3E_SELECTROLE='EVERYONE',G3E_EDITROLE='PRIV_EDIT',G3E_DELETEROLE='PRIV_DESIGN_ALL' Where G3E_FNO=2500;

---*** Manhole FNO: 106 *******
Update G3E_FEATURE  Set G3E_SELECTROLE='EVERYONE',G3E_EDITROLE='PRIV_EDIT',G3E_DELETEROLE='PRIV_SUPPORT' Where G3E_FNO=106;

---*** Maximo Work Order FNO: 187 *******
Update G3E_FEATURE  Set G3E_SELECTROLE='EVERYONE',G3E_EDITROLE='NOBODY',G3E_DELETEROLE='NOBODY' Where G3E_FNO=187;

---*** Miscellaneous Structure FNO: 107 *******
Update G3E_FEATURE  Set G3E_SELECTROLE='EVERYONE',G3E_EDITROLE='PRIV_EDIT',G3E_DELETEROLE='PRIV_DESIGN_ALL' Where G3E_FNO=107;

---*** Network Protector FNO: 157 *******
Update G3E_FEATURE  Set G3E_SELECTROLE='EVERYONE',G3E_EDITROLE='PRIV_DESIGN_NET',G3E_DELETEROLE='PRIV_DESIGN_NET' Where G3E_FNO=157;

---*** Pad FNO: 108 *******
Update G3E_FEATURE  Set G3E_SELECTROLE='EVERYONE',G3E_EDITROLE='PRIV_EDIT',G3E_DELETEROLE='PRIV_SUPPORT' Where G3E_FNO=108;

---*** Permanent Note FNO: 225 *******
Update G3E_FEATURE  Set G3E_SELECTROLE='EVERYONE',G3E_EDITROLE='PRIV_EDIT',G3E_DELETEROLE='PRIV_DESIGN_ALL' Where G3E_FNO=225;

---*** Permit FNO: 226 *******
Update G3E_FEATURE  Set G3E_SELECTROLE='EVERYONE',G3E_EDITROLE='PRIV_EDIT',G3E_DELETEROLE='PRIV_DESIGN_ALL' Where G3E_FNO=226;

---*** Phase Connector FNO: 42 *******
Update G3E_FEATURE  Set G3E_SELECTROLE='EVERYONE',G3E_EDITROLE='PRIV_EDIT',G3E_DELETEROLE='PRIV_DESIGN_ALL' Where G3E_FNO=42;

---*** Phase Connector - Network FNO: 83 *******
Update G3E_FEATURE  Set G3E_SELECTROLE='EVERYONE',G3E_EDITROLE='PRIV_DESIGN_NET',G3E_DELETEROLE='PRIV_DESIGN_NET' Where G3E_FNO=83;

---*** Plotting Boundary FNO: 188 *******
Update G3E_FEATURE  Set G3E_SELECTROLE='EVERYONE',G3E_EDITROLE='PRIV_EDIT',G3E_DELETEROLE='PRIV_DESIGN_ALL' Where G3E_FNO=188;

---*** Pole FNO: 110 *******
Update G3E_FEATURE  Set G3E_SELECTROLE='EVERYONE',G3E_EDITROLE='PRIV_EDIT',G3E_DELETEROLE='PRIV_SUPPORT' Where G3E_FNO=110;

---*** Primary Conductor - OH FNO: 8 *******
Update G3E_FEATURE  Set G3E_SELECTROLE='EVERYONE',G3E_EDITROLE='PRIV_EDIT',G3E_DELETEROLE='PRIV_SUPPORT' Where G3E_FNO=8;

---*** Primary Conductor - OH Network FNO: 84 *******
Update G3E_FEATURE  Set G3E_SELECTROLE='EVERYONE',G3E_EDITROLE='PRIV_DESIGN_NET',G3E_DELETEROLE='PRIV_SUPPORT' Where G3E_FNO=84;

---*** Primary Conductor - UG FNO: 9 *******
Update G3E_FEATURE  Set G3E_SELECTROLE='EVERYONE',G3E_EDITROLE='PRIV_EDIT',G3E_DELETEROLE='PRIV_SUPPORT' Where G3E_FNO=9;

---*** Primary Conductor - UG Network FNO: 85 *******
Update G3E_FEATURE  Set G3E_SELECTROLE='EVERYONE',G3E_EDITROLE='PRIV_DESIGN_NET',G3E_DELETEROLE='PRIV_SUPPORT' Where G3E_FNO=85;

---*** Primary Conductor Node FNO: 10 *******
Update G3E_FEATURE  Set G3E_SELECTROLE='EVERYONE',G3E_EDITROLE='PRIV_EDIT',G3E_DELETEROLE='PRIV_DESIGN_ALL' Where G3E_FNO=10;

---*** Primary Enclosure FNO: 5 *******
Update G3E_FEATURE  Set G3E_SELECTROLE='EVERYONE',G3E_EDITROLE='PRIV_EDIT',G3E_DELETEROLE='PRIV_SUPPORT' Where G3E_FNO=5;

---*** Primary Fuse - OH FNO: 11 *******
Update G3E_FEATURE  Set G3E_SELECTROLE='EVERYONE',G3E_EDITROLE='PRIV_EDIT',G3E_DELETEROLE='PRIV_SUPPORT' Where G3E_FNO=11;

---*** Primary Fuse - OH Network FNO: 87 *******
Update G3E_FEATURE  Set G3E_SELECTROLE='EVERYONE',G3E_EDITROLE='PRIV_DESIGN_NET',G3E_DELETEROLE='PRIV_SUPPORT' Where G3E_FNO=87;

---*** Primary Fuse - UG FNO: 38 *******
Update G3E_FEATURE  Set G3E_SELECTROLE='EVERYONE',G3E_EDITROLE='PRIV_EDIT',G3E_DELETEROLE='PRIV_SUPPORT' Where G3E_FNO=38;

---*** Primary Fuse - UG Network FNO: 88 *******
Update G3E_FEATURE  Set G3E_SELECTROLE='EVERYONE',G3E_EDITROLE='PRIV_DESIGN_NET',G3E_DELETEROLE='PRIV_SUPPORT' Where G3E_FNO=88;

---*** Primary Point of Delivery FNO: 12 *******
Update G3E_FEATURE  Set G3E_SELECTROLE='EVERYONE',G3E_EDITROLE='PRIV_EDIT',G3E_DELETEROLE='PRIV_SUPPORT' Where G3E_FNO=12;

---*** Primary Pull Box FNO: 109 *******
Update G3E_FEATURE  Set G3E_SELECTROLE='EVERYONE',G3E_EDITROLE='PRIV_EDIT',G3E_DELETEROLE='PRIV_SUPPORT' Where G3E_FNO=109;

---*** Primary Splice FNO: 21 *******
Update G3E_FEATURE  Set G3E_SELECTROLE='EVERYONE',G3E_EDITROLE='PRIV_EDIT',G3E_DELETEROLE='PRIV_SUPPORT' Where G3E_FNO=21;

---*** Primary Splice - Network FNO: 22 *******
Update G3E_FEATURE  Set G3E_SELECTROLE='EVERYONE',G3E_EDITROLE='PRIV_DESIGN_NET',G3E_DELETEROLE='PRIV_SUPPORT' Where G3E_FNO=22;

---*** Primary Switch - OH FNO: 13 *******
Update G3E_FEATURE  Set G3E_SELECTROLE='EVERYONE',G3E_EDITROLE='PRIV_EDIT',G3E_DELETEROLE='PRIV_SUPPORT' Where G3E_FNO=13;

---*** Primary Switch - OH Network FNO: 89 *******
Update G3E_FEATURE  Set G3E_SELECTROLE='EVERYONE',G3E_EDITROLE='PRIV_DESIGN_NET',G3E_DELETEROLE='PRIV_SUPPORT' Where G3E_FNO=89;

---*** Primary Switch - UG FNO: 39 *******
Update G3E_FEATURE  Set G3E_SELECTROLE='EVERYONE',G3E_EDITROLE='PRIV_EDIT',G3E_DELETEROLE='PRIV_SUPPORT' Where G3E_FNO=39;

---*** Primary Switch - UG Network FNO: 90 *******
Update G3E_FEATURE  Set G3E_SELECTROLE='EVERYONE',G3E_EDITROLE='PRIV_DESIGN_NET',G3E_DELETEROLE='PRIV_SUPPORT' Where G3E_FNO=90;

---*** Primary Switch Gear FNO: 19 *******
Update G3E_FEATURE  Set G3E_SELECTROLE='EVERYONE',G3E_EDITROLE='PRIV_EDIT',G3E_DELETEROLE='PRIV_SUPPORT' Where G3E_FNO=19;

---*** Primary Switch Gear Bus FNO: 20 *******
Update G3E_FEATURE  Set G3E_SELECTROLE='EVERYONE',G3E_EDITROLE='PRIV_EDIT',G3E_DELETEROLE='PRIV_DESIGN_ALL' Where G3E_FNO=20;

---*** Rack FNO: 111 *******
Update G3E_FEATURE  Set G3E_SELECTROLE='EVERYONE',G3E_EDITROLE='PRIV_EDIT',G3E_DELETEROLE='PRIV_SUPPORT' Where G3E_FNO=111;

---*** Recloser - OH FNO: 14 *******
Update G3E_FEATURE  Set G3E_SELECTROLE='EVERYONE',G3E_EDITROLE='PRIV_EDIT',G3E_DELETEROLE='PRIV_SUPPORT' Where G3E_FNO=14;

---*** Recloser - UG FNO: 15 *******
Update G3E_FEATURE  Set G3E_SELECTROLE='EVERYONE',G3E_EDITROLE='PRIV_EDIT',G3E_DELETEROLE='PRIV_SUPPORT' Where G3E_FNO=15;

---*** Remote Terminal Unit FNO: 160 *******
Update G3E_FEATURE  Set G3E_SELECTROLE='EVERYONE',G3E_EDITROLE='PRIV_EDIT',G3E_DELETEROLE='PRIV_SUPPORT' Where G3E_FNO=160;

---*** Riser FNO: 112 *******
Update G3E_FEATURE  Set G3E_SELECTROLE='EVERYONE',G3E_EDITROLE='PRIV_EDIT',G3E_DELETEROLE='PRIV_SUPPORT' Where G3E_FNO=112;

---*** Secondary Box FNO: 113 *******
Update G3E_FEATURE  Set G3E_SELECTROLE='EVERYONE',G3E_EDITROLE='PRIV_EDIT',G3E_DELETEROLE='PRIV_SUPPORT' Where G3E_FNO=113;

---*** Secondary Breaker FNO: 154 *******
Update G3E_FEATURE  Set G3E_SELECTROLE='EVERYONE',G3E_EDITROLE='PRIV_EDIT',G3E_DELETEROLE='PRIV_SUPPORT' Where G3E_FNO=154;

---*** Secondary Breaker - Network FNO: 94 *******
Update G3E_FEATURE  Set G3E_SELECTROLE='EVERYONE',G3E_EDITROLE='PRIV_DESIGN_NET',G3E_DELETEROLE='PRIV_SUPPORT' Where G3E_FNO=94;

---*** Secondary Bus Duct FNO: 52 *******
Update G3E_FEATURE  Set G3E_SELECTROLE='EVERYONE',G3E_EDITROLE='PRIV_EDIT',G3E_DELETEROLE='PRIV_SUPPORT' Where G3E_FNO=52;

---*** Secondary Bus Duct - Network FNO: 95 *******
Update G3E_FEATURE  Set G3E_SELECTROLE='EVERYONE',G3E_EDITROLE='PRIV_DESIGN_NET',G3E_DELETEROLE='PRIV_SUPPORT' Where G3E_FNO=95;

---*** Secondary Conductor - OH FNO: 53 *******
Update G3E_FEATURE  Set G3E_SELECTROLE='EVERYONE',G3E_EDITROLE='PRIV_EDIT',G3E_DELETEROLE='PRIV_SUPPORT' Where G3E_FNO=53;

---*** Secondary Conductor - OH Network FNO: 96 *******
Update G3E_FEATURE  Set G3E_SELECTROLE='EVERYONE',G3E_EDITROLE='PRIV_DESIGN_NET',G3E_DELETEROLE='PRIV_SUPPORT' Where G3E_FNO=96;

---*** Secondary Conductor - UG FNO: 63 *******
Update G3E_FEATURE  Set G3E_SELECTROLE='EVERYONE',G3E_EDITROLE='PRIV_EDIT',G3E_DELETEROLE='PRIV_SUPPORT' Where G3E_FNO=63;

---*** Secondary Conductor - UG Network FNO: 97 *******
Update G3E_FEATURE  Set G3E_SELECTROLE='EVERYONE',G3E_EDITROLE='PRIV_DESIGN_NET',G3E_DELETEROLE='PRIV_SUPPORT' Where G3E_FNO=97;

---*** Secondary Conductor Node FNO: 162 *******
Update G3E_FEATURE  Set G3E_SELECTROLE='EVERYONE',G3E_EDITROLE='PRIV_EDIT',G3E_DELETEROLE='PRIV_DESIGN_ALL' Where G3E_FNO=162;

---*** Secondary Enclosure FNO: 120 *******
Update G3E_FEATURE  Set G3E_SELECTROLE='EVERYONE',G3E_EDITROLE='PRIV_EDIT',G3E_DELETEROLE='PRIV_SUPPORT' Where G3E_FNO=120;

---*** Secondary Fuse FNO: 161 *******
Update G3E_FEATURE  Set G3E_SELECTROLE='EVERYONE',G3E_EDITROLE='PRIV_EDIT',G3E_DELETEROLE='PRIV_SUPPORT' Where G3E_FNO=161;

---*** Secondary Fuse - Network FNO: 86 *******
Update G3E_FEATURE  Set G3E_SELECTROLE='EVERYONE',G3E_EDITROLE='PRIV_DESIGN_NET',G3E_DELETEROLE='PRIV_SUPPORT' Where G3E_FNO=86;

---*** Secondary Splice - Network FNO: 23 *******
Update G3E_FEATURE  Set G3E_SELECTROLE='EVERYONE',G3E_EDITROLE='PRIV_DESIGN_NET',G3E_DELETEROLE='PRIV_SUPPORT' Where G3E_FNO=23;

---*** Secondary Switch Gear FNO: 153 *******
Update G3E_FEATURE  Set G3E_SELECTROLE='EVERYONE',G3E_EDITROLE='PRIV_DESIGN_NET',G3E_DELETEROLE='PRIV_SUPPORT' Where G3E_FNO=153;

---*** Secondary Switch Gear Bus FNO: 155 *******
Update G3E_FEATURE  Set G3E_SELECTROLE='EVERYONE',G3E_EDITROLE='PRIV_DESIGN_NET',G3E_DELETEROLE='PRIV_DESIGN_NET' Where G3E_FNO=155;

---*** Secondary Switch Gear Cabinet FNO: 156 *******
Update G3E_FEATURE  Set G3E_SELECTROLE='EVERYONE',G3E_EDITROLE='PRIV_DESIGN_NET',G3E_DELETEROLE='PRIV_DESIGN_NET' Where G3E_FNO=156;

---*** Service Line FNO: 54 *******
Update G3E_FEATURE  Set G3E_SELECTROLE='EVERYONE',G3E_EDITROLE='PRIV_EDIT',G3E_DELETEROLE='PRIV_SUPPORT' Where G3E_FNO=54;

---*** Service Point FNO: 55 *******
Update G3E_FEATURE  Set G3E_SELECTROLE='EVERYONE',G3E_EDITROLE='PRIV_EDIT',G3E_DELETEROLE='PRIV_SUPPORT' Where G3E_FNO=55;

---*** Street Light FNO: 56 *******
Update G3E_FEATURE  Set G3E_SELECTROLE='EVERYONE',G3E_EDITROLE='PRIV_EDIT',G3E_DELETEROLE='PRIV_SUPPORT' Where G3E_FNO=56;

---*** Street Light Control FNO: 58 *******
Update G3E_FEATURE  Set G3E_SELECTROLE='EVERYONE',G3E_EDITROLE='PRIV_EDIT',G3E_DELETEROLE='PRIV_SUPPORT' Where G3E_FNO=58;

---*** Street Light Standard FNO: 114 *******
Update G3E_FEATURE  Set G3E_SELECTROLE='EVERYONE',G3E_EDITROLE='PRIV_EDIT',G3E_DELETEROLE='PRIV_SUPPORT' Where G3E_FNO=114;

---*** Substation FNO: 115 *******
Update G3E_FEATURE  Set G3E_SELECTROLE='EVERYONE',G3E_EDITROLE='PRIV_MGMT_SSTA',G3E_DELETEROLE='PRIV_MGMT_SSTA' Where G3E_FNO=115;

---*** Substation Breaker FNO: 16 *******
Update G3E_FEATURE  Set G3E_SELECTROLE='EVERYONE',G3E_EDITROLE='PRIV_EDIT',G3E_DELETEROLE='PRIV_SUPPORT' Where G3E_FNO=16;

---*** Substation Breaker - Network FNO: 91 *******
Update G3E_FEATURE  Set G3E_SELECTROLE='EVERYONE',G3E_EDITROLE='PRIV_DESIGN_NET',G3E_DELETEROLE='PRIV_SUPPORT' Where G3E_FNO=91;

---*** Substation Bus FNO: 17 *******
Update G3E_FEATURE  Set G3E_SELECTROLE='EVERYONE',G3E_EDITROLE='PRIV_EDIT',G3E_DELETEROLE='PRIV_DESIGN_ALL' Where G3E_FNO=17;

---*** Substation Transformer FNO: 18 *******
Update G3E_FEATURE  Set G3E_SELECTROLE='EVERYONE',G3E_EDITROLE='PRIV_EDIT',G3E_DELETEROLE='PRIV_DESIGN_ALL' Where G3E_FNO=18;

---*** Traffic Light FNO: 62 *******
Update G3E_FEATURE  Set G3E_SELECTROLE='EVERYONE',G3E_EDITROLE='PRIV_MGMT_STLT',G3E_DELETEROLE='PRIV_MGMT_STLT' Where G3E_FNO=62;

---*** Transformer - OH FNO: 59 *******
Update G3E_FEATURE  Set G3E_SELECTROLE='EVERYONE',G3E_EDITROLE='PRIV_EDIT',G3E_DELETEROLE='PRIV_SUPPORT' Where G3E_FNO=59;

---*** Transformer - OH Network FNO: 98 *******
Update G3E_FEATURE  Set G3E_SELECTROLE='EVERYONE',G3E_EDITROLE='PRIV_DESIGN_NET',G3E_DELETEROLE='PRIV_SUPPORT' Where G3E_FNO=98;

---*** Transformer - UG FNO: 60 *******
Update G3E_FEATURE  Set G3E_SELECTROLE='EVERYONE',G3E_EDITROLE='PRIV_EDIT',G3E_DELETEROLE='PRIV_SUPPORT' Where G3E_FNO=60;

---*** Transformer - UG Network FNO: 99 *******
Update G3E_FEATURE  Set G3E_SELECTROLE='EVERYONE',G3E_EDITROLE='PRIV_DESIGN_NET',G3E_DELETEROLE='PRIV_SUPPORT' Where G3E_FNO=99;

---*** Transmission Tower FNO: 116 *******
Update G3E_FEATURE  Set G3E_SELECTROLE='EVERYONE',G3E_EDITROLE='PRIV_EDIT',G3E_DELETEROLE='PRIV_DESIGN_ALL' Where G3E_FNO=116;

---*** Tree-trimming Voucher FNO: 190 *******
Update G3E_FEATURE  Set G3E_SELECTROLE='EVERYONE',G3E_EDITROLE='PRIV_EDIT',G3E_DELETEROLE='PRIV_DESIGN_ALL' Where G3E_FNO=190;

---*** Vault FNO: 117 *******
Update G3E_FEATURE  Set G3E_SELECTROLE='EVERYONE',G3E_EDITROLE='PRIV_EDIT',G3E_DELETEROLE='PRIV_SUPPORT' Where G3E_FNO=117;

---*** Voltage Regulator FNO: 36 *******
Update G3E_FEATURE  Set G3E_SELECTROLE='EVERYONE',G3E_EDITROLE='PRIV_EDIT',G3E_DELETEROLE='PRIV_SUPPORT' Where G3E_FNO=36;

---*** Work Point FNO: 191 *******
Update G3E_FEATURE  Set G3E_SELECTROLE='EVERYONE',G3E_EDITROLE='PRIV_EDIT',G3E_DELETEROLE='PRIV_DESIGN_ALL' Where G3E_FNO=191;

spool off;