
set echo on
set linesize 1000
set pagesize 300
set trimspool on

spool c:\temp\CoreModel_PlacementSelection.log
--**************************************************************************************
--SCRIPT NAME: CoreModel_PlacementSelection.sql
--**************************************************************************************
-- AUTHOR         		: INGRNET\PVKURELL
-- DATE           		: 06-July-2018
-- PRODUCT VERSION		: 10.3
-- PRJ IDENTIFIER		: G/TECHNOLOGY - ONCOR
-- PROGRAM DESC			: Update PlacementSelection including role as per latest DFS
--**************************************************************************************
-- Modified:
--  18-JUL-2018, Rich Adase -- Corrected role for Tree-Trimming Voucher and Work Point from PRIV_DESIGN_NET to PRIV_DESIGN_ALL
--**************************************************************************************

Delete from G3E_PLACEMENTSELECTION;

Insert into G3E_PLACEMENTSELECTION (G3E_PCNO,G3E_FNO,G3E_USERNAME,G3E_LEVEL,G3E_ORDINAL,G3E_EDITDATE,G3E_PSROWNO,G3E_ICONORDINAL,G3E_ROLE) values (NULL,NULL,'Communications',1,10,sysdate,10,0,'PRIV_DESIGN_ALL');
Insert into G3E_PLACEMENTSELECTION (G3E_PCNO,G3E_FNO,G3E_USERNAME,G3E_LEVEL,G3E_ORDINAL,G3E_EDITDATE,G3E_PSROWNO,G3E_ICONORDINAL,G3E_ROLE) values (NULL,150,'AMS Collector',2,20,sysdate,20,0,'PRIV_DESIGN_ALL');
Insert into G3E_PLACEMENTSELECTION (G3E_PCNO,G3E_FNO,G3E_USERNAME,G3E_LEVEL,G3E_ORDINAL,G3E_EDITDATE,G3E_PSROWNO,G3E_ICONORDINAL,G3E_ROLE) values (NULL,152,'AMS Router',2,30,sysdate,30,0,'PRIV_DESIGN_ALL');
Insert into G3E_PLACEMENTSELECTION (G3E_PCNO,G3E_FNO,G3E_USERNAME,G3E_LEVEL,G3E_ORDINAL,G3E_EDITDATE,G3E_PSROWNO,G3E_ICONORDINAL,G3E_ROLE) values (NULL,158,'CES Battery',2,40,sysdate,40,0,'PRIV_DESIGN_ALL');
Insert into G3E_PLACEMENTSELECTION (G3E_PCNO,G3E_FNO,G3E_USERNAME,G3E_LEVEL,G3E_ORDINAL,G3E_EDITDATE,G3E_PSROWNO,G3E_ICONORDINAL,G3E_ROLE) values (NULL,159,'DA Fiber Modem',2,50,sysdate,50,0,'PRIV_DESIGN_ALL');
Insert into G3E_PLACEMENTSELECTION (G3E_PCNO,G3E_FNO,G3E_USERNAME,G3E_LEVEL,G3E_ORDINAL,G3E_EDITDATE,G3E_PSROWNO,G3E_ICONORDINAL,G3E_ROLE) values (NULL,151,'DA Radio',2,60,sysdate,60,0,'PRIV_DESIGN_ALL');
Insert into G3E_PLACEMENTSELECTION (G3E_PCNO,G3E_FNO,G3E_USERNAME,G3E_LEVEL,G3E_ORDINAL,G3E_EDITDATE,G3E_PSROWNO,G3E_ICONORDINAL,G3E_ROLE) values (NULL,160,'Remote Terminal Unit',2,70,sysdate,70,0,'PRIV_DESIGN_ALL');
Insert into G3E_PLACEMENTSELECTION (G3E_PCNO,G3E_FNO,G3E_USERNAME,G3E_LEVEL,G3E_ORDINAL,G3E_EDITDATE,G3E_PSROWNO,G3E_ICONORDINAL,G3E_ROLE) values (NULL,NULL,'Primary',1,80,sysdate,80,0,'PRIV_EDIT');
Insert into G3E_PLACEMENTSELECTION (G3E_PCNO,G3E_FNO,G3E_USERNAME,G3E_LEVEL,G3E_ORDINAL,G3E_EDITDATE,G3E_PSROWNO,G3E_ICONORDINAL,G3E_ROLE) values (NULL,33,'Arrestor',2,90,sysdate,90,0,'PRIV_DESIGN_ALL');
Insert into G3E_PLACEMENTSELECTION (G3E_PCNO,G3E_FNO,G3E_USERNAME,G3E_LEVEL,G3E_ORDINAL,G3E_EDITDATE,G3E_PSROWNO,G3E_ICONORDINAL,G3E_ROLE) values (403,NULL,'Autotransformer',2,100,sysdate,100,0,'PRIV_DESIGN_ALL');
Insert into G3E_PLACEMENTSELECTION (G3E_PCNO,G3E_FNO,G3E_USERNAME,G3E_LEVEL,G3E_ORDINAL,G3E_EDITDATE,G3E_PSROWNO,G3E_ICONORDINAL,G3E_ROLE) values (400,NULL,'Capacitor',2,110,sysdate,110,0,'PRIV_DESIGN_ALL');
Insert into G3E_PLACEMENTSELECTION (G3E_PCNO,G3E_FNO,G3E_USERNAME,G3E_LEVEL,G3E_ORDINAL,G3E_EDITDATE,G3E_PSROWNO,G3E_ICONORDINAL,G3E_ROLE) values (NULL,118,'Electronic Marker',2,120,sysdate,120,0,'PRIV_DESIGN_ALL');
Insert into G3E_PLACEMENTSELECTION (G3E_PCNO,G3E_FNO,G3E_USERNAME,G3E_LEVEL,G3E_ORDINAL,G3E_EDITDATE,G3E_PSROWNO,G3E_ICONORDINAL,G3E_ROLE) values (NULL,7,'Fault Indicator',2,130,sysdate,130,0,'PRIV_DESIGN_ALL');
Insert into G3E_PLACEMENTSELECTION (G3E_PCNO,G3E_FNO,G3E_USERNAME,G3E_LEVEL,G3E_ORDINAL,G3E_EDITDATE,G3E_PSROWNO,G3E_ICONORDINAL,G3E_ROLE) values (NULL,37,'Fuse Saver',2,140,sysdate,140,0,'PRIV_DESIGN_ALL');
Insert into G3E_PLACEMENTSELECTION (G3E_PCNO,G3E_FNO,G3E_USERNAME,G3E_LEVEL,G3E_ORDINAL,G3E_EDITDATE,G3E_PSROWNO,G3E_ICONORDINAL,G3E_ROLE) values (NULL,8,'Primary Conductor - OH',2,150,sysdate,150,0,'PRIV_DESIGN_ALL');
Insert into G3E_PLACEMENTSELECTION (G3E_PCNO,G3E_FNO,G3E_USERNAME,G3E_LEVEL,G3E_ORDINAL,G3E_EDITDATE,G3E_PSROWNO,G3E_ICONORDINAL,G3E_ROLE) values (NULL,9,'Primary Conductor - UG',2,160,sysdate,160,0,'PRIV_DESIGN_ALL');
Insert into G3E_PLACEMENTSELECTION (G3E_PCNO,G3E_FNO,G3E_USERNAME,G3E_LEVEL,G3E_ORDINAL,G3E_EDITDATE,G3E_PSROWNO,G3E_ICONORDINAL,G3E_ROLE) values (NULL,10,'Primary Conductor Node',2,170,sysdate,170,0,'PRIV_EDIT');
Insert into G3E_PLACEMENTSELECTION (G3E_PCNO,G3E_FNO,G3E_USERNAME,G3E_LEVEL,G3E_ORDINAL,G3E_EDITDATE,G3E_PSROWNO,G3E_ICONORDINAL,G3E_ROLE) values (NULL,5,'Primary Enclosure',2,180,sysdate,180,0,'PRIV_DESIGN_ALL');
Insert into G3E_PLACEMENTSELECTION (G3E_PCNO,G3E_FNO,G3E_USERNAME,G3E_LEVEL,G3E_ORDINAL,G3E_EDITDATE,G3E_PSROWNO,G3E_ICONORDINAL,G3E_ROLE) values (401,NULL,'Primary Enclosure + Elbows',2,190,sysdate,190,0,'PRIV_DESIGN_ALL');
Insert into G3E_PLACEMENTSELECTION (G3E_PCNO,G3E_FNO,G3E_USERNAME,G3E_LEVEL,G3E_ORDINAL,G3E_EDITDATE,G3E_PSROWNO,G3E_ICONORDINAL,G3E_ROLE) values (NULL,11,'Primary Fuse - OH',2,200,sysdate,200,0,'PRIV_DESIGN_ALL');
Insert into G3E_PLACEMENTSELECTION (G3E_PCNO,G3E_FNO,G3E_USERNAME,G3E_LEVEL,G3E_ORDINAL,G3E_EDITDATE,G3E_PSROWNO,G3E_ICONORDINAL,G3E_ROLE) values (NULL,38,'Primary Fuse - UG',2,210,sysdate,210,0,'PRIV_DESIGN_ALL');
Insert into G3E_PLACEMENTSELECTION (G3E_PCNO,G3E_FNO,G3E_USERNAME,G3E_LEVEL,G3E_ORDINAL,G3E_EDITDATE,G3E_PSROWNO,G3E_ICONORDINAL,G3E_ROLE) values (1201,NULL,'Primary Point of Delivery',2,220,sysdate,220,0,'PRIV_DESIGN_ALL');
Insert into G3E_PLACEMENTSELECTION (G3E_PCNO,G3E_FNO,G3E_USERNAME,G3E_LEVEL,G3E_ORDINAL,G3E_EDITDATE,G3E_PSROWNO,G3E_ICONORDINAL,G3E_ROLE) values (NULL,21,'Primary Splice',2,230,sysdate,230,0,'PRIV_DESIGN_ALL');
Insert into G3E_PLACEMENTSELECTION (G3E_PCNO,G3E_FNO,G3E_USERNAME,G3E_LEVEL,G3E_ORDINAL,G3E_EDITDATE,G3E_PSROWNO,G3E_ICONORDINAL,G3E_ROLE) values (NULL,13,'Primary Switch - OH',2,240,sysdate,240,0,'PRIV_DESIGN_ALL');
Insert into G3E_PLACEMENTSELECTION (G3E_PCNO,G3E_FNO,G3E_USERNAME,G3E_LEVEL,G3E_ORDINAL,G3E_EDITDATE,G3E_PSROWNO,G3E_ICONORDINAL,G3E_ROLE) values (NULL,39,'Primary Switch - UG',2,250,sysdate,250,0,'PRIV_DESIGN_ALL');
Insert into G3E_PLACEMENTSELECTION (G3E_PCNO,G3E_FNO,G3E_USERNAME,G3E_LEVEL,G3E_ORDINAL,G3E_EDITDATE,G3E_PSROWNO,G3E_ICONORDINAL,G3E_ROLE) values (NULL,19,'Primary Switch Gear',2,260,sysdate,260,0,'PRIV_DESIGN_ALL');
Insert into G3E_PLACEMENTSELECTION (G3E_PCNO,G3E_FNO,G3E_USERNAME,G3E_LEVEL,G3E_ORDINAL,G3E_EDITDATE,G3E_PSROWNO,G3E_ICONORDINAL,G3E_ROLE) values (NULL,20,'Primary Switch Gear Bus',2,270,sysdate,270,0,'PRIV_DESIGN_ALL');
Insert into G3E_PLACEMENTSELECTION (G3E_PCNO,G3E_FNO,G3E_USERNAME,G3E_LEVEL,G3E_ORDINAL,G3E_EDITDATE,G3E_PSROWNO,G3E_ICONORDINAL,G3E_ROLE) values (405,NULL,'Recloser - OH',2,280,sysdate,280,0,'PRIV_DESIGN_ALL');
Insert into G3E_PLACEMENTSELECTION (G3E_PCNO,G3E_FNO,G3E_USERNAME,G3E_LEVEL,G3E_ORDINAL,G3E_EDITDATE,G3E_PSROWNO,G3E_ICONORDINAL,G3E_ROLE) values (402,NULL,'Recloser - UG',2,290,sysdate,290,0,'PRIV_DESIGN_ALL');
Insert into G3E_PLACEMENTSELECTION (G3E_PCNO,G3E_FNO,G3E_USERNAME,G3E_LEVEL,G3E_ORDINAL,G3E_EDITDATE,G3E_PSROWNO,G3E_ICONORDINAL,G3E_ROLE) values (NULL,16,'Substation Breaker',2,300,sysdate,300,0,'PRIV_DESIGN_ALL');
Insert into G3E_PLACEMENTSELECTION (G3E_PCNO,G3E_FNO,G3E_USERNAME,G3E_LEVEL,G3E_ORDINAL,G3E_EDITDATE,G3E_PSROWNO,G3E_ICONORDINAL,G3E_ROLE) values (NULL,17,'Substation Bus',2,310,sysdate,310,0,'PRIV_DESIGN_ALL');
Insert into G3E_PLACEMENTSELECTION (G3E_PCNO,G3E_FNO,G3E_USERNAME,G3E_LEVEL,G3E_ORDINAL,G3E_EDITDATE,G3E_PSROWNO,G3E_ICONORDINAL,G3E_ROLE) values (NULL,18,'Substation Transformer',2,320,sysdate,320,0,'PRIV_DESIGN_ALL');
Insert into G3E_PLACEMENTSELECTION (G3E_PCNO,G3E_FNO,G3E_USERNAME,G3E_LEVEL,G3E_ORDINAL,G3E_EDITDATE,G3E_PSROWNO,G3E_ICONORDINAL,G3E_ROLE) values (414,NULL,'Voltage Regulator',2,330,sysdate,330,0,'PRIV_DESIGN_ALL');
Insert into G3E_PLACEMENTSELECTION (G3E_PCNO,G3E_FNO,G3E_USERNAME,G3E_LEVEL,G3E_ORDINAL,G3E_EDITDATE,G3E_PSROWNO,G3E_ICONORDINAL,G3E_ROLE) values (NULL,NULL,'Secondary',1,340,sysdate,340,0,'PRIV_EDIT');
Insert into G3E_PLACEMENTSELECTION (G3E_PCNO,G3E_FNO,G3E_USERNAME,G3E_LEVEL,G3E_ORDINAL,G3E_EDITDATE,G3E_PSROWNO,G3E_ICONORDINAL,G3E_ROLE) values (NULL,61,'Area Light',2,350,sysdate,350,0,'PRIV_DESIGN_ALL');
Insert into G3E_PLACEMENTSELECTION (G3E_PCNO,G3E_FNO,G3E_USERNAME,G3E_LEVEL,G3E_ORDINAL,G3E_EDITDATE,G3E_PSROWNO,G3E_ICONORDINAL,G3E_ROLE) values (NULL,154,'Secondary Breaker',2,360,sysdate,360,0,'PRIV_DESIGN_ALL');
Insert into G3E_PLACEMENTSELECTION (G3E_PCNO,G3E_FNO,G3E_USERNAME,G3E_LEVEL,G3E_ORDINAL,G3E_EDITDATE,G3E_PSROWNO,G3E_ICONORDINAL,G3E_ROLE) values (NULL,52,'Secondary Bus Duct',2,370,sysdate,370,0,'PRIV_EDIT');
Insert into G3E_PLACEMENTSELECTION (G3E_PCNO,G3E_FNO,G3E_USERNAME,G3E_LEVEL,G3E_ORDINAL,G3E_EDITDATE,G3E_PSROWNO,G3E_ICONORDINAL,G3E_ROLE) values (NULL,53,'Secondary Conductor - OH',2,380,sysdate,380,0,'PRIV_DESIGN_ALL');
Insert into G3E_PLACEMENTSELECTION (G3E_PCNO,G3E_FNO,G3E_USERNAME,G3E_LEVEL,G3E_ORDINAL,G3E_EDITDATE,G3E_PSROWNO,G3E_ICONORDINAL,G3E_ROLE) values (NULL,63,'Secondary Conductor - UG',2,390,sysdate,390,0,'PRIV_DESIGN_ALL');
Insert into G3E_PLACEMENTSELECTION (G3E_PCNO,G3E_FNO,G3E_USERNAME,G3E_LEVEL,G3E_ORDINAL,G3E_EDITDATE,G3E_PSROWNO,G3E_ICONORDINAL,G3E_ROLE) values (NULL,162,'Secondary Conductor Node',2,400,sysdate,400,0,'PRIV_EDIT');
Insert into G3E_PLACEMENTSELECTION (G3E_PCNO,G3E_FNO,G3E_USERNAME,G3E_LEVEL,G3E_ORDINAL,G3E_EDITDATE,G3E_PSROWNO,G3E_ICONORDINAL,G3E_ROLE) values (NULL,161,'Secondary Fuse',2,410,sysdate,410,0,'PRIV_DESIGN_ALL');
Insert into G3E_PLACEMENTSELECTION (G3E_PCNO,G3E_FNO,G3E_USERNAME,G3E_LEVEL,G3E_ORDINAL,G3E_EDITDATE,G3E_PSROWNO,G3E_ICONORDINAL,G3E_ROLE) values (NULL,153,'Secondary Switch Gear',2,420,sysdate,420,0,'PRIV_DESIGN_ALL');
Insert into G3E_PLACEMENTSELECTION (G3E_PCNO,G3E_FNO,G3E_USERNAME,G3E_LEVEL,G3E_ORDINAL,G3E_EDITDATE,G3E_PSROWNO,G3E_ICONORDINAL,G3E_ROLE) values (NULL,155,'Secondary Switch Gear Bus',2,430,sysdate,430,0,'PRIV_DESIGN_ALL');
Insert into G3E_PLACEMENTSELECTION (G3E_PCNO,G3E_FNO,G3E_USERNAME,G3E_LEVEL,G3E_ORDINAL,G3E_EDITDATE,G3E_PSROWNO,G3E_ICONORDINAL,G3E_ROLE) values (NULL,156,'Secondary Switch Gear Cabinet',2,440,sysdate,440,0,'PRIV_DESIGN_ALL');
Insert into G3E_PLACEMENTSELECTION (G3E_PCNO,G3E_FNO,G3E_USERNAME,G3E_LEVEL,G3E_ORDINAL,G3E_EDITDATE,G3E_PSROWNO,G3E_ICONORDINAL,G3E_ROLE) values (NULL,54,'Service Line',2,450,sysdate,450,0,'PRIV_DESIGN_ALL');
Insert into G3E_PLACEMENTSELECTION (G3E_PCNO,G3E_FNO,G3E_USERNAME,G3E_LEVEL,G3E_ORDINAL,G3E_EDITDATE,G3E_PSROWNO,G3E_ICONORDINAL,G3E_ROLE) values (NULL,55,'Service Point',2,460,sysdate,460,0,'PRIV_EDIT');
Insert into G3E_PLACEMENTSELECTION (G3E_PCNO,G3E_FNO,G3E_USERNAME,G3E_LEVEL,G3E_ORDINAL,G3E_EDITDATE,G3E_PSROWNO,G3E_ICONORDINAL,G3E_ROLE) values (NULL,56,'Street Light',2,470,sysdate,470,0,'PRIV_DESIGN_ALL');
Insert into G3E_PLACEMENTSELECTION (G3E_PCNO,G3E_FNO,G3E_USERNAME,G3E_LEVEL,G3E_ORDINAL,G3E_EDITDATE,G3E_PSROWNO,G3E_ICONORDINAL,G3E_ROLE) values (413,NULL,'Street Light + Standard',2,480,sysdate,480,0,'PRIV_DESIGN_ALL');
Insert into G3E_PLACEMENTSELECTION (G3E_PCNO,G3E_FNO,G3E_USERNAME,G3E_LEVEL,G3E_ORDINAL,G3E_EDITDATE,G3E_PSROWNO,G3E_ICONORDINAL,G3E_ROLE) values (416,NULL,'Street Light + Misc Structure',2,490,sysdate,490,0,'PRIV_DESIGN_ALL');
Insert into G3E_PLACEMENTSELECTION (G3E_PCNO,G3E_FNO,G3E_USERNAME,G3E_LEVEL,G3E_ORDINAL,G3E_EDITDATE,G3E_PSROWNO,G3E_ICONORDINAL,G3E_ROLE) values (NULL,58,'Street Light Control',2,500,sysdate,500,0,'PRIV_DESIGN_ALL');
Insert into G3E_PLACEMENTSELECTION (G3E_PCNO,G3E_FNO,G3E_USERNAME,G3E_LEVEL,G3E_ORDINAL,G3E_EDITDATE,G3E_PSROWNO,G3E_ICONORDINAL,G3E_ROLE) values (NULL,62,'Traffic Light',2,510,sysdate,510,0,'PRIV_MGMT_STLT');
Insert into G3E_PLACEMENTSELECTION (G3E_PCNO,G3E_FNO,G3E_USERNAME,G3E_LEVEL,G3E_ORDINAL,G3E_EDITDATE,G3E_PSROWNO,G3E_ICONORDINAL,G3E_ROLE) values (NULL,59,'Transformer - OH',2,520,sysdate,520,0,'PRIV_DESIGN_ALL');
Insert into G3E_PLACEMENTSELECTION (G3E_PCNO,G3E_FNO,G3E_USERNAME,G3E_LEVEL,G3E_ORDINAL,G3E_EDITDATE,G3E_PSROWNO,G3E_ICONORDINAL,G3E_ROLE) values (NULL,60,'Transformer - UG',2,530,sysdate,530,0,'PRIV_DESIGN_ALL');
Insert into G3E_PLACEMENTSELECTION (G3E_PCNO,G3E_FNO,G3E_USERNAME,G3E_LEVEL,G3E_ORDINAL,G3E_EDITDATE,G3E_PSROWNO,G3E_ICONORDINAL,G3E_ROLE) values (408,NULL,'Transformer - UG Loop Feed',2,540,sysdate,540,0,'PRIV_DESIGN_ALL');
Insert into G3E_PLACEMENTSELECTION (G3E_PCNO,G3E_FNO,G3E_USERNAME,G3E_LEVEL,G3E_ORDINAL,G3E_EDITDATE,G3E_PSROWNO,G3E_ICONORDINAL,G3E_ROLE) values (411,NULL,'Transformer - UG Loop Feed + Pad',2,550,sysdate,550,0,'PRIV_DESIGN_ALL');
Insert into G3E_PLACEMENTSELECTION (G3E_PCNO,G3E_FNO,G3E_USERNAME,G3E_LEVEL,G3E_ORDINAL,G3E_EDITDATE,G3E_PSROWNO,G3E_ICONORDINAL,G3E_ROLE) values (410,NULL,'Transformer - UG Radial',2,560,sysdate,560,0,'PRIV_DESIGN_ALL');
Insert into G3E_PLACEMENTSELECTION (G3E_PCNO,G3E_FNO,G3E_USERNAME,G3E_LEVEL,G3E_ORDINAL,G3E_EDITDATE,G3E_PSROWNO,G3E_ICONORDINAL,G3E_ROLE) values (412,NULL,'Transformer - UG Radial + Pad',2,570,sysdate,570,0,'PRIV_DESIGN_ALL');
Insert into G3E_PLACEMENTSELECTION (G3E_PCNO,G3E_FNO,G3E_USERNAME,G3E_LEVEL,G3E_ORDINAL,G3E_EDITDATE,G3E_PSROWNO,G3E_ICONORDINAL,G3E_ROLE) values (NULL,NULL,'Structure',1,580,sysdate,580,0,'PRIV_EDIT');
Insert into G3E_PLACEMENTSELECTION (G3E_PCNO,G3E_FNO,G3E_USERNAME,G3E_LEVEL,G3E_ORDINAL,G3E_EDITDATE,G3E_PSROWNO,G3E_ICONORDINAL,G3E_ROLE) values (NULL,104,'Conduit',2,590,sysdate,590,0,'PRIV_DESIGN_ALL');
Insert into G3E_PLACEMENTSELECTION (G3E_PCNO,G3E_FNO,G3E_USERNAME,G3E_LEVEL,G3E_ORDINAL,G3E_EDITDATE,G3E_PSROWNO,G3E_ICONORDINAL,G3E_ROLE) values (NULL,2200,'Duct Bank',2,600,sysdate,600,3,'PRIV_DESIGN_ALL');
Insert into G3E_PLACEMENTSELECTION (G3E_PCNO,G3E_FNO,G3E_USERNAME,G3E_LEVEL,G3E_ORDINAL,G3E_EDITDATE,G3E_PSROWNO,G3E_ICONORDINAL,G3E_ROLE) values (NULL,105,'Guy',2,610,sysdate,610,0,'PRIV_DESIGN_ALL');
Insert into G3E_PLACEMENTSELECTION (G3E_PCNO,G3E_FNO,G3E_USERNAME,G3E_LEVEL,G3E_ORDINAL,G3E_EDITDATE,G3E_PSROWNO,G3E_ICONORDINAL,G3E_ROLE) values (NULL,2500,'Junction Point',2,620,sysdate,620,5,'PRIV_EDIT');
Insert into G3E_PLACEMENTSELECTION (G3E_PCNO,G3E_FNO,G3E_USERNAME,G3E_LEVEL,G3E_ORDINAL,G3E_EDITDATE,G3E_PSROWNO,G3E_ICONORDINAL,G3E_ROLE) values (NULL,106,'Manhole',2,630,sysdate,630,0,'PRIV_DESIGN_ALL');
Insert into G3E_PLACEMENTSELECTION (G3E_PCNO,G3E_FNO,G3E_USERNAME,G3E_LEVEL,G3E_ORDINAL,G3E_EDITDATE,G3E_PSROWNO,G3E_ICONORDINAL,G3E_ROLE) values (NULL,107,'Miscellaneous Structure',2,640,sysdate,640,0,'PRIV_EDIT');
Insert into G3E_PLACEMENTSELECTION (G3E_PCNO,G3E_FNO,G3E_USERNAME,G3E_LEVEL,G3E_ORDINAL,G3E_EDITDATE,G3E_PSROWNO,G3E_ICONORDINAL,G3E_ROLE) values (NULL,108,'Pad',2,650,sysdate,650,0,'PRIV_DESIGN_ALL');
Insert into G3E_PLACEMENTSELECTION (G3E_PCNO,G3E_FNO,G3E_USERNAME,G3E_LEVEL,G3E_ORDINAL,G3E_EDITDATE,G3E_PSROWNO,G3E_ICONORDINAL,G3E_ROLE) values (NULL,110,'Pole',2,660,sysdate,660,0,'PRIV_DESIGN_ALL');
Insert into G3E_PLACEMENTSELECTION (G3E_PCNO,G3E_FNO,G3E_USERNAME,G3E_LEVEL,G3E_ORDINAL,G3E_EDITDATE,G3E_PSROWNO,G3E_ICONORDINAL,G3E_ROLE) values (NULL,109,'Primary Pull Box',2,670,sysdate,670,0,'PRIV_DESIGN_ALL');
Insert into G3E_PLACEMENTSELECTION (G3E_PCNO,G3E_FNO,G3E_USERNAME,G3E_LEVEL,G3E_ORDINAL,G3E_EDITDATE,G3E_PSROWNO,G3E_ICONORDINAL,G3E_ROLE) values (NULL,111,'Rack',2,680,sysdate,680,0,'PRIV_DESIGN_ALL');
Insert into G3E_PLACEMENTSELECTION (G3E_PCNO,G3E_FNO,G3E_USERNAME,G3E_LEVEL,G3E_ORDINAL,G3E_EDITDATE,G3E_PSROWNO,G3E_ICONORDINAL,G3E_ROLE) values (406,NULL,'Riser - Primary',2,690,sysdate,690,0,'PRIV_DESIGN_ALL');
Insert into G3E_PLACEMENTSELECTION (G3E_PCNO,G3E_FNO,G3E_USERNAME,G3E_LEVEL,G3E_ORDINAL,G3E_EDITDATE,G3E_PSROWNO,G3E_ICONORDINAL,G3E_ROLE) values (407,NULL,'Riser - Secondary',2,700,sysdate,700,0,'PRIV_DESIGN_ALL');
Insert into G3E_PLACEMENTSELECTION (G3E_PCNO,G3E_FNO,G3E_USERNAME,G3E_LEVEL,G3E_ORDINAL,G3E_EDITDATE,G3E_PSROWNO,G3E_ICONORDINAL,G3E_ROLE) values (NULL,113,'Secondary Box',2,710,sysdate,710,0,'PRIV_DESIGN_ALL');
Insert into G3E_PLACEMENTSELECTION (G3E_PCNO,G3E_FNO,G3E_USERNAME,G3E_LEVEL,G3E_ORDINAL,G3E_EDITDATE,G3E_PSROWNO,G3E_ICONORDINAL,G3E_ROLE) values (NULL,120,'Secondary Enclosure',2,720,sysdate,720,0,'PRIV_DESIGN_ALL');
Insert into G3E_PLACEMENTSELECTION (G3E_PCNO,G3E_FNO,G3E_USERNAME,G3E_LEVEL,G3E_ORDINAL,G3E_EDITDATE,G3E_PSROWNO,G3E_ICONORDINAL,G3E_ROLE) values (NULL,114,'Street Light Standard',2,730,sysdate,730,0,'PRIV_DESIGN_ALL');
Insert into G3E_PLACEMENTSELECTION (G3E_PCNO,G3E_FNO,G3E_USERNAME,G3E_LEVEL,G3E_ORDINAL,G3E_EDITDATE,G3E_PSROWNO,G3E_ICONORDINAL,G3E_ROLE) values (NULL,115,'Substation',2,740,sysdate,740,0,'PRIV_MGMT_SSTA');
Insert into G3E_PLACEMENTSELECTION (G3E_PCNO,G3E_FNO,G3E_USERNAME,G3E_LEVEL,G3E_ORDINAL,G3E_EDITDATE,G3E_PSROWNO,G3E_ICONORDINAL,G3E_ROLE) values (NULL,116,'Transmission Tower',2,750,sysdate,750,0,'PRIV_EDIT');
Insert into G3E_PLACEMENTSELECTION (G3E_PCNO,G3E_FNO,G3E_USERNAME,G3E_LEVEL,G3E_ORDINAL,G3E_EDITDATE,G3E_PSROWNO,G3E_ICONORDINAL,G3E_ROLE) values (NULL,117,'Vault',2,760,sysdate,760,0,'PRIV_DESIGN_ALL');
Insert into G3E_PLACEMENTSELECTION (G3E_PCNO,G3E_FNO,G3E_USERNAME,G3E_LEVEL,G3E_ORDINAL,G3E_EDITDATE,G3E_PSROWNO,G3E_ICONORDINAL,G3E_ROLE) values (NULL,NULL,'Network',1,770,sysdate,770,0,'PRIV_DESIGN_NET');
Insert into G3E_PLACEMENTSELECTION (G3E_PCNO,G3E_FNO,G3E_USERNAME,G3E_LEVEL,G3E_ORDINAL,G3E_EDITDATE,G3E_PSROWNO,G3E_ICONORDINAL,G3E_ROLE) values (NULL,157,'Network Protector',2,780,sysdate,780,0,'PRIV_DESIGN_NET');
Insert into G3E_PLACEMENTSELECTION (G3E_PCNO,G3E_FNO,G3E_USERNAME,G3E_LEVEL,G3E_ORDINAL,G3E_EDITDATE,G3E_PSROWNO,G3E_ICONORDINAL,G3E_ROLE) values (NULL,84,'Primary Conductor - OH Network',2,790,sysdate,790,0,'PRIV_DESIGN_NET');
Insert into G3E_PLACEMENTSELECTION (G3E_PCNO,G3E_FNO,G3E_USERNAME,G3E_LEVEL,G3E_ORDINAL,G3E_EDITDATE,G3E_PSROWNO,G3E_ICONORDINAL,G3E_ROLE) values (NULL,85,'Primary Conductor - UG Network',2,800,sysdate,800,0,'PRIV_DESIGN_NET');
Insert into G3E_PLACEMENTSELECTION (G3E_PCNO,G3E_FNO,G3E_USERNAME,G3E_LEVEL,G3E_ORDINAL,G3E_EDITDATE,G3E_PSROWNO,G3E_ICONORDINAL,G3E_ROLE) values (NULL,87,'Primary Fuse - OH Network',2,810,sysdate,810,0,'PRIV_DESIGN_NET');
Insert into G3E_PLACEMENTSELECTION (G3E_PCNO,G3E_FNO,G3E_USERNAME,G3E_LEVEL,G3E_ORDINAL,G3E_EDITDATE,G3E_PSROWNO,G3E_ICONORDINAL,G3E_ROLE) values (NULL,88,'Primary Fuse - UG Network',2,820,sysdate,820,0,'PRIV_DESIGN_NET');
Insert into G3E_PLACEMENTSELECTION (G3E_PCNO,G3E_FNO,G3E_USERNAME,G3E_LEVEL,G3E_ORDINAL,G3E_EDITDATE,G3E_PSROWNO,G3E_ICONORDINAL,G3E_ROLE) values (NULL,22,'Primary Splice - Network',2,830,sysdate,830,0,'PRIV_DESIGN_NET');
Insert into G3E_PLACEMENTSELECTION (G3E_PCNO,G3E_FNO,G3E_USERNAME,G3E_LEVEL,G3E_ORDINAL,G3E_EDITDATE,G3E_PSROWNO,G3E_ICONORDINAL,G3E_ROLE) values (NULL,89,'Primary Switch - OH Network',2,840,sysdate,840,0,'PRIV_DESIGN_NET');
Insert into G3E_PLACEMENTSELECTION (G3E_PCNO,G3E_FNO,G3E_USERNAME,G3E_LEVEL,G3E_ORDINAL,G3E_EDITDATE,G3E_PSROWNO,G3E_ICONORDINAL,G3E_ROLE) values (NULL,90,'Primary Switch - UG Network',2,850,sysdate,850,0,'PRIV_DESIGN_NET');
Insert into G3E_PLACEMENTSELECTION (G3E_PCNO,G3E_FNO,G3E_USERNAME,G3E_LEVEL,G3E_ORDINAL,G3E_EDITDATE,G3E_PSROWNO,G3E_ICONORDINAL,G3E_ROLE) values (NULL,94,'Secondary Breaker - Network',2,860,sysdate,860,0,'PRIV_DESIGN_NET');
Insert into G3E_PLACEMENTSELECTION (G3E_PCNO,G3E_FNO,G3E_USERNAME,G3E_LEVEL,G3E_ORDINAL,G3E_EDITDATE,G3E_PSROWNO,G3E_ICONORDINAL,G3E_ROLE) values (NULL,95,'Secondary Bus Duct - Network',2,870,sysdate,870,0,'PRIV_DESIGN_NET');
Insert into G3E_PLACEMENTSELECTION (G3E_PCNO,G3E_FNO,G3E_USERNAME,G3E_LEVEL,G3E_ORDINAL,G3E_EDITDATE,G3E_PSROWNO,G3E_ICONORDINAL,G3E_ROLE) values (NULL,96,'Secondary Conductor - OH Network',2,880,sysdate,880,0,'PRIV_DESIGN_NET');
Insert into G3E_PLACEMENTSELECTION (G3E_PCNO,G3E_FNO,G3E_USERNAME,G3E_LEVEL,G3E_ORDINAL,G3E_EDITDATE,G3E_PSROWNO,G3E_ICONORDINAL,G3E_ROLE) values (NULL,97,'Secondary Conductor - UG Network',2,890,sysdate,890,0,'PRIV_DESIGN_NET');
Insert into G3E_PLACEMENTSELECTION (G3E_PCNO,G3E_FNO,G3E_USERNAME,G3E_LEVEL,G3E_ORDINAL,G3E_EDITDATE,G3E_PSROWNO,G3E_ICONORDINAL,G3E_ROLE) values (NULL,23,'Secondary Splice - Network',2,900,sysdate,900,0,'PRIV_DESIGN_NET');
Insert into G3E_PLACEMENTSELECTION (G3E_PCNO,G3E_FNO,G3E_USERNAME,G3E_LEVEL,G3E_ORDINAL,G3E_EDITDATE,G3E_PSROWNO,G3E_ICONORDINAL,G3E_ROLE) values (NULL,91,'Substation Breaker - Network',2,910,sysdate,910,0,'PRIV_DESIGN_NET');
Insert into G3E_PLACEMENTSELECTION (G3E_PCNO,G3E_FNO,G3E_USERNAME,G3E_LEVEL,G3E_ORDINAL,G3E_EDITDATE,G3E_PSROWNO,G3E_ICONORDINAL,G3E_ROLE) values (NULL,98,'Transformer - OH Network',2,920,sysdate,920,0,'PRIV_DESIGN_NET');
Insert into G3E_PLACEMENTSELECTION (G3E_PCNO,G3E_FNO,G3E_USERNAME,G3E_LEVEL,G3E_ORDINAL,G3E_EDITDATE,G3E_PSROWNO,G3E_ICONORDINAL,G3E_ROLE) values (409,NULL,'Transformer - UG Network',2,930,sysdate,930,0,'PRIV_DESIGN_NET');
Insert into G3E_PLACEMENTSELECTION (G3E_PCNO,G3E_FNO,G3E_USERNAME,G3E_LEVEL,G3E_ORDINAL,G3E_EDITDATE,G3E_PSROWNO,G3E_ICONORDINAL,G3E_ROLE) values (NULL,NULL,'Virtual Points',1,940,sysdate,940,0,'PRIV_EDIT');
Insert into G3E_PLACEMENTSELECTION (G3E_PCNO,G3E_FNO,G3E_USERNAME,G3E_LEVEL,G3E_ORDINAL,G3E_EDITDATE,G3E_PSROWNO,G3E_ICONORDINAL,G3E_ROLE) values (NULL,40,'Bypass Point',2,950,sysdate,950,0,'PRIV_EDIT');
Insert into G3E_PLACEMENTSELECTION (G3E_PCNO,G3E_FNO,G3E_USERNAME,G3E_LEVEL,G3E_ORDINAL,G3E_EDITDATE,G3E_PSROWNO,G3E_ICONORDINAL,G3E_ROLE) values (NULL,41,'Elbow',2,960,sysdate,960,0,'PRIV_EDIT');
Insert into G3E_PLACEMENTSELECTION (G3E_PCNO,G3E_FNO,G3E_USERNAME,G3E_LEVEL,G3E_ORDINAL,G3E_EDITDATE,G3E_PSROWNO,G3E_ICONORDINAL,G3E_ROLE) values (NULL,6,'Isolation Point',2,970,sysdate,970,0,'PRIV_EDIT');
Insert into G3E_PLACEMENTSELECTION (G3E_PCNO,G3E_FNO,G3E_USERNAME,G3E_LEVEL,G3E_ORDINAL,G3E_EDITDATE,G3E_PSROWNO,G3E_ICONORDINAL,G3E_ROLE) values (NULL,42,'Phase Connector',2,980,sysdate,980,0,'PRIV_EDIT');
Insert into G3E_PLACEMENTSELECTION (G3E_PCNO,G3E_FNO,G3E_USERNAME,G3E_LEVEL,G3E_ORDINAL,G3E_EDITDATE,G3E_PSROWNO,G3E_ICONORDINAL,G3E_ROLE) values (NULL,80,'Bypass Point -Network',2,990,sysdate,990,0,'PRIV_DESIGN_NET');
Insert into G3E_PLACEMENTSELECTION (G3E_PCNO,G3E_FNO,G3E_USERNAME,G3E_LEVEL,G3E_ORDINAL,G3E_EDITDATE,G3E_PSROWNO,G3E_ICONORDINAL,G3E_ROLE) values (NULL,81,'Elbow - Network',2,1000,sysdate,1000,0,'PRIV_DESIGN_NET');
Insert into G3E_PLACEMENTSELECTION (G3E_PCNO,G3E_FNO,G3E_USERNAME,G3E_LEVEL,G3E_ORDINAL,G3E_EDITDATE,G3E_PSROWNO,G3E_ICONORDINAL,G3E_ROLE) values (NULL,82,'Isolation Point - Network',2,1010,sysdate,1010,0,'PRIV_DESIGN_NET');
Insert into G3E_PLACEMENTSELECTION (G3E_PCNO,G3E_FNO,G3E_USERNAME,G3E_LEVEL,G3E_ORDINAL,G3E_EDITDATE,G3E_PSROWNO,G3E_ICONORDINAL,G3E_ROLE) values (NULL,83,'Phase Connector - Network',2,1020,sysdate,1020,0,'PRIV_DESIGN_NET');
Insert into G3E_PLACEMENTSELECTION (G3E_PCNO,G3E_FNO,G3E_USERNAME,G3E_LEVEL,G3E_ORDINAL,G3E_EDITDATE,G3E_PSROWNO,G3E_ICONORDINAL,G3E_ROLE) values (NULL,NULL,'Operational',1,1030,sysdate,1030,0,'PRIV_EDIT');
Insert into G3E_PLACEMENTSELECTION (G3E_PCNO,G3E_FNO,G3E_USERNAME,G3E_LEVEL,G3E_ORDINAL,G3E_EDITDATE,G3E_PSROWNO,G3E_ICONORDINAL,G3E_ROLE) values (NULL,184,'Corrections Tag',2,1040,sysdate,1040,0,'PRIV_EDIT');
Insert into G3E_PLACEMENTSELECTION (G3E_PCNO,G3E_FNO,G3E_USERNAME,G3E_LEVEL,G3E_ORDINAL,G3E_EDITDATE,G3E_PSROWNO,G3E_ICONORDINAL,G3E_ROLE) values (NULL,219,'DOC Note',2,1050,sysdate,1050,0,'PRIV_EDIT');
Insert into G3E_PLACEMENTSELECTION (G3E_PCNO,G3E_FNO,G3E_USERNAME,G3E_LEVEL,G3E_ORDINAL,G3E_EDITDATE,G3E_PSROWNO,G3E_ICONORDINAL,G3E_ROLE) values (NULL,220,'Easement',2,1060,sysdate,1060,0,'PRIV_EDIT');
Insert into G3E_PLACEMENTSELECTION (G3E_PCNO,G3E_FNO,G3E_USERNAME,G3E_LEVEL,G3E_ORDINAL,G3E_EDITDATE,G3E_PSROWNO,G3E_ICONORDINAL,G3E_ROLE) values (NULL,186,'Foreign Cable',2,1070,sysdate,1070,0,'PRIV_EDIT');
Insert into G3E_PLACEMENTSELECTION (G3E_PCNO,G3E_FNO,G3E_USERNAME,G3E_LEVEL,G3E_ORDINAL,G3E_EDITDATE,G3E_PSROWNO,G3E_ICONORDINAL,G3E_ROLE) values (NULL,225,'Permanent Note',2,1080,sysdate,1080,0,'PRIV_EDIT');
Insert into G3E_PLACEMENTSELECTION (G3E_PCNO,G3E_FNO,G3E_USERNAME,G3E_LEVEL,G3E_ORDINAL,G3E_EDITDATE,G3E_PSROWNO,G3E_ICONORDINAL,G3E_ROLE) values (NULL,226,'Permit',2,1090,sysdate,1090,0,'PRIV_EDIT');
Insert into G3E_PLACEMENTSELECTION (G3E_PCNO,G3E_FNO,G3E_USERNAME,G3E_LEVEL,G3E_ORDINAL,G3E_EDITDATE,G3E_PSROWNO,G3E_ICONORDINAL,G3E_ROLE) values (NULL,188,'Plotting Boundary',2,1100,sysdate,1100,0,'PRIV_EDIT');
Insert into G3E_PLACEMENTSELECTION (G3E_PCNO,G3E_FNO,G3E_USERNAME,G3E_LEVEL,G3E_ORDINAL,G3E_EDITDATE,G3E_PSROWNO,G3E_ICONORDINAL,G3E_ROLE) values (NULL,190,'Tree-trimming Voucher',2,1110,sysdate,1110,0,'PRIV_DESIGN_ALL');
Insert into G3E_PLACEMENTSELECTION (G3E_PCNO,G3E_FNO,G3E_USERNAME,G3E_LEVEL,G3E_ORDINAL,G3E_EDITDATE,G3E_PSROWNO,G3E_ICONORDINAL,G3E_ROLE) values (NULL,191,'Work Point',2,1120,sysdate,1120,0,'PRIV_DESIGN_ALL');
Insert into G3E_PLACEMENTSELECTION (G3E_PCNO,G3E_FNO,G3E_USERNAME,G3E_LEVEL,G3E_ORDINAL,G3E_EDITDATE,G3E_PSROWNO,G3E_ICONORDINAL,G3E_ROLE) values (NULL,NULL,'Fiber',1,1130,sysdate,1130,17,'FIBER_DESIGN');
Insert into G3E_PLACEMENTSELECTION (G3E_PCNO,G3E_FNO,G3E_USERNAME,G3E_LEVEL,G3E_ORDINAL,G3E_EDITDATE,G3E_PSROWNO,G3E_ICONORDINAL,G3E_ROLE) values (NULL,NULL,'Conductors',2,1140,sysdate,1140,41,'FIBER_DESIGN');
Insert into G3E_PLACEMENTSELECTION (G3E_PCNO,G3E_FNO,G3E_USERNAME,G3E_LEVEL,G3E_ORDINAL,G3E_EDITDATE,G3E_PSROWNO,G3E_ICONORDINAL,G3E_ROLE) values (NULL,7200,'Fiber Cable',3,1150,sysdate,1150,41,'FIBER_DESIGN');
Insert into G3E_PLACEMENTSELECTION (G3E_PCNO,G3E_FNO,G3E_USERNAME,G3E_LEVEL,G3E_ORDINAL,G3E_EDITDATE,G3E_PSROWNO,G3E_ICONORDINAL,G3E_ROLE) values (NULL,7203,'Foreign Communications Cable',3,1160,sysdate,1160,41,'FIBER_DESIGN');
Insert into G3E_PLACEMENTSELECTION (G3E_PCNO,G3E_FNO,G3E_USERNAME,G3E_LEVEL,G3E_ORDINAL,G3E_EDITDATE,G3E_PSROWNO,G3E_ICONORDINAL,G3E_ROLE) values (NULL,NULL,'Enclosures',2,1170,sysdate,1170,23,'FIBER_DESIGN');
Insert into G3E_PLACEMENTSELECTION (G3E_PCNO,G3E_FNO,G3E_USERNAME,G3E_LEVEL,G3E_ORDINAL,G3E_EDITDATE,G3E_PSROWNO,G3E_ICONORDINAL,G3E_ROLE) values (NULL,11800,'Fiber Splice Enclosure',3,1180,sysdate,1180,45,'FIBER_DESIGN');
Insert into G3E_PLACEMENTSELECTION (G3E_PCNO,G3E_FNO,G3E_USERNAME,G3E_LEVEL,G3E_ORDINAL,G3E_EDITDATE,G3E_PSROWNO,G3E_ICONORDINAL,G3E_ROLE) values (NULL,15700,'Fiber Rack',3,1190,sysdate,1190,46,'FIBER_DESIGN');
Insert into G3E_PLACEMENTSELECTION (G3E_PCNO,G3E_FNO,G3E_USERNAME,G3E_LEVEL,G3E_ORDINAL,G3E_EDITDATE,G3E_PSROWNO,G3E_ICONORDINAL,G3E_ROLE) values (NULL,NULL,'Infrastructure',2,1200,sysdate,1200,1,'FIBER_DESIGN');
Insert into G3E_PLACEMENTSELECTION (G3E_PCNO,G3E_FNO,G3E_USERNAME,G3E_LEVEL,G3E_ORDINAL,G3E_EDITDATE,G3E_PSROWNO,G3E_ICONORDINAL,G3E_ROLE) values (NULL,14100,'Fiber Building',3,1210,sysdate,1210,24,'FIBER_DESIGN');
Insert into G3E_PLACEMENTSELECTION (G3E_PCNO,G3E_FNO,G3E_USERNAME,G3E_LEVEL,G3E_ORDINAL,G3E_EDITDATE,G3E_PSROWNO,G3E_ICONORDINAL,G3E_ROLE) values (NULL,7500,'Fiber Riser',3,1220,sysdate,1220,3,'FIBER_DESIGN');
Insert into G3E_PLACEMENTSELECTION (G3E_PCNO,G3E_FNO,G3E_USERNAME,G3E_LEVEL,G3E_ORDINAL,G3E_EDITDATE,G3E_PSROWNO,G3E_ICONORDINAL,G3E_ROLE) values (NULL,7600,'Fiber Note',3,1230,sysdate,1230,3,'FIBER_DESIGN');
Insert into G3E_PLACEMENTSELECTION (G3E_PCNO,G3E_FNO,G3E_USERNAME,G3E_LEVEL,G3E_ORDINAL,G3E_EDITDATE,G3E_PSROWNO,G3E_ICONORDINAL,G3E_ROLE) values (NULL,NULL,'Landbase',1,1240,sysdate,1240,0,'PRIV_EDIT');
Insert into G3E_PLACEMENTSELECTION (G3E_PCNO,G3E_FNO,G3E_USERNAME,G3E_LEVEL,G3E_ORDINAL,G3E_EDITDATE,G3E_PSROWNO,G3E_ICONORDINAL,G3E_ROLE) values (NULL,217,'Building - Manual',2,1250,sysdate,1250,0,'PRIV_EDIT');
Insert into G3E_PLACEMENTSELECTION (G3E_PCNO,G3E_FNO,G3E_USERNAME,G3E_LEVEL,G3E_ORDINAL,G3E_EDITDATE,G3E_PSROWNO,G3E_ICONORDINAL,G3E_ROLE) values (NULL,222,'Manmade Feature',2,1260,sysdate,1260,0,'PRIV_EDIT');
Insert into G3E_PLACEMENTSELECTION (G3E_PCNO,G3E_FNO,G3E_USERNAME,G3E_LEVEL,G3E_ORDINAL,G3E_EDITDATE,G3E_PSROWNO,G3E_ICONORDINAL,G3E_ROLE) values (NULL,208,'Operational Boundary',2,1270,sysdate,1270,0,'PRIV_SUPPORT');
Insert into G3E_PLACEMENTSELECTION (G3E_PCNO,G3E_FNO,G3E_USERNAME,G3E_LEVEL,G3E_ORDINAL,G3E_EDITDATE,G3E_PSROWNO,G3E_ICONORDINAL,G3E_ROLE) values (NULL,224,'Parcel - Manual',2,1280,sysdate,1280,0,'PRIV_EDIT');
Insert into G3E_PLACEMENTSELECTION (G3E_PCNO,G3E_FNO,G3E_USERNAME,G3E_LEVEL,G3E_ORDINAL,G3E_EDITDATE,G3E_PSROWNO,G3E_ICONORDINAL,G3E_ROLE) values (NULL,228,'Pipeline Manual',2,1290,sysdate,1290,0,'PRIV_EDIT');
Insert into G3E_PLACEMENTSELECTION (G3E_PCNO,G3E_FNO,G3E_USERNAME,G3E_LEVEL,G3E_ORDINAL,G3E_EDITDATE,G3E_PSROWNO,G3E_ICONORDINAL,G3E_ROLE) values (NULL,238,'Restricted Area',2,1300,sysdate,1300,0,'PRIV_MGMT_RESTRICTION');
Insert into G3E_PLACEMENTSELECTION (G3E_PCNO,G3E_FNO,G3E_USERNAME,G3E_LEVEL,G3E_ORDINAL,G3E_EDITDATE,G3E_PSROWNO,G3E_ICONORDINAL,G3E_ROLE) values (NULL,232,'Street Centerline - Manual',2,1310,sysdate,1310,0,'PRIV_EDIT');
Insert into G3E_PLACEMENTSELECTION (G3E_PCNO,G3E_FNO,G3E_USERNAME,G3E_LEVEL,G3E_ORDINAL,G3E_EDITDATE,G3E_PSROWNO,G3E_ICONORDINAL,G3E_ROLE) values (NULL,230,'Street Right-of-Way Line',2,1320,sysdate,1320,0,'PRIV_EDIT');

spool off;