set echo on
set linesize 1000
set pagesize 300
set trimspool on

spool c:\temp\Legend_DisplayScale.log

--**************************************************************************************
-- SCRIPT NAME: Legend_DisplayScale.sql
--**************************************************************************************
-- AUTHOR			    : INGRNET\RRADASE
-- DATE				    : 16-JUL-2018
-- PRODUCT VERSION: 10.3.0
-- PRJ IDENTIFIER	: G/TECHNOLOGY - ONCOR
-- PROGRAM DESC		: Set legend display scale ranges
--**************************************************************************************


update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_ARRESTOR_S');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_ARRESTOR_ML');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_ARRESTOR_LL');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_AUTOXFMR_S');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_AUTOXFMR_T');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_AUTOXFMR_ML');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_AUTOXFMR_LL');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_CAPACITOR_S');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_CAPACITOR_T');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_CAPACITOR_ML');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_CAPACITOR_LL');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_FAULTIND_S');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_FAULTIND_T');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_FAULTIND_ML');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_FAULTIND_LL');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_FUSESAVER_S');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_FUSESAVER_ML');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_FUSESAVER_LL');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=15000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_PRICONOH_L');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=15000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_PRICONOH_DESC_T');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=15000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_PRICONOH_FEED_T');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=15000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_PRICONOH_NEUT_T');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=15000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_PRICONOH_PHASE_T');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=15000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_PRICONOH_ML');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=15000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_PRICONOH_LL');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=15000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_PRICONUG_L');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=15000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_PRICONUG_DESC_T');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=15000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_PRICONUG_FEED_T');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=15000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_PRICONUG_NEUT_T');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=15000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_PRICONUG_PHASE_T');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=15000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_PRICONUG_ML');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=15000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_PRICONUG_LL');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_PRICONUGNODE_S');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_PRICONUGNODE_T');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_PRICONUGNODE_ML');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_PRICONUGNODE_LL');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=3000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_PRIFUSEOH_S');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=3000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_PRIFUSEOH_EQPT_T');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=3000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_PRIFUSEOH_SIZE_T');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=3000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_PRIFUSEOH_ML');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=3000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_PRIFUSEOH_LL');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=3000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_PRIFUSEUG_S');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=3000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_PRIFUSEUG_EQPT_T');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=3000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_PRIFUSEUG_SIZE_T');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=3000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_PRIFUSEUG_ML');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=3000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_PRIFUSEUG_LL');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_PPOD_S');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_PPOD_ML');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_PPOD_LL');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_PRIPULLBOX_S');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_PRIPULLBOX_T');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_PRIPULLBOX_ML');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_PRIPULLBOX_LL');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=3000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_PRISWITCHOH_S');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=3001, G3E_DISPLAYSCALEMAX=7500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_PRISWITCHOH_LS');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=3000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_PRISWITCHOH_T');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=3001, G3E_DISPLAYSCALEMAX=7500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_PRISWITCHOH_LT');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=3000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_PRISWITCHOH_ML');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=3000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_PRISWITCHOH_LL');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=3000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_PRISWITCHUG_S');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=3001, G3E_DISPLAYSCALEMAX=7500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_PRISWITCHUG_LS');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=3000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_PRISWITCHUG_T');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=3001, G3E_DISPLAYSCALEMAX=7500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_PRISWITCHUG_LT');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=3000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_PRISWITCHUG_ML');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=3000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_PRISWITCHUG_LL');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=3000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_PRISWGEAR_P');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=3000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_PRISWGEAR_T');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=3000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_PRISWITCHOH_SGO_S');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=3001, G3E_DISPLAYSCALEMAX=7500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_PRISWITCHOH_SGO_LS');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=3000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_PRISWITCHUG_SGO_S');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=3001, G3E_DISPLAYSCALEMAX=7500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_PRISWITCHUG_SGO_LS');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=3000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_PRISWGEAR_ML');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=3000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_PRISWGEAR_LL');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=3000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_RECLOSER_S');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=3000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_RECLOSER_T');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=3001, G3E_DISPLAYSCALEMAX=7500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_RECLOSER_LARGE_T');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=3000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_RECLOSER_ML');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=3000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_RECLOSER_LL');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=3000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_RECLOSERUG_S');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=3000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_RECLOSERUG_T');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=3001, G3E_DISPLAYSCALEMAX=7500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_RECLOSERUG_LT');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=3000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_RECLOSERUG_ML');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=3000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_RECLOSERUG_LL');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_VOLTREG_S');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_VOLTREG_T');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_VOLTREG_ML');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_VOLTREG_LL');


update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_AREALIGHT_S');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_AREALIGHT_DIS_S');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_AREALIGHT_T');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_AREALIGHT_ML');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_AREALIGHT_LL');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_SECCONDOH_L');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_SECCONDOH_T');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_SECCONDOH_ML');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_SECCONDOH_LL');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_SECCONDUG_L');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_SECCONDUG_T');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_SECCONDUG_ML');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_SECCONDUG_LL');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_SECCONDNODE_S');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_SECCONDNODE_T');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_SECCONDNODE_ML');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_SECCONDNODE_LL');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_SERVICELINE_L');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_SERVICELINE_T');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_SERVICELINE_ML');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_SERVICELINE_LL');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_SERVICEPOINT_S');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_SERVICEPOINT_T');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_SERVICEPOINT_ML');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_SERVICEPOINT_LL');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_STLT_LCTD_LL');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_STLT_LCTD_ML');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_STLT_LCTD_CUST_S');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_STLT_LCTD_DIS_S');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_STLT_LCTD_T');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_STLT_LCTD_S');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_STLT_S');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_STLT_CUST_S');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_STLT_DIS_S');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_STLT_T');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_STLT_ML');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_STLT_LL');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_STLTCONTROL_S');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_STLTCONTROL_ML');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_STLTCONTROL_LL');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_TRFLT_S');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_TRFLT_T');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_TRFLT_ML');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_TRFLT_LL');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=3000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_XFMROH_S');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=3000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_XFMROH_T');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=3000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_XFMROH_ML');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=3000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_XFMROH_LL');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=3000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_XFMRUG_S');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=3000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_XFMRUG_T');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=3000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_XFMRUG_ML');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=3000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_XFMRUG_LL');


update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=7500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_CONDUIT_L');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=7500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_CONDUIT_T');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=7500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_CONDUIT_ML');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=7500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_CONDUIT_LL');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_DUCT_FROM_S');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_DUCT_TO_S');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_DUCT_FROM_T');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_DUCT_TO_T');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=7500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_DUCTBANK_L');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=7500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_DUCTBANK_T');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=7500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_DUCTBANK_ML');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=7500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_DUCTBANK_LL');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_ELEC_MARKER_S');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_INNERDUCT_FROM_S');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_INNERDUCT_TO_S');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_INNERDUCT_FROM_T');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_INNERDUCT_TO_T');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=3000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_JUNCTIONPOINT_S');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=3000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_JUNCTIONPOINT_DI');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=3000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_JUNCTIONPOINT_ML');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=3000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_JUNCTIONPOINT_LL');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_FORMATION_FROM_L');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_FORMATION_TO_L');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_FORMATION_FROM_T');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_FORMATION_TO_T');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_GUY_L');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_GUY_ML');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_GUY_LL');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=3000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_MANHOLE_S');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=3000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_MANHOLE_T');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=3000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_MANHOLE_ID_T');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=3000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_MANHOLE_DI');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=3000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_MANHOLE_ML');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=3000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_MANHOLE_LL');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=3000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_MISCSTRUCT_S');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=3000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_MISCSTRUCT_SPNL_S');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=3000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_MISCSTRUCT_T');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=3000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_MISCSTRUCT_ML');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=3000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_MISCSTRUCT_LL');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=3000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_PAD_S');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=3000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_PAD_T');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=3000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_PAD_ML');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=3000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_PAD_LL');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=3000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_POLE_S');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=3000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_POLE_PROPOSED_S');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=3000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_POLE_ACT_PERMIT_S');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=3000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_POLE_HEIGHT_T');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=3000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_POLE_T');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=3000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_POLE_ML');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=3000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_POLE_LL');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_PRIENCLOSURE_S');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_PRIENCLOSURE_ML');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_PRIENCLOSURE_LL');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_RACK_S');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_RACK_ML');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_RACK_LL');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_RISER_S');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_RISER_ML');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_RISER_LL');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_SECBOX_S');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_SECBOX_T');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_SECBOX_ML');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_SECBOX_LL');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_SECENCLOSURE_S');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_SECENCLOSURE_ML');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_SECENCLOSURE_LL');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=3000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_STLTSTANDARD_S');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=3000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_SLS_PROPOSED_S');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=3000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_STLTST_ACT_PERMIT_S');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=3000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_STLTSTANDARD_T');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=3000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_STLTSTANDARD_ML');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=3000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_STLTSTANDARD_LL');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=3000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_TRANSTOWER_S');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=3000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_TRANSTOWER_T');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=3000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_TRANSTOWER_ML');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=3000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_TRANSTOWER_LL');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=3000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_VAULT_S');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=3000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_VAULT_T');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=3000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_VAULT_ID_T');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=3000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_VAULT_DI');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=3000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_VAULT_ML');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=3000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_VAULT_LL');


update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_SUBSTATION_S');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_SUBSTATION_T');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_SUBSTATION_ML');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_SUBSTATION_LL');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_SUBBREAKER_S');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_SUBBREAKER_T');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_SUBBUS_L');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_SUBXFMR_S');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_SUBXFMR_T');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_SUBXFMR_ML');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_SUBXFMR_LL');


update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_AMSCOLLECTOR_S');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_AMSCOLLECTOR_T');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_AMSROUTER_S');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_CESBATTERY_S');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_DARADIO_S');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_DAFIBERMDM_S');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_RTU_S');


update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_PRICONOHN_L');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_PRICONOHN_DESC_T');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_PRICONOHN_FEED_T');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_PRICONOHN_NEUT_T');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_PRICONOHN_PHASE_T');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_PRICONOHN_ML');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_PRICONOHN_LL');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_PRICONUGN_L');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_PRICONUGN_DESC_T');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_PRICONUGN_FEED_T');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_PRICONUGN_NEUT_T');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_PRICONUGN_PHASE_T');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_PRICONUGN_ML');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_PRICONUGN_LL');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_PRIFUSEOHN_S');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_PRIFUSEOHN_EQPT_T');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_PRIFUSEOHN_SIZE_T');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_PRIFUSEOHN_ML');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_PRIFUSEOHN_LL');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_PRIFUSEUGN_S');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_PRIFUSEUGN_EQPT_T');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_PRIFUSEUGN_SIZE_T');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_PRIFUSEUGN_ML');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_PRIFUSEUGN_LL');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_PRISWITCHOHN_S');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_PRISWITCHOHN_LS');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_PRISWITCHOHN_T');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_PRISWITCHOHN_LT');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_PRISWITCHOHN_ML');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_PRISWITCHOHN_LL');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_PRISWITCHUGN_S');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_PRISWITCHUGN_LS');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_PRISWITCHUGN_T');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_PRISWITCHUGN_LT');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_PRISWITCHUGN_ML');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_PRISWITCHUGN_LL');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_SECCONDOHN_L');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_SECCONDOHN_T');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_SECCONDOHN_ML');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_SECCONDOHN_LL');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_SECCONDUGN_L');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_SECCONDUGN_T');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_SECCONDUGN_ML');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_SECCONDUGN_LL');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_SUBBREAKERN_S');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_SUBBREAKERN_T');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_XFMROHN_S');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_XFMROHN_T');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_XFMROHN_ML');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_XFMROHN_LL');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_XFMRUGN_S');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_XFMRUGN_T');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_XFMRUGN_KVA_T');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_XFMRUGN_ML');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_XFMRUGN_LL');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_VIRTUALPTBN_S');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_VIRTUALPTBN_ML');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_VIRTUALPTBN_LL');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_VIRTUALPTEN_S');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_VIRTUALPTEN_ML');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_VIRTUALPTEN_LL');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_VIRTUALPTIN_S');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_VIRTUALPTIN_ML');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_VIRTUALPTIN_LL');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_VIRTUALPTPN_S');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_VIRTUALPTPN_ML');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_VIRTUALPTPN_LL');


update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_VIRTUALPTB_S');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_VIRTUALPTB_ML');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_VIRTUALPTB_LL');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_VIRTUALPTE_S');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_VIRTUALPTE_ML');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_VIRTUALPTE_LL');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_VIRTUALPTI_S');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_VIRTUALPTI_ML');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_VIRTUALPTI_LL');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_VIRTUALPTP_S');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_VIRTUALPTP_ML');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_VIRTUALPTP_LL');


update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=15000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_CORRECT_TAG_S');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=60000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_DESIGNAREA_P');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=60000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_DESIGNAREA_T');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=60000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_DESIGNAREA_PC');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=60000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_DESIGNAREA_TC');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=30000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_DOCNOTE_T');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=30000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_DOCNOTE_S');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=30000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_DOCNOTE_LL');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=30000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_PERM_NOTE_LL');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_EASEMENT_AR');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_EASEMENT_T');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=15000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_FOREIGNCABLE_L');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=15000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_FOREIGNCABLE_T');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=15000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_MAXIMOWO_T');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_PERM_NOTE_T');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_PERMIT_AR');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_PERMIT_LB');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=3000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_TREETRIMBOUN_P');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=3000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_TREETRIMBOUN_T');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=3000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_TREETRIMWORK_T');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=3000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_TREETRIMMISCLAB_ML');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=3000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_TREETRIMLDRLIN_LL');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=3000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_WORKPOINT_S');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=3000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_WORKPOINT_T');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=3000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_WORKPOINTCU_T');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=3000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_WORKPOINTVCHR_ S');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=3000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_WORKPOINT_ML');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=3000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_WORKPOINT_LL');


update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=500000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_AIRPORT_LN');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=500000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_AIRPORT_T');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=3000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_BUILDING_CL_AR');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=3000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_BUILDING_CL_T');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=3000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_BUILDING_ML_AR');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=3000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_BUILDING_ML_T');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1000000000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_CENSUS_BNDY_AR');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1000000000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_CENSUS_BNDY_T');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=500000, G3E_DISPLAYSCALEMAX=1000000000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_CERTFNBNDY_AR');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1000000000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_COUNTY_AR');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1000000000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_COUNTY_T');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=30000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_DEM_LN');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=60000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_HYDROLOGY_LN');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=60000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_HYDROLOGY_L');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=60000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_HYDROLOGY_T');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=30000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_INSTITUTION_S');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=30000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_INSTITUTION_T');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=30000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_LANDMARK_AR');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=30000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_LANDMARK_T');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=30000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_MANMADE_LN');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=30000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_MANMADE_ML');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=500000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_MUNICIPALITY_AR');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=200000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_OPERBNDY_AR');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=200000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_OPERBNDY_T');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=15000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_PARCEL_CL_AR');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=15000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_PARCEL_CL_T');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=15000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_PARCEL_CL_S');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=15000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_PARCEL_CL_ML');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=15000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_PARCEL_ML_AR');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=15000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_PARCEL_ML_T');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=15000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_PARCEL_ML_S');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=15000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_PARCEL_ML_ML');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=3000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_PIPELINE_CL_LN');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=3000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_PIPELINE_CL_T');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=3000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_PIPELINE_ML_LN');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=3000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_PIPELINE_ML_T');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=125000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_POLBNDY_AR');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=125000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_POLBNDY_T');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=30000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_RAILROAD_LN');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=30000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_RAILROAD_T');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=30000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_RESTRICTED_AR');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=15000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_ROW_LN');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=30000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_STREETCTR_CL_LN');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=30000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_STREETCTR_CL_T');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=30000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_STREETCTR_ML_LN');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=30000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_STREETCTR_ML_T');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=125000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_TAXDISTRICT_AR');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=125000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_TAXDISTRICT_T');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=125000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_TELECOMBNDY_AR');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=125000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_TELECOMBNDY_T');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=125000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_TEXAS_SECTION_AR');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=125000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_TEXAS_SECTION_T');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1000000000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_TX_STATE_AR');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=125000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_THIRD_PARTY_AR');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=125000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_THIRD_PARTY_T');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=30000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_TRANSIT_S');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=30000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_TRANSIT_T');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=125000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_ZIPCODE_AR');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=125000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_ZIPCODE_T');


update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=500000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_AIRPORT_LN_AS');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=500000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_AIRPORT_T_AS');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=3000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_BUILDING_CL_AR_AS');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=3000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_BUILDINGCL_T_AS');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=3000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_BUILDING_ML_AR_AS');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=3000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_BUILDING_ML_T_AS');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1000000000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_CENSUS_BNDY_AR_AS');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1000000000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_CENSUS_BNDY_T_AS');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=500000, G3E_DISPLAYSCALEMAX=1000000000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_CERTFNBNDY_AR_AS');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1000000000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_COUNTY_AR_AS');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1000000000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_COUNTY_T_AS');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=30000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_DEM_LN_AS');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=60000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_HYDROLOGY_LN_AS');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=60000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_HYDROLOGY_L_AS');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=60000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_HYDROLOGY_T_AS');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=30000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_INSTITUTION_S_AS');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=30000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_INSTITUTION_T_AS');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=30000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_LANDMARK_AR_AS');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=30000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_LANDMARK_T_AS');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=30000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_MANMADE_LN_AS');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=30000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_MANMADE_ML_AS');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=500000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_MUNICIPALITY_AR_AS');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=200000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_OPERBNDY_AR_AS');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=200000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_OPERBNDY_T_AS');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=15000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_PARCEL_CL_AR_AS');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=15000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_PARCEL_CL_T_AS');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=15000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_PARCEL_CL_S_AS');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=15000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_PARCEL_CL_ML_AS');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=15000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_PARCEL_ML_AR_AS');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=15000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_PARCEL_ML_T_AS');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=15000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_PARCEL_ML_S_AS');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=15000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_PARCEL_ML_ML_AS');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=3000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_PIPELINE_CL_LN_AS');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=3000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_PIPELINE_CL_T_AS');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=3000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_PIPELINE_ML_LN_AS');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=3000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_PIPELINE_ML_T_AS');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=125000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_POLBNDY_AR_AS');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=125000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_POLBNDY_T_AS');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=30000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_RAILROAD_LN_AS');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=30000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_RAILROAD_T_AS');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=30000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_RESTRICTED_AR_AS');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=15000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_ROW_LN_AS');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=30000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_STREETCTR_CL_LN_AS');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=30000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_STREETCTR_CL_T_AS');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=30000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_STREETCTR_ML_LN_AS');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=30000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_STREETCTR_ML_T_AS');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=125000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_TAXDISTRICT_AR_AS');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=125000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_TAXDISTRICT_T_AS');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=125000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_TELECOMBNDY_AR_AS');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=125000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_TELECOMBNDY_T_AS');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=125000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_TEXAS_SECTION_AR_AS');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=125000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_TEXAS_SECTION_T_AS');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1000000000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_TX_STATE_AR_AS');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=125000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_THIRD_PARTY_AR_AS');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=125000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_THIRD_PARTY_T_AS');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=30000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_TRANSIT_S_AS');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=30000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_TRANSIT_T_AS');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=125000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_ZIPCODE_AR_AS');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=125000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_ZIPCODE_T_AS');



update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=15000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='VGC_FCBL_L');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='VGC_FCBL_T');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='VGC_FCBLCMPLEN_T');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='VGC_FCBLSCTLEN_T');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='VGC_FCBLSLACK_S');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='VGC_FCBLSLACK_T');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='VGC_FCBLCNT_BL_T');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='VGC_FCBLCNT_TL_T');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='V_FORNCOMMSCABLE_L');


update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='VGC_FSPLICE_S');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='VGC_FSPLICE_T');


update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=3000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='VGC_ISPCONNECT_T');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='VGC_ISPCONNECT_S');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='VGC_ONU_S');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=3000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='VGC_ONU_T');


update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=3000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='VGC_FBRANCH_T');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='VGC_FBRANCH_S');

update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=3000 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='VGC_BLDG_P');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='VGC_BLDG_T');
update G3E_LS_LEGDIST set G3E_DISPLAYSCALEMIN=1, G3E_DISPLAYSCALEMAX=1500 where G3E_LENO = (select G3E_LENO from G3E_LEGENDENTRY where G3E_LEGENDENTRY='VGC_BLDGDI_S');


spool off;
