CREATE OR REPLACE VIEW GIS_ONC.DEIS_LOCATION_VW (G3E_FID, COMPANY_ID, OGGX_H, OGGY_H, STRUCTURE_ID, SERVICE_CENTER_C)
AS
  SELECT T.G3E_FID,
    T.COMPANY_ID,
    C.OGGX_H,
    C.OGGY_H,
    C.STRUCTURE_ID,
    SB.SERVICE_CENTER_C
  FROM XFMR_OH_UNIT_N T
  JOIN COMMON_N C
  ON C.G3E_FID =T.G3E_FID
  AND T.G3E_FNO=59
  JOIN CONNECTIVITY_N TC
  ON T.G3E_FID  =TC.G3E_FID
  AND TC.G3E_FNO=59
  JOIN CONNECTIVITY_N BC
  ON BC.FEEDER_1_ID=TC.FEEDER_1_ID
  AND BC.G3E_FNO   =16
  JOIN SUB_BREAKER_N SB
  ON SB.G3E_FID=BC.G3E_FID
  UNION
  SELECT T.G3E_FID,
    T.COMPANY_ID,
    C.OGGX_H,
    C.OGGY_H,
    C.STRUCTURE_ID,
    SB.SERVICE_CENTER_C
  FROM XFMR_UG_UNIT_N T
  JOIN COMMON_N C
  ON C.G3E_FID =T.G3E_FID
  AND T.G3E_FNO=60
  JOIN CONNECTIVITY_N TC
  ON T.G3E_FID  =TC.G3E_FID
  AND TC.G3E_FNO=60
  JOIN CONNECTIVITY_N BC
  ON BC.FEEDER_1_ID=TC.FEEDER_1_ID
  AND BC.G3E_FNO   =16
  JOIN SUB_BREAKER_N SB
  ON SB.G3E_FID=BC.G3E_FID;
