  CREATE OR REPLACE TRIGGER GIS_STG.BIU_STG_MAX_WORKORDER_TBL_TR
BEFORE INSERT OR UPDATE ON STG_MAXIMO_WORKORDER

FOR EACH ROW 
BEGIN 
  IF UPDATING THEN
	SELECT SYSDATE INTO :NEW.AUD_MOD_DT FROM dual;
	SELECT USER INTO :NEW.AUD_MOD_USR_ID FROM dual;
  END IF;
END;