  CREATE OR REPLACE TABLE "GIS_ONC"."STLT_BOUNDARY" 
   (	"BND_CLASS" NUMBER(5,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"BND_FNO" NUMBER(5,0) NOT NULL ENABLE, 
	"BND_TYPE_ANO" NUMBER(10,0), 
	"BND_TYPE" VARCHAR2(80 BYTE), 
	"BND_ID_ANO" NUMBER(10,0) NOT NULL ENABLE, 
	 CONSTRAINT "PK_STLT_BOUNDARY" PRIMARY KEY ("BND_CLASS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GIS_ONC_IX"  ENABLE, 
	 SUPPLEMENTAL LOG GROUP "GIS00450_STLT_BOUNDARY" ("BND_CLASS", "BND_FNO", "BND_TYPE_ANO", "BND_TYPE", "BND_ID_ANO") ALWAYS, 
	 CONSTRAINT "FK_STLT_BOUNDARY_BND_FNO" FOREIGN KEY ("BND_FNO")
	  REFERENCES "GIS"."G3E_FEATURE" ("G3E_FNO") ENABLE, 
	 CONSTRAINT "FK_STLT_BOUNDARY_BND_ID_ANO" FOREIGN KEY ("BND_ID_ANO")
	  REFERENCES "GIS"."G3E_ATTRIBUTE" ("G3E_ANO") ENABLE, 
	 CONSTRAINT "FK_STLT_BOUNDARY_BND_TYPE_ANO" FOREIGN KEY ("BND_TYPE_ANO")
	  REFERENCES "GIS"."G3E_ATTRIBUTE" ("G3E_ANO") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GIS_ONC_TS" ;